# -*- coding: utf-8 -*-
"""Emit bpho/data/concepts.js from the hand-authored lessons in concepts_*.py.

Run:  python build_concepts.py
Gate: unique ids · every prerequisite exists · no cycles · a prerequisite never sits
      in a later stage · every question's key points resolve · every concept is used
      by at least one question.
"""
import io
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import concepts_a
import concepts_b
import concepts_c
from keys import KEYS

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "out", "concepts.js")

CONCEPTS = concepts_a.C + concepts_b.C + concepts_c.C
errors = []

# ── gate 1: unique ids
ids = [x["id"] for x in CONCEPTS]
for i in sorted(set(i for i in ids if ids.count(i) > 1)):
    errors.append("duplicate concept id: %s" % i)
by_id = {x["id"]: x for x in CONCEPTS}

# ── gate 2: prerequisites exist, and never sit in a later stage
for x in CONCEPTS:
    for p in x["pre"]:
        if p not in by_id:
            errors.append("%s: unknown prerequisite %r" % (x["id"], p))
        elif by_id[p]["stage"] > x["stage"]:
            errors.append("%s: prerequisite %s is in a later stage (%d > %d)"
                          % (x["id"], p, by_id[p]["stage"], x["stage"]))
        if p == x["id"]:
            errors.append("%s: lists itself as a prerequisite" % x["id"])

# ── gate 3: no cycles (depth-first, three-state marking)
WHITE, GREY, BLACK = 0, 1, 2
mark = {i: WHITE for i in ids}


def dfs(u, stack):
    mark[u] = GREY
    for v in by_id[u]["pre"]:
        if v not in by_id:
            continue
        if mark[v] == GREY:
            errors.append("prerequisite cycle: %s" % " → ".join(stack + [u, v]))
        elif mark[v] == WHITE:
            dfs(v, stack + [u])
    mark[u] = BLACK


for i in ids:
    if mark[i] == WHITE:
        dfs(i, [])

# ── gate 4: the question → key-point mapping resolves both ways
for qid, ks in KEYS.items():
    if len(set(ks)) != len(ks):
        errors.append("%s: repeated key point" % qid)
    for k in ks:
        if k not in by_id:
            errors.append("%s: unknown key point %r" % (qid, k))

used_by = {i: [] for i in ids}
for qid in sorted(KEYS):
    for k in KEYS[qid]:
        if k in used_by:
            used_by[k].append(qid)
for i in ids:
    if not used_by[i]:
        errors.append("concept %s is not used by any question" % i)

if errors:
    print("GATE FAILED:")
    for e in errors:
        print("  -", e)
    raise SystemExit(1)


def js_str(s):
    return s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def arr(items):
    return "[" + ", ".join('"%s"' % i for i in items) + "]"


lines = []
lines.append("/* BPhO Round 0 — key points.")
lines.append("")
lines.append("   Generated by tools/paper2025/build_concepts.py from concepts_a/b/c.py. Edit those,")
lines.append("   never this file. Each entry is a self-contained lesson written for someone meeting")
lines.append("   the idea for the first time: what the quantity is, where the formula comes from,")
lines.append("   what each symbol and unit means, and the trap the paper is setting.")
lines.append("")
lines.append("   `stage` orders the course (0 toolkit · 1 mechanics · 2 materials & thermal ·")
lines.append("   3 waves & optics · 4 electricity · 5 quantum & nuclear). `pre` lists what must be")
lines.append("   read first; it is acyclic and never points at a later stage. `q` is the reverse")
lines.append("   index: which of the 25 past-paper questions use this point.")
lines.append("")
lines.append("   %d key points, used %d times across the paper." % (len(CONCEPTS), sum(len(v) for v in used_by.values())))
lines.append("*/")
lines.append("window.BPHO_CONCEPTS = [")

order = sorted(CONCEPTS, key=lambda x: (x["stage"], ids.index(x["id"])))
for n, x in enumerate(order):
    lines.append("  {")
    lines.append('    id: "%s", m: "%s", stage: %d, t: "%s",' % (x["id"], x["m"], x["stage"], x["t"]))
    lines.append("    pre: %s," % arr(x["pre"]))
    lines.append('    one: "%s",' % js_str(x["one"]).replace('"', "'"))
    lines.append("    body: `%s`," % js_str(x["body"]))
    lines.append('    used: "%s",' % js_str(x["used"]).replace('"', "'"))
    lines.append("    q: %s" % arr(sorted(used_by[x["id"]])))
    lines.append("  }" + ("," if n < len(order) - 1 else ""))
lines.append("];")
lines.append("")
lines.append("/* question → key points, the forward direction of the same index */")
lines.append("window.BPHO_QKEYS = {")
for n, qid in enumerate(sorted(KEYS)):
    lines.append('  "%s": %s%s' % (qid, arr(KEYS[qid]), "," if n < len(KEYS) - 1 else ""))
lines.append("};")
lines.append("")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with io.open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("concepts:", len(CONCEPTS), "→", OUT)
print("links:   ", sum(len(v) for v in used_by.values()))
for st in sorted(set(x["stage"] for x in CONCEPTS)):
    grp = [x for x in order if x["stage"] == st]
    print("  stage %d: %2d  %s" % (st, len(grp), ", ".join(x["id"] for x in grp)))
