// 词汇复习站 · 扩展词库（第四批，全面加厚各类）
const EXTRA3 = [
  // ============== 旅游（补充，冲到约49） ==============
  { w:"backpacker", ipa:"/ˈbækpækə(r)/", pos:"n.", cat:"旅游",
    senses:[{ def:"背包客；自助旅行者", ex:["The hostel was full of backpackers.",
      "Backpackers roam Southeast Asia on a budget.",
      "He travelled as a backpacker for a year."],
      note:"budget travel 穷游；hostel 青旅。" }],
    syn:["traveller","tourist"], ant:[], synDiff:"" },

  { w:"cruise", ipa:"/kruːz/", pos:"n./v.", cat:"旅游",
    senses:[{ def:"游轮航行；巡航", ex:["They took a Mediterranean cruise.",
      "The ship cruised past the cliffs.",
      "A cruise is an easy way to see many ports."],
      note:"cruise ship 游轮；也指‘悠闲巡航’。" }],
    syn:["voyage","sail"], ant:[], synDiff:"" },

  { w:"pilgrimage", ipa:"/ˈpɪlɡrɪmɪdʒ/", pos:"n.", cat:"旅游",
    senses:[{ def:"朝圣；瞻仰之旅", ex:["They made a pilgrimage to Mecca.",
      "Fans treat the shrine as a pilgrimage.",
      "The pilgrimage crossed the mountains."],
      note:"pilgrim 朝圣者；也喻‘心驰神往的旅程’。" }],
    syn:["journey","quest"], ant:[], synDiff:"" },

  { w:"bazaar", ipa:"/bəˈzɑː(r)/", pos:"n.", cat:"旅游",
    senses:[{ def:"集市；（东方）露天市场", ex:["The bazaar teemed with spices and silk.",
      "We haggled at the night bazaar.",
      "The old bazaar smelled of incense."],
      note:"中东/南亚市场；haggle 讨价还价。" }],
    syn:["market","fair"], ant:[], synDiff:"" },

  { w:"panorama", ipa:"/ˌpænəˈrɑːmə/", pos:"n.", cat:"旅游",
    senses:[{ def:"全景", ex:["The summit offered a vast panorama.",
      "The window framed a panorama of the bay.",
      "The city panorama lit up at dusk."],
      note:"panoramic 全景的；比 view 更‘一览无余’。" }],
    syn:["vista","view"], ant:[], synDiff:"" },

  { w:"emporium", ipa:"/ɪmˈpɔːriəm/", pos:"n.", cat:"旅游",
    senses:[{ def:"（文）大商场；百货店", ex:["The emporium sold goods from afar.",
      "A grand emporium anchored the square.",
      "The Christmas emporium drew crowds."],
      note:"文学/古雅；近 department store。" }],
    syn:["store","market"], ant:[], synDiff:"" },

  { w:"hostel", ipa:"/ˈhɒstl/", pos:"n.", cat:"旅游",
    senses:[{ def:"青年旅舍；招待所", ex:["We stayed in a cheap hostel.",
      "The hostel had a shared kitchen.",
      "Backpackers favour hostels over hotels."],
      note:"shared dorm 多人间；budget lodging。" }],
    syn:["lodging","inn"], ant:["hotel"], synDiff:"" },

  { w:"succumb", ipa:"/səˈkʌm/", pos:"v.", cat:"旅游",
    senses:[{ def:"屈服；因…而死（succumb to）", ex:["He succumbed to the altitude.",
      "Many succumbed to the desert heat.",
      "She succumbed to temptation and bought it."],
      note:"正式；succumb to 死于/屈从于。" }],
    syn:["yield","submit"], ant:["resist","withstand"], synDiff:"" },

  { w:"sojourn", ipa:"/ˈsɒdʒɜːn/", pos:"n.", cat:"旅游",
    senses:[{ def:"（文）逗留；暂居", ex:["His sojourn in Paris lasted a year.",
      "A brief sojourn by the lake refreshed her.",
      "The poet's sojourn abroad shaped his work."],
      note:"文学‘短暂停留’；比 stay 雅致。" }],
    syn:["stay","visit"], ant:[], synDiff:"" },

  { w:"caravan", ipa:"/ˈkærəvæn/", pos:"n.", cat:"旅游",
    senses:[{ def:"（沙漠）商队；房车（英）", ex:["A caravan crossed the dunes at dawn.",
      "They rented a caravan for the trip.",
      "The caravan of camels stretched for miles."],
      note:"商队/驼队；英式也指‘房车’（美 RV）。" }],
    syn:["convoy","camper"], ant:[], synDiff:"" },

  { w:"nomad", ipa:"/ˈnəʊmæd/", pos:"n.", cat:"旅游",
    senses:[{ def:"游牧民；流浪者", ex:["The nomads followed the herds.",
      "Digital nomads work from anywhere.",
      "Once a nomad, he settled at last."],
      note:"nomadic 游牧的；digital nomad 数字游民。" }],
    syn:["wanderer","roamer"], ant:["settler"], synDiff:"" },

  { w:"cobbled", ipa:"/ˈkɒbld/", pos:"adj.", cat:"旅游",
    senses:[{ def:"（街道）铺鹅卵石的", ex:["We strolled the cobbled lane.",
      "The cobbled square buzzed with cafés.",
      "Cobbled streets charm old towns."],
      note:"cobble 鹅卵石；cobblestone 同义。" }],
    syn:["paved"], ant:[], synDiff:"" },

  { w:"enchanting", ipa:"/ɪnˈtʃɑːntɪŋ/", pos:"adj.", cat:"旅游",
    senses:[{ def:"迷人的； enchanting", ex:["The village was utterly enchanting.",
      "An enchanting garden lay behind the wall.",
      "The music was soft and enchanting."],
      note:"enchant 使迷醉；比 charming 更‘魔法般’。" }],
    syn:["charming","bewitching"], ant:["repulsive"], synDiff:"" },

  { w:"quaint", ipa:"/kweɪnt/", pos:"adj.", cat:"旅游",
    senses:[{ def:"古雅的；别致的", ex:["A quaint cottage nestled in the hill.",
      "The town has quaint little shops.",
      "They loved the quaint harbour."],
      note:"褒义‘小巧古雅’；有时略带‘过时可爱’。" }],
    syn:["charming","old-fashioned"], ant:["modern"], synDiff:"" },

  { w:"wanderlust", ipa:"/ˈwɒndəlʌst/", pos:"n.", cat:"旅游",
    senses:[{ def:"旅行癖；漫游渴望", ex:["Wanderlust drove him abroad.",
      "She felt a sudden wanderlust.",
      "The book fed his wanderlust."],
      note:"德语借词；lust 渴望 + wander 漫游。" }],
    syn:["restlessness","itchy feet"], ant:[], synDiff:"" },

  { w:"expedition", ipa:"/ˌekspəˈdɪʃn/", pos:"n.", cat:"旅游",
    senses:[{ def:"远征；考察队", ex:["An expedition mapped the glacier.",
      "They joined an Arctic expedition.",
      "The expedition returned after months."],
      note:"explore 探险；military expedition 远征军。" }],
    syn:["journey","voyage"], ant:[], synDiff:"" },

  { w:"relic", ipa:"/ˈrelɪk/", pos:"n.", cat:"旅游",
    senses:[{ def:"遗迹；遗物", ex:["The museum kept a relic of the saint.",
      "Ruins are relics of a lost city.",
      "The relic drew pilgrims for centuries."],
      note:"relic 圣物/遗骸；也指‘陈旧残余’。" }],
    syn:["artifact","remnant"], ant:[], synDiff:"" },

  { w:"jaunt", ipa:"/dʒɔːnt/", pos:"n.", cat:"旅游",
    senses:[{ def:"短途游览；闲游", ex:["We took a jaunt to the coast.",
      "A Sunday jaunt lifted his mood.",
      "The jaunt lasted but an afternoon."],
      note:"轻松愉快的短途；近 outing。" }],
    syn:["outing","trip"], ant:[], synDiff:"" },

  { w:"lodge", ipa:"/lɒdʒ/", pos:"n./v.", cat:"旅游",
    senses:[{ def:"小屋；住宿；寄宿", ex:["They stayed in a mountain lodge.",
      "We lodged with local villagers.",
      "The hunting lodge sat by the lake."],
      note:"lodge 小木屋/旅舍；也指‘正式提出’（lodge a complaint）。" }],
    syn:["cabin","inn"], ant:[], synDiff:"" },

  { w:"serene", ipa:"/səˈriːn/", pos:"adj.", cat:"旅游",
    senses:[{ def:"宁静的；安详的", ex:["The lake was perfectly serene.",
      "A serene sunset calmed the crowd.",
      "She kept a serene expression."],
      note:"serenity 宁静；比 calm 更‘平和优美’。" }],
    syn:["calm","tranquil"], ant:["turbulent","agitated"], synDiff:"" },

  { w:"twilight", ipa:"/ˈtwaɪlaɪt/", pos:"n.", cat:"旅游",
    senses:[{ def:"黄昏；暮光", ex:["We walked home in the twilight.",
      "The town glowed at twilight.",
      "Fireflies appeared at twilight."],
      note:"dawn/dusk；也喻‘衰落期’（the twilight of his career）。" }],
    syn:["dusk","gloaming"], ant:["dawn"], synDiff:"" },

  // ============== 地理环境（补充，冲到约49） ==============
  { w:"savanna", ipa:"/səˈvænə/", pos:"n.", cat:"地理环境",
    senses:[{ def:"热带草原（稀树草原）", ex:["Lions roam the African savanna.",
      "The savanna burns dry each winter.",
      "Acacia dot the savanna."],
      note:"热带草原生态；与 grassland 不同更热。" }],
    syn:["grassland","plain"], ant:[], synDiff:"" },

  { w:"fjord", ipa:"/fjɔːd/", pos:"n.", cat:"地理环境",
    senses:[{ def:"峡湾", ex:["The fjord cut deep into the coast.",
      "A cruise entered the narrow fjord.",
      "Norway is famed for its fjords."],
      note:"冰川侵蚀的狭长海湾；挪威特色地貌。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"delta", ipa:"/ˈdeltə/", pos:"n.", cat:"地理环境",
    senses:[{ def:"三角洲", ex:["The Nile delta is fertile.",
      "The river fanned into a delta.",
      "Sediment built the delta over centuries."],
      note:"河流入海泥沙堆积；与 estuary 河口不同。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"oasis", ipa:"/əʊˈeɪsɪs/", pos:"n.", cat:"地理环境",
    senses:[{ def:"绿洲；慰藉处", ex:["An oasis broke the desert monotony.",
      "The garden was an oasis of calm.",
      "Camels rested at the oasis."],
      note:"沙漠中的水源地；喻‘慰藉之所’。" }],
    syn:["haven","refuge"], ant:[], synDiff:"" },

  { w:"basin", ipa:"/ˈbeɪsn/", pos:"n.", cat:"地理环境",
    senses:[{ def:"盆地；流域", ex:["The city lies in a river basin.",
      "The Amazon basin is vast.",
      "Sediment filled the geological basin."],
      note:"river basin 流域；geological basin 盆地。" }],
    syn:["valley","watershed"], ant:[], synDiff:"" },

  { w:"ridge", ipa:"/rɪdʒ/", pos:"n.", cat:"地理环境",
    senses:[{ def:"山脊；分水岭", ex:["We climbed the rocky ridge.",
      "Snow capped the ridge.",
      "The ridge divides two valleys."],
      note:"mountain ridge 山脊；与 peak 峰不同。" }],
    syn:["crest","spine"], ant:["valley"], synDiff:"" },

  { w:"valley", ipa:"/ˈvæli/", pos:"n.", cat:"地理环境",
    senses:[{ def:"山谷；流域", ex:["The river wound through the valley.",
      "Mist hung in the valley.",
      "They farmed the fertile valley floor."],
      note:"与 ridge 相对；river valley 河谷。" }],
    syn:["dale","glen"], ant:["peak","ridge"], synDiff:"" },

  { w:"strait", ipa:"/streɪt/", pos:"n.", cat:"地理环境",
    senses:[{ def:"海峡", ex:["Ships passed through the strait.",
      "The strait links two seas.",
      "The Strait of Gibraltar guards the Mediterranean."],
      note:"窄水道；与 channel 近义。" }],
    syn:["channel","sound"], ant:[], synDiff:"" },

  { w:"peninsula", ipa:"/pəˈnɪnsjələ/", pos:"n.", cat:"地理环境",
    senses:[{ def:"半岛", ex:["Italy is a peninsula.",
      "They hiked the peninsula's spine.",
      "The peninsula juts into the sea."],
      note:"peninsular 半岛的；几乎被水包围。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"gorge", ipa:"/ɡɔːdʒ/", pos:"n.", cat:"地理环境",
    senses:[{ def:"峡谷", ex:["The river carved a deep gorge.",
      "A bridge spanned the gorge.",
      "The gorge echoed with the falls."],
      note:"深窄峡谷；canyon 更大更宽。" }],
    syn:["canyon","ravine"], ant:[], synDiff:"" },

  { w:"meadow", ipa:"/ˈmedəʊ/", pos:"n.", cat:"地理环境",
    senses:[{ def:"草地；牧场", ex:["Cows grazed the flowering meadow.",
      "The meadow glowed with buttercups.",
      "They picnicked in the meadow."],
      note:"野生花草草地；与 lawn 草坪不同。" }],
    syn:["field","pasture"], ant:[], synDiff:"" },

  { w:"marsh", ipa:"/mɑːʃ/", pos:"n.", cat:"地理环境",
    senses:[{ def:"沼泽；湿地", ex:["Reeds swayed in the marsh.",
      "The marsh teemed with birds.",
      "They drained the marsh for farmland."],
      note:"marshland；与 swamp 近（swamp 树木多）。" }],
    syn:["swamp","bog"], ant:[], synDiff:"" },

  { w:"volcano", ipa:"/vɒlˈkeɪnəʊ/", pos:"n.", cat:"地理环境",
    senses:[{ def:"火山", ex:["The volcano erupted at dawn.",
      "Lava flowed down the volcano.",
      "The volcano has been dormant for years."],
      note:"erupt 喷发；dormant 休眠；magma 岩浆。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"tsunami", ipa:"/tsuːˈnɑːmi/", pos:"n.", cat:"地理环境",
    senses:[{ def:"海啸", ex:["The tsunami swept the coast.",
      "A quake triggered the tsunami.",
      "Warning systems spotted the tsunami."],
      note:"日语借词；地震引发的海浪。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"equator", ipa:"/ɪˈkweɪtə(r)/", pos:"n.", cat:"地理环境",
    senses:[{ def:"赤道", ex:["The equator splits the globe.",
      "The climate is hot near the equator.",
      "They crossed the equator at sea."],
      note:"equatorial 赤道的；0°纬线。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"latitude", ipa:"/ˈlætɪtjuːd/", pos:"n.", cat:"地理环境",
    senses:[{ def:"纬度；余地", ex:["The city lies at high latitude.",
      "Latitude affects the climate.",
      "The rule gives judges some latitude."],
      note:"地理‘纬度’；喻‘自由裁量余地’。" }],
    syn:["scope","freedom"], ant:["longitude"], synDiff:"" },

  { w:"current", ipa:"/ˈkʌrənt/", pos:"n.", cat:"地理环境",
    senses:[{ def:"洋流；水流；电流", ex:["The current carried the raft seaward.",
      "The Gulf Stream is a warm current.",
      "Ocean currents shape the climate."],
      note:"ocean current 洋流；也指‘时下的’（current affairs）。" }],
    syn:["flow","stream"], ant:[], synDiff:"" },

  { w:"erosion", ipa:"/ɪˈrəʊʒn/", pos:"n.", cat:"地理环境",
    senses:[{ def:"侵蚀；磨损", ex:["Wind causes coastal erosion.",
      "Soil erosion ruined the farmland.",
      "Erosion carved the cliffs over ages."],
      note:"erode 侵蚀（动词）；与 weathering 风化相关。" }],
    syn:["wearing away","corrosion"], ant:["deposition"], synDiff:"" },

  { w:"vegetation", ipa:"/ˌvedʒəˈteɪʃn/", pos:"n.", cat:"地理环境",
    senses:[{ def:"植被", ex:["The slope was bare of vegetation.",
      "Dense vegetation hid the ruins.",
      "Altitude limits the vegetation."],
      note:"总称‘植物覆盖’；非单株 plant。" }],
    syn:["flora","plant cover"], ant:[], synDiff:"" },

  { w:"canopy", ipa:"/ˈkænəpi/", pos:"n.", cat:"地理环境",
    senses:[{ def:"（森林）树冠层", ex:["Birds nested in the canopy.",
      "Sunlight filtered through the canopy.",
      "The canopy blocked the rain."],
      note:"forest canopy 林冠；也指‘天篷’。" }],
    syn:["cover","crown"], ant:[], synDiff:"" },

  { w:"biodiversity hotspot", ipa:"/ˌbaɪəʊdaɪˈvɜːsəti ˈhɒtspɒt/", pos:"n.", cat:"地理环境",
    senses:[{ def:"生物多样性热点区", ex:["Madagascar is a biodiversity hotspot.",
      "The hotspot hosts many endemics.",
      "Conservation targets biodiversity hotspots."],
      note:"endemic 特有种；热点区物种极丰富但受威胁。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"permafrost", ipa:"/ˈpɜːməfrɒst/", pos:"n.", cat:"地理环境",
    senses:[{ def:"永冻层", ex:["Permafrost underlies the tundra.",
      "Thawing permafrost releases methane.",
      "Buildings sink as permafrost melts."],
      note:"永久冻结土层；北极/高山。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"biome", ipa:"/ˈbaɪəʊm/", pos:"n.", cat:"地理环境",
    senses:[{ def:"生物群系", ex:["The desert is a harsh biome.",
      "Each biome has distinct life.",
      "Climate defines the biome."],
      note:"大尺度生态区（雨林/苔原等）；ecosystem 更小。" }],
    syn:["ecosystem"], ant:[], synDiff:"" },

  // ============== 艺术音乐（补充，冲到约49） ==============
  { w:"genre", ipa:"/ˈʒɒnrə/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"体裁；类型", ex:["Sci-fi is a popular genre.",
      "The novel crosses several genres.",
      "Each genre has its conventions."],
      note:"文学/电影/音乐‘体裁’； conventions 惯例。" }],
    syn:["category","style"], ant:[], synDiff:"" },

  { w:"aesthetic", ipa:"/iːsˈθetɪk/", pos:"adj./n.", cat:"艺术音乐",
    senses:[{ def:"审美的；美感", ex:["The design has a clean aesthetic.",
      "She has a minimalist aesthetic.",
      "Aesthetic value matters here."],
      note:"aesthetics 美学；也指‘外观品味’。" }],
    syn:["artistic","tasteful"], ant:["unaesthetic"], synDiff:"" },

  { w:"sculpture", ipa:"/ˈskʌlptʃə(r)/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"雕塑", ex:["The sculpture depicted a horse.",
      "She studied sculpture at art school.",
      "Marble sculpture lined the hall."],
      note:"sculpt 雕塑（动词）；sculptor 雕塑家。" }],
    syn:["statue","carving"], ant:[], synDiff:"" },

  { w:"mural", ipa:"/ˈmjʊərəl/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"壁画", ex:["A mural covered the wall.",
      "The mural celebrated the town's history.",
      "Artists painted a street mural."],
      note:"mural 墙上的画；与 fresco 湿壁画相关。" }],
    syn:["fresco","wall painting"], ant:[], synDiff:"" },

  { w:"chiaroscuro", ipa:"/kiˌɑːrəˈskjʊərəʊ/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"明暗对照法", ex:["Caravaggio mastered chiaroscuro.",
      "Chiaroscuro gives drama to the scene.",
      "The painting uses stark chiaroscuro."],
      note:"美术‘明暗对比’；Caravaggio 善用。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"perspective", ipa:"/pəˈspektɪv/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"透视；视角", ex:["The lines show linear perspective.",
      "The artist fixed the perspective.",
      "From this perspective the figure recedes."],
      note:"绘画‘透视法’；也指‘观点’。" }],
    syn:["viewpoint","foreshortening"], ant:[], synDiff:"" },

  { w:"contrast", ipa:"/ˈkɒntrɑːst/", pos:"n./v.", cat:"艺术音乐",
    senses:[{ def:"对比；反差", ex:["The red contrasts with the green.",
      "High contrast sharpens the image.",
      "The essay contrasts two views."],
      note:"contrast 对比；与 compare 比较不同。" }],
    syn:["opposition","difference"], ant:["similarity"], synDiff:"" },

  { w:"orchestra", ipa:"/ˈɔːkɪstrə/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"管弦乐队", ex:["The orchestra tuned before the show.",
      "She joined the youth orchestra.",
      "The orchestra played Beethoven."],
      note:"conductor 指挥；symphony orchestra 交响乐团。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"solo", ipa:"/ˈsəʊləʊ/", pos:"n./adj.", cat:"艺术音乐",
    senses:[{ def:"独奏；独唱", ex:["He played a violin solo.",
      "The solo drew loud applause.",
      "She sang a solo in the choir."],
      note:"soloist 独奏者；与 ensemble 合奏相对。" }],
    syn:["recital"], ant:["ensemble"], synDiff:"" },

  { w:"choir", ipa:"/ˈkwaɪə(r)/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"唱诗班；合唱团", ex:["The choir sang at the service.",
      "The school choir toured Europe.",
      "The choir's harmony was pure."],
      note:"chorus 合唱（也可指歌曲中的副歌）；choir 团体。" }],
    syn:["chorus","ensemble"], ant:[], synDiff:"" },

  { w:"lyrics", ipa:"/ˈlɪrɪks/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"歌词", ex:["The lyrics moved the crowd.",
      "He wrote the music and she the lyrics.",
      "The lyrics touch on loss."],
      note:"lyric 也可作形容词‘抒情的’；注意复数。" }],
    syn:["words"], ant:[], synDiff:"" },

  { w:"rhythm", ipa:"/ˈrɪðəm/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"节奏", ex:["The rhythm drove the dancers.",
      "He kept a steady rhythm.",
      "The poem has a gentle rhythm."],
      note:"beat 节拍；rhythm 整体节奏律动。" }],
    syn:["beat","cadence"], ant:[], synDiff:"" },

  { w:"improvisational", ipa:"/ɪmˌprɒvəˈzeɪʃənl/", pos:"adj.", cat:"艺术音乐",
    senses:[{ def:"即兴的", ex:["Jazz is largely improvisational.",
      "His style is bold and improvisational.",
      "The scene felt improvisational."],
      note:"来 improvisation；强调‘临场发挥’。" }],
    syn:["spontaneous","ad-lib"], ant:["scripted"], synDiff:"" },

  { w:"virtuoso", ipa:"/ˌvɜːtʃuˈəʊzəʊ/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"演奏大师；高手", ex:["He is a piano virtuoso.",
      "The virtuoso dazzled the hall.",
      "Few reach virtuoso level."],
      note:"形容技艺极高者；也作形容词。" }],
    syn:["master","expert"], ant:[], synDiff:"" },

  { w:"octave", ipa:"/ˈɒktɪv/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"八度（音程）", ex:["She sang an octave higher.",
      "The tune jumps an octave.",
      "The scale spans two octaves."],
      note:"音乐音程；八度音。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"resonance", ipa:"/ˈrezənəns/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"共鸣；共振", ex:["The hall has rich resonance.",
      "His words had emotional resonance.",
      "The string's resonance lingered."],
      note:"resonate 共鸣；喻‘引起共鸣’。" }],
    syn:["echo","reverberation"], ant:[], synDiff:"" },

  { w:"timbre", ipa:"/ˈtæmbə(r)/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"音色", ex:["The timbre of a cello is warm.",
      "Each voice has its own timbre.",
      "Synthesizers mimic timbre."],
      note:"音‘色彩/质地’；法语借词，也写 timbre。" }],
    syn:["tone colour"], ant:[], synDiff:"" },

  { w:"movement", ipa:"/ˈmuːvmənt/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"（乐曲）乐章；运动", ex:["The second movement is slow.",
      "The symphony has four movements.",
      "The art movement favoured colour."],
      note:"音乐‘乐章’；也指‘艺术/社会运动’。" }],
    syn:["section","movement"], ant:[], synDiff:"" },

  { w:"libretto", ipa:"/lɪˈbretoʊ/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"（歌剧）剧本；歌词本", ex:["He wrote the opera's libretto.",
      "The libretto tells a grim tale.",
      "The libretto was in Italian."],
      note:"歌剧/音乐剧脚本；复数 libretti。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"ensemble", ipa:"/ɒnˈsɒmbl/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"合奏团；整体", ex:["The chamber ensemble played softly.",
      "The ensemble wore black.",
      "The costume and set formed a whole ensemble."],
      note:"集体演出；也指‘整套/合身’。" }],
    syn:["group","company"], ant:["solo"], synDiff:"" },

  { w:"acoustics", ipa:"/əˈkuːstɪks/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"声学；音响效果", ex:["The hall's acoustics are superb.",
      "Poor acoustics marred the concert.",
      "Acoustics studies how sound behaves."],
      note:"单数‘音响效果’，复数‘声学’。" }],
    syn:[], ant:[], synDiff:"" },

  // ============== 英语文学（补充，冲到约43） ==============
  { w:"protagonist", ipa:"/prəˈtæɡənɪst/", pos:"n.", cat:"英语文学",
    senses:[{ def:"主人公；主角", ex:["The protagonist faces a hard choice.",
      "The novel's protagonist is a child.",
      "The protagonist grows through the tale."],
      note:"反义 antagonist 对手/反派；与 hero 不同（主角未必是英雄）。" }],
    syn:["hero","main character"], ant:["antagonist"], synDiff:"" },

  { w:"antagonist", ipa:"/ænˈtæɡənɪst/", pos:"n.", cat:"英语文学",
    senses:[{ def:"对手；反派", ex:["The antagonist thwarts the hero.",
      "The antagonist is not purely evil.",
      "A worthy antagonist sharpens the plot."],
      note:"与 protagonist 相对；未必是‘坏人’。" }],
    syn:["rival","foe"], ant:["protagonist"], synDiff:"" },

  { w:"narrator", ipa:"/nəˈreɪtə(r)/", pos:"n.", cat:"英语文学",
    senses:[{ def:"叙述者", ex:["The narrator is unreliable.",
      "A first-person narrator tells the tale.",
      "The narrator comments on the action."],
      note:"narrative 叙事；unreliable narrator 不可靠叙述者（高频考点）。" }],
    syn:["storyteller"], ant:[], synDiff:"" },

  { w:"denouement", ipa:"/deɪˈnuːmɒ̃/", pos:"n.", cat:"英语文学",
    senses:[{ def:"结局；收场", ex:["The denouement revealed the spy.",
      "The denouement felt rushed.",
      "All threads meet at the denouement."],
      note:"法语；情节‘解开/收束’。" }],
    syn:["ending","resolution"], ant:[], synDiff:"" },

  { w:"catharsis", ipa:"/kəˈθɑːsɪs/", pos:"n.", cat:"英语文学",
    senses:[{ def:"（悲剧的）宣泄；净化", ex:["The play offered emotional catharsis.",
      "Tragedy aims at catharsis.",
      "Crying brought a sense of catharsis."],
      note:"亚里士多德；通过怜悯恐惧达到净化。" }],
    syn:["relief","purging"], ant:[], synDiff:"" },

  { w:"subplot", ipa:"/ˈsʌbplɒt/", pos:"n.", cat:"英语文学",
    senses:[{ def:"次要情节", ex:["A romance forms the subplot.",
      "The subplot mirrors the main plot.",
      "The subplot resolves by the end."],
      note:"main plot 主情节；subplot 支线。" }],
    syn:["side story"], ant:["main plot"], synDiff:"" },

  { w:"epithet", ipa:"/ˈepɪθet/", pos:"n.", cat:"英语文学",
    senses:[{ def:"（修饰性）称号；绰号", ex:["‘The Great’ is an epithet.",
      "Homer uses fixed epithets.",
      "He earned the epithet ‘the Wise’."],
      note:"描述性形容词/称号；有时指‘贬称’。" }],
    syn:["title","nickname"], ant:[], synDiff:"" },

  { w:"in medias res", ipa:"/ɪn ˈmeɪdiəs reɪs/", pos:"n.", cat:"英语文学",
    senses:[{ def:"从中间入手（开篇即高潮）", ex:["The epic opens in medias res.",
      "The film begins in medias res.",
      "In medias res hooks the reader fast."],
      note:"拉丁‘in the middle of things’；叙事技巧。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"pastoral elegy", ipa:"/ˈpɑːstərəl ˈelədʒi/", pos:"n.", cat:"英语文学",
    senses:[{ def:"田园挽歌", ex:["Lycidas is a pastoral elegy.",
      "The pastoral elegy mourns a shepherd.",
      "Milton wrote a famous pastoral elegy."],
      note:"结合田园+哀悼；如 Milton 的 Lycidas。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"ballad", ipa:"/ˈbæləd/", pos:"n.", cat:"英语文学",
    senses:[{ def:"民谣；叙事诗", ex:["The ballad told of a lost love.",
      "A folk ballad circled the village.",
      "He set the ballad to music."],
      note:"叙事性歌谣；ballad stanza 民谣诗节。" }],
    syn:["folk song","narrative poem"], ant:[], synDiff:"" },

  { w:"ode", ipa:"/əʊd/", pos:"n.", cat:"英语文学",
    senses:[{ def:"颂诗", ex:["Keats wrote an ode to a nightingale.",
      "The ode praises autumn.",
      "An ode addresses its subject directly."],
      note:"lyric poem 抒情诗的一种；直接赞颂。" }],
    syn:["paean"], ant:[], synDiff:"" },

  { w:"soliloquy", ipa:"/səˈlɪləkwi/", pos:"n.", cat:"英语文学",
    senses:[{ def:"（戏剧）独白", ex:["Hamlet's soliloquy ponders death.",
      "The soliloquy reveals inner doubt.",
      "She delivered the soliloquy alone on stage."],
      note:"旁若无人的自言自语；monologue 泛指独白。" }],
    syn:["monologue"], ant:[], synDiff:"" },

  { w:"epigraph", ipa:"/ˈepɪɡrɑːf/", pos:"n.", cat:"英语文学",
    senses:[{ def:"（卷首/篇首）引文", ex:["The novel opens with an epigraph.",
      "The epigraph sets the tone.",
      "He chose a line from Dante as epigraph."],
      note:"置于作品前的引语；与 epilogue 尾声不同。" }],
    syn:["quotation","motto"], ant:["epilogue"], synDiff:"" },

  { w:"motif", ipa:"/məʊˈtiːf/", pos:"n.", cat:"英语文学",
    senses:[{ def:"（反复出现的）主题/动机", ex:["The bird is a recurring motif.",
      "Light is a motif in the film.",
      "The composer states the motif twice."],
      note:"leitmotif 主导动机；与 theme 近但更小更具体。" }],
    syn:["theme","pattern"], ant:[], synDiff:"" },

  { w:"caricature", ipa:"/ˈkærɪkətʃʊə(r)/", pos:"n.", cat:"英语文学",
    senses:[{ def:"漫画；夸张讽刺", ex:["The cartoon was a caricature of the mayor.",
      "He drew a cruel caricature.",
      "The speech was a caricature of reason."],
      note:"夸张讽刺画/文；也作动词。" }],
    syn:["parody","satire"], ant:[], synDiff:"" },

  // ============== 医疗健康（补充，冲到约54） ==============
  { w:"symptomatic", ipa:"/ˌsɪmptəˈmætɪk/", pos:"adj.", cat:"医疗健康",
    senses:[{ def:"有症状的；作为征兆的", ex:["He is symptomatic and must isolate.",
      "The rash is symptomatic of allergy.",
      "Low turnout is symptomatic of apathy."],
      note:"反义 asymptomatic 无症状；也喻‘是…征兆’。" }],
    syn:["indicative","telling"], ant:["asymptomatic"], synDiff:"" },

  { w:"prognostic", ipa:"/prɒɡˈnɒstɪk/", pos:"adj.", cat:"医疗健康",
    senses:[{ def:"预后的；预示的", ex:["The marker is prognostic of outcome.",
      "Prognostic factors guide treatment.",
      "Age is a prognostic variable."],
      note:"来自 prognosis；predictive 预测性。" }],
    syn:["predictive","indicative"], ant:[], synDiff:"" },

  { w:"remission", ipa:"/rɪˈmɪʃn/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"（病）缓解；豁免", ex:["The cancer is in remission.",
      "She has been in remission for years.",
      "The tax was granted a remission."],
      note:"疾病减轻/消失期；与 relapse 复发相对。" }],
    syn:["recovery","abatement"], ant:["relapse","recurrence"], synDiff:"" },

  { w:"morbidity", ipa:"/mɔːˈbɪdəti/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"发病率；病态", ex:["The morbidity rate rose sharply.",
      "Smoking raises morbidity.",
      "Morbidity burdens the health system."],
      note:"与 mortality 死亡率不同；morbid 病态的。" }],
    syn:["illness","sickness"], ant:["mortality"], synDiff:"" },

  { w:"mortality", ipa:"/mɔːˈtæləti/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"死亡率；必死性", ex:["The mortality rate fell this year.",
      "Infant mortality is a key metric.",
      "The disease has high mortality."],
      note:"death rate；与 morbidity 发病率相对。" }],
    syn:["death rate"], ant:["survival"], synDiff:"" },

  { w:"benign", ipa:"/bɪˈnaɪn/", pos:"adj.", cat:"医疗健康",
    senses:[{ def:"良性的（非癌）", ex:["The tumour was benign.",
      "A benign growth needs no surgery.",
      "The lesion proved benign."],
      note:"反义 malignant 恶性；benign 也指‘温和的’。" }],
    syn:["harmless","gentle"], ant:["malignant"], synDiff:"" },

  { w:"malignant", ipa:"/məˈlɪɡnənt/", pos:"adj.", cat:"医疗健康",
    senses:[{ def:"恶性的（癌）", ex:["The biopsy was malignant.",
      "Malignant cells spread fast.",
      "A malignant tumour needs urgent care."],
      note:"反义 benign；malignancy 恶性。" }],
    syn:["cancerous","virulent"], ant:["benign"], synDiff:"" },

  { w:"inoculate", ipa:"/ɪˈnɒkjuleɪt/", pos:"v.", cat:"医疗健康",
    senses:[{ def:"接种；灌输", ex:["They inoculated the children early.",
      "The serum inoculates against flu.",
      "Schools inoculate pupils each autumn."],
      note:"inoculation 接种；与 vaccinate 近（inoculate 更泛）。" }],
    syn:["vaccinate","immunise"], ant:[], synDiff:"" },

  { w:"anaesthetic", ipa:"/ˌænəsˈθetɪk/", pos:"n./adj.", cat:"医疗健康",
    senses:[{ def:"麻醉剂", ex:["The surgeon used a local anaesthetic.",
      "She woke after the anaesthetic.",
      "The anaesthetic numbed the area."],
      note:"美 anesthetic；general/local 全/局麻。" }],
    syn:["numbing agent"], ant:[], synDiff:"" },

  { w:"nausea", ipa:"/ˈnɔːziə/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"恶心", ex:["The drug caused nausea.",
      "She felt nausea on the boat.",
      "Nausea passed by morning."],
      note:"nauseous 感到恶心；也喻‘极度厌恶’。" }],
    syn:["queasiness","sickness"], ant:[], synDiff:"" },

  { w:"palatable", ipa:"/ˈpælətəbl/", pos:"adj.", cat:"医疗健康",
    senses:[{ def:"可口的；可接受的", ex:["The medicine is barely palatable.",
      "A palatable compromise emerged.",
      "The broth was palatable and warm."],
      note:"palate 上颚/味觉；喻‘可接受’。" }],
    syn:["tasty","acceptable"], ant:["unpalatable"], synDiff:"" },

  { w:"lesion", ipa:"/ˈliːʒn/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"损伤；病灶", ex:["The scan showed a brain lesion.",
      "The skin lesion healed slowly.",
      "The lesion was benign."],
      note:"组织损伤/病变；如 skin/mucosal lesion。" }],
    syn:["wound","injury"], ant:[], synDiff:"" },

  { w:"chronicity", ipa:"/krɒˈnɪsəti/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"慢性（程度）", ex:["The chronicity worried the doctor.",
      "Chronicity reduces quality of life.",
      "We measured the chronicity of pain."],
      note:"chronic 的名词化；长期不愈状态。" }],
    syn:["persistence"], ant:[], synDiff:"" },

  { w:"trauma", ipa:"/ˈtrɔːmə/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"创伤；外伤", ex:["The crash left physical trauma.",
      "She counsels victims of trauma.",
      "The war caused deep trauma."],
      note:"traumatic 创伤的；psychological trauma 心理创伤。" }],
    syn:["injury","shock"], ant:[], synDiff:"" },

  { w:"palliative", ipa:"/ˈpæliətɪv/", pos:"adj./n.", cat:"医疗健康",
    senses:[{ def:"姑息的；缓解剂", ex:["The care is palliative, not curative.",
      "A palliative eased the pain.",
      "Palliative care improves comfort."],
      note:"palliative care 姑息治疗（舒缓疗护）；非治愈。" }],
    syn:["relieving","soothing"], ant:["curative"], synDiff:"" },

  { w:"incidence", ipa:"/ˈɪnsɪdəns/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"发病率；发生频率", ex:["The incidence of flu peaks in winter.",
      "Higher incidence alarms health bodies.",
      "We tracked the incidence over a decade."],
      note:"与 prevalence 患病率不同（incidence=新发）。" }],
    syn:["rate","frequency"], ant:[], synDiff:"" },

  { w:"aetiology", ipa:"/ˌiːtiˈɒlədʒi/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"病因学；成因", ex:["The aetiology remains unclear.",
      "Smoking is the aetiology in many cases.",
      "They studied the aetiology of the disease."],
      note:"美 etiology；疾病起因研究。" }],
    syn:["cause","origin"], ant:[], synDiff:"" },

  { w:"analgesic", ipa:"/ˌænlˈdʒiːzɪk/", pos:"adj./n.", cat:"医疗健康",
    senses:[{ def:"止痛的；镇痛药", ex:["She took an analgesic for the pain.",
      "Aspirin is a common analgesic.",
      "The analgesic dulled the ache."],
      note:"analgesia 痛觉缺失；painkiller 近义。" }],
    syn:["painkiller"], ant:["analgesic-free"], synDiff:"" },

  // ============== 法律政治（补充，冲到约54） ==============
  { w:"legislation", ipa:"/ˌledʒɪsˈleɪʃn/", pos:"n.", cat:"法律政治",
    senses:[{ def:"立法；法律", ex:["The legislation passed both houses.",
      "New legislation bans the practice.",
      "They drafted the legislation carefully."],
      note:"legislate 立法；legislature 立法机关。" }],
    syn:["law","act"], ant:[], synDiff:"" },

  { w:"enact", ipa:"/ɪˈnækt/", pos:"v.", cat:"法律政治",
    senses:[{ def:"颁布；制定（法律）", ex:["Congress enacted the bill.",
      "The law was enacted in 1990.",
      "Parliament enacted sweeping reform."],
      note:"enactment 立法/ enact 演出（双义）。" }],
    syn:["pass","ordain"], ant:["repeal"], synDiff:"" },

  { w:"repeal", ipa:"/rɪˈpiːl/", pos:"v./n.", cat:"法律政治",
    senses:[{ def:"废除（法律）", ex:["The Act was repealed last year.",
      "They moved to repeal the tax.",
      "Repeal reversed the old law."],
      note:"与 enact 相对；abolish 近义但更泛。" }],
    syn:["abolish","revoke"], ant:["enact","pass"], synDiff:"" },

  { w:"mandate", ipa:"/ˈmændeɪt/", pos:"n./v.", cat:"法律政治",
    senses:[{ def:"授权；委任；命令", ex:["The election gave a clear mandate.",
      "The UN mandated a ceasefire.",
      "He claimed a mandate to reform."],
      note:"民意授权；mandatory 强制的。" }],
    syn:["authority","commission"], ant:[], synDiff:"" },

  { w:"treaty", ipa:"/ˈtriːti/", pos:"n.", cat:"法律政治",
    senses:[{ def:"条约", ex:["The treaty ended the war.",
      "Both sides signed the treaty.",
      "The treaty binds all parties."],
      note:"international treaty 国际条约；ratify 批准。" }],
    syn:["pact","accord"], ant:[], synDiff:"" },

  { w:"bipartisan", ipa:"/ˌbaɪˈpɑːtɪzæn/", pos:"adj.", cat:"法律政治",
    senses:[{ def:"两党的；跨党派的", ex:["The bill won bipartisan support.",
      "A bipartisan committee was formed.",
      "Bipartisan consensus is rare."],
      note:"bi- 两 + partisan 党派；跨党合作。" }],
    syn:["cross-party"], ant:["partisan"], synDiff:"" },

  { w:"gerrymander", ipa:"/ˈdʒeriˌmændə(r)/", pos:"v./n.", cat:"法律政治",
    senses:[{ def:"（为胜选）操纵选区划分", ex:["They gerrymandered the districts.",
      "Gerrymandering skews representation.",
      "The court struck down the gerrymander."],
      note:"源自 Gov. Gerry + salamander；选举操纵。" }],
    syn:["manipulate"], ant:[], synDiff:"" },

  { w:"filibuster", ipa:"/ˈfɪlɪbʌstə(r)/", pos:"n./v.", cat:"法律政治",
    senses:[{ def:"（议会）冗长演说阻挠", ex:["He staged a filibuster for hours.",
      "The filibuster blocked the vote.",
      "They ended the filibuster by cloture."],
      note:"美国参议院阻挠议事；cloture 终结辩论。" }],
    syn:["obstruction"], ant:[], synDiff:"" },

  { w:"plaintiff", ipa:"/ˈpleɪntɪf/", pos:"n.", cat:"法律政治",
    senses:[{ def:"原告（民事）", ex:["The plaintiff sued for damages.",
      "The plaintiff bore the burden of proof.",
      "The court ruled for the plaintiff."],
      note:"刑事对应 prosecution；defendant 被告。" }],
    syn:["claimant"], ant:["defendant"], synDiff:"" },

  { w:"testimony", ipa:"/ˈtestɪməni/", pos:"n.", cat:"法律政治",
    senses:[{ def:"证词；证言", ex:["Her testimony swayed the jury.",
      "The witness gave false testimony.",
      "The testimony was recorded under oath."],
      note:"testify 作证；under oath 宣誓下。" }],
    syn:["evidence","witness"], ant:[], synDiff:"" },

  { w:"verdict", ipa:"/ˈvɜːdɪkt/", pos:"n.", cat:"法律政治",
    senses:[{ def:"裁决；结论", ex:["The jury returned a guilty verdict.",
      "The verdict surprised observers.",
      "Public verdict was harsh."],
      note:"court verdict 法庭裁决；也喻‘定论’。" }],
    syn:["judgment","finding"], ant:[], synDiff:"" },

  { w:"acquit", ipa:"/əˈkwɪt/", pos:"v.", cat:"法律政治",
    senses:[{ def:"宣判无罪", ex:["The jury acquitted him.",
      "She was acquitted for lack of proof.",
      "The court acquitted all defendants."],
      note:"acquittal 无罪判决；反义 convict。" }],
    syn:["clear","exonerate"], ant:["convict"], synDiff:"" },

  { w:"convict", ipa:"/kənˈvɪkt/", pos:"v.", cat:"法律政治",
    senses:[{ def:"宣判有罪", ex:["The court convicted the accused.",
      "He was convicted of fraud.",
      "The jury convicted on all counts."],
      note:"名词 /ˈkɒnvɪkt/ 指‘囚犯’；反义 acquit。" }],
    syn:["find guilty"], ant:["acquit"], synDiff:"" },

  { w:"jurisprudence", ipa:"/ˌdʒʊərɪsˈpruːdns/", pos:"n.", cat:"法律政治",
    senses:[{ def:"法学；判例体系", ex:["She studied jurisprudence at law school.",
      "Constitutional jurisprudence evolved.",
      "His jurisprudence favours restraint."],
      note:"法哲学/法律体系；judicial 司法的。" }],
    syn:["legal theory","law"], ant:[], synDiff:"" },

  { w:"due process", ipa:"/ˈdjuː ˈprəʊses/", pos:"n.", cat:"法律政治",
    senses:[{ def:"正当程序", ex:["He was denied due process.",
      "Due process protects the accused.",
      "The clause guarantees due process."],
      note:"宪法权利；法定程序公正。" }],
    syn:["fair procedure"], ant:[], synDiff:"" },

  { w:"sovereign", ipa:"/ˈsɒvrɪn/", pos:"adj./n.", cat:"法律政治",
    senses:[{ def:"有主权的；君主", ex:["A sovereign state makes its own laws.",
      "The sovereign ratified the treaty.",
      "They defended sovereign rights."],
      note:"sovereignty 主权；sovereign 也指‘君主/金币’。" }],
    syn:["independent","monarch"], ant:["subject"], synDiff:"" },

  { w:"federalism", ipa:"/ˈfedərəlɪzəm/", pos:"n.", cat:"法律政治",
    senses:[{ def:"联邦制", ex:["Federalism divides power by design.",
      "The debate tests American federalism.",
      "Federalism balances centre and states."],
      note:"federal 联邦的；与 unitary 单一制相对。" }],
    syn:[], ant:["unitarism"], synDiff:"" },

  { w:"proclamation", ipa:"/ˌprɒkləˈmeɪʃn/", pos:"n.", cat:"法律政治",
    senses:[{ def:"公告；宣告", ex:["The king issued a proclamation.",
      "The proclamation freed the enslaved.",
      "The proclamation took effect at once."],
      note:"proclaim 宣告；正式文告。" }],
    syn:["declaration","announcement"], ant:[], synDiff:"" },

  // ============== 美食食品（补充，冲到约54） ==============
  { w:"umami", ipa:"/uːˈmɑːmi/", pos:"n.", cat:"美食食品",
    senses:[{ def:"鲜味", ex:["Miso adds umami depth.",
      "The broth is rich in umami.",
      "Umami balances salt and acid."],
      note:"第五味觉；来自日语。" }],
    syn:["savouriness"], ant:[], synDiff:"" },

  { w:"braise", ipa:"/breɪz/", pos:"v.", cat:"美食食品",
    senses:[{ def:"炖；焖（先煎后慢煨）", ex:["Braise the beef in red wine.",
      "She braised the lamb for two hours.",
      "Braise the veg slowly in stock."],
      note:"braising 炖焖；与 stew 近但先煎。" }],
    syn:["stew","pot-roast"], ant:[], synDiff:"" },

  { w:"blanch", ipa:"/blɑːntʃ/", pos:"v.", cat:"美食食品",
    senses:[{ def:"焯；去皮前烫煮", ex:["Blanch the almonds to peel them.",
      "Blanch the beans for a minute.",
      "Blanch then ice the broccoli."],
      note:"沸水速烫；blanch 也指‘（脸色）发白’。" }],
    syn:["scald","parboil"], ant:[], synDiff:"" },

  { w:"sautéed", ipa:"/ˈsəʊteɪd/", pos:"adj.", cat:"美食食品",
    senses:[{ def:"嫩煎的", ex:["Sautéed mushrooms smelled great.",
      "The sautéed greens kept their colour.",
      "He served sautéed pears."],
      note:"来 sauté；少油快煎。" }],
    syn:["fried"], ant:[], synDiff:"" },

  { w:"glaze", ipa:"/ɡleɪz/", pos:"v./n.", cat:"美食食品",
    senses:[{ def:"上光；糖衣；釉", ex:["Glaze the ham with honey.",
      "The cake got a shiny glaze.",
      "Brush the pastry with egg glaze."],
      note:"food glaze 糖衣/蛋液；也指‘陶瓷釉’。" }],
    syn:["icing","coating"], ant:[], synDiff:"" },

  { w:"roux", ipa:"/ruː/", pos:"n.", cat:"美食食品",
    senses:[{ def:"（油面）糊；增稠底", ex:["Make a roux with butter and flour.",
      "The sauce starts from a dark roux.",
      "Whisk the roux to avoid lumps."],
      note:"法餐基础；黄油+面粉炒制增稠。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"bias", ipa:"/ˈbaɪəs/", pos:"n.", cat:"美食食品",
    senses:[{ def:"（布纹）斜裁；偏见", ex:["Cut the cloth on the bias.",
      "The bias gives a softer drape.",
      "A bias-cut skirt swings as she walks."],
      note:"此处为裁缝‘斜裁’；也常用‘偏见’义。" }],
    syn:["diagonal","prejudice"], ant:[], synDiff:"" },

  { w:"pantry", ipa:"/ˈpæntri/", pos:"n.", cat:"美食食品",
    senses:[{ def:"食品储藏室", ex:["The pantry held tins and pasta.",
      "She restocked the pantry.",
      "The pantry sat off the kitchen."],
      note:"存放干货；非冰箱。" }],
    syn:["larder","cupboard"], ant:[], synDiff:"" },

  { w:"confection", ipa:"/kənˈfekʃn/", pos:"n.", cat:"美食食品",
    senses:[{ def:"甜食；糖果（制品）", ex:["The shop sold fine confections.",
      "A confection of sugar and nuts.",
      "The confection melted on the tongue."],
      note:"confectionery 糖果业；甜点统称。" }],
    syn:["sweet","candy"], ant:[], synDiff:"" },

  { w:"beverage", ipa:"/ˈbevərɪdʒ/", pos:"n.", cat:"美食食品",
    senses:[{ def:"饮料", ex:["The meal came with a beverage.",
      "Alcoholic beverages are restricted.",
      "A hot beverage warmed her hands."],
      note:"正式‘饮料’；drink 口语。" }],
    syn:["drink"], ant:[], synDiff:"" },

  { w:"aroma", ipa:"/əˈrəʊmə/", pos:"n.", cat:"美食食品",
    senses:[{ def:"芳香（食物/酒）", ex:["The aroma of coffee filled the room.",
      "The bread had a nutty aroma.",
      "Wine releases its aroma as it breathes."],
      note:"褒义‘香气’；与 scent/smell 近但更悦人。" }],
    syn:["scent","fragrance"], ant:["stench"], synDiff:"" },

  { w:"pungent", ipa:"/ˈpʌndʒənt/", pos:"adj.", cat:"美食食品",
    senses:[{ def:"（气味/味道）刺鼻的；辛辣的", ex:["The cheese was pungent.",
      "Garlic has a pungent smell.",
      "A pungent sauce cleared the nose."],
      note:"sharp/strong 刺激感官；褒贬皆可。" }],
    syn:["sharp","tangy"], ant:["bland"], synDiff:"" },

  { w:"bland", ipa:"/blænd/", pos:"adj.", cat:"美食食品",
    senses:[{ def:"清淡的；乏味的", ex:["The diet food was bland.",
      "A bland sauce suited the fish.",
      "His speech was bland and safe."],
      note:"食物‘淡’；也指‘平淡乏味’。" }],
    syn:["tasteless","mild"], ant:["pungent","flavourful"], synDiff:"" },

  { w:"savoury", ipa:"/ˈseɪvəri/", pos:"adj.", cat:"美食食品",
    senses:[{ def:"咸鲜的；开胃的", ex:["A savoury pie for lunch.",
      "The tart was more savoury than sweet.",
      "Savoury snacks beat sweets."],
      note:"咸口（非甜）；美 savory；umami 鲜。" }],
    syn:["salty","piquant"], ant:["sweet"], synDiff:"" },

  { w:"tangy", ipa:"/ˈtæŋi/", pos:"adj.", cat:"美食食品",
    senses:[{ def:"爽口酸辣的", ex:["The yoghurt was tangy.",
      "A tangy dressing lifted the salad.",
      "The fruit had a tangy zest."],
      note:"sharp but pleasant；与 pungent 比更宜人。" }],
    syn:["sharp","zesty"], ant:["bland"], synDiff:"" },

  { w:"glutton", ipa:"/ˈɡlʌtn/", pos:"n.", cat:"美食食品",
    senses:[{ def:"贪吃者", ex:["He is a glutton for sweets.",
      "The glutton cleaned his plate twice.",
      "A glutton eats far beyond need."],
      note:"gluttony 暴食（七宗罪之一）；贬义。" }],
    syn:["gourmand"], ant:["ascetic"], synDiff:"" },

  { w:"gourmet", ipa:"/ˈɡʊəmeɪ/", pos:"n./adj.", cat:"美食食品",
    senses:[{ def:"美食家；精致的", ex:["A gourmet judged the dish.",
      "Gourmet coffee costs more.",
      "He is a true gourmet."],
      note:"美食鉴赏者；gourmet food 精致料理。" }],
    syn:["connoisseur","epicure"], ant:["glutton"], synDiff:"" },

  { w:"culinary", ipa:"/ˈkʌlɪnəri/", pos:"adj.", cat:"美食食品",
    senses:[{ def:"烹饪的；厨房的", ex:["She has culinary talent.",
      "The culinary tradition is old.",
      "A culinary school trained him."],
      note:"culinary arts 烹饪艺术；与 cuisine 菜系近。" }],
    syn:["cooking"], ant:[], synDiff:"" },

  // ============== 外貌性格（补充，冲到约58） ==============
  { w:"luminous", ipa:"/ˈluːmɪnəs/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"发光的；明亮的（眼神/肌肤）", ex:["Her luminous eyes met his.",
      "The luminous skin glowed.",
      "A luminous smile lit the room."],
      note:"luminosity 光亮；喻‘明亮动人’。" }],
    syn:["radiant","glowing"], ant:["dim"], synDiff:"" },

  { w:"vivacious", ipa:"/vɪˈveɪʃəs/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"活泼的；生机勃勃的", ex:["A vivacious hostess enlivened dinner.",
      "Her vivacious laugh was infectious.",
      "The vivacious girl danced through the room."],
      note:"vivacity 活泼；褒义‘灵动有活力’。" }],
    syn:["lively","animated"], ant:["listless"], synDiff:"" },

  { w:"demure", ipa:"/dɪˈmjʊə(r)/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"端庄娴静的", ex:["She gave a demure smile.",
      "A demure young woman bowed.",
      "The demure dress was plain but neat."],
      note:"demure 含蓄端庄；可褒可略带‘拘谨’。" }],
    syn:["modest","reserved"], ant:["brazen","bold"], synDiff:"" },

  { w:"winsome", ipa:"/ˈwɪnsəm/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"讨人喜欢的；甜美的", ex:["A winsome child waved hello.",
      "Her winsome smile charmed all.",
      "The winsome tune stayed with him."],
      note:"winsomeness 讨喜；甜美可人。" }],
    syn:["charming","engaging"], ant:["repellent"], synDiff:"" },

  { w:"pallid", ipa:"/ˈpælɪd/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"苍白的（不健康）", ex:["His pallid face worried the nurse.",
      "A pallid glow lit the sky.",
      "She looked pallid after the fever."],
      note:"pallor 苍白；比 pale 更‘病态/无神’。" }],
    syn:["pale","wan"], ant:["ruddy","flushed"], synDiff:"" },

  { w:"rubicund", ipa:"/ˈruːbɪkʌnd/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"（面色）红润的", ex:["The rubicund farmer laughed.",
      "A rubicund complexion shows health.",
      "His rubicund cheeks reddened further."],
      note:"面色红润（常带圆满健康感）；与 ruddy 近。" }],
    syn:["ruddy","florid"], ant:["pallid"], synDiff:"" },

  { w:"saturnine", ipa:"/ˈsætənaɪn/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"阴郁的；沉默寡言的", ex:["A saturnine man brooded in the corner.",
      "His saturnine look chilled the room.",
      "The saturnine poet wrote of gloom."],
      note:"古典‘土星气质’忧郁；gloomy 阴沉。" }],
    syn:["gloomy","morose"], ant:["sanguine","cheerful"], synDiff:"" },

  { w:"foppish", ipa:"/ˈfɒpɪʃ/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"（男子）过分讲究穿戴的；纨绔的", ex:["A foppish dandy adjusted his cuff.",
      "His foppish manner amused the court.",
      "The foppish lord lolled in his chair."],
      note:"fop 纨绔子；贬义‘浮夸尚饰’。" }],
    syn:["dandified","affected"], ant:["austere"], synDiff:"" },

  { w:"weather-beaten", ipa:"/ˈweðə biːtn/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"饱经风霜的", ex:["The sailor's weather-beaten face told of years at sea.",
      "A weather-beaten hut stood on the cliff.",
      "His weather-beaten hands gripped the oar."],
      note:"风吹日晒的沧桑；也指物‘破旧’。" }],
    syn:["worn","sunburnt"], ant:["smooth"], synDiff:"" },

  { w:"gawky", ipa:"/ˈɡɔːki/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"笨拙的；不协调的（多指青少年）", ex:["A gawky teenager tripped on the step.",
      "Her gawky grace amused him.",
      "The gawky colt lurched to its feet."],
      note:"awkward 笨拙；gawky 偏‘高大不协调’。" }],
    syn:["awkward","ungainly"], ant:["graceful"], synDiff:"" },

  { w:"meticulous", ipa:"/məˈtɪkjələs/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"一丝不苟的；极仔细的", ex:["A meticulous editor caught the error.",
      "He is meticulous about dress.",
      "Her meticulous notes saved the day."],
      note:"meticulousness 细致；褒义认真。" }],
    syn:["careful","thorough"], ant:["careless","sloppy"], synDiff:"" },

  { w:"irascible", ipa:"/ɪˈræsəbl/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"易怒的", ex:["An irascible old man snapped at noise.",
      "His irascible temper flared fast.",
      "The irascible cat swiped at intruders."],
      note:"irascibility 暴躁；近 choleric。" }],
    syn:["touchy","hot-tempered"], ant:["placid","even-tempered"], synDiff:"" },

  { w:"benevolent", ipa:"/bəˈnevələnt/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"仁慈的；乐善好施的", ex:["A benevolent patron funded the school.",
      "Her benevolent smile reassured the child.",
      "The benevolent king eased the tax."],
      note:"benevolence 仁慈；反义 malevolent 恶意的。" }],
    syn:["kind","charitable"], ant:["malevolent","cruel"], synDiff:"" },

  { w:"malevolent", ipa:"/məˈlevələnt/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"恶意的；怀恨的", ex:["A malevolent glare froze the room.",
      "His malevolent plot failed.",
      "The malevolent sprite cursed the well."],
      note:"malevolence 恶意；反义 benevolent。" }],
    syn:["malicious","spiteful"], ant:["benevolent","kind"], synDiff:"" },

  { w:"unctuous", ipa:"/ˈʌŋktʃuəs/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"（态度）过分热络奉承的", ex:["The unctuous waiter over-praised the wine.",
      "His unctuous manner rang false.",
      "She disliked the unctuous salesman."],
      note:"贬义；油滑谄媚。" }],
    syn:["oily","fulsome"], ant:["sincere"], synDiff:"" },

  { w:"sagacious", ipa:"/səˈɡeɪʃəs/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"睿智的；有洞察力的", ex:["A sagacious elder advised the chief.",
      "Her sagacious remark settled the row.",
      "The sagacious fox avoided the trap."],
      note:"sagacity 睿智；比 wise 更‘通达世情’。" }],
    syn:["wise","shrewd"], ant:["foolish"], synDiff:"" },

  { w:"obsequious", ipa:"/əbˈsiːkwiəs/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"谄媚的；过度恭顺的", ex:["The obsequious clerk flattered the boss.",
      "His obsequious bow looked false.",
      "Obsequious attendants crowded the throne."],
      note:"obsequiousness 逢迎；贬义‘奴颜婢膝’。" }],
    syn:["sycophantic","servile"], ant:["assertive"], synDiff:"" },

  { w:"peripatetic", ipa:"/ˌperɪpəˈtetɪk/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"四处走动的；巡回的", ex:["A peripatetic teacher visited many schools.",
      "His peripatetic life spanned continents.",
      "The peripatetic preacher walked the towns."],
      note:"peripatetic 常移动的；亚里士多德‘漫步学派’。" }],
    syn:["itinerant","wandering"], ant:["sedentary"], synDiff:"" },

  { w:"iconoclastic", ipa:"/aɪˌkɒnəˈklæstɪk/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"反传统的；打破偶像的", ex:["An iconoclastic thinker mocked norms.",
      "Her iconoclastic art shocked critics.",
      "The iconoclastic reformer broke the rules."],
      note:"iconoclast 反传统者；挑战成规。" }],
    syn:["radical","unconventional"], ant:["traditional"], synDiff:"" },

  { w:"ebullient", ipa:"/ɪˈbʌliənt/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"热情奔放的；沸腾般的", ex:["An ebullient crowd cheered the win.",
      "Her ebullient greeting lit the room.",
      "The ebullient child bounced with joy."],
      note:"ebullience 奔放热情；比 enthusiastic 更外放。" }],
    syn:["exuberant","buoyant"], ant:["listless"], synDiff:"" },

  // ============== 学术写作（补充，冲到约66） ==============
  { w:"postulate", ipa:"/ˈpɒstjəleɪt/", pos:"v./n.", cat:"学术写作",
    senses:[{ def:"假定； postulate", ex:["We postulate a single cause.",
      "The theory postulates free markets.",
      "This postulate underlies the model."],
      note:"假设性前提；比 assume 更‘作为立论基础’。" }],
    syn:["assume","hypothesize"], ant:[], synDiff:"" },

  { w:"rebut", ipa:"/rɪˈbʌt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"反驳；驳回", ex:["She rebutted the claim with data.",
      "The essay rebuts the counter-argument.",
      "He rebutted each point in turn."],
      note:"rebuttal 反驳；与 refute 近但 rebut 偏‘逐条回应’。" }],
    syn:["refute","disprove"], ant:["support"], synDiff:"" },

  { w:"tenet", ipa:"/ˈtenet/", pos:"n.", cat:"学术写作",
    senses:[{ def:"信条；宗旨", ex:["A core tenet of the theory.",
      "They defended the tenet fiercely.",
      "This tenet guides the method."],
      note:"tenets 原则/教义；与 principle 近。" }],
    syn:["principle","doctrine"], ant:[], synDiff:"" },

  { w:"epoch", ipa:"/ˈiːpɒk/", pos:"n.", cat:"学术写作",
    senses:[{ def:"时代；纪元", ex:["The discovery opened a new epoch.",
      "An epoch of peace began.",
      "The epoch is marked by change."],
      note:"epoch-making 划时代的；比 era 更‘分界性’。" }],
    syn:["era","age"], ant:[], synDiff:"" },

  { w:"heuristic", ipa:"/hjʊˈrɪstɪk/", pos:"adj./n.", cat:"学术写作",
    senses:[{ def:"启发式的；经验法则", ex:["Use a heuristic to guess first.",
      "A heuristic guides but may err.",
      "Heuristic methods speed search."],
      note:"heuristics 经验法则；非严格证明但实用。" }],
    syn:["rule of thumb"], ant:["algorithmic"], synDiff:"" },

  { w:"discourse", ipa:"/ˈdɪskɔːs/", pos:"n.", cat:"学术写作",
    senses:[{ def:"论述；话语", ex:["Political discourse grew toxic.",
      "The discourse analysed the text.",
      "Academic discourse values precision."],
      note:"discourse 言说/论述；critical discourse 批判话语。" }],
    syn:["discussion","dialogue"], ant:[], synDiff:"" },

  { w:"caveat", ipa:"/ˈkæviæt/", pos:"n.", cat:"学术写作",
    senses:[{ def:"警告；但书", ex:["One caveat: the data are small.",
      "We add a caveat about bias.",
      "The caveat limits the claim."],
      note:"caveat emptor 买者自负；提醒性限制。" }],
    syn:["warning","qualification"], ant:[], synDiff:"" },

  { w:"paradox", ipa:"/ˈpærədɒks/", pos:"n.", cat:"学术写作",
    senses:[{ def:"悖论；似非而是", ex:["‘Less is more’ is a paradox.",
      "The finding is a paradox.",
      "He loves the paradox of freedom."],
      note:"paradoxical 矛盾的；self-contradictory 但含真理。" }],
    syn:["contradiction","absurdity"], ant:["axiom"], synDiff:"" },

  { w:"rigorous", ipa:"/ˈrɪɡərəs/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"严谨的；严格的", ex:["A rigorous method was used.",
      "The review was rigorous.",
      "Rigorous training built the skill."],
      note:"rigour 严谨；反义 lax 松懈。" }],
    syn:["strict","thorough"], ant:["lax"], synDiff:"" },

  { w:"empiricism", ipa:"/ɪmˈpɪrɪsɪzəm/", pos:"n.", cat:"学术写作",
    senses:[{ def:"经验主义", ex:["Empiricism trusts observation.",
      "His empiricism shaped the lab.",
      "Empiricism contrasts with rationalism."],
      note:"empirical 经验的；与 rationalism 理性主义相对。" }],
    syn:["experientialism"], ant:["rationalism"], synDiff:"" },

  { w:"anomaly", ipa:"/əˈnɒməli/", pos:"n.", cat:"学术写作",
    senses:[{ def:"异常；反常", ex:["The result was an anomaly.",
      "One anomaly broke the pattern.",
      "We explained the anomaly away."],
      note:"anomalous 异常的；偏离常态。" }],
    syn:["irregularity","deviation"], ant:["norm"], synDiff:"" },

  { w:"correlation", ipa:"/ˌkɒrəˈleɪʃn/", pos:"n.", cat:"学术写作",
    senses:[{ def:"相关（非因果）", ex:["There is a correlation, not causation.",
      "The correlation is weak.",
      "We found a strong correlation."],
      note:"correlate 相关；注意‘相关≠因果’。" }],
    syn:["association","link"], ant:[], synDiff:"" },

  { w:"methodology", ipa:"/ˌmeθəˈdɒlədʒi/", pos:"n.", cat:"学术写作",
    senses:[{ def:"方法论", ex:["The methodology is clearly stated.",
      "We adopted a mixed methodology.",
      "The methodology ensures validity."],
      note:"method 方法；methodology 方法的‘体系/学’。" }],
    syn:["approach","method"], ant:[], synDiff:"" },

  { w:"plausible", ipa:"/ˈplɔːzəbl/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"看似合理的", ex:["A plausible explanation emerged.",
      "The claim sounds plausible but unproven.",
      "He offered a plausible excuse."],
      note:"plausibility 可信度；未必真，仅‘像真的’。" }],
    syn:["believable","credible"], ant:["implausible"], synDiff:"" },

  { w:"definitive", ipa:"/dɪˈfɪnətɪv/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"确定的；权威的", ex:["The study is definitive.",
      "A definitive edition appeared.",
      "We await definitive proof."],
      note:"definitive 定论性；反义 tentative 暂定。" }],
    syn:["authoritative","conclusive"], ant:["tentative","provisional"], synDiff:"" },

  { w:"cumulative", ipa:"/ˈkjuːmjələtɪv/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"累积的", ex:["The effect is cumulative.",
      "Cumulative evidence mounted.",
      "Cumulative debt crushed him."],
      note:"cumulatively 累积地；叠加效应。" }],
    syn:["accumulative","growing"], ant:["isolated"], synDiff:"" },

  { w:"inherent", ipa:"/ɪnˈhɪərənt/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"内在的；固有的", ex:["Risk is inherent in the plan.",
      "An inherent flaw doomed it.",
      "The value is inherent, not added."],
      note:"inherently 内在地；与 intrinsic 近。" }],
    syn:["intrinsic","built-in"], ant:["extrinsic"], synDiff:"" },

  { w:"mitigate", ipa:"/ˈmɪtɪɡeɪt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"减轻；缓和", ex:["Steps mitigate the harm.",
      "The policy mitigates risk.",
      "Nothing mitigated his grief."],
      note:"mitigation 缓解；与 alleviate 近。" }],
    syn:["alleviate","lessen"], ant:["exacerbate","aggravate"], synDiff:"" },

  { w:"exacerbate", ipa:"/ɪɡˈzæsəbeɪt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"使恶化；加剧", ex:["The tax exacerbated inequality.",
      "His remark exacerbated the row.",
      "Drought exacerbated the crisis."],
      note:"exacerbation 恶化；反义 mitigate。" }],
    syn:["worsen","aggravate"], ant:["mitigate","ease"], synDiff:"" },

  // ============== 动植物（补充，冲到约98） ==============
  { w:"fauna", ipa:"/ˈfɔːnə/", pos:"n.", cat:"动植物",
    senses:[{ def:"动物群（某地区）", ex:["The island's fauna is unique.",
      "Marine fauna thrive here.",
      "The fauna includes rare birds."],
      note:"与 flora（植物群）相对；faunal 动物的。" }],
    syn:["animal life"], ant:["flora"], synDiff:"" },

  { w:"flora", ipa:"/ˈflɔːrə/", pos:"n.", cat:"动植物",
    senses:[{ def:"植物群", ex:["The tundra flora is sparse.",
      "Tropical flora dazzles botanists.",
      "The flora recovers after fire."],
      note:"与 fauna 相对；floral 植物的/花的。" }],
    syn:["plant life"], ant:["fauna"], synDiff:"" },

  { w:"conifer", ipa:"/ˈkɒnɪfə(r)/", pos:"n.", cat:"动植物",
    senses:[{ def:"针叶树；松柏类", ex:["Conifers keep leaves year-round.",
      "The conifer bore woody cones.",
      "Conifers dominate northern forests."],
      note:"cone-bearing 结球果；evergreen 多常绿。" }],
    syn:["evergreen"], ant:[], synDiff:"" },

  { w:"herbivore", ipa:"/ˈhɜːbɪvɔː(r)/", pos:"n.", cat:"动植物",
    senses:[{ def:"食草动物", ex:["The deer is a herbivore.",
      "Herbivores graze the plains.",
      "A herbivore eats no meat."],
      note:"与 carnivore 食肉、omnivore 杂食相对。" }],
    syn:["plant-eater"], ant:["carnivore"], synDiff:"" },

  { w:"carnivore", ipa:"/ˈkɑːnɪvɔː(r)/", pos:"n.", cat:"动植物",
    senses:[{ def:"食肉动物", ex:["The wolf is a carnivore.",
      "Carnivores need meat to live.",
      "A carnivore hunts at dusk."],
      note:"carnivorous 食肉的；与 herbivore 相对。" }],
    syn:["meat-eater"], ant:["herbivore"], synDiff:"" },

  { w:"omnivore", ipa:"/ˈɒmnɪvɔː(r)/", pos:"n.", cat:"动植物",
    senses:[{ def:"杂食动物", ex:["Humans are omnivores.",
      "Bears are omnivores too.",
      "An omnivore eats plants and meat."],
      note:"omni- 全；与 herbivore/carnivore 相对。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"pollinator", ipa:"/ˈpɒlɪneɪtə(r)/", pos:"n.", cat:"动植物",
    senses:[{ def:"传粉者", ex:["Bees are key pollinators.",
      "The pollinator visited each bloom.",
      "Loss of pollinators hurts crops."],
      note:"pollinate 传粉；传粉媒介（蜂/蝶/风）。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"evergreen", ipa:"/ˈevəɡriːn/", pos:"adj./n.", cat:"动植物",
    senses:[{ def:"常绿的", ex:["Pines are evergreen.",
      "The evergreen brightens winter.",
      "An evergreen keeps its leaves."],
      note:"与 deciduous 落叶相对；也喻‘长青’。" }],
    syn:["coniferous"], ant:["deciduous"], synDiff:"" },

  { w:"thrive", ipa:"/θraɪv/", pos:"v.", cat:"动植物",
    senses:[{ def:"茂盛；茁壮成长", ex:["Ferns thrive in shade.",
      "The species thrives in heat.",
      "Children thrive on routine."],
      note:"thriving 繁荣；反义 wither 枯萎。" }],
    syn:["flourish","prosper"], ant:["wither","decline"], synDiff:"" },

  { w:"wither", ipa:"/ˈwɪðə(r)/", pos:"v.", cat:"动植物",
    senses:[{ def:"枯萎；凋谢", ex:["The leaves withered in drought.",
      "Hope withered away.",
      "The flower withered by noon."],
      note:"withered 干枯；反义 thrive/bloom。" }],
    syn:["shrivel","fade"], ant:["thrive","bloom"], synDiff:"" },

  { w:"bloom", ipa:"/bluːm/", pos:"n./v.", cat:"动植物",
    senses:[{ def:"开花；盛开", ex:["The cherry trees bloom in spring.",
      "The bloom lasted a week.",
      "Her career is in full bloom."],
      note:"blossom 近义；也喻‘盛期’。" }],
    syn:["blossom","flower"], ant:["wither"], synDiff:"" },

  { w:"fungi", ipa:"/ˈfʌŋɡaɪ/", pos:"n.", cat:"动植物",
    senses:[{ def:"真菌（复数）", ex:["Fungi recycle dead matter.",
      "Mushrooms are fungi.",
      "Fungi thrive in damp wood."],
      note:"单数 fungus；与 plant/animal 并列三界之一。" }],
    syn:["mushrooms","moulds"], ant:[], synDiff:"" },

  { w:"reptile", ipa:"/ˈreptaɪl/", pos:"n.", cat:"动植物",
    senses:[{ def:"爬行动物", ex:["The lizard is a reptile.",
      "Reptiles are cold-blooded.",
      "The reptile basked on the rock."],
      note:"cold-blooded 冷血；snake/lizard/turtle 属之。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"amphibian", ipa:"/æmˈfɪbiən/", pos:"n.", cat:"动植物",
    senses:[{ def:"两栖动物", ex:["The frog is an amphibian.",
      "Amphibians live in water and land.",
      "Amphibian numbers are falling."],
      note:"frog/toad 属之；与 reptile 不同。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"primate", ipa:"/ˈpraɪmeɪt/", pos:"n.", cat:"动植物",
    senses:[{ def:"灵长类", ex:["Humans are primates.",
      "The primate groomed its young.",
      "Primates have large brains."],
      note:"apes/monkeys 属之；intelligence 高。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"migration", ipa:"/maɪˈɡreɪʃn/", pos:"n.", cat:"动植物",
    senses:[{ def:"迁徙", ex:["Bird migration follows the seasons.",
      "The migration crossed the strait.",
      "Climate shifts the migration route."],
      note:"migrate 迁徙；migratory 候的。" }],
    syn:["movement","transit"], ant:[], synDiff:"" },

  { w:"hibernation", ipa:"/ˌhaɪbəˈneɪʃn/", pos:"n.", cat:"动植物",
    senses:[{ def:"冬眠", ex:["Bears enter hibernation in winter.",
      "Hibernation saves energy.",
      "The animal woke from hibernation."],
      note:"hibernate 冬眠；与 estivation 夏眠相对。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"symbiosis", ipa:"/ˌsɪmbaɪˈəʊsɪs/", pos:"n.", cat:"动植物",
    senses:[{ def:"共生", ex:["Lichens show symbiosis.",
      "Symbiosis aids both species.",
      "The symbiosis is mutual."],
      note:"symbiotic 共生的；mutualism 互利共生。" }],
    syn:["mutualism"], ant:[], synDiff:"" },

  { w:"predation", ipa:"/prɪˈdeɪʃn/", pos:"n.", cat:"动植物",
    senses:[{ def:"捕食", ex:["Predation controls the herd.",
      "Predation shapes evolution.",
      "Predation risk changes behaviour."],
      note:"predator 捕食者；predatory 捕食性的。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"canopy", ipa:"/ˈkænəpi/", pos:"n.", cat:"动植物",
    senses:[{ def:"林冠层", ex:["Birds sing in the canopy.",
      "Light fades under the canopy.",
      "The canopy broke the storm."],
      note:"forest canopy 树冠；也指天篷。" }],
    syn:["cover"], ant:[], synDiff:"" },

  { w:"understory", ipa:"/ˈʌndəstɔːri/", pos:"n.", cat:"动植物",
    senses:[{ def:"林下层（灌木层）", ex:["Ferns fill the understory.",
      "The understory is dim and still.",
      "Shrubs form the understory."],
      note:"canopy 之下；林下层植被。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"endemic", ipa:"/enˈdemɪk/", pos:"adj.", cat:"动植物",
    senses:[{ def:"特有的（某地独有）", ex:["The lemur is endemic to Madagascar.",
      "Endemic species face risk.",
      "The bird is endemic here."],
      note:"与 exotic 外来相对；endemic 地域特有。" }],
    syn:["native","indigenous"], ant:["exotic"], synDiff:"" },

  { w:"invasive", ipa:"/ɪnˈveɪsɪv/", pos:"adj.", cat:"动植物",
    senses:[{ def:"入侵的（物种）", ex:["The plant is invasive.",
      "Invasive species crowd natives out.",
      "Invasive weeds spread fast."],
      note:"invasive species 入侵物种；生态危害。" }],
    syn:["alien"], ant:["native"], synDiff:"" },

  { w:"myriad", ipa:"/ˈmɪriəd/", pos:"adj./n.", cat:"动植物",
    senses:[{ def:"无数的；多种的", ex:["A myriad of insects teemed.",
      "The forest holds myriad life.",
      "Myriad stars lit the sky."],
      note:"myriad 极多；文学‘无数’。" }],
    syn:["countless","numerous"], ant:["few"], synDiff:"" },

  { w:"verdant", ipa:"/ˈvɜːdnt/", pos:"adj.", cat:"动植物",
    senses:[{ def:"（草木）葱绿的", ex:["The verdant hills rolled on.",
      "A verdant valley after rain.",
      "Verdant fields stretched far."],
      note:"verdure 青绿；文学‘苍翠’。" }],
    syn:["green","lush"], ant:["barren"], synDiff:"" },

  { w:"fertilise", ipa:"/ˈfɜːtəlaɪz/", pos:"v.", cat:"动植物",
    senses:[{ def:"施肥；使受精", ex:["Bees fertilise the flowers.",
      "Farmers fertilise the soil.",
      "The pollen fertilises the ovule."],
      note:"美 fertilize；fertiliser 肥料。" }],
    syn:["enrich","pollinate"], ant:[], synDiff:"" },

  { w:"germinate", ipa:"/ˈdʒɜːmɪneɪt/", pos:"v.", cat:"动植物",
    senses:[{ def:"发芽；萌生", ex:["The seed germinated in days.",
      "Ideas germinate slowly.",
      "Warmth helps it germinate."],
      note:"germination 发芽；与 sprout 近。" }],
    syn:["sprout","bud"], ant:["wither"], synDiff:"" },

  { w:"blossom", ipa:"/ˈblɒsəm/", pos:"n./v.", cat:"动植物",
    senses:[{ def:"（树）开花；繁盛", ex:["The apple tree blossomed.",
      "The blossom fell like snow.",
      "Her talent blossomed late."],
      note:"与 bloom 近；喻‘发展兴盛’。" }],
    syn:["bloom","flower"], ant:["wither"], synDiff:"" },

  { w:"foliage", ipa:"/ˈfəʊliɪdʒ/", pos:"n.", cat:"动植物",
    senses:[{ def:"叶（总称）", ex:["The foliage turned gold.",
      "Dense foliage hid the path.",
      "The foliage rustled in wind."],
      note:"leaf 的总汇；leafy 多叶的。" }],
    syn:["leaves","greenery"], ant:[], synDiff:"" },

  { w:"thorn", ipa:"/θɔːn/", pos:"n.", cat:"动植物",
    senses:[{ def:"刺；荆棘", ex:["The rose has a sharp thorn.",
      "He grasped the branch despite thorns.",
      "Thorns guard the stem."],
      note:"thorny 多刺的；也喻‘棘手’。" }],
    syn:["spike","prickle"], ant:[], synDiff:"" },

  { w:"nectar", ipa:"/ˈnektə(r)/", pos:"n.", cat:"动植物",
    senses:[{ def:"花蜜", ex:["Bees sip the nectar.",
      "The flower offers rich nectar.",
      "Nectar lures pollinators."],
      note:"nectar 花蜜；神饮（也喻‘美味’）。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"pollen", ipa:"/ˈpɒlɪn/", pos:"n.", cat:"动植物",
    senses:[{ def:"花粉", ex:["The bee carried pollen.",
      "Pollen triggers her allergy.",
      "Wind spreads the pollen."],
      note:"pollinate 传粉；pollen 花粉。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"seedling", ipa:"/ˈsiːdlɪŋ/", pos:"n.", cat:"动植物",
    senses:[{ def:"幼苗", ex:["The seedling sprouted two leaves.",
      "She planted the seedling.",
      "The seedling wilted without water."],
      note:"seed 种子长出的苗；young plant。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"roost", ipa:"/ruːst/", pos:"n./v.", cat:"动植物",
    senses:[{ def:"（鸟）栖木；栖息", ex:["Birds roost in the eaves.",
      "The hen returned to the roost.",
      "They disturbed the roost at dusk."],
      note:"bird roost 栖处；come home to roost 喻‘报应’。" }],
    syn:["perch"], ant:[], synDiff:"" },

  { w:"flock", ipa:"/flɒk/", pos:"n./v.", cat:"动植物",
    senses:[{ def:"（鸟/羊）群；聚集", ex:["A flock of starlings wheeled.",
      "Sheep flock to the shepherd.",
      "The crowd flocked to the square."],
      note:"一群鸟/羊；herd 指大兽群。" }],
    syn:["herd","group"], ant:[], synDiff:"" },

  { w:"herd", ipa:"/hɜːd/", pos:"n./v.", cat:"动植物",
    senses:[{ def:"（大兽）群；放牧", ex:["A herd of elephants crossed.",
      "The cows herd together.",
      "He herds the cattle at dawn."],
      note:"象/牛/马等大群；flock 指鸟/羊。" }],
    syn:["drove","flock"], ant:[], synDiff:"" },

  { w:"burrow", ipa:"/ˈbʌrəʊ/", pos:"n./v.", cat:"动植物",
    senses:[{ def:"（动物）洞穴；掘洞", ex:["The rabbit burrowed underground.",
      "A burrow hid the fox.",
      "The mole burrowed through the lawn."],
      note:"burrow 兽穴；动词‘钻洞’。" }],
    syn:["tunnel","hole"], ant:[], synDiff:"" },

  { w:"lair", ipa:"/leə(r)/", pos:"n.", cat:"动植物",
    senses:[{ def:"（兽）巢穴； lurking 处", ex:["The lion returned to its lair.",
      "The dragon guarded its lair.",
      "Police found the lair of the gang."],
      note:"野兽巢穴；喻‘老巢’。" }],
    syn:["den","hideout"], ant:[], synDiff:"" },

  { w:"cocoon", ipa:"/kəˈkuːn/", pos:"n.", cat:"动植物",
    senses:[{ def:"茧", ex:["The silkworm spun a cocoon.",
      "The moth broke from the cocoon.",
      "He lay wrapped like in a cocoon."],
      note:"chrysalis 蛹（蝶）；cocoon 茧（包括蚕）。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"tentacle", ipa:"/ˈtentəkl/", pos:"n.", cat:"动植物",
    senses:[{ def:"触手；触角", ex:["The octopus waved a tentacle.",
      "The tentacle grasped the crab.",
      "Tentacles drifted in the current."],
      note:"头足类/水母的触手；喻‘势力触角’。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"fin", ipa:"/fɪn/", pos:"n.", cat:"动植物",
    senses:[{ def:"鳍", ex:["The shark's fin cut the water.",
      "The fish flicked its fin.",
      "A fin steers the swimmer."],
      note:"鱼鳍；dorsal fin 背鳍。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"mane", ipa:"/meɪn/", pos:"n.", cat:"动植物",
    senses:[{ def:"（狮/马）鬃毛", ex:["The lion shook its mane.",
      "The horse's mane flowed.",
      "The mane framed the face."],
      note:"lion/male horse 颈部长毛。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"tusk", ipa:"/tʌsk/", pos:"n.", cat:"动植物",
    senses:[{ def:"（象/獠）长牙", ex:["The elephant's tusk gleamed.",
      "Poachers took the tusk.",
      "The walrus raised a tusk."],
      note:"象牙/海象牙；ivory 象牙制品。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"poultry", ipa:"/ˈpəʊltri/", pos:"n.", cat:"动植物",
    senses:[{ def:"家禽（鸡鸭等）", ex:["Poultry farms dot the county.",
      "The market sold live poultry.",
      "Poultry provides meat and eggs."],
      note:"chicken/duck/turkey 总称；也指禽肉。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"livestock", ipa:"/ˈlaɪvstɒk/", pos:"n.", cat:"动植物",
    senses:[{ def:"牲畜", ex:["The drought killed the livestock.",
      "Livestock grazed the range.",
      "They insured the livestock."],
      note:"牛/羊/猪等农畜总称。" }],
    syn:["cattle","herd"], ant:[], synDiff:"" },

  { w:"graze", ipa:"/ɡreɪz/", pos:"v.", cat:"动植物",
    senses:[{ def:"吃草；擦伤", ex:["Cattle graze the meadow.",
      "The sheep grazed all day.",
      "He grazed his knee on the rock."],
      note:"动物吃草；也指‘轻擦（伤）’。" }],
    syn:["browse","pasture"], ant:[], synDiff:"" },

  { w:"photosynthesis", ipa:"/ˌfəʊtəʊˈsɪnθəsɪs/", pos:"n.", cat:"动植物",
    senses:[{ def:"光合作用", ex:["Photosynthesis feeds the plant.",
      "Leaves perform photosynthesis.",
      "Photosynthesis needs light and water."],
      note:"光合；plant 自养基础。" }],
    syn:[], ant:[], synDiff:"" },

  // ============== 历史人物（补充，冲到约60） ==============
  { w:"Homer", ipa:"/ˈhəʊmə(r)/", pos:"n.", cat:"历史人物",
    senses:[{ def:"荷马（约前8C，希腊史诗诗人）", ex:["Homer wrote the Iliad and Odyssey.",
      "Homer shaped Western epic.",
      "Scholars debate if Homer was one man."],
      note:"《伊利亚特》《奥德赛》；blind poet 传说。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Confucius", ipa:"/kənˈfjuːʃəs/", pos:"n.", cat:"历史人物",
    senses:[{ def:"孔子（前551–前479，中国思想家）", ex:["Confucius taught the Analects.",
      "Confucius stressed filial piety.",
      "His ideas shaped East Asia for millennia."],
      note:"《论语》；ren 仁、li 礼；儒家创始人。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Alexander the Great", ipa:"/ˌælɪɡˈzɑːndə ðə ˈɡreɪt/", pos:"n.", cat:"历史人物",
    senses:[{ def:"亚历山大大帝（前356–前323，马其顿王）", ex:["Alexander conquered Persia by 330 BCE.",
      "Alexander spread Hellenistic culture.",
      "He died young at Babylon."],
      note:"马其顿；Hellenistic 希腊化；版图至印度。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Julius Caesar", ipa:"/ˈdʒuːliəs ˈsiːzə/", pos:"n.", cat:"历史人物",
    senses:[{ def:"尤利乌斯·凯撒（前100–前44，罗马独裁官）", ex:["Caesar crossed the Rubicon in 49 BCE.",
      "Caesar was assassinated on the Ides of March.",
      "His commentaries record the Gallic War."],
      note:"‘跨越卢比孔’喻破釜沉舟；dictator 终身独裁。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Augustus", ipa:"/ɔːˈɡʌstəs/", pos:"n.", cat:"历史人物",
    senses:[{ def:"奥古斯都（前63–14，罗马首位皇帝）", ex:["Augustus founded the Empire.",
      "Augustus ended the civil wars.",
      "The Pax Romana began under Augustus."],
      note:"屋大维；Roman Empire 开端；Pax Romana 罗马和平。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Genghis Khan", ipa:"/ˈdʒeŋɡɪs ˈkɑːn/", pos:"n.", cat:"历史人物",
    senses:[{ def:"成吉思汗（约1162–1227，蒙古帝国建立者）", ex:["Genghis Khan united the Mongol tribes.",
      "His empire became the largest contiguous one.",
      "Genghis Khan reformed the cavalry."],
      note:"Mongol Empire；最庞大陆地帝国；驿站制度。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Isaac Newton", ipa:"/ˈaɪzək ˈnjuːtn/", pos:"n.", cat:"历史人物",
    senses:[{ def:"艾萨克·牛顿（1643–1727，物理学家）", ex:["Newton formulated the laws of motion.",
      "Newton invented calculus.",
      "His Principia laid the foundations of physics."],
      note:"《自然哲学的数学原理》；万有引力；微积分。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Louis Pasteur", ipa:"/ˈluːi pæˈstɜː/", pos:"n.", cat:"历史人物",
    senses:[{ def:"路易·巴斯德（1822–1895，微生物学家）", ex:["Pasteur proved germs cause disease.",
      "Pasteur invented pasteurisation.",
      "He developed vaccines against rabies."],
      note:"巴氏消毒；germ theory 病菌说；疫苗。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Thomas Edison", ipa:"/ˈtɒməs ˈedɪsn/", pos:"n.", cat:"历史人物",
    senses:[{ def:"托马斯·爱迪生（1847–1931，发明家）", ex:["Edison patented the light bulb.",
      "Edison built the first lab.",
      "He held over a thousand patents."],
      note:"电灯/留声机；inventor 发明家。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Albert Einstein", ipa:"/ˈælbət ˈaɪnstaɪn/", pos:"n.", cat:"历史人物",
    senses:[{ def:"阿尔伯特·爱因斯坦（1879–1955，物理学家）", ex:["Einstein proposed relativity.",
      "Einstein's E=mc² reshaped physics.",
      "He fled Nazi Germany in 1933."],
      note:"相对论；光电效应诺奖；20C 科学象征。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Mao Zedong", ipa:"/ˈmaʊ tsəˈtʊŋ/", pos:"n.", cat:"历史人物",
    senses:[{ def:"毛泽东（1893–1976，中国领导人）", ex:["Mao led the Communist revolution in 1949.",
      "Mao wrote poetry and essays.",
      "His thought shaped modern China."],
      note:"新中国成立；兼具政治家与诗人身份。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Deng Xiaoping", ipa:"/ˈdʊŋ ʃaʊˈpɪŋ/", pos:"n.", cat:"历史人物",
    senses:[{ def:"邓小平（1904–1997，中国改革设计师）", ex:["Deng launched Reform and Opening-up.",
      "Deng promoted ‘Socialism with Chinese characteristics’.",
      "His pragmatism transformed the economy."],
      note:"改革开放；‘黑猫白猫’论；现代化推手。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"George Washington", ipa:"/ˈdʒɔːdʒ ˈwɒʃɪŋtən/", pos:"n.", cat:"历史人物",
    senses:[{ def:"乔治·华盛顿（1732–1799，美国首任总统）", ex:["Washington led the Revolution.",
      "Washington was the first U.S. president.",
      "He refused a crown, setting a precedent."],
      note:"‘国父’；两任后隐退；precedent 先例。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Franklin Roosevelt", ipa:"/ˈfræŋklɪn ˈrəʊzəvelt/", pos:"n.", cat:"历史人物",
    senses:[{ def:"富兰克林·罗斯福（1882–1945，美国总统）", ex:["FDR led the U.S. through the Depression and WWII.",
      "He launched the New Deal.",
      "He was elected four times."],
      note:"新政 New Deal；唯一四任总统；二战领袖。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Margaret Thatcher", ipa:"/ˈmɑːɡərət ˈθætʃə/", pos:"n.", cat:"历史人物",
    senses:[{ def:"玛格丽特·撒切尔（1925–2013，英国首相）", ex:["Thatcher was Britain's first woman PM.",
      "Thatcher promoted free-market reform.",
      "She was called the ‘Iron Lady’."],
      note:"铁娘子；保守党；新自由主义。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Queen Elizabeth I", ipa:"/ˈkwɪn ɪˈlɪzəbəθ ðə ˈfɜːst/", pos:"n.", cat:"历史人物",
    senses:[{ def:"伊丽莎白一世（1533–1603，英格兰女王）", ex:["Elizabeth I reigned in a golden age.",
      "She defeated the Spanish Armada.",
      "The Elizabethan era blossomed in arts."],
      note:"都铎；黄金时代；Shakespeare 同期。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Peter the Great", ipa:"/ˈpiːtə ðə ˈɡreɪt/", pos:"n.", cat:"历史人物",
    senses:[{ def:"彼得大帝（1672–1725，俄国沙皇）", ex:["Peter modernised Russia by force.",
      "He built the city of St Petersburg.",
      "Peter opened a window to the West."],
      note:"西化改革；俄罗斯帝国。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Catherine the Great", ipa:"/ˈkæθrɪn ðə ˈɡreɪt/", pos:"n.", cat:"历史人物",
    senses:[{ def:"叶卡捷琳娜大帝（1729–1796，俄国女皇）", ex:["Catherine expanded the empire.",
      "She patronised the arts and law.",
      "Her reign was an age of enlightenment."],
      note:"俄国黄金时代；启蒙专制。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Otto von Bismarck", ipa:"/ˈɒtəʊ fɒn ˈbɪzmɑːk/", pos:"n.", cat:"历史人物",
    senses:[{ def:"俾斯麦（1815–1898，德国统一者）", ex:["Bismarck united Germany by realpolitik.",
      "He engineered wars to unify the states.",
      "Bismarck built the welfare state."],
      note:"铁血宰相；realpolitik 现实政治；德意志统一。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Mohandas Gandhi", ipa:"/moʊˈhændəs ˈɡɑːndi/", pos:"n.", cat:"历史人物",
    senses:[{ def:"莫罕达斯·甘地（即 Mahatma Gandhi）", ex:["Gandhi led non-violent resistance.",
      "His Salt March challenged British rule.",
      "Gandhi inspired civil-rights movements."],
      note:"satyagraha 非暴力；印度独立。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Kublai Khan", ipa:"/ˈkuːblaɪ ˈkɑːn/", pos:"n.", cat:"历史人物",
    senses:[{ def:"忽必烈（1215–1294，元朝开国皇帝）", ex:["Kublai Khan founded the Yuan dynasty.",
      "He completed the conquest of China.",
      "Marco Polo visited his court."],
      note:"元世祖；蒙古帝国中原政权；大都。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Plato", ipa:"/ˈpleɪtəʊ/", pos:"n.", cat:"历史人物",
    senses:[{ def:"柏拉图（前427–前347，希腊哲学家）", ex:["Plato founded the Academy.",
      "Plato wrote the Republic.",
      "His theory of forms shaped philosophy."],
      note:"理念论；Socrates 之徒、Aristotle 之师。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Aristotle", ipa:"/ˈærɪstɒtl/", pos:"n.", cat:"历史人物",
    senses:[{ def:"亚里士多德（前384–前322，希腊哲学家）", ex:["Aristotle tutored Alexander.",
      "Aristotle systematised logic.",
      "His works span science and ethics."],
      note:"柏拉图之徒；Lyceum 学园；百科全书式。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Socrates", ipa:"/ˈsɒkrətiːz/", pos:"n.", cat:"历史人物",
    senses:[{ def:"苏格拉底（前470–前399，希腊哲学家）", ex:["Socrates used questioning to teach.",
      "Socrates was sentenced to death by Athens.",
      "The Socratic method lives on."],
      note:"苏格拉底法（诘问）；柏拉图《对话录》载其言。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Tutankhamun", ipa:"/ˌtuːtənkˈɑːmuːn/", pos:"n.", cat:"历史人物",
    senses:[{ def:"图坦卡蒙（前1341–前1323，埃及法老）", ex:["Tutankhamun's tomb was found intact in 1922.",
      "The boy king ruled briefly.",
      "His gold mask is world-famous."],
      note:"最完整法老墓；1922 Carter 发现。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Hammurabi", ipa:"/ˌhæmʊˈrɑːbi/", pos:"n.", cat:"历史人物",
    senses:[{ def:"汉谟拉比（前1792–前1750，巴比伦王）", ex:["Hammurabi issued the famous code.",
      "The Code of Hammurabi is an eye for an eye.",
      "His laws shaped Mesopotamian law."],
      note:"《汉谟拉比法典》；最早成文法之一；‘以眼还眼’。" }],
    syn:[], ant:[], synDiff:"" }
];
