// 词汇复习站 · 扩展词库（第三批，重点扩充动植物及其他各类）
// 格式同 data.js / data_extra.js。index.html 合并 WORDS + EXTRA + EXTRA2 + CUSTOM。
const EXTRA2 = [
  // ============== 动植物（大幅扩充） ==============
  { w:"lion", ipa:"/ˈlaɪən/", pos:"n.", cat:"动植物",
    senses:[{ def:"狮子", ex:["The lion is a top predator of the savanna.",
      "A lioness hunted alone while the males rested.",
      "The lion roared to mark its territory."],
      note:"雄狮 lion，雌狮 lioness；幼崽 cub。象征 courage / royalty。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"tiger", ipa:"/ˈtaɪɡə(r)/", pos:"n.", cat:"动植物",
    senses:[{ def:"老虎", ex:["The tiger stalks its prey through tall grass.",
      "Tigers are solitary and mostly nocturnal.",
      "The South China tiger is critically endangered."],
      note:"big cat 之一；幼崽 cub。与 lion 不同，tiger 独居。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"elephant", ipa:"/ˈelɪfənt/", pos:"n.", cat:"动植物",
    senses:[{ def:"大象", ex:["The elephant uses its trunk to drink.",
      "Elephants have remarkable long-term memory.",
      "Poaching threatens wild elephant populations."],
      note:"trunk 象鼻；tusk 象牙。象征 memory / wisdom。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"giraffe", ipa:"/dʒəˈrɑːf/", pos:"n.", cat:"动植物",
    senses:[{ def:"长颈鹿", ex:["The giraffe browses leaves high in the trees.",
      "A giraffe's neck has the same number of vertebrae as ours.",
      "Giraffes live in loose herds on the savanna."],
      note:"世界上最高的陆生动物。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"zebra", ipa:"/ˈzebrə/", pos:"n.", cat:"动植物",
    senses:[{ def:"斑马", ex:["The zebra's stripes deter biting flies.",
      "Zebras graze alongside wildebeest on the plains.",
      "No two zebras have identical stripes."],
      note:"stripes 条纹；常群居。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"kangaroo", ipa:"/ˌkæŋɡəˈruː/", pos:"n.", cat:"动植物",
    senses:[{ def:"袋鼠", ex:["The kangaroo moves by powerful hops.",
      "A joey lives in its mother's pouch.",
      "Kangaroos are endemic to Australia."],
      note:"marsupial 有袋类；joey 幼崽；pouch 育儿袋。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"dolphin", ipa:"/ˈdɒlfɪn/", pos:"n.", cat:"动植物",
    senses:[{ def:"海豚", ex:["The dolphin leapt clean out of the water.",
      "Dolphins use echolocation to find fish.",
      "A pod of dolphins raced the bow wave."],
      note:"marine mammal 海洋哺乳动物；pod 群。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"whale", ipa:"/weɪl/", pos:"n.", cat:"动植物",
    senses:[{ def:"鲸", ex:["The blue whale is the largest animal ever.",
      "Whales sing complex songs to communicate.",
      "The whale breached and crashed back down."],
      note:"mammal 非 fish；breach 跃出水面。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"bat", ipa:"/bæt/", pos:"n.", cat:"动植物",
    senses:[{ def:"蝙蝠", ex:["The bat navigated the cave by echolocation.",
      "Bats are the only mammals capable of true flight.",
      "Fruit bats pollinate many tropical trees."],
      note:"nocturnal 夜行性；echolocation 回声定位。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"fox", ipa:"/fɒks/", pos:"n.", cat:"动植物",
    senses:[{ def:"狐狸", ex:["The fox slipped silently into the henhouse.",
      "A fox is clever and notoriously cunning.",
      "Arctic foxes turn white in winter."],
      note:"象征 cunning 狡猾；cub 幼崽。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"wolf", ipa:"/wʊlf/", pos:"n.", cat:"动植物",
    senses:[{ def:"狼", ex:["The wolf howled at the moon.",
      "Wolves hunt in coordinated packs.",
      "The wolf pack defended its territory fiercely."],
      note:"pack 狼群；复数 wolves。象征 loyalty / wildness。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"bear", ipa:"/beə(r)/", pos:"n.", cat:"动植物",
    senses:[{ def:"熊", ex:["The bear fished for salmon in the stream.",
      "Bears hibernate through the coldest months.",
      "A panda is a bear that eats almost only bamboo."],
      note:"hibernate 冬眠；cub 幼崽。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"deer", ipa:"/dɪə(r)/", pos:"n.", cat:"动植物",
    senses:[{ def:"鹿", ex:["The deer froze at the sound of footsteps.",
      "A stag shed its antlers each spring.",
      "Deer grazed quietly at the forest edge."],
      note:"复数同形 deer；雄鹿 stag / buck，雌鹿 doe，幼鹿 fawn。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"monkey", ipa:"/ˈmʌŋki/", pos:"n.", cat:"动植物",
    senses:[{ def:"猴子", ex:["The monkey swung from branch to branch.",
      "Capuchin monkeys use tools to crack nuts.",
      "The monkey chattered noisily in the canopy."],
      note:"primate 灵长类；与 ape（猿，无尾）不同。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"gorilla", ipa:"/ɡəˈrɪlə/", pos:"n.", cat:"动植物",
    senses:[{ def:"大猩猩", ex:["The gorilla beat its chest in display.",
      "Gorillas are gentle, plant-eating apes.",
      "Mountain gorillas are severely endangered."],
      note:"ape 类（无尾）；与 monkey 不同。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"panda", ipa:"/ˈpændə/", pos:"n.", cat:"动植物",
    senses:[{ def:"熊猫", ex:["The giant panda feeds mainly on bamboo.",
      "A panda cub is pink and tiny at birth.",
      "Pandas are a global symbol of conservation."],
      note:"giant panda 大熊猫；red panda 小熊猫（不同科）。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"camel", ipa:"/ˈkɑːml/", pos:"n.", cat:"动植物",
    senses:[{ def:"骆驼", ex:["The camel stores fat in its hump.",
      "Camels can go days without water.",
      "A caravan of camels crossed the desert."],
      note:"hump 驼峰；dromedary 单峰驼，Bactrian 双峰驼。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"hedgehog", ipa:"/ˈhedʒhɒɡ/", pos:"n.", cat:"动植物",
    senses:[{ def:"刺猬", ex:["The hedgehog curled into a ball at danger.",
      "Hedgehogs forage for insects at night.",
      "A hedgehog's spines deter predators."],
      note:"spines 刺；curl into a ball 卷成球。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"otter", ipa:"/ˈɒtə(r)/", pos:"n.", cat:"动植物",
    senses:[{ def:"水獭", ex:["The sea otter floats on its back.",
      "Otters hold hands while sleeping to stay together.",
      "Otters slide down muddy banks for fun."],
      note:"semiaquatic 半水生；playful 性情。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"eagle", ipa:"/ˈiːɡl/", pos:"n.", cat:"动植物",
    senses:[{ def:"鹰（大型猛禽）", ex:["The eagle soared on rising thermals.",
      "The bald eagle is the national bird of the U.S.",
      "An eagle snatched a fish from the lake."],
      note:"bird of prey 猛禽；象征 strength / freedom。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"owl", ipa:"/aʊl/", pos:"n.", cat:"动植物",
    senses:[{ def:"猫头鹰", ex:["The owl hooted from the oak.",
      "Owls hunt silently under cover of darkness.",
      "An owl turned its head nearly all the way round."],
      note:"nocturnal；象征 wisdom。rotate head 转头。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"penguin", ipa:"/ˈpeŋɡwɪn/", pos:"n.", cat:"动植物",
    senses:[{ def:"企鹅", ex:["The penguin waddled to the water's edge.",
      "Emperor penguins breed in the Antarctic winter.",
      "Penguins ‘fly’ underwater with their flippers."],
      note:"flightless 不会飞；flippers 鳍状肢； Antarctic 南极。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"parrot", ipa:"/ˈpærət/", pos:"n.", cat:"动植物",
    senses:[{ def:"鹦鹉", ex:["The parrot mimicked the doorbell perfectly.",
      "Parrots are among the most intelligent birds.",
      "A flock of parrots screeched overhead."],
      note:"mimic 模仿（声音）；常作宠物。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"swan", ipa:"/swɒn/", pos:"n.", cat:"动植物",
    senses:[{ def:"天鹅", ex:["The swan glided across the lake.",
      "A swan can be fiercely defensive of its nest.",
      "Two swans formed a lifelong pair bond."],
      note:"象征 grace / love；pair bond 终身配偶。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"peacock", ipa:"/ˈpiːkɒk/", pos:"n.", cat:"动植物",
    senses:[{ def:"孔雀", ex:["The peacock fanned its dazzling tail.",
      "A peacock displayed to attract a peahen.",
      "Peacocks strut across palace gardens."],
      note:"雄 peacock，雌 peahen；tail 尾屏 display 开屏。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"flamingo", ipa:"/fləˈmɪŋɡəʊ/", pos:"n.", cat:"动植物",
    senses:[{ def:"火烈鸟", ex:["Flamingos stand on one leg in shallow lakes.",
      "Their pink colour comes from carotenoid food.",
      "A flock of flamingos took off in unison."],
      note:"pink 粉色；stand on one leg 单脚站立。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"hummingbird", ipa:"/ˈhʌmɪŋbɜːd/", pos:"n.", cat:"动植物",
    senses:[{ def:"蜂鸟", ex:["The hummingbird hovered before the flower.",
      "Its wings beat too fast to see.",
      "Hummingbirds drink nectar through a long beak."],
      note:"hover 悬停；nectar 花蜜；smallest bird。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"snake", ipa:"/sneɪk/", pos:"n.", cat:"动植物",
    senses:[{ def:"蛇", ex:["The snake slithered into the grass.",
      "Some snakes constrict their prey; others venom it.",
      "The snake shed its old skin."],
      note:"reptile 爬行类；slither 滑行；shed skin 蜕皮。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"lizard", ipa:"/ˈlɪzəd/", pos:"n.", cat:"动植物",
    senses:[{ def:"蜥蜴", ex:["The lizard basked on a warm rock.",
      "Many lizards can regrow a lost tail.",
      "The gecko is a small lizard that climbs walls."],
      note:"reptile；bask 晒太阳；regrow tail 再生尾巴。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"turtle", ipa:"/ˈtɜːtl/", pos:"n.", cat:"动植物",
    senses:[{ def:"龟；海龟", ex:["The turtle withdrew into its shell.",
      "Sea turtles return to the beach where they hatched.",
      "A turtle swam slowly past the reef."],
      note:"shell 龟壳；hatch 孵化。tortoise 陆龟。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"crocodile", ipa:"/ˈkrɒkədaɪl/", pos:"n.", cat:"动植物",
    senses:[{ def:"鳄鱼", ex:["The crocodile lay motionless in the mud.",
      "Crocodiles ambush prey at the water's edge.",
      "A crocodile's jaws snap shut with huge force."],
      note:"reptile；ambush 伏击。alligator 短吻鳄。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"frog", ipa:"/frɒɡ/", pos:"n.", cat:"动植物",
    senses:[{ def:"青蛙", ex:["The frog leapt into the pond.",
      "Frogs breathe through their skin as well as lungs.",
      "Tadpoles grow into frogs in a few weeks."],
      note:"amphibian 两栖类；tadpole 蝌蚪；croak 呱呱叫。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"chameleon", ipa:"/kəˈmiːliən/", pos:"n.", cat:"动植物",
    senses:[{ def:"变色龙", ex:["The chameleon changed colour to match the leaf.",
      "Chameleons shoot out a long sticky tongue.",
      "Its swivelling eyes watch in two directions at once."],
      note:"象征‘善变’；change colour 变色。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"salmon", ipa:"/ˈsæmən/", pos:"n.", cat:"动植物",
    senses:[{ def:"三文鱼；鲑鱼", ex:["Salmon swim upstream to spawn.",
      "Grilled salmon is rich in omega-3.",
      "The salmon leapt the waterfall on its way home."],
      note:"fish；swim upstream 洄游；spawn 产卵。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"shark", ipa:"/ʃɑːk/", pos:"n.", cat:"动植物",
    senses:[{ def:"鲨鱼", ex:["The shark circled the struggling fish.",
      "Sharks have sensors that detect faint movement.",
      "A great white shark breached beside the boat."],
      note:"cartilaginous fish 软骨鱼；predator 顶级掠食者。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"octopus", ipa:"/ˈɒktəpəs/", pos:"n.", cat:"动植物",
    senses:[{ def:"章鱼", ex:["The octopus squeezed through a tiny gap.",
      "An octopus squirts ink to escape.",
      "Octopuses have three hearts and blue blood."],
      note:"cephalopod 头足类；squirt ink 喷墨。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"crab", ipa:"/kræb/", pos:"n.", cat:"动植物",
    senses:[{ def:"螃蟹", ex:["The crab scuttled sideways across the sand.",
      "Crabs moult their shells as they grow.",
      "He cracked the crab's claw with a nutcracker."],
      note:"crustacean 甲壳类；scuttle 横行；moult 蜕壳。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"jellyfish", ipa:"/ˈdʒelifɪʃ/", pos:"n.", cat:"动植物",
    senses:[{ def:"水母", ex:["The jellyfish drifted with the current.",
      "Its tentacles deliver a painful sting.",
      "Blooms of jellyfish are increasing in warming seas."],
      note:"tentacle 触手；sting 蜇；gelatinous 凝胶状。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"butterfly", ipa:"/ˈbʌtəflaɪ/", pos:"n.", cat:"动植物",
    senses:[{ def:"蝴蝶", ex:["The butterfly flitted from flower to flower.",
      "A caterpillar becomes a butterfly in its chrysalis.",
      "Monarch butterflies migrate thousands of miles."],
      note:"insect；chrysalis 蛹；metamorphosis 变态发育。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"bee", ipa:"/biː/", pos:"n.", cat:"动植物",
    senses:[{ def:"蜜蜂", ex:["The bee buzzed around the blossom.",
      "Bees pollinate a third of our food crops.",
      "A honeybee stings only once, then dies."],
      note:"pollinate 传粉；hive 蜂巢；swarm 蜂群。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"ant", ipa:"/ænt/", pos:"n.", cat:"动植物",
    senses:[{ def:"蚂蚁", ex:["The ant carried a leaf many times its weight.",
      "Ants cooperate in complex colonies.",
      "A line of ants marched toward the crumb."],
      note:"insect；colony 群落；social insect。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"spider", ipa:"/ˈspaɪdə(r)/", pos:"n.", cat:"动植物",
    senses:[{ def:"蜘蛛", ex:["The spider spun a meticulous web.",
      "A spider waits at the centre of its trap.",
      "Most spiders are harmless to humans."],
      note:"arachnid 蛛形纲（非 insect）；web 网；spin 结网。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"dragonfly", ipa:"/ˈdræɡənflaɪ/", pos:"n.", cat:"动植物",
    senses:[{ def:"蜻蜓", ex:["The dragonfly hovered, then darted off.",
      "Dragonflies hunt other insects in flight.",
      "Its four wings beat independently."],
      note:"insect；hover 悬停；dart 疾飞。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"ladybug", ipa:"/ˈleɪdibʌɡ/", pos:"n.", cat:"动植物",
    senses:[{ def:"瓢虫", ex:["The ladybug crawled across the leaf.",
      "Ladybugs eat aphids that harm crops.",
      "A red ladybug with black spots landed on her hand."],
      note:"beetle 甲虫；益虫，吃蚜虫 aphid。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"oak", ipa:"/əʊk/", pos:"n.", cat:"动植物",
    senses:[{ def:"橡树", ex:["The oak stood for centuries in the field.",
      "Acorns are the seeds of the oak.",
      "Oak wood is prized for its strength."],
      note:"deciduous 落叶树；acorn 橡果；hardwood 硬木。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"pine", ipa:"/paɪn/", pos:"n.", cat:"动植物",
    senses:[{ def:"松树", ex:["The pine smells of resin in summer.",
      "Pines keep their needles all winter.",
      "Pine cones release seeds when dry."],
      note:"evergreen conifer 常绿针叶树；needle 针叶；cone 球果。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"willow", ipa:"/ˈwɪləʊ/", pos:"n.", cat:"动植物",
    senses:[{ def:"柳树", ex:["The willow wept over the still pond.",
      "Willow branches bend without breaking.",
      "They wove baskets from willow withes."],
      note:"weeping willow 垂柳；flexible 柔韧。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"bamboo", ipa:"/bæmˈbuː/", pos:"n.", cat:"动植物",
    senses:[{ def:"竹子", ex:["Bamboo grows astonishingly fast.",
      "Pandas depend almost entirely on bamboo.",
      "They built the fence from split bamboo."],
      note:"grass 禾本科（非树）；hollow 中空；fast-growing。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"cactus", ipa:"/ˈkæktəs/", pos:"n.", cat:"动植物",
    senses:[{ def:"仙人掌", ex:["The cactus stores water in its stem.",
      "Cacti thrive in harsh deserts.",
      "A cactus blooms with surprising bright flowers."],
      note:"succulent 多肉；spine 刺；desert 沙漠。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"fern", ipa:"/fɜːn/", pos:"n.", cat:"动植物",
    senses:[{ def:"蕨类", ex:["Ferns unfurl their fronds in spring.",
      "Ferns prefer the damp shade of the forest.",
      "Tree ferns grew as tall as houses in prehistoric times."],
      note:"non-flowering 不开花；spore 孢子繁殖；frond 叶。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"moss", ipa:"/mɒs/", pos:"n.", cat:"动植物",
    senses:[{ def:"苔藓", ex:["Moss carpeted the damp stones.",
      "Moss grows where sunlight is faint.",
      "The log was soft with green moss."],
      note:"non-vascular 非维管；damp shade 阴湿处。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"palm", ipa:"/pɑːm/", pos:"n.", cat:"动植物",
    senses:[{ def:"棕榈树", ex:["Palms lined the tropical beach.",
      "The palm yielded coconuts and dates.",
      "Its fronds swayed in the sea breeze."],
      note:"tropical 热带；frond 棕榈叶；coconut 椰子。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"maple", ipa:"/ˈmeɪpl/", pos:"n.", cat:"动植物",
    senses:[{ def:"枫树", ex:["The maple blazed red in October.",
      "Maple syrup is tapped from the trunk.",
      "Its leaf is Canada's national symbol."],
      note:"deciduous；maple syrup 枫糖浆；symbol of Canada。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"rose", ipa:"/rəʊz/", pos:"n.", cat:"动植物",
    senses:[{ def:"玫瑰；蔷薇", ex:["She placed a red rose on the grave.",
      "The rose bush bristled with thorns.",
      "He pressed a dried rose between the pages."],
      note:"thorn 刺；象征 love；rose 也指‘玫瑰色’。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"tulip", ipa:"/ˈtjuːlɪp/", pos:"n.", cat:"动植物",
    senses:[{ def:"郁金香", ex:["Tulips bobbed in the spring wind.",
      "The Dutch once traded tulip bulbs like gold.",
      "A field of tulips stretched to the horizon."],
      note:"bulb 球茎；荷兰象征；spring flower。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"lily", ipa:"/ˈlɪli/", pos:"n.", cat:"动植物",
    senses:[{ def:"百合", ex:["The white lily symbolised purity.",
      "Lilies filled the room with scent.",
      "The pond lily floated a single bloom."],
      note:"symbol of purity 纯洁；fragrant 芳香。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"sunflower", ipa:"/ˈsʌnflaʊə(r)/", pos:"n.", cat:"动植物",
    senses:[{ def:"向日葵", ex:["The sunflower turned to face the sun.",
      "Sunflowers yield oil-rich seeds.",
      "A row of sunflowers stood like sentinels."],
      note:"heliotrope 向光性；seed 瓜子；oil 葵花油。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"orchid", ipa:"/ˈɔːkɪd/", pos:"n.", cat:"动植物",
    senses:[{ def:"兰花", ex:["The orchid perched on a branch, not soil.",
      "Orchids are prized for their exotic shapes.",
      "She nursed the rare orchid for years."],
      note:"epiphyte 附生；exotic 奇特的花形；rare 稀有。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"lavender", ipa:"/ˈlævəndə(r)/", pos:"n.", cat:"动植物",
    senses:[{ def:"薰衣草", ex:["Lavender scented the whole garden.",
      "She stuffed the pillow with dried lavender.",
      "Lavender fields purple the Provence hills."],
      note:"fragrant 芳香；calming 安神；purple 紫。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"lotus", ipa:"/ˈləʊtəs/", pos:"n.", cat:"动植物",
    senses:[{ def:"莲花；荷", ex:["The lotus rose clean from the mud.",
      "The lotus is sacred in Buddhism and Hinduism.",
      "Its seed pod sits like a shower head."],
      note:"aquatic 水生；symbol of purity/ enlightenment 清净。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"habitat", ipa:"/ˈhæbɪtæt/", pos:"n.", cat:"动植物",
    senses:[{ def:"栖息地", ex:["Logging destroys the panda's habitat.",
      "Wetlands are a vital habitat for birds.",
      "Climate change is shifting many species' habitats."],
      note:"与 niche（生态位）不同；habitat 指物理环境。" }],
    syn:["environment","territory"], ant:[],
    synDiff:"environment 泛指环境；territory 指动物领地；habitat 强调物种自然生存的物理栖所。" },

  { w:"species", ipa:"/ˈspiːʃiːz/", pos:"n.", cat:"动植物",
    senses:[{ def:"物种", ex:["This species is found only in Madagascar.",
      "The giant panda is a vulnerable species.",
      "Two species interbred to produce the hybrid."],
      note:"单复同形；endangered / extinct species 濒危/灭绝物种。" }],
    syn:["kind","breed"], ant:[],
    synDiff:"kind 日常‘种类’；breed 多指人工培育‘品种’；species 是生物学分类基本单位。" },

  { w:"predator", ipa:"/ˈpredətə(r)/", pos:"n.", cat:"动植物",
    senses:[{ def:"捕食者；天敌", ex:["The fox is a predator of rabbits.",
      "Apex predators keep ecosystems in balance.",
      "The predator stalked its prey unseen."],
      note:"反义 prey 猎物；apex predator 顶级掠食者。" }],
    syn:["hunter"], ant:["prey"],
    synDiff:"hunter 泛指狩猎者（可指人）；predator 生态上‘捕食者’。" },

  { w:"extinct", ipa:"/ɪkˈstɪŋkt/", pos:"adj.", cat:"动植物",
    senses:[{ def:"灭绝的", ex:["The dodo has been extinct for centuries.",
      "Many species went extinct before we named them.",
      "Conservation aims to keep nonextinct what remains."],
      note:"名词 extinction 灭绝；go extinct 灭绝。" }],
    syn:["vanished","gone"], ant:["extant","alive"],
    synDiff:"vanished 强调‘消失’；extinct 专指物种‘灭绝’。" },

  // ============== 学术写作（补充） ==============
  { w:"corroborate", ipa:"/kəˈrɒbəreɪt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"证实；支持（证据）", ex:["Witnesses corroborated his account.",
      "The later data corroborate the initial finding.",
      "Her diary corroborates the official record."],
      note:"宾语常是 evidence / finding / account；名词 corroboration。" }],
    syn:["confirm","verify","substantiate"], ant:["contradict","refute"],
    synDiff:"confirm 一般‘确认’；verify 强调‘核对无误’；corroborate 专指‘用独立证据支持/佐证’。" },

  { w:"dichotomy", ipa:"/daɪˈkɒtəmi/", pos:"n.", cat:"学术写作",
    senses:[{ def:"二分；对立", ex:["He rejected the mind–body dichotomy.",
      "The dichotomy between nature and nurture is false.",
      "We must move beyond this simple dichotomy."],
      note:"常接 between；形容词 dichotomous。" }],
    syn:["division","contrast"], ant:["continuum"],
    synDiff:"division 泛指‘划分’；dichotomy 强调‘非此即彼的两分对立’。" },

  { w:"paradigm", ipa:"/ˈpærədaɪm/", pos:"n.", cat:"学术写作",
    senses:[{ def:"范式；典范", ex:["The discovery triggered a paradigm shift.",
      "This model is the dominant paradigm in economics.",
      "We need a new paradigm for urban transport."],
      note:"Kuhn 提出的 paradigm shift 范式转移； paradigm 比 model 更根本。" }],
    syn:["model","framework"], ant:[],
    synDiff:"model 具体模型；framework 框架；paradigm 是‘根本性的认知范式’。" },

  { w:"nuance", ipa:"/ˈnjuːɑːns/", pos:"n.", cat:"学术写作",
    senses:[{ def:"细微差别", ex:["The translation misses a crucial nuance.",
      "He appreciated the nuance of her tone.",
      "These terms differ only in nuance."],
      note:"形容词 nuanced 细腻的/有层次的（高频写作词）。" }],
    syn:["subtlety","shade"], ant:["bluntness"],
    synDiff:"subtlety 泛指‘微妙’；nuance 特指语义/语气上‘细微差异’。" },

  { w:"robust", ipa:"/rəʊˈbʌst/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"稳健的；强健的", ex:["The results are robust to alternative specifications.",
      "We need a robust statistical method.",
      "A robust economy withstands shocks."],
      note:"论文中常指‘结论经得起检验/稳健’；也指身体强健。" }],
    syn:["strong","sturdy","sound"], ant:["fragile","weak"],
    synDiff:"strong 一般‘强’；robust 强调‘在各种条件下都站得住’；sturdy 偏物理结实。" },

  { w:"derive", ipa:"/dɪˈraɪv/", pos:"v.", cat:"学术写作",
    senses:[{ def:"源自；推导", ex:["We derive the formula from first principles.",
      "The word is derived from Latin.",
      "Benefits derived from the policy were modest."],
      note:"derive from 源自；derivation 派生/推导。" }],
    syn:["obtain","originate"], ant:[],
    synDiff:"obtain 泛指‘获得’；derive 强调‘从源头推导/得出’。" },

  { w:"underpin", ipa:"/ˌʌndəˈpɪn/", pos:"v.", cat:"学术写作",
    senses:[{ def:"支撑；构成基础", ex:["Four pillars underpin the theory.",
      "Strong institutions underpin economic growth.",
      "The claim is underpinned by solid data."],
      note:"比喻‘打下基础’；名词 underpinning。" }],
    syn:["support","bolster"], ant:["undermine"],
    synDiff:"support 泛‘支持’；underpin 强调‘从根基上支撑’。" },

  { w:"facilitate", ipa:"/fəˈsɪlɪteɪt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"促进；使便利", ex:["Trade agreements facilitate exchange.",
      "The app facilitates communication across teams.",
      "Good design facilitates learning."],
      note:"不以‘人’作宾语（不说 facilitate sb.）；名词 facility 设施。" }],
    syn:["ease","promote"], ant:["hinder"],
    synDiff:"ease 使‘更容易’；facilitate 较正式‘促成/提供便利’。" },

  { w:"conducive", ipa:"/kənˈdjuːsɪv/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"有益于…的；促成…的", ex:["A quiet room is conducive to study.",
      "The climate is conducive to outdoor life.",
      "This culture is not conducive to frank debate."],
      note:"常接 to + 名词/动名词；反义 detrimental（有害的）。" }],
    syn:["favourable","helpful"], ant:["detrimental","hostile"],
    synDiff:"favourable 有利；conducive 强调‘有助于产生某结果的环境条件’。" },

  { w:"scrutinise", ipa:"/ˈskruːtənaɪz/", pos:"v.", cat:"学术写作",
    senses:[{ def:"仔细审查（美 scrutinize）", ex:["Reviewers scrutinised every claim.",
      "We must scrutinise the assumptions closely.",
      "The data were scrutinised for errors."],
      note:"名词 scrutiny 审查；形容‘细致检查’。" }],
    syn:["examine","inspect"], ant:["ignore"],
    synDiff:"examine 一般‘检查’；scrutinise 强调‘逐字逐句地仔细审查’。" },

  { w:"attribute", ipa:"/əˈtrɪbjuːt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"把…归因于（attribute A to B）", ex:["She attributed the drop to poor policy.",
      "The effect is attributed to climate change.",
      "We attribute the result to random chance."],
      note:"注意重音：动词 /əˈtrɪbjuːt/，名词 /ˈætrɪbjuːt/‘特质’。" }],
    syn:["ascribe","assign"], ant:[],
    synDiff:"ascribe 也‘归于’，常偏主观；attribute 更常用于因果归因。" },

  { w:"notwithstanding", ipa:"/ˌnɒtwɪθˈstændɪŋ/", pos:"prep./conj.", cat:"学术写作",
    senses:[{ def:"尽管；虽然", ex:["Notwithstanding the risks, they proceeded.",
      "The law applies, difficulties notwithstanding.",
      "His objections notwithstanding, the plan passed."],
      note:"正式，位置灵活（可置句首/句末/名词后）；= despite。" }],
    syn:["despite","although"], ant:[],
    synDiff:"despite 最常用；notwithstanding 更正式且位置灵活。" },

  { w:"salient", ipa:"/ˈseɪliənt/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"显著的；突出的", ex:["The salient point is the cost.",
      "She summarised the salient features.",
      "Three salient differences emerged."],
      note:"常修饰 point / feature / fact；名词 salience 显著性。" }],
    syn:["prominent","notable"], ant:["minor","trivial"],
    synDiff:"prominent 显眼；salient 强调‘最值得注意的关键点’。" },

  { w:"tentative", ipa:"/ˈtentətɪv/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"暂定的；试探性的", ex:["We offer a tentative conclusion.",
      "His tentative steps showed his uncertainty.",
      "These are tentative findings pending review."],
      note:"名词 tentativeness；反义 definitive 确定的。" }],
    syn:["provisional","hesitant"], ant:["definitive","firm"],
    synDiff:"provisional 偏‘临时安排’；tentative 强调结论‘尚不确定、待验证’。" },

  { w:"comprise", ipa:"/kəmˈpraɪz/", pos:"v.", cat:"学术写作",
    senses:[{ def:"包含；由…组成", ex:["The sample comprises 500 households.",
      "The committee is comprised of experts.",
      "The book comprises three parts."],
      note:"不用被动进行时‘comprising of’是错的；正确 comprise / be comprised of。" }],
    syn:["consist of","include"], ant:[],
    synDiff:"consist of 与 comprise 同义但 comprise 语气更正式；include 不一定穷尽。" },

  { w:"elucidate", ipa:"/iˈluːsɪdeɪt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"阐明；解释清楚", ex:["The diagram elucidates the mechanism.",
      "Let me elucidate the key assumption.",
      "The author elucidates a difficult concept."],
      note:"正式；= clarify / explain，但更书面。" }],
    syn:["clarify","explain"], ant:["obscure","confuse"],
    synDiff:"clarify 使清楚；elucidate 正式‘详细阐明（复杂事物）’。" },

  // ============== 英语文学（补充） ==============
  { w:"metonymy", ipa:"/məˈtɒnəmi/", pos:"n.", cat:"英语文学",
    senses:[{ def:"转喻（以相关物代本体）", ex:["‘The crown’ is a metonymy for the monarchy.",
      "‘The pen is mightier than the sword’ uses metonymy.",
      "Wall Street is a metonymy for finance."],
      note:"与 metaphor 不同：metonymy 是‘相关替换’，非‘类比’。" }],
    syn:["synecdoche"], ant:[],
    synDiff:"synecdoche 以部分代整体（如 wheels 代 car）；metonymy 以相关物代（crown 代 king）。" },

  { w:"allegory", ipa:"/ˈæləɡəri/", pos:"n.", cat:"英语文学",
    senses:[{ def:"寓言；讽喻", ex:["Animal Farm is an allegory of totalitarianism.",
      "The poem is an allegory of the soul's journey.",
      "He read the tale as a political allegory."],
      note:"allegory 整篇为喻；metaphor 单句是喻；形容词 allegorical。" }],
    syn:["fable","parable"], ant:[],
    synDiff:"fable 多动物寓言之；parable 宗教道德短喻；allegory 篇幅更长、系统性的讽喻。" },

  { w:"sonnet", ipa:"/ˈsɒnɪt/", pos:"n.", cat:"英语文学",
    senses:[{ def:"十四行诗", ex:["Shakespeare wrote 154 sonnets.",
      "The sonnet follows a strict rhyme scheme.",
      "She composed a Petrarchan sonnet."],
      note:"Shakespearean (ABAB CDCD EFEF GG) / Petrarchan 两种韵式。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"elegy", ipa:"/ˈelədʒi/", pos:"n.", cat:"英语文学",
    senses:[{ def:"挽歌；哀诗", ex:["Tennyson's elegy honoured his friend.",
      "The elegy mourns a lost world.",
      "She wrote an elegy for the fallen city."],
      note:"悼亡之作；形容词 elegiac；与 eulogy（颂词）不同。" }],
    syn:["lament","dirge"], ant:["eulogy"],
    synDiff:"eulogy 是‘赞颂词’；elegy 是‘哀悼诗’。" },

  { w:"pastoral", ipa:"/ˈpɑːstərəl/", pos:"adj./n.", cat:"英语文学",
    senses:[{ def:"田园的（牧歌体裁）", ex:["The play has a pastoral setting.",
      "Pastoral poems idealise rural life.",
      "He painted a pastoral of shepherds and streams."],
      note:"题材：乡村/牧人理想化；名词 a pastoral 田园诗/画。" }],
    syn:["bucolic","idyllic"], ant:["urban"],
    synDiff:"bucolic 乡村的；pastoral 特指‘牧歌式理想化乡村’；idyllic 偏‘恬静美好’。" },

  { w:"blank verse", ipa:"/ˈblæŋk vɜːs/", pos:"n.", cat:"英语文学",
    senses:[{ def:"无韵诗（素体诗，不押韵的抑扬格五音步）", ex:["Much of Hamlet is written in blank verse.",
      "Milton's Paradise Lost uses blank verse.",
      "Blank verse suits the rhythms of speech."],
      note:"= unrhymed iambic pentameter；与 free verse 自由诗不同。" }],
    syn:["unrhymed verse"], ant:["free verse"],
    synDiff:"free verse 完全自由无格律；blank verse 有格律但不押韵。" },

  { w:"tragicomedy", ipa:"/ˌtrædʒiˈkɒmədi/", pos:"n.", cat:"英语文学",
    senses:[{ def:"悲喜剧", ex:["The play is a tragicomedy of misunderstanding.",
      "Waiting for Godot blends farce and tragicomedy.",
      "Her novel is a quiet tragicomedy of family life."],
      note:"混合悲剧与喜剧元素；形容词 tragicomic。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"deus ex machina", ipa:"/ˌdeɪəs eks ˈmækɪnə/", pos:"n.", cat:"英语文学",
    senses:[{ def:"（戏剧）机械降神；突兀解困", ex:["The rescue felt like a deus ex machina.",
      "Critics mocked the deus ex machina ending.",
      "Avoid a deus ex machina in your plot."],
      note:"原指古希腊舞台机关送神解围；今指‘生硬强行收尾’。" }],
    syn:["contrived ending"], ant:[], synDiff:"" },

  { w:"anaphora", ipa:"/əˈnæfərə/", pos:"n.", cat:"英语文学",
    senses:[{ def:"首语重复（句首重复以加强）", ex:["‘I have a dream’ uses anaphora.",
      "Anaphora opens each stanza with ‘We shall’.",
      "The speech gains force from anaphora."],
      note:"修辞格；与 epistrophe（尾语重复）相对。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"metre", ipa:"/ˈmiːtə(r)/", pos:"n.", cat:"英语文学",
    senses:[{ def:"格律；韵律（美 meter）", ex:["The metre is iambic pentameter.",
      "He scanned the line for its metre.",
      "Free verse abandons regular metre."],
      note:"韵律单位；scan 析韵律；与 rhythm 不同，metre 是规则格律。" }],
    syn:["rhythm","prosody"], ant:[],
    synDiff:"rhythm 泛指节奏；metre 是‘系统化格律’。" },

  { w:"verisimilitude", ipa:"/ˌverɪsɪˈmɪlɪtjuːd/", pos:"n.", cat:"英语文学",
    senses:[{ def:"逼真；似真性", ex:["The novel achieves verisimilitude through detail.",
      "Realism prizes verisimilitude over fantasy.",
      "The film's verisimilitude impressed critics."],
      note:"‘the appearance of being true’；形容词 verisimilar。" }],
    syn:["realism","authenticity"], ant:["implausibility"],
    synDiff:"authenticity 真实（确实真）；verisimilitude 是‘看起来像真的’。" },

  { w:"anachronism", ipa:"/əˈnækrənɪzəm/", pos:"n.", cat:"英语文学",
    senses:[{ def:"时代错误（置于错误年代的事物）", ex:["A wristwatch in a Roman film is an anachronism.",
      "The clock was an anachronism in the medieval scene.",
      "Calling them ‘nations’ is a historical anachronism."],
      note:"形容词 anachronistic；常用于批评年代错置。" }],
    syn:["chronological error"], ant:[], synDiff:"" },

  // ============== 法律政治（补充） ==============
  { w:"ratify", ipa:"/ˈrætɪfaɪ/", pos:"v.", cat:"法律政治",
    senses:[{ def:"批准；正式签署生效", ex:["The senate ratified the treaty.",
      "The contract was ratified by both boards.",
      "Member states must ratify the amendment."],
      note:"用于条约/宪法修正案；名词 ratification。" }],
    syn:["approve","sanction"], ant:["reject","veto"],
    synDiff:"approve 一般批准；ratify 特指‘依程序正式批准（条约等）’。" },

  { w:"sovereignty", ipa:"/ˈsɒvrənti/", pos:"n.", cat:"法律政治",
    senses:[{ def:"主权；最高统治权", ex:["The treaty respects national sovereignty.",
      "Parliament is the seat of popular sovereignty.",
      "They defended their economic sovereignty."],
      note:"sovereign state 主权国家；popular sovereignty 人民主权。" }],
    syn:["autonomy","supremacy"], ant:["dependency"],
    synDiff:"autonomy 自治权；sovereignty 国际法上‘最高且独立的权力’。" },

  { w:"jurisdiction", ipa:"/ˌdʒʊərɪsˈdɪkʃn/", pos:"n.", cat:"法律政治",
    senses:[{ def:"管辖权；司法管辖区", ex:["The court lacks jurisdiction here.",
      "The crime fell outside our jurisdiction.",
      "Two states claimed jurisdiction over the waters."],
      note:"within/outside one's jurisdiction 在/不在管辖范围内。" }],
    syn:["authority","purview"], ant:[],
    synDiff:"authority 泛指职权；jurisdiction 法律‘管辖范围’。" },

  { w:"litigation", ipa:"/ˌlɪtɪˈɡeɪʃn/", pos:"n.", cat:"法律政治",
    senses:[{ def:"诉讼；打官司", ex:["The dispute ended in litigation.",
      "Litigation can take years and drain funds.",
      "They settled to avoid litigation."],
      note:"动词 litigate；litigious 好诉讼的。" }],
    syn:["lawsuit","suit"], ant:["settlement"],
    synDiff:"lawsuit 指具体‘一案’；litigation 泛指‘诉讼过程/行为’。" },

  { w:"defendant", ipa:"/dɪˈfendənt/", pos:"n.", cat:"法律政治",
    senses:[{ def:"被告", ex:["The defendant pleaded not guilty.",
      "The defendant was acquitted for lack of evidence.",
      "Witnesses testified against the defendant."],
      note:"民事诉讼 plaintiff 原告；刑事 prosecution 检方。" }],
    syn:["accused"], ant:["plaintiff","prosecutor"],
    synDiff:"accused 偏刑事‘被指控者’；defendant 通用‘被告’。" },

  { w:"plaintiff", ipa:"/ˈpleɪntɪf/", pos:"n.", cat:"法律政治",
    senses:[{ def:"原告（民事诉讼）", ex:["The plaintiff filed the suit in May.",
      "The plaintiff bore the burden of proof.",
      "Damages were awarded to the plaintiff."],
      note:"刑事案对应 prosecution（检方），非 plaintiff。" }],
    syn:["claimant"], ant:["defendant"],
    synDiff:"claimant 泛指‘索赔人’；plaintiff 专指民事‘原告’。" },

  { w:"statute", ipa:"/ˈstætʃuːt/", pos:"n.", cat:"法律政治",
    senses:[{ def:"成文法；制定法", ex:["The statute prohibits such sales.",
      "By statute, the deadline is fixed.",
      "The court interpreted the statute narrowly."],
      note:"与 case law（判例法）相对；statutory 法定的。" }],
    syn:["act","law"], ant:["common law"],
    synDiff:"act 指‘法案/法令’；statute 泛指‘成文制定法’；common law 判例法。" },

  { w:"precedent", ipa:"/ˈpresɪdənt/", pos:"n.", cat:"法律政治",
    senses:[{ def:"先例", ex:["The ruling set a dangerous precedent.",
      "Decisions follow established precedent.",
      "There is no precedent for such a case."],
      note:"stare decisis 遵循先例；binding / persuasive precedent。" }],
    syn:["example","authority"], ant:[],
    synDiff:"example 普通例子；precedent 法律‘可援引的先例’。" },

  { w:"impartial", ipa:"/ɪmˈpɑːʃl/", pos:"adj.", cat:"法律政治",
    senses:[{ def:"公正的；不偏不倚的", ex:["The judge must remain impartial.",
      "An impartial jury is essential to fairness.",
      "The mediator was wholly impartial."],
      note:"名词 impartiality；与 neutral 近义但更正式。" }],
    syn:["neutral","unbiased"], ant:["biased","partial"],
    synDiff:"neutral 中立；impartial 强调‘无偏私、公正裁决’。" },

  { w:"constituency", ipa:"/kənˈstɪtjuənsi/", pos:"n.", cat:"法律政治",
    senses:[{ def:"选区；选民群体", ex:["He won his London constituency.",
      "The policy pleases her rural constituency.",
      "MPs represent their constituencies in parliament."],
      note:"议员 constituency MP；也泛指‘支持群体’。" }],
    syn:["district","electorate"], ant:[],
    synDiff:"district 地理选区；electorate 全体选民；constituency 二者皆可。" },

  { w:"coalition", ipa:"/ˌkəʊəˈlɪʃn/", pos:"n.", cat:"法律政治",
    senses:[{ def:"联合政府；联盟", ex:["A coalition formed after the hung election.",
      "The coalition collapsed within a year.",
      "They built a coalition of civil-society groups."],
      note:"coalition government 联合政府；动词 coalesce 联合。" }],
    syn:["alliance","bloc"], ant:["faction"],
    synDiff:"alliance 泛指联盟；coalition 多指‘为执政/行动临时结成的联合’。" },

  { w:"sanction", ipa:"/ˈsæŋkʃn/", pos:"n./v.", cat:"法律政治",
    senses:[{ def:"制裁；批准", ex:["The UN imposed economic sanctions.",
      "The deal needs board sanction.",
      "States sanctioned the offending regime."],
      note:"一词两义易混：sanction 可作‘制裁’也可作‘批准/认可’（依语境）。" }],
    syn:["penalty","approval"], ant:[],
    synDiff:"作‘制裁’近 penalty；作‘批准’近 approval；注意上下文。" },

  { w:"ideology", ipa:"/ˌaɪdiˈɒlədʒi/", pos:"n.", cat:"法律政治",
    senses:[{ def:"意识形态", ex:["The policy reflects a free-market ideology.",
      "Competing ideologies shaped the century.",
      "He rejected all political ideology."],
      note:" ideological 意识形态的；-ism 常表具体思潮。" }],
    syn:["doctrine","creed"], ant:[],
    synDiff:"doctrine 教义/学说；ideology 更宽‘一套政治社会信念体系’。" },

  { w:"autocracy", ipa:"/ɔːˈtɒkrəsi/", pos:"n.", cat:"法律政治",
    senses:[{ def:"独裁统治", ex:["The country slid into autocracy.",
      "Autocracy concentrates power in one ruler.",
      "They opposed the return to autocracy."],
      note:"autocrat 独裁者；对比 democracy / theocracy。" }],
    syn:["dictatorship","despotism"], ant:["democracy"],
    synDiff:"dictatorship 强调‘独裁者个人统治’；autocracy 泛指‘集权政体’。" },

  { w:"referendum", ipa:"/ˌrefəˈrendəm/", pos:"n.", cat:"法律政治",
    senses:[{ def:"公民投票；公投", ex:["A referendum decided the question.",
      "The referendum passed by a narrow margin.",
      "They called a referendum on independence."],
      note:"复数 referendums / referenda；直接民主形式。" }],
    syn:["plebiscite","vote"], ant:[],
    synDiff:"plebiscite 亦‘全民表决’，常带权威主导色彩；referendum 最常用。" },

  { w:"extradite", ipa:"/ˈekstrədaɪt/", pos:"v.", cat:"法律政治",
    senses:[{ def:"引渡", ex:["France refused to extradite the suspect.",
      "The treaty allows us to extradite fugitives.",
      "He was extradited to stand trial abroad."],
      note:"名词 extradition；extradite sb. to..." }],
    syn:[], ant:[], synDiff:"" },

  { w:"amnesty", ipa:"/ˈæmnəsti/", pos:"n.", cat:"法律政治",
    senses:[{ def:"大赦", ex:["The king granted a general amnesty.",
      "Amnesty was offered to defectors.",
      "They demanded amnesty for political prisoners."],
      note:"与 pardon（特赦个别人）不同；amnesty 多针对群体。" }],
    syn:["pardon"], ant:[],
    synDiff:"pardon 特赦个人；amnesty 对一类人的‘大赦’。" },

  // ============== 医疗健康（补充） ==============
  { w:"symptom", ipa:"/ˈsɪmptəm/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"症状", ex:["Fever is a common symptom.",
      "The symptom appeared three days later.",
      "These symptoms warrant a doctor's visit."],
      note:"与 sign（体征，医生可测）不同；symptom 病人主观感受。" }],
    syn:["indication","manifestation"], ant:[],
    synDiff:"sign 是客观体征；symptom 是主观症状。" },

  { w:"chronic", ipa:"/ˈkrɒnɪk/", pos:"adj.", cat:"医疗健康",
    senses:[{ def:"慢性的（长期的）", ex:["He has chronic back pain.",
      "Chronic stress harms the heart.",
      "Diabetes is a chronic condition."],
      note:"反义 acute 急性的；chronic 也口语‘严重的’（chronic liar）。" }],
    syn:["persistent","long-term"], ant:["acute","temporary"],
    synDiff:"persistent 持续；chronic 医学‘慢性/长期不愈’。" },

  { w:"acute", ipa:"/əˈkjuːt/", pos:"adj.", cat:"医疗健康",
    senses:[{ def:"急性的；剧烈的", ex:["He felt acute chest pain.",
      "An acute infection needs swift care.",
      "The crisis reached an acute stage."],
      note:"反义 chronic；acute 也指‘敏锐/尖锐’（acute sense of smell）。" }],
    syn:["severe","sudden"], ant:["chronic","mild"],
    synDiff:"severe 严重；acute 强调‘突然发作、剧烈’。" },

  { w:"vaccine", ipa:"/ˈvæksiːn/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"疫苗", ex:["The vaccine prevents the disease.",
      "She got the flu vaccine in autumn.",
      "Researchers developed a vaccine in record time."],
      note:"动词 vaccinate；名词 vaccination。来自 vacca‘牛’（牛痘）。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"diagnosis", ipa:"/ˌdaɪəɡˈnəʊsɪs/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"诊断", ex:["The diagnosis was confirmed by scan.",
      "Early diagnosis improves the odds.",
      "He received a diagnosis of diabetes."],
      note:"动词 diagnose；复数 diagnoses；反义 misdiagnosis。" }],
    syn:["identification","assessment"], ant:["misdiagnosis"],
    synDiff:"assessment 评估；diagnosis 专指‘疾病诊断’。" },

  { w:"prognosis", ipa:"/prɒɡˈnəʊsɪs/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"预后（对病程的判断）", ex:["The prognosis is favourable.",
      "Doctors gave a poor prognosis.",
      "The prognosis depends on early treatment."],
      note:"与 diagnosis 不同：diagnosis 是‘是什么病’，prognosis 是‘会怎样’。" }],
    syn:["outlook","forecast"], ant:[],
    synDiff:"outlook 前景；prognosis 医学‘预后’。" },

  { w:"therapy", ipa:"/ˈθerəpi/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"治疗；疗法", ex:["She is in physical therapy.",
      "Speech therapy helped the child.",
      "Cognitive therapy eased his anxiety."],
      note:"therapist 治疗师；-therapy 复合词多（chemotherapy 化疗）。" }],
    syn:["treatment","cure"], ant:[],
    synDiff:"cure 强调‘治愈’；therapy 是‘疗程/疗法’。" },

  { w:"relapse", ipa:"/rɪˈlæps/", pos:"v./n.", cat:"医疗健康",
    senses:[{ def:"复发；故态复萌", ex:["The patient relapsed after a month.",
      "A relapse sent him back to hospital.",
      "She feared a relapse into old habits."],
      note:"也可指戒瘾/恶习复发；反义 recover / remit。" }],
    syn:["recur","regress"], ant:["recover","remit"],
    synDiff:"recur 泛指‘再发生’；relapse 特指‘病/瘾复发倒退’。" },

  { w:"contagious", ipa:"/kənˈteɪdʒəs/", pos:"adj.", cat:"医疗健康",
    senses:[{ def:"传染性的（接触传播）", ex:["The flu is highly contagious.",
      "Keep contagious children home.",
      "Yawning is surprisingly contagious."],
      note:"与 infectious 区别：contagious 多经接触；infectious 可经空气/体液，也喻‘有感染力’。" }],
    syn:["infectious","catching"], ant:["non-contagious"],
    synDiff:"infectious 空气/体液传播或‘有感染力’；contagious 接触传播。" },

  { w:"allergy", ipa:"/ˈælədʒi/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"过敏", ex:["She has an allergy to nuts.",
      "The rash was an allergic reaction.",
      "Peanut allergy can be life-threatening."],
      note:"形容词 allergic；allergen 过敏原。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"fracture", ipa:"/ˈfræktʃə(r)/", pos:"n./v.", cat:"医疗健康",
    senses:[{ def:"骨折；断裂", ex:["He suffered a fractured wrist.",
      "The bone fractured on impact.",
      "The fracture healed in six weeks."],
      note:"compound fracture 开放性骨折；fissure 裂纹。" }],
    syn:["break","crack"], ant:["heal"],
    synDiff:"break 口语‘断’；fracture 医学‘骨折/裂’。" },

  { w:"syndrome", ipa:"/ˈsɪndrəʊm/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"综合征（一组并发症状）", ex:["Down syndrome is genetic.",
      "He has carpal tunnel syndrome.",
      "The syndrome has no known cure."],
      note:"一组症状集合，非单一病；与 disease 不同。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"placebo", ipa:"/pləˈsiːbəʊ/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"安慰剂", ex:["The trial used a placebo control.",
      "The pill was a inert placebo.",
      "Some felt better on placebo alone."],
      note:"placebo effect 安慰剂效应；inert 无药效的。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"transplant", ipa:"/trænsˈplɑːnt/", pos:"v./n.", cat:"医疗健康",
    senses:[{ def:"移植", ex:["He had a kidney transplant.",
      "Doctors transplanted the liver.",
      "The transplanted organ was rejected."],
      note:"organ transplant 器官移植；reject 排异。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"sedative", ipa:"/ˈsedətɪv/", pos:"n./adj.", cat:"医疗健康",
    senses:[{ def:"镇静剂", ex:["The doctor gave a mild sedative.",
      "Sedatives calm the nervous system.",
      "He was drowsy from the sedative."],
      note:"与 stimulant（兴奋剂）反义；sedate 使镇静。" }],
    syn:["tranquilliser"], ant:["stimulant"],
    synDiff:"tranquilliser 安定剂；sedative 泛指镇静剂。" },

  { w:"incision", ipa:"/ɪnˈsɪʒn/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"切口；开刀", ex:["The surgeon made a small incision.",
      "The incision healed without infection.",
      "The incision was closed with sutures."],
      note:"动词 incise；反义 suture/stitch 缝合。" }],
    syn:["cut","wound"], ant:["suture"],
    synDiff:"cut 普通切；incision 医学‘手术切口’。" },

  { w:"palpitate", ipa:"/ˈpælpɪteɪt/", pos:"v.", cat:"医疗健康",
    senses:[{ def:"（心脏）悸动；心悸", ex:["Her heart palpitated with fear.",
      "Caffeine made his heart palpitate.",
      "The heart palpitated irregularly."],
      note:"palpitations 心悸（症状）；与 beat 不同，指‘异常快/乱跳’。" }],
    syn:["flutter","pound"], ant:[], synDiff:"" },

  // ============== 美食食品（补充） ==============
  { w:"avocado", ipa:"/ˌævəˈkɑːdəʊ/", pos:"n.", cat:"美食食品",
    senses:[{ def:"牛油果；鳄梨", ex:["She mashed avocado on toast.",
      "Avocado adds creaminess to salads.",
      "The avocado was ripe but not brown."],
      note:"fruit 但常作蔬菜用；guacamole 鳄梨酱。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"asparagus", ipa:"/əˈspærəɡəs/", pos:"n.", cat:"美食食品",
    senses:[{ def:"芦笋", ex:["We grilled the asparagus with oil.",
      "Asparagus is in season in spring.",
      "She trimmed the woody ends of the asparagus."],
      note:"蔬菜；woody end 老根需去。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"zucchini", ipa:"/zuˈkiːni/", pos:"n.", cat:"美食食品",
    senses:[{ def:"西葫芦（美；英 courgette）", ex:["He sautéed zucchini with garlic.",
      "Grate zucchini into the batter.",
      "The zucchini plant yielded all summer."],
      note:"英式 courgette /ˌkʊəˈʒet/；葫芦科。" }],
    syn:["courgette"], ant:[], synDiff:"" },

  { w:"pomegranate", ipa:"/ˈpɒmɪɡrænɪt/", pos:"n.", cat:"美食食品",
    senses:[{ def:"石榴", ex:["She sprinkled pomegranate seeds on the salad.",
      "Pomegranate juice is tart and deep red.",
      "The pomegranate split to show its arils."],
      note:"seed 称 aril 果粒；tart 酸。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"quinoa", ipa:"/ˈkiːnwɑː/", pos:"n.", cat:"美食食品",
    senses:[{ def:"藜麦", ex:["Quinoa is a protein-rich grain.",
      "She cooked quinoa as a rice substitute.",
      "Rinse quinoa before boiling it."],
      note:"伪谷物 pseudocereal；gluten-free 无麸质。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"tofu", ipa:"/ˈtəʊfuː/", pos:"n.", cat:"美食食品",
    senses:[{ def:"豆腐", ex:["He stir-fried tofu with greens.",
      "Silken tofu blends into smooth soups.",
      "Tofu takes on the flavour of the sauce."],
      note:"soybean 大豆制；silken/firm 嫩/老豆腐。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"saute", ipa:"/ˈsəʊteɪ/", pos:"v.", cat:"美食食品",
    senses:[{ def:"嫩煎；快炒", ex:["Sauté the onions until translucent.",
      "She sautéed the mushrooms in butter.",
      "Sauté the garlic briefly, don't burn it."],
      note:"法文；= pan-fry lightly；名词 a sauté。" }],
    syn:["pan-fry","fry"], ant:[],
    synDiff:"fry 泛指煎炸；sauté 强调‘少油快火嫩煎’。" },

  { w:"marinate", ipa:"/ˈmærɪneɪt/", pos:"v.", cat:"美食食品",
    senses:[{ def:"腌制；浸泡入味", ex:["Marinate the chicken overnight.",
      "The beef marinated in wine and herbs.",
      "Let it marinate at least two hours."],
      note:"marinade 腌料；也写作 marine。" }],
    syn:["cure","pickle"], ant:[],
    synDiff:"cure 风干/盐制保存；marinate 用液料浸泡入味。" },

  { w:"umami", ipa:"/uːˈmɑːmi/", pos:"n.", cat:"美食食品",
    senses:[{ def:"鲜味（第五种基本味）", ex:["Mushrooms add umami to the dish.",
      "Soy sauce is rich in umami.",
      "Umami balances sweetness and acid."],
      note:"日语‘うま味’；第五味觉，与 sweet/sour/salty/bitter 并列。" }],
    syn:["savouriness"], ant:[],
    synDiff:"savouriness 英式‘咸鲜’；umami 专指‘鲜味’。" },

  { w:"pastry", ipa:"/ˈpeɪstri/", pos:"n.", cat:"美食食品",
    senses:[{ def:"油酥面团；糕点", ex:["The pastry was light and flaky.",
      "She rolled the pastry thin.",
      "French pastries lined the window."],
      note:"flaky 起酥；与 pasta（面团/意面）不同。" }],
    syn:["dough","baked good"], ant:[],
    synDiff:"dough 生面团；pastry 指‘油酥类糕点’。" },

  { w:"umami broth", ipa:"/uːˈmɑːmi brɒθ/", pos:"n.", cat:"美食食品",
    senses:[{ def:"高汤；鲜汤", ex:["The broth simmered for hours.",
      "Skim the broth before serving.",
      "A clear broth started the meal."],
      note:"broth 清汤；stock 高汤（更浓）；bouillon 块汤。" }],
    syn:["stock","soup"], ant:[],
    synDiff:"stock 熬制的浓高汤；broth 较稀的汤；soup 成品汤。" },

  { w:"tannin", ipa:"/ˈtænɪn/", pos:"n.", cat:"美食食品",
    senses:[{ def:"单宁（茶/酒中的涩味物质）", ex:["The red wine's tannin dried the mouth.",
      "Tannin gives tea its astringency.",
      "Young wines are high in tannin."],
      note:"astringent 涩；也用于皮革鞣制。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"ferment", ipa:"/fəˈment/", pos:"v.", cat:"美食食品",
    senses:[{ def:"发酵", ex:["Yeast ferments the sugar into alcohol.",
      "The cabbage fermented into sauerkraut.",
      "Let the dough ferment overnight."],
      note:"名词 fermentation；fermented 发酵的（酸奶/酒/泡菜）。" }],
    syn:["culture","leaven"], ant:[],
    synDiff:"leaven 用酵母发（面团）；ferment 广义‘发酵（含酒/乳/菜）’。" },

  { w:"garnish", ipa:"/ˈɡɑːnɪʃ/", pos:"v./n.", cat:"美食食品",
    senses:[{ def:"装饰（菜）；（配菜）", ex:["Garnish the soup with herbs.",
      "A lemon wedge garnished the plate.",
      "Parsley is a common garnish."],
      note:"名词‘装饰配菜’；与 decorate 近但专指食物。" }],
    syn:["decorate","embellish"], ant:[],
    synDiff:"decorate 泛指装饰；garnish 专指‘菜肴点缀’。" },

  { w:"cuisine", ipa:"/kwɪˈziːn/", pos:"n.", cat:"美食食品",
    senses:[{ def:"菜系；烹饪风格", ex:["French cuisine is rich and buttery.",
      "The region boasts a unique cuisine.",
      "She trained in classic cuisine."],
      note:"表‘某国/地烹饪’；也指厨房（设备）。" }],
    syn:["cooking","gastronomy"], ant:[],
    synDiff:"cooking 烹饪行为；cuisine 指‘体系化的菜系’。" },

  { w:"umami-laden", ipa:"/uːˈmɑːmi ˈleɪdn/", pos:"adj.", cat:"美食食品",
    senses:[{ def:"富含鲜味的", ex:["The broth was umami-laden and deep.",
      "Aged cheese is umami-laden.",
      "The sauce turned umami-laden with miso."],
      note:"-laden 充满…的；描述鲜味浓。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"mince", ipa:"/mɪns/", pos:"v./n.", cat:"美食食品",
    senses:[{ def:"剁碎；肉末（美 ground meat）", ex:["Mince the garlic finely.",
      "She bought beef mince for the sauce.",
      "He minced the herbs with a knife."],
      note:"英 mince / 美 ground；mincemeat 果脯馅（非肉）。" }],
    syn:["grind","chop"], ant:[],
    synDiff:"chop 切块；mince/grind 剁/磨成末。" },

  { w:"caramelise", ipa:"/ˈkærəməlaɪz/", pos:"v.", cat:"美食食品",
    senses:[{ def:"熬成焦糖；炒糖色", ex:["Caramelise the sugar slowly.",
      "Onions caramelise to a golden brown.",
      "The sauce caramelised at the edges."],
      note:"美 caramelize；焦糖化反应。" }],
    syn:[], ant:[], synDiff:"" },

  // ============== 外貌性格（高阶补充） ==============
  { w:"comely", ipa:"/ˈkʌmli/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"清秀的；好看的（旧式/文雅）", ex:["A comely village maid appeared.",
      "He described her as comely and kind.",
      "The comely face hid a sharp mind."],
      note:"较 archaic，现多用于文学；近 pretty 但更端庄。" }],
    syn:["attractive","pretty"], ant:["plain","homely"],
    synDiff:"pretty 日常漂亮；comely 文雅‘清秀端庄’。" },

  { w:"willowy", ipa:"/ˈwɪləʊi/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"（身形）苗条柔韧的", ex:["The willowy model glided in.",
      "She had a willowy, graceful figure.",
      "A willowy dancer bent like a reed."],
      note:"喻 like a willow 柳树般柔韧；tall and slender。" }],
    syn:["slender","lithe"], ant:["stocky"],
    synDiff:"slender 苗条；willowy 强调‘高挑且柔韧如柳’。" },

  { w:"matronly", ipa:"/ˈmeɪtrənli/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"（女性）庄重丰腴的；主妇气的", ex:["She wore a matronly dress.",
      "A matronly figure supervised the hall.",
      "The matronly host welcomed them warmly."],
      note:"matron 年长已婚妇女/女主管；非贬，指‘稳重丰润’。" }],
    syn:["dignified","stately"], ant:["girlish"],
    synDiff:"stately 庄严；matronly 特指‘成熟主妇般的丰润庄重’。" },

  { w:"dapper", ipa:"/ˈdæpə(r)/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"（男子）衣冠楚楚的；精干的", ex:["A dapper old gentleman tipped his hat.",
      "He looked dapper in a waistcoat.",
      "The dapper clerk bowed slightly."],
      note:"small and neat 小个子但整洁利落；常带欣赏。" }],
    syn:["spruce","smart"], ant:["scruffy","slovenly"],
    synDiff:"smart 整洁帅；dapper 强调‘小而精致、利落有型’。" },

  { w:"sallow", ipa:"/ˈsæləʊ/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"（肤色）蜡黄的病态", ex:["His sallow skin betrayed fatigue.",
      "The patient looked sallow and drawn.",
      "A sallow complexion needs warm tones."],
      note:"非 tan（晒黑）；sallow 是‘不健康枯黄’。" }],
    syn:["pallid","wan"], ant:["ruddy","rosy"],
    synDiff:"pallid 苍白；sallow 偏‘黄而病态’；ruddy 红润健康。" },

  { w:"inscrutable", ipa:"/ɪnˈskruːtəbl/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"莫测高深的；难以读懂的", ex:["He wore an inscrutable smile.",
      "Her inscrutable face gave nothing away.",
      "The monk's expression was inscrutable."],
      note:"scrutable 可测的；inscrutable 常用于‘面无表情、深不可测’。" }],
    syn:["enigmatic","mysterious"], ant:["readable","transparent"],
    synDiff:"enigmatic 神秘；inscrutable 强调‘无法从表情推断内心’。" },

  { w:"imperturbable", ipa:"/ˌɪmpəˈtɜːbəbl/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"沉着的；不为所动的", ex:["She stayed imperturbable under fire.",
      "His imperturbable calm reassured the crew.",
      "The diplomat was imperturbable in crisis."],
      note:"perturb 使不安；imperturbable ‘泰山崩于前而色不变’。" }],
    syn:["composed","unflappable"], ant:["flappable","agitated"],
    synDiff:"composed 镇定；imperturbable 强调‘根本无法被扰动’。" },

  { w:"diffident", ipa:"/ˈdɪfɪdənt/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"缺乏自信的；羞怯的", ex:["He was too diffident to speak up.",
      "A diffident smile flickered on her face.",
      "She gave a diffident little laugh."],
      note:"与 confident 反；diffidence 缺乏自信。" }],
    syn:["shy","timid"], ant:["confident","assertive"],
    synDiff:"shy 怕生；diffident 强调‘对自己能力不自信而不敢表达’。" },

  { w:"unctuous", ipa:"/ˈʌŋktʃuəs/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"（言谈）过分奉承的；油腻的", ex:["The salesman gave an unctuous smile.",
      "His unctuous praise rang false.",
      "She found his unctuous manner offensive."],
      note:"贬义；原指‘油滑’，喻‘虚伪热情’。" }],
    syn:["fulsome","oily"], ant:["sincere","blunt"],
    synDiff:"fulsome 过度到令人不适的；unctuous 强调‘油嘴滑舌、谄媚’。" },

  { w:"querulous", ipa:"/ˈkwerələs/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"爱抱怨的；易怒的", ex:["A querulous old man grumbled on.",
      "Her querulous tone alienated friends.",
      "He grew querulous in his illness."],
      note:"常形容老人/病人‘动辄怨天尤人’；名词 querulousness。" }],
    syn:["complaining","peevish"], ant:["cheerful","content"],
    synDiff:"peevish 小脾气；querulous 持续‘抱怨不休’。" },

  { w:"sanguine", ipa:"/ˈsæŋɡwɪn/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"乐观自信的；面色红润的", ex:["He was sanguine about the outcome.",
      "A sanguine temperament meets setbacks lightly.",
      "She remained sanguine despite the delays."],
      note:"原义‘血红/红润’；现多指‘乐观’；反义 melancholy。" }],
    syn:["optimistic","cheerful"], ant:["melancholy","pessimistic"],
    synDiff:"optimistic 乐观；sanguine 带‘从容自信、不慌’的古典味。" },

  { w:"phlegmatic", ipa:"/fleɡˈmætɪk/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"冷静迟钝的；不易激动的", ex:["His phlegmatic nature never flared.",
      "A phlegmatic referee ignored the taunts.",
      "She was phlegmatic to the point of apathy."],
      note:"四体液说中 phlegm 黏液质；与 sanguine 相对。" }],
    syn:["calm","apathetic"], ant:["choleric","excitable"],
    synDiff:"calm 平静；phlegmatic 强调‘迟钝、缺乏激情’。" },

  { w:"choleric", ipa:"/ˈkɒlərɪk/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"暴躁的；易生气的", ex:["A choleric boss terrified the staff.",
      "His choleric temper flared at trifles.",
      "The choleric old man stamped his stick."],
      note:"四体液说 choler 胆汁质；与 phlegmatic 相反。" }],
    syn:["irascible","hot-tempered"], ant:["phlegmatic","placid"],
    synDiff:"irascible 易怒；choleric 古典‘胆汁质暴躁’。" },

  { w:"volatile", ipa:"/ˈvɒlətaɪl/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"情绪多变的；反复无常的", ex:["His volatile moods unsettled the team.",
      "A volatile crowd turned ugly fast.",
      "She is volatile, laughing then sulking."],
      note:"也形容市场/物质易变；volatile temperament 情绪不稳。" }],
    syn:["mercurial","unstable"], ant:["steady","stable"],
    synDiff:"mercurial 多变善变（可褒可贬）；volatile 偏‘危险地易爆发’。" },

  { w:"intrepid", ipa:"/ɪnˈtrepɪd/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"无畏的；勇敢的", ex:["An intrepid explorer crossed the ice.",
      "The intrepid climber scaled the cliff.",
      "She is an intrepid traveller."],
      note:"褒义；intrepidity 无畏；近 brave 但更‘敢闯’。" }],
    syn:["brave","dauntless"], ant:["timid","fearful"],
    synDiff:"brave 一般勇敢；intrepid 强调‘面对未知危险仍无畏’。" },

  { w:"fastidious", ipa:"/fæˈstɪdiəs/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"一丝不苟的；过分讲究的", ex:["He is fastidious about grammar.",
      "A fastidious host arranged everything just so.",
      "She is fastidious to a fault about cleanliness."],
      note:"可褒（细致）可贬（挑剔）；名词 fastidiousness。" }],
    syn:["meticulous","fussy"], ant:["careless","sloppy"],
    synDiff:"meticulous 细致；fastidious 强调‘对细节过分讲究/挑剔’。" },

  { w:"blithe", ipa:"/blaɪð/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"无忧无虑的；轻率的", ex:["She sang with blithe cheer.",
      "His blithe disregard for rules cost him.",
      "A blithe spirit danced through life."],
      note:"blithe 可褒‘快乐无忧’也可贬‘轻率不在意’。" }],
    syn:["carefree","nonchalant"], ant:["careworn","solemn"],
    synDiff:"carefree 无忧；blithe 多带‘不在意后果’的轻率感。" },

  // ============== 地理环境（补充） ==============
  { w:"plateau", ipa:"/ˈplætəʊ/", pos:"n.", cat:"地理环境",
    senses:[{ def:"高原；平稳期", ex:["The train crossed a vast plateau.",
      "Sales hit a plateau last quarter.",
      "The plateau rises gently to the east."],
      note:"地理‘高原’；也喻‘停滞平台期’。" }],
    syn:["highland","tableland"], ant:[],
    synDiff:"highland 高地；plateau 平坦的高原面。" },

  { w:"estuary", ipa:"/ˈestʃuəri/", pos:"n.", cat:"地理环境",
    senses:[{ def:"河口（感潮河口）", ex:["The Thames estuary meets the sea.",
      "Salt marsh lines the estuary.",
      "Many fish spawn in the estuary."],
      note:"river mouth 入海口；brackish 半咸水。" }],
    syn:["delta","mouth"], ant:[],
    synDiff:"delta 三角洲（泥沙堆积）；estuary 受潮汐影响的河口湾。" },

  { w:"tundra", ipa:"/ˈtʌndrə/", pos:"n.", cat:"地理环境",
    senses:[{ def:"苔原（极地冻土带）", ex:["The tundra blooms briefly in summer.",
      "Reindeer graze the tundra.",
      "Permafrost underlies the tundra."],
      note:"permafrost 永冻层；arctic 北极；与 taiga 针叶林相邻。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"monsoon", ipa:"/mɒnˈsuːn/", pos:"n.", cat:"地理环境",
    senses:[{ def:"季风；雨季", ex:["The monsoon brings heavy rain.",
      "Crops depend on the summer monsoon.",
      "The monsoon broke in June."],
      note:"seasonal wind + rain；break 雨季开始。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"glacier", ipa:"/ˈɡlæsiə(r)/", pos:"n.", cat:"地理环境",
    senses:[{ def:"冰川", ex:["The glacier calves ice into the sea.",
      "Glaciers carved the valley over ages.",
      "The glacier is retreating fast."],
      note:"calve 崩冰；retreat 退缩（气候变暖）。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"archipelago", ipa:"/ˌɑːkɪˈpeləɡəʊ/", pos:"n.", cat:"地理环境",
    senses:[{ def:"群岛", ex:["Indonesia is a vast archipelago.",
      "The archipelago stretches for miles.",
      "Islands dot the archipelago."],
      note:"一组岛屿；如 Malay / Japanese archipelago。" }],
    syn:["islands"], ant:[], synDiff:"" },

  { w:"watershed", ipa:"/ˈwɔːtəʃed/", pos:"n.", cat:"地理环境",
    senses:[{ def:"分水岭；转折点", ex:["The hills form the watershed.",
      "The year was a watershed in his life.",
      "This election is a political watershed."],
      note:"地理‘分水岭’；喻‘重大转折’。" }],
    syn:["turning point","divide"], ant:[],
    synDiff:"turning point 转折点；watershed 强调‘分界/分水岭’。" },

  { w:"sediment", ipa:"/ˈsedɪmənt/", pos:"n.", cat:"地理环境",
    senses:[{ def:"沉积物；泥沙", ex:["Sediment settled at the bottom.",
      "The river carries rich sediment.",
      "Layers of sediment built the plain."],
      note:"sedimentary 沉积岩；deposit 堆积。" }],
    syn:["deposit","silt"], ant:[], synDiff:"" },

  { w:"topography", ipa:"/təˈpɒɡrəfi/", pos:"n.", cat:"地理环境",
    senses:[{ def:"地形；地貌", ex:["The region's topography is rugged.",
      "Topography shapes local climate.",
      "They mapped the topography in detail."],
      note:"topographic 地形的；relief 地势起伏。" }],
    syn:["terrain","landscape"], ant:[],
    synDiff:"terrain 地形（可通行）；topography 是‘地形学/地貌特征’。" },

  { w:"arid", ipa:"/ˈærɪd/", pos:"adj.", cat:"地理环境",
    senses:[{ def:"干旱的", ex:["The arid desert receives little rain.",
      "Arid conditions limit farming.",
      "The soil is arid and cracked."],
      note:"名词 aridity；反义 humid / fertile。" }],
    syn:["dry","barren"], ant:["humid","fertile"],
    synDiff:"dry 干；arid 强调‘长期缺水不宜生长’。" },

  { w:"biodiversity", ipa:"/ˌbaɪəʊdaɪˈvɜːsəti/", pos:"n.", cat:"地理环境",
    senses:[{ def:"生物多样性", ex:["The reef teems with biodiversity.",
      "Logging reduces biodiversity.",
      "Biodiversity underpins ecosystem health."],
      note:"bio- 生命；-diversity 多样；hotspot 热点区。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"deforestation", ipa:"/diːˌfɒrɪˈsteɪʃn/", pos:"n.", cat:"地理环境",
    senses:[{ def:"森林砍伐", ex:["Deforestation drives species loss.",
      "The Amazon faces rapid deforestation.",
      "Deforestation worsens flooding."],
      note:"reforestation 再造林；forestry 林业。" }],
    syn:[], ant:["reforestation"], synDiff:"" },

  { w:"ecosystem", ipa:"/ˈiːkəʊsɪstəm/", pos:"n.", cat:"地理环境",
    senses:[{ def:"生态系统", ex:["Coral reefs are fragile ecosystems.",
      "One species can unbalance an ecosystem.",
      "Human activity disrupts the ecosystem."],
      note:"eco- 生态；biotic + abiotic 生物与非生物因素。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"phenomenon", ipa:"/fəˈnɒmɪnən/", pos:"n.", cat:"地理环境",
    senses:[{ def:"现象", ex:["The aurora is a natural phenomenon.",
      "Climate change is a global phenomenon.",
      "This social phenomenon puzzled researchers."],
      note:"复数 phenomena；phenomenal 非凡的。" }],
    syn:["occurrence","event"], ant:[],
    synDiff:"event 事件；phenomenon 可观察的‘现象/事物’。" },

  { w:"meteorology", ipa:"/ˌmiːtiəˈrɒlədʒi/", pos:"n.", cat:"地理环境",
    senses:[{ def:"气象学", ex:["Meteorology predicts the weather.",
      "He studied meteorology at university.",
      "Satellite data aids meteorology."],
      note:"meteorologist 气象学家；注意与 meteorite 陨石无关。" }],
    syn:[], ant:[], synDiff:"" },

  // ============== 艺术音乐（补充） ==============
  { w:"impressionism", ipa:"/ɪmˈpreʃənɪzəm/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"印象派", ex:["Impressionism captured light, not detail.",
      "Monet is a pillar of Impressionism.",
      "Impressionism broke with academic rules."],
      note:"画家 Monet/Renoir；强调‘光与瞬间印象’；形容词 impressionist。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"cubism", ipa:"/ˈkjuːbɪzəm/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"立体主义", ex:["Cubism fractured form into facets.",
      "Picasso pioneered Cubism.",
      "Cubism shows many views at once."],
      note:"Picasso / Braque；multi-perspective 多视角。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"surrealism", ipa:"/səˈrɪəlɪzəm/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"超现实主义", ex:["Surrealism mixed dream and reality.",
      "Dalí epitomised Surrealism.",
      "Surrealism sought the unconscious mind."],
      note:"Dalí / Magritte；dreamlike 梦幻。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"baroque", ipa:"/bəˈrɒk/", pos:"adj./n.", cat:"艺术音乐",
    senses:[{ def:"巴洛克的（华丽繁复的）", ex:["Bach wrote baroque music.",
      "The baroque church gleamed with gold.",
      "Baroque art delights in ornament."],
      note:"17–18C 风格；ornate 华丽；与 classical 简约相对。" }],
    syn:["ornate","elaborate"], ant:["plain","austere"],
    synDiff:"ornate 华丽；baroque 特指‘巴洛克时期繁复华丽风’。" },

  { w:"renaissance", ipa:"/rəˈneɪsns/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"文艺复兴；复兴", ex:["The Renaissance rebirth of art and learning.",
      "Florence was the heart of the Renaissance.",
      "There is a renaissance of craft today."],
      note:"‘rebirth’；Renaissance 大写指欧洲文艺复兴。" }],
    syn:["revival","rebirth"], ant:[],
    synDiff:"revival 复兴（泛指）；Renaissance 特指欧洲文艺复兴运动。" },

  { w:"palette", ipa:"/ˈpælət/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"调色板；（用色）范畴", ex:["The painter's palette was muted.",
      "Her palette favoured blues and greys.",
      "The film's palette is cold and grey."],
      note:"注意与 palate（上颚/味觉）、pallet（托盘）同音不同义。" }],
    syn:["colour scheme"], ant:[],
    synDiff:"colour scheme 配色方案；palette 本义‘调色板’，引申‘所用色彩范围’。" },

  { w:"composition", ipa:"/ˌkɒmpəˈzɪʃn/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"构图；作曲；作品", ex:["The composition balances dark and light.",
      "He studied musical composition.",
      "The photograph's composition is striking."],
      note:"绘画‘构图’、音乐‘作曲’、文学‘写作’通用。" }],
    syn:["arrangement","layout"], ant:[],
    synDiff:"layout 版面排布；composition 艺术‘构图/曲式结构’。" },

  { w:"tempo", ipa:"/ˈtempəʊ/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"速度；节奏（乐曲）", ex:["The conductor slowed the tempo.",
      "The tempo quickened toward the finale.",
      "Keep a steady tempo here."],
      note:"音乐术语；比喻‘步伐/进度’（the tempo of life）。" }],
    syn:["pace","speed"], ant:[],
    synDiff:"pace 步伐/节奏；tempo 音乐‘演奏速度’。" },

  { w:"crescendo", ipa:"/krəˈʃendəʊ/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"渐强；高潮", ex:["The music built to a crescendo.",
      "Tension rose to a crescendo.",
      "The crescendo crashed into the chorus."],
      note:"音乐‘渐强’；喻‘逐步高涨至顶点’。" }],
    syn:["climax","swelling"], ant:["diminuendo"],
    synDiff:"climax 顶点；crescendo 强调‘逐渐增强到顶点’。" },

  { w:"harmony", ipa:"/ˈhɑːməni/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"和声；和谐", ex:["The voices blended in harmony.",
      "He studied four-part harmony.",
      "The colours are in harmony."],
      note:"音乐‘和声’；反义 discord 不和谐；harmonious 和谐的。" }],
    syn:["concord","agreement"], ant:["discord","dissonance"],
    synDiff:"agreement 一致；harmony 音乐‘和声/协调美’。" },

  { w:"melody", ipa:"/ˈmelədi/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"旋律", ex:["The melody stuck in my head.",
      "She hummed a simple melody.",
      "The melody soars above the bass."],
      note:"melodic 旋律的；与 harmony（和声）相对。" }],
    syn:["tune","air"], ant:[],
    synDiff:"tune 曲调（口语）；melody 音乐‘旋律线’。" },

  { w:"improvisation", ipa:"/ˌɪmprəvaɪˈzeɪʃn/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"即兴（演奏/创作）", ex:["Jazz relies on improvisation.",
      "He answered with quick improvisation.",
      "The scene was pure improvisation."],
      note:"动词 improvise；jazz 核心技法。" }],
    syn:["extempore","ad-lib"], ant:["script","score"],
    synDiff:"ad-lib 临时凑；improvisation 艺术‘即兴创作’。" },

  { w:"repertoire", ipa:"/ˈrepətwɑː(r)/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"（演员/乐团的）演出曲目；全部本领", ex:["The pianist's repertoire is vast.",
      "They added the piece to the repertoire.",
      "She has a wide repertoire of skills."],
      note:"表演‘保留剧目/曲库’；也喻‘全部技能库’。" }],
    syn:["repertory","stock"], ant:[], synDiff:"" },

  { w:"ethos", ipa:"/ˈiːθɒs/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"（团体/时代的）精神气质", ex:["The ethos of the school is rigorous.",
      "The film captures the ethos of the 60s.",
      "Its ethos values freedom over order."],
      note:"亚里士多德修辞三诉求之一（ethos/pathos/logos）；精神特质。" }],
    syn:["spirit","character"], ant:[],
    synDiff:"spirit 精神；ethos 指‘共同体深层的价值观与气质’。" },

  { w:"avant-garde", ipa:"/ˌævɒ̃ ˈɡɑːd/", pos:"n./adj.", cat:"艺术音乐",
    senses:[{ def:"先锋派（前卫的）", ex:["The avant-garde shocked audiences.",
      "She favours avant-garde cinema.",
      "The gallery shows avant-garde work."],
      note:"法语‘先遣队’；指艺术上激进前卫。" }],
    syn:["experimental","cutting-edge"], ant:["traditional","conservative"],
    synDiff:"experimental 实验性；avant-garde 强调‘走在最前、挑战成规’。" },

  // ============== 旅游（补充） ==============
  { w:"itinerary", ipa:"/aɪˈtɪnərəri/", pos:"n.", cat:"旅游",
    senses:[{ def:"行程；旅行计划", ex:["Our itinerary covers three cities.",
      "The tour itinerary left little free time.",
      "She planned a tight itinerary."],
      note:"行程单；动词 itinerary 不作动词，用 plan an itinerary。" }],
    syn:["schedule","route"], ant:[],
    synDiff:"route 路线；itinerary 详细‘日程行程’。" },

  { w:"excursion", ipa:"/ɪkˈskɜːʃn/", pos:"n.", cat:"旅游",
    senses:[{ def:"短途游览；远足", ex:["We took a day excursion to the coast.",
      "The excursion included a guide.",
      "A boat excursion explored the fjord."],
      note:"day excursion 一日游；比 trip 更‘观光性’。" }],
    syn:["outing","trip"], ant:[],
    synDiff:"trip 泛旅行；excursion 短途观光/远足。" },

  { w:"landmark", ipa:"/ˈlændmɑːk/", pos:"n.", cat:"旅游",
    senses:[{ def:"地标；里程碑", ex:["The tower is the city's landmark.",
      "We photographed every landmark.",
      "The law was a landmark in civil rights."],
      note:"地理‘地标’；喻‘重大里程碑’。" }],
    syn:["monument","milestone"], ant:[],
    synDiff:"monument 纪念碑；landmark 可指自然地标/标志建筑。" },

  { w:"heritage", ipa:"/ˈherɪtɪdʒ/", pos:"n.", cat:"旅游",
    senses:[{ def:"遗产；传统", ex:["The town is a cultural heritage site.",
      "They preserve their linguistic heritage.",
      "UNESCO lists world heritage."],
      note:"cultural/natural heritage；继承的‘传统/遗存’。" }],
    syn:["legacy","inheritance"], ant:[],
    synDiff:"legacy 抽象‘遗产/影响’；heritage 强调‘可珍视的文化传统’。" },

  { w:"resort", ipa:"/rɪˈzɔːt/", pos:"n.", cat:"旅游",
    senses:[{ def:"度假胜地", ex:["They stayed at a beach resort.",
      "The ski resort opened in December.",
      "A luxury resort lined the bay."],
      note:"也作动词 resort to‘诉诸’；last resort 最后手段。" }],
    syn:["retreat","destination"], ant:[],
    synDiff:"destination 目的地；resort 专指‘度假疗养地’。" },

  { w:"souvenir", ipa:"/ˌsuːvəˈnɪə(r)/", pos:"n.", cat:"旅游",
    senses:[{ def:"纪念品", ex:["She bought a souvenir magnet.",
      "The shop sells local souvenirs.",
      "I kept the ticket as a souvenir."],
      note:"来自法语‘回忆’；memento 近义。" }],
    syn:["memento","keepsake"], ant:[],
    synDiff:"memento 纪念物（可任何）；souvenir 旅游‘纪念品’。" },

  { w:"transit", ipa:"/ˈtrænzɪt/", pos:"n.", cat:"旅游",
    senses:[{ def:"中转；公共交通", ex:["Allow time for transit between flights.",
      "The city has reliable public transit.",
      "We were in transit for twelve hours."],
      note:"in transit 在运输/中转中；transit visa 过境签。" }],
    syn:["transfer","transport"], ant:[],
    synDiff:"transfer 换乘；transit 泛指‘中转/公交系统’。" },

  { w:"visa", ipa:"/ˈviːzə/", pos:"n.", cat:"旅游",
    senses:[{ def:"签证", ex:["You need a visa to enter.",
      "She applied for a tourist visa.",
      "The visa expires next month."],
      note:"tourist/business/transit visa；entry permit 入境许可。" }],
    syn:["permit","entry clearance"], ant:[], synDiff:"" },

  { w:"cater", ipa:"/ˈkeɪtə(r)/", pos:"v.", cat:"旅游",
    senses:[{ def:"提供餐饮；迎合", ex:["The hotel caters weddings.",
      "The menu caters to vegetarians.",
      "They catered for 200 guests."],
      note:"cater to 迎合需求；caterer 餐饮承办。" }],
    syn:["provide","serve"], ant:[],
    synDiff:"serve 服务；cater 专指‘承办饮食/迎合特定需求’。" },

  { w:"vista", ipa:"/ˈvɪstə/", pos:"n.", cat:"旅游",
    senses:[{ def:"（远眺的）景色；景观", ex:["The hill offered a wide vista.",
      "A vista of rooftops opened below.",
      "The valley revealed a stunning vista."],
      note:"long view 远景；与 view 近但更‘开阔深远’。" }],
    syn:["view","panorama"], ant:[],
    synDiff:"view 一般视野；vista 强调‘延伸的远景/林荫道尽头的景’。" },

  { w:"wayfarer", ipa:"/ˈweɪfeərə(r)/", pos:"n.", cat:"旅游",
    senses:[{ def:"（文）旅行者；行路人", ex:["A weary wayfarer rested at the inn.",
      "The poem follows a lone wayfarer.",
      "Wayfarers crossed the mountain pass."],
      note:"文学/古雅用词；近 traveller 但更诗意。" }],
    syn:["traveller","wanderer"], ant:[],
    synDiff:"traveller 旅行者；wayfarer 文雅‘行旅之人’。" },

  { w:"currency", ipa:"/ˈkʌrənsi/", pos:"n.", cat:"旅游",
    senses:[{ def:"货币；流通", ex:["The local currency is the baht.",
      "Exchange your currency at the bank.",
      "The idea gained currency among youth."],
      note:"foreign currency 外汇；也指‘流传/通用’。" }],
    syn:["money","cash"], ant:[],
    synDiff:"money 钱；currency 指‘流通的货币种类’。" },

  // ============== 历史人物（补充） ==============
  { w:"Charlemagne", ipa:"/ˈʃɑːləmeɪn/", pos:"n.", cat:"历史人物",
    senses:[{ def:"查理曼（742–814，法兰克国王，加洛林王朝）", ex:["Charlemagne united much of Western Europe.",
      "Charlemagne was crowned Holy Roman Emperor in 800.",
      "The Carolingian Renaissance bore his name."],
      note:"法兰克国王/神圣罗马皇帝；推广教育、加洛林文艺复兴。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"William Shakespeare", ipa:"/ˈwɪljəm ˈʃeɪkspɪə/", pos:"n.", cat:"历史人物",
    senses:[{ def:"威廉·莎士比亚（1564–1616，英国剧作家）", ex:["Shakespeare wrote about 39 plays.",
      "Shakespeare shaped the English language itself.",
      "Hamlet is Shakespeare's most famous tragedy."],
      note:"‘ Bard of Avon’；sonnets +  tragedies/comedies 奠基英语文学。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Napoleon Bonaparte", ipa:"/nəˈpəʊliən ˈbəʊnəpɑːt/", pos:"n.", cat:"历史人物",
    senses:[{ def:"拿破仑·波拿巴（1769–1821，法国皇帝）", ex:["Napoleon rose in the Revolution's wake.",
      "Napoleon was defeated at Waterloo in 1815.",
      "The Napoleonic Code reshaped law."],
      note:"军事天才；法典影响大陆法系；滑铁卢战败。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Charles Darwin", ipa:"/tʃɑːlz ˈdɑːwɪn/", pos:"n.", cat:"历史人物",
    senses:[{ def:"查尔斯·达尔文（1809–1882，生物学家）", ex:["Darwin proposed evolution by natural selection.",
      "Darwin sailed on the Beagle to the Galápagos.",
      "On the Origin of Species changed science."],
      note:"《物种起源》；natural selection 自然选择。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Abraham Lincoln", ipa:"/ˈeɪbrəhæm ˈlɪŋkən/", pos:"n.", cat:"历史人物",
    senses:[{ def:"亚伯拉罕·林肯（1809–1865，美国第16任总统）", ex:["Lincoln led the Union through the Civil War.",
      "Lincoln issued the Emancipation Proclamation.",
      "Lincoln was assassinated in 1865."],
      note:"维护统一、解放黑奴；Gettysburg Address 名篇。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Karl Marx", ipa:"/kɑːl ˈmɑːks/", pos:"n.", cat:"历史人物",
    senses:[{ def:"卡尔·马克思（1818–1883，哲学家/经济学家）", ex:["Marx co-wrote The Communist Manifesto.",
      "Marx analysed capital and class struggle.",
      "Marx's ideas shaped the 20th century."],
      note:"《资本论》《共产党宣言》；historical materialism 历史唯物主义。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Florence Nightingale", ipa:"/ˈflɒrəns ˈnaɪtɪŋɡeɪl/", pos:"n.", cat:"历史人物",
    senses:[{ def:"弗洛伦斯·南丁格尔（1820–1910，现代护理奠基人）", ex:["Nightingale reformed military nursing.",
      "Nightingale pioneered health statistics.",
      "The Lady with the Lamp served in Crimea."],
      note:"‘提灯女神’；现代护理与卫生统计之父（母）。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Mahatma Gandhi", ipa:"/məˈhætmə ˈɡɑːndi/", pos:"n.", cat:"历史人物",
    senses:[{ def:"圣雄甘地（1869–1948，印度独立领袖）", ex:["Gandhi led non-violent resistance.",
      "Gandhi's Salt March challenged British rule.",
      "Gandhi inspired civil-rights movements worldwide."],
      note:"satyagraha 非暴力不合作；印度独立。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Winston Churchill", ipa:"/ˈwɪnstən ˈtʃɜːtʃɪl/", pos:"n.", cat:"历史人物",
    senses:[{ def:"温斯顿·丘吉尔（1874–1965，英国首相）", ex:["Churchill rallied Britain in WWII.",
      "Churchill's speeches steeled resistance.",
      "Churchill was a prolific writer and painter."],
      note:"战时领袖；‘Iron Curtain’演说；诺贝尔文学奖。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Rosa Parks", ipa:"/ˈrəʊzə pɑːks/", pos:"n.", cat:"历史人物",
    senses:[{ def:"罗莎·帕克斯（1913–2005，民权运动者）", ex:["Parks refused to give up her bus seat.",
      "Parks sparked the Montgomery bus boycott.",
      "Parks became an icon of civil rights."],
      note:"1955 蒙哥马利巴士抵制运动导火索。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Nelson Mandela", ipa:"/ˈnelsn mænˈdelə/", pos:"n.", cat:"历史人物",
    senses:[{ def:"纳尔逊·曼德拉（1918–2013，南非反种族隔离领袖）", ex:["Mandela spent 27 years in prison.",
      "Mandela became South Africa's first black president.",
      "Mandela preached reconciliation, not revenge."],
      note:"反 apartheid；真相与和解委员会。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Marie Curie", ipa:"/məˈriː ˈkjʊəri/", pos:"n.", cat:"历史人物",
    senses:[{ def:"玛丽·居里（1867–1934，物理学家/化学家）", ex:["Curie discovered radium and polonium.",
      "Curie won Nobel Prizes in two sciences.",
      "Curie pioneered research on radioactivity."],
      note:"首位两获诺奖、跨物理与化学；radioactivity 放射性。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Alan Turing", ipa:"/ˈælən ˈtjʊərɪŋ/", pos:"n.", cat:"历史人物",
    senses:[{ def:"艾伦·图灵（1912–1954，计算机科学先驱）", ex:["Turing devised the Turing machine.",
      "Turing broke the Enigma code in WWII.",
      "Turing founded the theory of computation."],
      note:"图灵机、人工智能之父；破解 Enigma。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Sima Qian", ipa:"/ˈsiːmə ˈtʃjɛn/", pos:"n.", cat:"历史人物",
    senses:[{ def:"司马迁（约前145–前86，中国史学家）", ex:["Sima Qian wrote the Shiji (Records of the Grand Historian).",
      "Sima Qian endured castration yet finished his history.",
      "The Shiji shaped Chinese historiography for millennia."],
      note:"《史记》纪传体通史之祖；‘史家之绝唱’。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Zheng He", ipa:"/dʒeŋ ˈhɜː/", pos:"n.", cat:"历史人物",
    senses:[{ def:"郑和（1371–1433，明代航海家）", ex:["Zheng He led seven voyages to the Indian Ocean.",
      "Zheng He's fleets reached Africa and Arabia.",
      "Zheng He sailed decades before Columbus."],
      note:"三宝太监；宝船下西洋，早于大航海。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Emperor Qin Shi Huang", ipa:"/ˈtʃɪn ʃiː ˈhwæŋ/", pos:"n.", cat:"历史人物",
    senses:[{ def:"秦始皇（前259–前210，中国首位皇帝）", ex:["Qin Shi Huang unified China in 221 BCE.",
      "He ordered the Great Wall and the Terracotta Army.",
      "His reforms standardised writing and weights."],
      note:"统一文字度量衡；兵马俑；焚书坑儒争议。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Ibn Battuta", ipa:"/ˌɪbən bæˈtuːtə/", pos:"n.", cat:"历史人物",
    senses:[{ def:"伊本·白图泰（1304–1369，摩洛哥旅行家）", ex:["Ibn Battuta travelled across three continents.",
      "His Rihla records medieval Eurasia and Africa.",
      "He voyaged farther than Marco Polo."],
      note:"《游记》Rihla；伊斯兰世界最伟大旅行家。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Leonardo da Vinci", ipa:"/ˌliːəˈnɑːdəʊ də ˈvɪntʃi/", pos:"n.", cat:"历史人物",
    senses:[{ def:"列奥纳多·达·芬奇（1452–1519，文艺复兴全才）", ex:["Da Vinci painted the Mona Lisa.",
      "Da Vinci sketched flying machines centuries early.",
      "He embodied the Renaissance ideal of the universal man."],
      note:"画家/工程师/科学家；polymath 博学家。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Cleopatra", ipa:"/ˈkliːəpɑːtrə/", pos:"n.", cat:"历史人物",
    senses:[{ def:"克利奥帕特拉（前69–前30，埃及托勒密王朝末代女王）", ex:["Cleopatra ruled Egypt with Rome's favour.",
      "Cleopatra allied with Caesar and Antony.",
      "Her death ended the Ptolemaic dynasty."],
      note:"最后一任法老；与罗马政治纠葛；文化符号。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Sun Yat-sen", ipa:"/ˌsʌn ˈjætˈsen/", pos:"n.", cat:"历史人物",
    senses:[{ def:"孙中山（1866–1925，中国革命家）", ex:["Sun Yat-sen founded the Republic of China in 1912.",
      "He promoted the Three Principles of the People.",
      "Sun is honoured as the ‘Father of the Nation’."],
      note:"辛亥革命；三民主义；推翻帝制。" }],
    syn:[], ant:[], synDiff:"" }
];
