// 词汇复习站 · 扩展词库（第二批）
// 格式同 data.js。index.html 已合并 WORDS + EXTRA + CUSTOM。
const EXTRA = [
  // ---------------- 学术写作（补充） ----------------
  { w:"premise", ipa:"/ˈpremɪs/", pos:"n.", cat:"学术写作",
    senses:[{ def:"前提；假定（论证的起点）",
      ex:["The argument rests on a false premise.",
          "We must question the premise that growth equals progress.",
          "His theory starts from the premise of equal opportunity."],
      note:"常用 on the premise that...；复数 premises 也指‘房屋/经营场所’。" }],
    syn:["assumption","presupposition"], ant:["conclusion"],
    synDiff:"assumption 最日常‘假定’；presupposition 是‘预先假定’；premise 在逻辑/论文中指‘作为推理基础的前提’。" },

  { w:"thesis", ipa:"/ˈθiːsɪs/", pos:"n.", cat:"学术写作",
    senses:[{ def:"论点；论文（学位论文）",
      ex:["The thesis of the book is that cities make us freer.",
          "She is writing her doctoral thesis on climate law.",
          "His thesis challenges the standard view."],
      note:"复数 theses；‘毕业论文’英式 dissertation，美式 thesis 常指硕士/博士论文。" }],
    syn:["argument","dissertation","claim"], ant:[],
    synDiff:"argument 泛指论证；claim 指‘主张’；thesis 是系统性的‘中心论点/学位论文’。" },

  { w:"empirical", ipa:"/ɪmˈpɪrɪkl/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"实证的；基于观察/实验的",
      ex:["We need empirical evidence, not just theory.",
          "The claim lacks empirical support.",
          "Empirical studies show a clear effect."],
      note:"反义 theoretical；名词 empiricism（经验主义）。" }],
    syn:["observational","experimental"], ant:["theoretical","speculative"],
    synDiff:"observational 偏‘观察得来’；experimental 指‘实验控制’；empirical 总称‘来自经验证据’。" },

  { w:"quantitative", ipa:"/ˈkwɒntɪtətɪv/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"定量的（可用数字衡量）",
      ex:["The study uses quantitative data from 10,000 surveys.",
          "Quantitative analysis reveals a steady decline.",
          "They prefer quantitative over qualitative methods."],
      note:"反义 qualitative（定性的）；量化研究 quantitative research。" }],
    syn:["numerical","measurable"], ant:["qualitative"],
    synDiff:"numerical 泛指‘数字的’；measurable 指‘可测的’；quantitative 是方法论上‘定量’研究。" },

  { w:"qualitative", ipa:"/ˈkwɒlɪtətɪv/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"定性的（关于性质、特征）",
      ex:["We collected qualitative feedback through interviews.",
          "Qualitative research explores meanings, not numbers.",
          "The report combines qualitative and quantitative findings."],
      note:"反义 quantitative。" }],
    syn:["descriptive","subjective"], ant:["quantitative"],
    synDiff:"descriptive 指‘描述性’；subjective 指‘主观’；qualitative 专指‘质性/非数值’研究取向。" },

  { w:"synthesize", ipa:"/ˈsɪnθəsaɪz/", pos:"v.", cat:"学术写作",
    senses:[{ def:"综合；归纳（整合多方信息得出结论）",
      ex:["The paper synthesizes findings from 40 studies.",
          "He synthesized the debate into three positions.",
          "Chapter 5 synthesizes the main arguments."],
      note:"名词 synthesis；形容词 synthetic（合成的）。论文常用‘综合既有研究’。" }],
    syn:["integrate","summarize","combine"], ant:["analyze","break down"],
    synDiff:"summarize 偏‘简要重述’；integrate 指‘整合’；synthesize 强调‘把分散材料提炼成新整体’。" },

  { w:"articulate", ipa:"/ɑːˈtɪkjuleɪt/", pos:"v./adj.", cat:"学术写作",
    senses:[{ def:"清晰表达；发音清晰的",
      ex:["She articulated her concerns with precision.",
          "The report articulates a novel framework.",
          "He is an articulate and confident speaker."],
      note:"作形容词读 /ɑːˈtɪkjələt/ 指‘口齿清晰、善于表达’；作动词指‘阐明’。" }],
    syn:["express","voice","eloquent"], ant:["mumble","incoherent"],
    synDiff:"express 通用‘表达’；voice 指‘说出（意见）’；articulate 强调‘条理清晰、措辞到位’。" },

  { w:"salient", ipa:"/ˈseɪliənt/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"显著的；最突出的",
      ex:["The salient feature of the data is its volatility.",
          "Three salient points emerge from the discussion.",
          "He ignored the most salient fact."],
      note:"正式；常修饰 point / feature / difference。" }],
    syn:["prominent","notable","striking"], ant:["minor","trivial"],
    synDiff:"prominent 指‘显眼/重要’；notable 指‘值得注意’；salient 正式、强调‘最关健、跃然而出’。" },

  { w:"tentative", ipa:"/ˈtentətɪv/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"初步的；试探性的",
      ex:["These are tentative conclusions pending more data.",
          "We offer a tentative explanation.",
          "He made a tentative suggestion."],
      note:"名词 tentativeness；常修饰 finding / conclusion / plan。" }],
    syn:["provisional","preliminary","hesitant"], ant:["definitive","firm"],
    synDiff:"provisional 指‘临时替代’；preliminary 指‘前期’；tentative 强调‘尚不肯定、留有余地’。" },

  { w:"underlie", ipa:"/ˌʌndəˈlaɪ/", pos:"v.", cat:"学术写作",
    senses:[{ def:"构成…的基础；是…的深层原因",
      ex:["A shared belief underlies both policies.",
          "The principle that underlies the law is fairness.",
          "Several factors underlie the recent unrest."],
      note:"过去式 underlay，过去分词 underlain；形容词 underlying（潜在的）。" }],
    syn:["ground","base","explain"], ant:[],
    synDiff:"base 通用‘基于’；ground 指‘使有根据’；underlie 强调‘在底层支撑/成因’。" },

  { w:"albeit", ipa:"/ɔːlˈbiːɪt/", pos:"conj.", cat:"学术写作",
    senses:[{ def:"尽管；虽然（语气正式）",
      ex:["The plan succeeded, albeit slowly.",
          "Useful, albeit limited, evidence was found.",
          "He agreed, albeit reluctantly."],
      note:"= although，但更书面，常连接一个让步小句。" }],
    syn:["though","although"], ant:[],
    synDiff:"though/although 更口语；albeit 正式、紧凑，常置于形容词或短语前。" },

  // ---------------- 英语文学（补充） ----------------
  { w:"allegory", ipa:"/ˈæləɡəri/", pos:"n.", cat:"英语文学",
    senses:[{ def:"寓言；讽喻（整体象征叙事）",
      ex:["'Animal Farm' is an allegory of the Russian Revolution.",
          "The poem works as a political allegory.",
          "Mediaeval allegories taught moral lessons."],
      note:"形容词 allegorical；与 metaphor 区别：allegory 是整篇的系统性象征。" }],
    syn:["parable","fable","symbolism"], ant:[],
    synDiff:"fable 短小的道德故事（常动物主角）；parable 圣经式比喻；allegory 是长篇、多层象征叙事。" },

  { w:"symbolism", ipa:"/ˈsɪmbəlɪzəm/", pos:"n.", cat:"英语文学",
    senses:[{ def:"象征主义；象征手法",
      ex:["The green light is a symbolism of Gatsby's hope.",
          "The novel is rich in religious symbolism.",
          "Symbolism conveys meaning beyond the literal."],
      note:"也指 19 世纪‘象征主义’文艺流派；形容词 symbolic。" }],
    syn:["metaphor","allegory"], ant:[],
    synDiff:"metaphor 是单个修辞；allegory 是整篇象征；symbolism 是‘用象征表意’的手法或流派。" },

  { w:"imagery", ipa:"/ˈɪmɪdʒəri/", pos:"n.", cat:"英语文学",
    senses:[{ def:"意象（唤起感官的画面语言）",
      ex:["The poem's sea imagery evokes calm.",
          "Visual imagery dominates the opening scene.",
          "He uses olfactory imagery to recall childhood."],
      note:"分 visual / auditory / tactile 等；不是‘图片’。" }],
    syn:["figures","descriptive language"], ant:[],
    synDiff:"description 通用‘描写’；imagery 特指‘唤起感官形象的修辞语言’。" },

  { w:"motif", ipa:"/məʊˈtiːf/", pos:"n.", cat:"英语文学",
    senses:[{ def:"母题；反复出现的主题元素",
      ex:["The journey is a recurring motif in the book.",
          "Water is a motif symbolizing renewal.",
          "The composer reuses a musical motif."],
      note:"也用于艺术/音乐；区别于 theme（更抽象的中心思想）。" }],
    syn:["theme","leitmotif"], ant:[],
    synDiff:"theme 是中心思想；motif 是‘反复出现的具体意象/元素’，可视为 theme 的载体。" },

  { w:"protagonist", ipa:"/prəˈtæɡənɪst/", pos:"n.", cat:"英语文学",
    senses:[{ def:"主角；主要人物",
      ex:["The protagonist struggles against fate.",
          "A flawed protagonist engages readers more.",
          "The protagonist learns humility by the end."],
      note:"反义 antagonist（对手）；复数 protagonists。" }],
    syn:["hero","main character"], ant:["antagonist"],
    synDiff:"hero 带‘正面’色彩；main character 中性；protagonist 是叙事学‘推动情节的主角’，可非正面。" },

  { w:"climax", ipa:"/ˈklaɪmæks/", pos:"n.", cat:"英语文学",
    senses:[{ def:"高潮（情节最紧张处）",
      ex:["The climax occurs when the two rivals meet.",
          "The film's climax is quietly moving.",
          "The argument builds to a climax."],
      note:"结构：exposition → rising action → climax → falling action → resolution。" }],
    syn:["peak","turning point"], ant:["anticlimax"],
    synDiff:"peak 泛指‘顶点’；turning point 指‘转折’；climax 专指叙事‘张力顶点’。" },

  { w:"denouement", ipa:"/deɪˈnuːmɒ̃/", pos:"n.", cat:"英语文学",
    senses:[{ def:"结局；收场（谜团解开）",
      ex:["The denouement reveals the murderer.",
          "The novel's denouement feels rushed.",
          "In the denouement, loose ends are tied."],
      note:"源自法语；也拼 dénouement；指‘解结’。" }],
    syn:["resolution","ending"], ant:[],
    synDiff:"ending 通用‘结尾’；resolution 指‘矛盾解决’；denouement 强调‘此前悬疑的最终揭晓’。" },

  { w:"catharsis", ipa:"/kəˈθɑːsɪs/", pos:"n.", cat:"英语文学",
    senses:[{ def:"宣泄；净化（观众情绪释放）",
      ex:["Tragedy offers catharsis through pity and fear.",
          "The finale provides emotional catharsis.",
          "Writing became her catharsis."],
      note:"亚里士多德《诗学》；形容词 cathartic。" }],
    syn:["release","purification"], ant:[],
    synDiff:"release 通用‘释放’；purification 指‘净化’；catharsis 是美学/心理专用‘情感宣泄’。" },

  { w:"soliloquy", ipa:"/səˈlɪləkwi/", pos:"n.", cat:"英语文学",
    senses:[{ def:"独白（角色自言自语，观众听见）",
      ex:["Hamlet's soliloquy 'To be or not to be' is famous.",
          "The soliloquy reveals her true motive.",
          "He delivers a long soliloquy in Act III."],
      note:"区别于 aside（旁白，对其他角色隐蔽）；复数 soliloquies。" }],
    syn:["monologue","aside"], ant:[],
    synDiff:"monologue 泛指‘个人长篇讲话’；aside 是‘面向观众、他人听不到’的旁白；soliloquy 是‘独自思考出声’。" },

  { w:"realism", ipa:"/ˈrɪəlɪzəm/", pos:"n.", cat:"英语文学",
    senses:[{ def:"现实主义（如实描写现实）",
      ex:["Nineteenth-century realism depicted ordinary life.",
          "The novel is a study in social realism.",
          "Magical realism blends the real with the fantastic."],
      note:"反义 romanticism；相关 naturalism（自然主义更决定论）。" }],
    syn:["naturalism","verisimilitude"], ant:["romanticism","fantasy"],
    synDiff:"naturalism 更强调‘环境/遗传决定论’；verisimilitude 指‘逼真感’；realism 是‘如实再现现实’的流派/态度。" },

  { w:"modernism", ipa:"/ˈmɒdənɪzəm/", pos:"n.", cat:"英语文学",
    senses:[{ def:"现代主义（20 世纪初反传统的实验潮流）",
      ex:["Modernism broke with Victorian conventions.",
          "Stream of consciousness is a modernist technique.",
          "Eliot and Woolf are modernist writers."],
      note:"反义/后继 postmodernism（后现代主义）。" }],
    syn:["avant-garde","experimentalism"], ant:["traditionalism"],
    synDiff:"avant-garde 泛指‘先锋’；experimentalism 指‘实验性’；modernism 是特定历史流派。" },

  // ---------------- 法律与政治（补充） ----------------
  { w:"statute", ipa:"/ˈstætʃuːt/", pos:"n.", cat:"法律政治",
    senses:[{ def:"成文法；制定法",
      ex:["The statute prohibits discrimination at work.",
          "Under the statute, the act is a crime.",
          "Congress passed a new statute."],
      note:"区别于 common law（判例法）；形容词 statutory。" }],
    syn:["law","act","legislation"], ant:[],
    synDiff:"law 泛指法律；act 指‘法案/单行法’；statute 是‘经立法程序制定的成文法条’。" },

  { w:"plaintiff", ipa:"/ˈpleɪntɪf/", pos:"n.", cat:"法律政治",
    senses:[{ def:"原告（民事诉讼起诉方）",
      ex:["The plaintiff filed suit for breach of contract.",
          "The plaintiff must prove the claim.",
          "The court ruled for the plaintiff."],
      note:"刑事称 prosecutor（公诉人）；被告 defendant。" }],
    syn:["claimant","complainant"], ant:["defendant"],
    synDiff:"claimant 泛指‘索赔人’；complainant 指‘投诉人’；plaintiff 是民事诉讼‘原告’专称。" },

  { w:"jurisdiction", ipa:"/ˌdʒʊərɪsˈdɪkʃn/", pos:"n.", cat:"法律政治",
    senses:[{ def:"管辖权；司法辖区",
      ex:["The court lacks jurisdiction over the case.",
          "The crime falls within federal jurisdiction.",
          "They disputed which country had jurisdiction."],
      note:"形容词 jurisdictional。" }],
    syn:["authority","competence"], ant:[],
    synDiff:"authority 通用‘权力’；competence 指‘职权能力’；jurisdiction 法律专指‘管辖权限/区域’。" },

  { w:"sanction", ipa:"/ˈsæŋkʃn/", pos:"n./v.", cat:"法律政治",
    senses:[{ def:"制裁；批准（一词两义，看语境）",
      ex:["The UN imposed economic sanctions on the regime.",
          "The treaty received legislative sanction.",
          "Sanctions aim to change behavior without war."],
      note:"作‘制裁’多为复数；作‘批准’为单数。易混淆，务必看语境！" }],
    syn:["penalty","embargo","approval"], ant:["approval","reward"],
    synDiff:"embargo 专指‘禁运’；penalty 指‘处罚’；sanction 作动词/名词可同时表‘批准’与‘制裁’，需据语境判别。" },

  { w:"referendum", ipa:"/ˌrefəˈrendəm/", pos:"n.", cat:"法律政治",
    senses:[{ def:"全民公投",
      ex:["A referendum decided the constitutional change.",
          "The government called a referendum on membership.",
          "The referendum passed by a narrow margin."],
      note:"复数 referendums 或 referenda。" }],
    syn:["plebiscite","vote"], ant:[],
    synDiff:"plebiscite 也指‘公投’（常带权威性）；vote 泛指‘投票’；referendum 是就具体议题的全民表决。" },

  { w:"federal", ipa:"/ˈfedərəl/", pos:"adj.", cat:"法律政治",
    senses:[{ def:"联邦的（中央与地方分权）",
      ex:["The federal government shares power with states.",
          "Federal law overrides conflicting state law.",
          "Germany is a federal republic."],
      note:"名词 federation（联邦）；反义 unitary（单一制）。" }],
    syn:["national","unitary(反)"], ant:["unitary","centralized"],
    synDiff:"national 指‘全国的’；unitary 指‘单一集权’；federal 特指‘中央与地方分权的联邦制’。" },

  { w:"unilateral", ipa:"/ˌjuːnɪˈlætrəl/", pos:"adj.", cat:"法律政治",
    senses:[{ def:"单边的；单方面的",
      ex:["They took unilateral action without allies.",
          "A unilateral ceasefire was declared.",
          "Unilateral tariffs breach trade norms."],
      note:"反义 multilateral（多边的）/ bilateral（双边的）。" }],
    syn:["one-sided","sole"], ant:["multilateral","bilateral"],
    synDiff:"one-sided 通用‘一面倒’；bilateral 指‘双方’；unilateral 专指‘一方单独行动’。" },

  { w:"annex", ipa:"/əˈneks/", pos:"v./n.", cat:"法律政治",
    senses:[{ def:"吞并； annex（附件）",
      ex:["The state annexed the neighbouring territory.",
          "The report annexed a detailed table.",
          "Annexation of the region was condemned."],
      note:"作动词‘吞并’；作名词‘附录/附件’。名词 annexation。" }],
    syn:["seize","append","attachment"], ant:["cede"],
    synDiff:"seize 指‘武力夺取’；append 指‘附上’；annex 在政治指‘正式吞并’，在文件指‘附件’。" },

  { w:"embargo", ipa:"/ɪmˈbɑːɡəʊ/", pos:"n.", cat:"法律政治",
    senses:[{ def:"禁运；贸易禁令",
      ex:["An oil embargo hurt the economy.",
          "The embargo was lifted last year.",
          "They imposed an arms embargo."],
      note:"动词 impose / lift an embargo；复数 embargoes。" }],
    syn:["ban","sanction","blockade"], ant:["free trade"],
    synDiff:"ban 通用‘禁止’；blockade 指‘封锁’；embargo 专指‘贸易/物资禁运’。" },

  { w:"apartheid", ipa:"/əˈpɑːtaɪt/", pos:"n.", cat:"法律政治",
    senses:[{ def:"种族隔离（南非旧制）",
      ex:["Apartheid divided the population by race.",
          "The regime ended apartheid in 1994.",
          "They compared the policy to apartheid."],
      note:"源自南非荷兰语‘分离’；现泛指制度化种族隔离。" }],
    syn:["segregation","discrimination"], ant:["integration"],
    synDiff:"segregation 泛指‘隔离’；discrimination 指‘歧视’；apartheid 特指‘制度化、法律化的种族隔离’。" },

  // ---------------- 医疗与健康（补充） ----------------
  { w:"symptom", ipa:"/ˈsɪmptəm/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"症状（疾病表现）",
      ex:["Fever is a symptom of infection.",
          "He showed no symptoms at first.",
          "Cough is a common symptom."],
      note:"区别于 sign（体征，医生可测）；复数 symptoms。" }],
    syn:["indication","manifestation"], ant:[],
    synDiff:"sign 是客观‘体征’（如血压高）；symptom 是患者主观‘症状’（如疼痛）。" },

  { w:"syndrome", ipa:"/ˈsɪndrəʊm/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"综合征（一组并发症状）",
      ex:["Down syndrome is a genetic condition.",
          "She was diagnosed with chronic fatigue syndrome.",
          "Metabolic syndrome raises heart risk."],
      note:"指‘症候群’，不等于单一疾病。" }],
    syn:["condition","disorder"], ant:[],
    synDiff:"disorder 指‘紊乱/障碍’；condition 泛指‘病症’；syndrome 是‘多个症状成组出现’。" },

  { w:"benign", ipa:"/bɪˈnaɪn/", pos:"adj.", cat:"医疗健康",
    senses:[{ def:"良性的（非癌、不恶化）",
      ex:["The tumour was found to be benign.",
          "A benign growth needs no surgery.",
          "The condition is benign and self-limiting."],
      note:"反义 malignant（恶性）；也指‘温和的’（a benign climate）。" }],
    syn:["harmless","non-cancerous"], ant:["malignant","deadly"],
    synDiff:"harmless 通用‘无害’；non-cancerous 指‘非癌’；benign 医学专指‘良性（不扩散）’。" },

  { w:"malignant", ipa:"/məˈlɪɡnənt/", pos:"adj.", cat:"医疗健康",
    senses:[{ def:"恶性的（癌性、会扩散）",
      ex:["The biopsy showed a malignant tumour.",
          "Malignant cells spread to nearby tissue.",
          "Early detection of malignant growth saves lives."],
      note:"反义 benign；名词 malignancy。" }],
    syn:["cancerous","virulent"], ant:["benign","harmless"],
    synDiff:"cancerous 指‘癌’；virulent 指‘剧毒/烈性’；malignant 医学指‘恶性、具侵袭性’。" },

  { w:"immunity", ipa:"/ɪˈmjuːnəti/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"免疫力；豁免",
      ex:["Vaccination builds immunity to the virus.",
          "Her natural immunity protected her.",
          "Diplomats enjoy diplomatic immunity."],
      note:"形容词 immune；相关 antibody 抗体、antigen 抗原。" }],
    syn:["resistance","exemption"], ant:["susceptibility"],
    synDiff:"resistance 指‘抵抗（力）’；exemption 指‘豁免’；immunity 专指‘免疫能力’或‘法律豁免’。" },

  { w:"antibiotic", ipa:"/ˌæntibaɪˈɒtɪk/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"抗生素",
      ex:["The doctor prescribed an antibiotic for the infection.",
          "Overuse of antibiotics breeds resistance.",
          "This antibiotic targets bacteria, not viruses."],
      note:"对病毒无效；滥用致 antibiotic resistance（耐药）。" }],
    syn:["antimicrobial"], ant:[],
    synDiff:"antimicrobial 更广‘抗菌/微生物’；antibiotic 特指‘抗细菌的抗生素’。" },

  { w:"relapse", ipa:"/rɪˈlæps/", pos:"n./v.", cat:"医疗健康",
    senses:[{ def:"复发；旧病复发",
      ex:["The patient relapsed after stopping treatment.",
          "A relapse is common with this illness.",
          "She feared a relapse into depression."],
      note:"也可喻‘恶习重犯’（relapse into smoking）。" }],
    syn:["recurrence","setback"], ant:["recovery"],
    synDiff:"recurrence 通用‘再发生’；setback 指‘挫折’；relapse 专指‘病愈后复发/恶习重犯’。" },

  { w:"palliative", ipa:"/ˈpæliətɪv/", pos:"adj./n.", cat:"医疗健康",
    senses:[{ def:"姑息的；缓解（不治之症的对症处理）",
      ex:["The care is palliative, not curative.",
          "Palliative treatment eases the pain.",
          "They chose palliative care at home."],
      note:"palliative care = 姑息治疗（减轻痛苦，非治愈）。" }],
    syn:["relieving","soothing"], ant:["curative"],
    synDiff:"relieving 通用‘缓解’；curative 指‘治愈’；palliative 专指‘减轻症状而非根治’。" },

  { w:"triage", ipa:"/ˈtriːɑːʒ/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"分诊；优先排序（按紧急程度）",
      ex:["Nurses triage patients in the ER.",
          "Triage decides who is treated first.",
          "Disaster triage saves the most lives."],
      note:"源自法语‘分拣’；也用于资源/任务优先级。" }],
    syn:["prioritization","screening"], ant:[],
    synDiff:"screening 指‘筛查’；prioritization 指‘排优先级’；triage 专指‘按危重程度分配救治’。" },

  // ---------------- 美食与食品（补充） ----------------
  { w:"mango", ipa:"/ˈmæŋɡəʊ/", pos:"n.", cat:"美食食品",
    senses:[{ def:"芒果",
      ex:["She peeled a ripe mango.",
          "Mango adds sweetness to the salsa.",
          "The mango is the national fruit of India."],
      note:"复数 mangoes / mangos。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"blueberry", ipa:"/ˈbluːbəri/", pos:"n.", cat:"美食食品",
    senses:[{ def:"蓝莓",
      ex:["I put blueberries in my cereal.",
          "Blueberries are high in antioxidants.",
          "She baked blueberry muffins."],
      note:"复数 blueberries；相关 cranberry 蔓越莓。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"broccoli", ipa:"/ˈbrɒkəli/", pos:"n.", cat:"美食食品",
    senses:[{ def:"西兰花",
      ex:["Steam the broccoli for five minutes.",
          "Broccoli is rich in vitamin C.",
          "The kids refused to eat broccoli."],
      note:"不可数；十字花科。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"spinach", ipa:"/ˈspɪnɪtʃ/", pos:"n.", cat:"美食食品",
    senses:[{ def:"菠菜",
      ex:["Add spinach to the omelette.",
          "Spinach wilts quickly in the pan.",
          "Fresh spinach is best in spring."],
      note:"不可数。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"basil", ipa:"/ˈbæzl/", pos:"n.", cat:"美食食品",
    senses:[{ def:"罗勒（香草）",
      ex:["Tear basil over the tomato salad.",
          "Pesto is made from basil and pine nuts.",
          "Thai basil differs from Italian basil."],
      note:"不可数；常用于意/泰菜。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"saffron", ipa:"/ˈsæfrən/", pos:"n.", cat:"美食食品",
    senses:[{ def:"藏红花（珍贵香料）",
      ex:["A pinch of saffron colors the rice.",
          "Saffron gives paella its golden hue.",
          "Real saffron is the world's costliest spice."],
      note:"不可数；取自古花柱头。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"tofu", ipa:"/ˈtəʊfuː/", pos:"n.", cat:"美食食品",
    senses:[{ def:"豆腐",
      ex:["She stir-fried tofu with greens.",
          "Silken tofu goes in the soup.",
          "Tofu is a key source of plant protein."],
      note:"不可数；源自日语。" }],
    syn:["bean curd"], ant:[],
    synDiff:"bean curd 是直译‘豆凝乳’；tofu 是通用名。" },

  { w:"risotto", ipa:"/rɪˈzɒtəʊ/", pos:"n.", cat:"美食食品",
    senses:[{ def:"意式炖饭",
      ex:["We ordered mushroom risotto.",
          "Risotto is stirred until creamy.",
          "He made a saffron risotto."],
      note:"意式，用 Arborio 米慢炖。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"croissant", ipa:"/ˈkwæsɒ̃/", pos:"n.", cat:"美食食品",
    senses:[{ def:"羊角面包；可颂",
      ex:["She ate a buttery croissant for breakfast.",
          "The croissant was still warm.",
          "A chocolate croissant pairs with coffee."],
      note:"源自法语。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"sorbet", ipa:"/ˈsɔːbeɪ/", pos:"n.", cat:"美食食品",
    senses:[{ def:"雪芭（冰品，无奶）",
      ex:["Lemon sorbet cleansed the palate.",
          "Mango sorbet is dairy-free.",
          "We served sorbet between courses."],
      note:"区别于 ice cream（含奶）；gelato（意式冰淇淋）。" }],
    syn:["water ice"], ant:[],
    synDiff:"ice cream 含乳脂；gelato 意式更密；sorbet 是水果冰、无奶。" },

  { w:"hummus", ipa:"/ˈhʊməs/", pos:"n.", cat:"美食食品",
    senses:[{ def:"鹰嘴豆泥",
      ex:["Dip the pita in hummus.",
          "Hummus is made from chickpeas and tahini.",
          "We bought red-pepper hummus."],
      note:"不可数；中东食品。" }],
    syn:[], ant:[],
    synDiff:"" },

  // ---------------- 外貌与性格（高阶补充） ----------------
  { w:"gregarious", ipa:"/ɡrɪˈɡeəriəs/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"合群的；爱社交的",
      ex:["He is gregarious and loves parties.",
          "Gregarious animals live in herds.",
          "Her gregarious nature eased the meeting."],
      note:"反义 solitary / reclusive；名词 gregariousness。" }],
    syn:["sociable","outgoing","extroverted"], ant:["solitary","reclusive"],
    synDiff:"sociable 通用‘好社交’；outgoing 指‘外向’；gregarious 强调‘天然喜欢群处’（也可形容动物）。" },

  { w:"phlegmatic", ipa:"/fleɡˈmætɪk/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"冷静淡漠的；不易激动的",
      ex:["His phlegmatic manner calmed the room.",
          "A phlegmatic captain stays calm in storms.",
          "She is phlegmatic even under pressure."],
      note:"源自‘黏液质’（体液说）；反义 choleric（易怒）。" }],
    syn:["calm","impassive","composed"], ant:["excitable","choleric"],
    synDiff:"calm 通用‘平静’；impassive 指‘无表情’；phlegmatic 强调‘天性不易动情、淡然’。" },

  { w:"diffident", ipa:"/ˈdɪfɪdənt/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"羞怯缺乏自信的",
      ex:["He was too diffident to speak up.",
          "A diffident smile crossed her face.",
          "Don't be diffident; your idea is good."],
      note:"名词 diffidence；反义 confident。" }],
    syn:["shy","timid","self-effacing"], ant:["confident","assertive"],
    synDiff:"shy 通用‘害羞’；timid 指‘胆怯’；diffident 强调‘对自己能力缺乏信心而不敢表达’。" },

  { w:"laconic", ipa:"/ləˈkɒnɪk/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"言简意赅的；惜字如金的",
      ex:["His laconic reply ended the debate.",
          "She gave a laconic 'No.'",
          "The general was famously laconic."],
      note:"反义 garrulous / verbose；名词 laconicism。" }],
    syn:["terse","concise","brief"], ant:["garrulous","verbose"],
    synDiff:"concise 褒义‘简洁’；terse 可能带‘生硬’；laconic 强调‘少言但往往有力’。" },

  { w:"quixotic", ipa:"/kwɪkˈsɒtɪk/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"堂吉诃德式不切实际的；理想主义的",
      ex:["His quixotic plan to end all war amused them.",
          "She launched a quixotic campaign.",
          "The quest was noble but quixotic."],
      note:"源自《堂吉诃德》；常带‘虽不切实际但可爱’的意味。" }],
    syn:["idealistic","impractical","romantic"], ant:["pragmatic","realistic"],
    synDiff:"impractical 中性‘不实用’；idealistic 指‘理想化’；quixotic 强调‘为崇高但虚幻的目标而战’。" },

  { w:"whimsical", ipa:"/ˈwɪmzɪkl/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"异想天开的；随兴的",
      ex:["The garden had a whimsical design.",
          "His whimsical humor delighted children.",
          "She made a whimsical choice of career."],
      note:"名词 whim（突发奇想）；反义 serious / predictable。" }],
    syn:["fanciful","playful","capricious"], ant:["solemn","predictable"],
    synDiff:"fanciful 指‘爱幻想’；capricious 指‘任性多变’；whimsical 强调‘轻松、俏皮、随兴的奇想’。" },

  { w:"sagacious", ipa:"/səˈɡeɪʃəs/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"睿智的；明察的",
      ex:["A sagacious elder advised the king.",
          "Her sagacious investment paid off.",
          "He made a sagacious choice."],
      note:"名词 sagacity；比 wise 更正式、带‘洞察力’。" }],
    syn:["wise","astute","prudent"], ant:["foolish","frivolous"],
    synDiff:"wise 通用‘智慧’；astute 指‘精明敏锐’；sagacious 正式、强调‘深邃的判断力’。" },

  { w:"erudite", ipa:"/ˈerudaɪt/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"博学的；有学问的",
      ex:["The erudite professor cited rare texts.",
          "His erudite lecture impressed all.",
          "She is erudite yet humble."],
      note:"名词 erudition；区别于 learned（也指博学，更平实）。" }],
    syn:["learned","scholarly","knowledgeable"], ant:["ignorant","unlettered"],
    synDiff:"learned 通用‘有学识’；scholarly 指‘学术的’；erudite 强调‘广博而深、博闻’。" },

  { w:"peevish", ipa:"/ˈpiːvɪʃ/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"爱抱怨的；脾气坏的",
      ex:["The peevish child whined all day.",
          "His peevish tone annoyed colleagues.",
          "Don't be so peevish about small things."],
      note:"名词 peevishness；近 petulant。" }],
    syn:["irritable","petulant","querulous"], ant:["cheerful","good-natured"],
    synDiff:"irritable 指‘易恼’；petulant 指‘任性地闹情绪’；peevish 强调‘为小事抱怨、性情乖戾’。" },

  { w:"churlish", ipa:"/ˈtʃɜːlɪʃ/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"粗鲁无礼的；脾气坏的",
      ex:["He gave a churlish refusal.",
          "It would be churlish to decline the gift.",
          "Her churlish remark silenced the room."],
      note:"较正式、贬义；名词 churlishness。" }],
    syn:["rude","boorish","surly"], ant:["courteous","gracious"],
    synDiff:"rude 通用‘粗鲁’；boorish 指‘粗野没教养’；churlish 强调‘无礼且脾气糟’。" },

  { w:"statuesque", ipa:"/stæˈtjuːesk/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"雕像般端庄高挑的（多形容女性）",
      ex:["The statuesque model walked the runway.",
          "She had a statuesque grace.",
          "A statuesque figure stood at the door."],
      note:"褒义，强调‘端庄、如雕塑般美’。" }],
    syn:["dignified","stately","majestic"], ant:["ungainly"],
    synDiff:"stately 指‘庄重’；majestic 指‘宏伟’；statuesque 特指‘身姿如雕像般优美挺拔’。" },

  { w:"svelte", ipa:"/svelte/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"优雅苗条的",
      ex:["She looked svelte in the gown.",
          "He kept svelte with daily yoga.",
          "The dancer was slim and svelte."],
      note:"源自法语，偏褒义、带‘优雅’。" }],
    syn:["slender","lithe","graceful"], ant:["stout","ponderous"],
    synDiff:"slender 通用‘纤细’；lithe 指‘柔软灵活’；svelte 强调‘苗条而优雅’。" },

  // ---------------- 地理与环境（补充） ----------------
  { w:"ecosystem", ipa:"/ˈiːkəʊsɪstəm/", pos:"n.", cat:"地理环境",
    senses:[{ def:"生态系统",
      ex:["Coral reefs are fragile ecosystems.",
          "Human activity disrupts the ecosystem.",
          "The pond supports a rich ecosystem."],
      note:"形容词 ecological（生态的）。" }],
    syn:["habitat","environment"], ant:[],
    synDiff:"habitat 指‘物种栖息地’；environment 泛指‘环境’；ecosystem 强调整体‘生物+环境’的互动系统。" },

  { w:"deforestation", ipa:"/diːˌfɒrɪˈsteɪʃn/", pos:"n.", cat:"地理环境",
    senses:[{ def:"森林砍伐",
      ex:["Deforestation accelerates climate change.",
          "The region suffers severe deforestation.",
          "Reforestation can reverse deforestation."],
      note:"动词 deforest；反义 reforestation（造林）。" }],
    syn:["clear-cutting","logging"], ant:["reforestation"],
    synDiff:"logging 指‘伐木（产业）’；clear-cutting 指‘皆伐’；deforestation 是‘森林消失’这一现象。" },

  { w:"emission", ipa:"/iˈmɪʃn/", pos:"n.", cat:"地理环境",
    senses:[{ def:"排放（物）",
      ex:["Carbon emissions must fall by 2030.",
          "The factory cut its emissions by half.",
          "Zero-emission vehicles are spreading."],
      note:"常用 carbon / greenhouse gas emissions。" }],
    syn:["discharge","release"], ant:["absorption"],
    synDiff:"discharge 泛指‘排出（液/气）’；release 指‘释放’；emission 环境专指‘温室气体等排放’。" },

  { w:"conservation", ipa:"/ˌkɒnsəˈveɪʃn/", pos:"n.", cat:"地理环境",
    senses:[{ def:"保护；保育（自然资源）",
      ex:["Wildlife conservation needs funding.",
          "Water conservation saves the city.",
          "She works in heritage conservation."],
      note:"动词 conserve；形容词 conservative（保守的，注意歧义）。" }],
    syn:["preservation","protection"], ant:["depletion","exploitation"],
    synDiff:"preservation 指‘原样保存’；protection 指‘保护’；conservation 强调‘可持续利用式保育’。" },

  { w:"peninsula", ipa:"/pəˈnɪnsjələ/", pos:"n.", cat:"地理环境",
    senses:[{ def:"半岛",
      ex:["Italy is a peninsula.",
          "They hiked the peninsula's coast.",
          "The peninsula juts into the sea."],
      note:"形容词 peninsular。" }],
    syn:["headland"], ant:[],
    synDiff:"headland 指‘海岬（小）’；peninsula 指‘三面环水的半岛’。" },

  { w:"archipelago", ipa:"/ˌɑːkɪˈpeləɡəʊ/", pos:"n.", cat:"地理环境",
    senses:[{ def:"群岛",
      ex:["Indonesia is a vast archipelago.",
          "The archipelago has over a thousand islands.",
          "They sailed among the archipelago."],
      note:"复数 archipelagos。" }],
    syn:["islands"], ant:[],
    synDiff:"islands 泛指‘岛屿’；archipelago 是‘成群的群岛’。" },

  { w:"monsoon", ipa:"/mɒnˈsuːn/", pos:"n.", cat:"地理环境",
    senses:[{ def:"季风；雨季",
      ex:["The monsoon brings heavy rain.",
          "Rice depends on the summer monsoon.",
          "The monsoon failed this year."],
      note:"也指‘季风季节’；形容词 monsoon。" }],
    syn:["seasonal rains"], ant:[],
    synDiff:"seasonal rains 是描述；monsoon 是气象专名‘季风/雨季’。" },

  { w:"tundra", ipa:"/ˈtʌndrə/", pos:"n.", cat:"地理环境",
    senses:[{ def:"苔原（寒带无树平原）",
      ex:["Reindeer graze the tundra.",
          "The tundra freezes in winter.",
          "Permafrost underlies the tundra."],
      note:"生态带；与 savanna 热带草原、taiga 针叶林并列。" }],
    syn:["polar plain"], ant:[],
    synDiff:"polar plain 是描述；tundra 是生态专名‘苔原’。" },

  { w:"drought", ipa:"/draʊt/", pos:"n.", cat:"地理环境",
    senses:[{ def:"干旱；旱灾",
      ex:["The drought ruined the harvest.",
          "Prolonged drought emptied the reservoir.",
          "Drought forced farmers to leave."],
      note:"形容词 drought-stricken。" }],
    syn:["dry spell","aridity"], ant:["flood","deluge"],
    synDiff:"dry spell 指‘一段干期’；aridity 指‘干旱状态’；drought 是‘造成灾害的旱’。" },

  { w:"estuary", ipa:"/ˈestʃuəri/", pos:"n.", cat:"地理环境",
    senses:[{ def:"河口（咸淡水交汇）",
      ex:["The river forms a wide estuary.",
          "Estuaries teem with young fish.",
          "The estuary is a protected wetland."],
      note:"形容词 estuarine。" }],
    syn:["river mouth"], ant:[],
    synDiff:"river mouth 是‘入海口’通俗说法；estuary 是‘受潮汐影响的河口湾’专名。" },

  // ---------------- 动植物（补充） ----------------
  { w:"photosynthesis", ipa:"/ˌfəʊtəʊˈsɪnθəsɪs/", pos:"n.", cat:"动植物",
    senses:[{ def:"光合作用",
      ex:["Photosynthesis turns sunlight into sugar.",
          "Plants perform photosynthesis in leaves.",
          "Without photosynthesis, life would starve."],
      note:"动词 photosynthesize；形容词 photosynthetic。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"carnivore", ipa:"/ˈkɑːnɪvɔː(r)/", pos:"n.", cat:"动植物",
    senses:[{ def:"肉食动物",
      ex:["The lion is a carnivore.",
          "Carnivores sit atop the food chain.",
          "A strict carnivore eats only meat."],
      note:"形容词 carnivorous；反义 herbivore（草食）、omnivore（杂食）。" }],
    syn:["predator"], ant:["herbivore"],
    synDiff:"predator 指‘捕食者’；carnivore 是‘食性为肉’的分类词。" },

  { w:"herbivore", ipa:"/ˈhɜːbɪvɔː(r)/", pos:"n.", cat:"动植物",
    senses:[{ def:"草食动物",
      ex:["The deer is a herbivore.",
          "Herbivores graze on grasses.",
          "Rabbits are small herbivores."],
      note:"形容词 herbivorous；反义 carnivore。" }],
    syn:["plant-eater"], ant:["carnivore"],
    synDiff:"plant-eater 是描述；herbivore 是‘食草动物’分类词。" },

  { w:"endangered", ipa:"/ɪnˈdeɪndʒəd/", pos:"adj.", cat:"动植物",
    senses:[{ def:"濒危的",
      ex:["The tiger is an endangered species.",
          "Endangered habitats need protection.",
          "Poaching makes rhinos endangered."],
      note:"程度：vulnerable < endangered < critically endangered；反义 thriving。" }],
    syn:["threatened","at risk"], ant:["thriving","abundant"],
    synDiff:"threatened 泛指‘受威胁’；at risk 通用‘有风险’；endangered 是 IUCN‘濒危’正式等级。" },

  { w:"extinct", ipa:"/ɪkˈstɪŋkt/", pos:"adj.", cat:"动植物",
    senses:[{ def:"灭绝的",
      ex:["The dodo is extinct.",
          "Many species went extinct recently.",
          "An extinct volcano no longer erupts."],
      note:"名词 extinction（灭绝）；也形容‘熄灭的/死火山’。" }],
    syn:["gone","vanished"], ant:["extant","alive"],
    synDiff:"gone 通用‘没了’；vanished 指‘消失’；extinct 生物专指‘物种灭绝’。" },

  { w:"canopy", ipa:"/ˈkænəpi/", pos:"n.", cat:"动植物",
    senses:[{ def:"树冠层；顶盖",
      ex:["Birds nest in the forest canopy.",
          "Sunlight filters through the canopy.",
          "The canopy shields the ground below."],
      note:"也指‘华盖/罩’；形容词 canopied。" }],
    syn:["cover","ceiling"], ant:[],
    synDiff:"cover 通用‘覆盖’；ceiling 指‘天花板’；canopy 专指‘树冠层/顶篷’。" },

  { w:"fauna", ipa:"/ˈfɔːnə/", pos:"n.", cat:"动植物",
    senses:[{ def:"动物群（某区）",
      ex:["The island's fauna includes rare birds.",
          "Australian fauna is unique.",
          "The park protects its flora and fauna."],
      note:"与 flora（植物群）对应；常 flora and fauna 连用。" }],
    syn:["animal life"], ant:[],
    synDiff:"animal life 是描述；fauna 是‘某地区动物群’专名，与 flora 对举。" },

  { w:"flora", ipa:"/ˈflɔːrə/", pos:"n.", cat:"动植物",
    senses:[{ def:"植物群（某区）",
      ex:["The region's flora is diverse.",
          "Alpine flora survives the cold.",
          "The guide lists local flora and fauna."],
      note:"与 fauna（动物群）对应。" }],
    syn:["plant life"], ant:[],
    synDiff:"plant life 是描述；flora 是‘某地区植物群’专名。" },

  { w:"migration", ipa:"/maɪˈɡreɪʃn/", pos:"n.", cat:"动植物",
    senses:[{ def:"迁徙；迁移",
      ex:["Bird migration follows the seasons.",
          "Wildebeest migration crosses the plains.",
          "Human migration reshapes cities."],
      note:"动词 migrate；形容词 migratory。" }],
    syn:["movement","displacement"], ant:[],
    synDiff:"movement 通用‘移动’；displacement 指‘被迫 displacement’；migration 专指‘周期性/跨国迁徙’。" },

  { w:"symbiotic", ipa:"/ˌsɪmbaɪˈɒtɪk/", pos:"adj.", cat:"动植物",
    senses:[{ def:"共生的",
      ex:["The relationship is symbiotic and mutual.",
          "Clownfish and anemones are symbiotic.",
          "They formed a symbiotic partnership."],
      note:"名词 symbiosis；可互利也可寄生。" }],
    syn:["mutual","interdependent"], ant:["parasitic"],
    synDiff:"mutual 指‘相互’；interdependent 指‘互相依赖’；symbiotic 生物专指‘共生’。" },

  { w:"species", ipa:"/ˈspiːʃiːz/", pos:"n.", cat:"动植物",
    senses:[{ def:"物种",
      ex:["This species is found only here.",
          "A new species was discovered.",
          "The species is at risk of loss."],
      note:"单复同形 species；形容词 specific。" }],
    syn:["kind","breed"], ant:[],
    synDiff:"kind 通用‘种类’；breed 指‘品种（家畜）’；species 是生物分类‘物种’。" },

  // ---------------- 艺术与音乐（补充） ----------------
  { w:"baroque", ipa:"/bəˈrɒk/", pos:"adj./n.", cat:"艺术音乐",
    senses:[{ def:"巴洛克（艺术/音乐风格，华丽繁复）",
      ex:["Bach wrote baroque music.",
          "The cathedral is a baroque masterpiece.",
          "Baroque art delights in ornament."],
      note:"约 1600–1750；反义/后继 classical（古典）。" }],
    syn:["ornate","elaborate"], ant:["austere","minimalist"],
    synDiff:"ornate 指‘华丽装饰’；elaborate 指‘精细复杂’；baroque 是特定历史风格‘繁复华丽’。" },

  { w:"impressionism", ipa:"/ɪmˈpreʃənɪzəm/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"印象派（绘画，重光影瞬间感）",
      ex:["Monet is a leader of impressionism.",
          "Impressionism broke with strict realism.",
          "The show surveys French impressionism."],
      note:"形容词 impressionist；代表：莫奈、雷诺阿。" }],
    syn:["plein-air painting"], ant:[],
    synDiff:"plein-air 指‘外光写生’（技法）；impressionism 是‘印象派’流派。" },

  { w:"surrealism", ipa:"/səˈrɪəlɪzəm/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"超现实主义",
      ex:["Dali is a surrealism icon.",
          "Surrealism fuses dream and reality.",
          "The film owes much to surrealism."],
      note:"形容词 surreal（超现实的）；代表：达利、马格利特。" }],
    syn:["dreamlike art"], ant:[],
    synDiff:"dreamlike 形容‘如梦’；surrealism 是‘超现实’艺术流派。" },

  { w:"chiaroscuro", ipa:"/ˌkiːɑːrəˈskʊərəʊ/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"明暗对照法（绘画用光）",
      ex:["Caravaggio mastered chiaroscuro.",
          "The chiaroscuro adds drama.",
          "Renaissance art used chiaroscuro."],
      note:"意大利语‘明+暗’；也用于电影用光。" }],
    syn:["shading","contrast"], ant:[],
    synDiff:"shading 指‘明暗渐变’；contrast 指‘对比’；chiaroscuro 是‘强明强暗’的造型技法。" },

  { w:"sonata", ipa:"/səˈnɑːtə/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"奏鸣曲（乐器作品）",
      ex:["Beethoven's Moonlight Sonata is famous.",
          "She performed a piano sonata.",
          "The sonata has three movements."],
      note:"区别于 symphony（交响曲，管弦乐）。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"symphony", ipa:"/ˈsɪmfəni/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"交响曲（管弦乐大型作品）",
      ex:["Mahler's symphony moved the hall.",
          "The orchestra played a symphony.",
          "His Ninth Symphony is beloved."],
      note:"复数 symphonies；交响乐团 symphony orchestra。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"harmony", ipa:"/ˈhɑːməni/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"和声；和谐",
      ex:["The voices blend in harmony.",
          "The chords create rich harmony.",
          "Social harmony needs tolerance."],
      note:"反义 dissonance（不和谐）；形容词 harmonious。" }],
    syn:["concord","agreement"], ant:["dissonance","discord"],
    synDiff:"concord 通用‘一致’；agreement 指‘协议/同意’；harmony 音乐指‘和声’，引申‘和谐’。" },

  { w:"tempo", ipa:"/ˈtempəʊ/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"速度；节奏（乐曲）",
      ex:["The conductor slowed the tempo.",
          "A brisk tempo lifted the piece.",
          "Keep a steady tempo."],
      note:"复数 tempos / tempi；也喻‘步调’。" }],
    syn:["pace","speed"], ant:["slowness"],
    synDiff:"pace 通用‘步速’；speed 指‘速度’；tempo 音乐专指‘演奏速度’。" },

  { w:"melody", ipa:"/ˈmelədi/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"旋律",
      ex:["The melody is easy to hum.",
          "She sang the melody alone.",
          "The melody stays in your head."],
      note:"形容词 melodic；与 harmony（和声）相对。" }],
    syn:["tune","theme"], ant:[],
    synDiff:"tune 口语‘曲调’；theme 指‘主题’；melody 是‘旋律’专业词。" },

  { w:"libretto", ipa:"/lɪˈbretoʊ/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"歌剧剧本；唱词",
      ex:["He wrote the libretto for the opera.",
          "The libretto is in Italian.",
          "Read the libretto before the show."],
      note:"复数 librettos / libretti。" }],
    syn:["script","text"], ant:[],
    synDiff:"script 通用‘剧本’；text 指‘文本’；libretto 专指‘歌剧/音乐剧唱词本’。" },

  { w:"ensemble", ipa:"/ɒnˈsɒmbl/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"合奏团；全体（演出）",
      ex:["The ensemble played a quartet.",
          "She joined the dance ensemble.",
          "The period ensemble uses old instruments."],
      note:"源自法语；也指‘整体服装搭配’。" }],
    syn:["group","company"], ant:[],
    synDiff:"group 通用‘团体’；company 指‘剧团’；ensemble 专指‘小型合奏/表演团体’。" },

  // ---------------- 旅游（补充） ----------------
  { w:"souvenir", ipa:"/ˌsuːvəˈnɪə(r)/", pos:"n.", cat:"旅游",
    senses:[{ def:"纪念品",
      ex:["She bought a souvenir magnet.",
          "I kept the ticket as a souvenir.",
          "The shop sells local souvenirs."],
      note:"也拼 souvenier（误）；动词‘留念’。" }],
    syn:["memento","keepsake"], ant:[],
    synDiff:"memento 指‘唤起回忆之物’；keepsake 指‘被珍藏的物件’；souvenir 是‘旅游纪念品’。" },

  { w:"excursion", ipa:"/ɪkˈskɜːʃn/", pos:"n.", cat:"旅游",
    senses:[{ def:"短途游览；远足",
      ex:["We took a day excursion to the lake.",
          "The excursion included a guide.",
          "A boat excursion left at noon."],
      note:"比 trip 短、更‘出游’；动词 excurse。" }],
    syn:["trip","outing","jaunt"], ant:[],
    synDiff:"trip 通用‘旅行’；outing 指‘外出游玩’；excursion 强调‘当日往返的短途游览’。" },

  { w:"transit", ipa:"/ˈtrænzɪt/", pos:"n.", cat:"旅游",
    senses:[{ def:"中转；公共交通",
      ex:["We were in transit for eight hours.",
          "The city has good public transit.",
          "Allow time for transit between flights."],
      note:"in transit = 在运输/转机中；形容词 transiting。" }],
    syn:["transfer","transport"], ant:[],
    synDiff:"transfer 指‘换乘’；transport 指‘交通系统’；transit 强调‘途中/中转’状态。" },

  { w:"visa", ipa:"/ˈviːzə/", pos:"n.", cat:"旅游",
    senses:[{ def:"签证",
      ex:["You need a visa to enter the country.",
          "Her visa expires next month.",
          "Apply for a tourist visa early."],
      note:"复数 visas；动词 approve / deny a visa。" }],
    syn:["permit","entry clearance"], ant:[],
    synDiff:"permit 通用‘许可’；entry clearance 指‘入境许可’；visa 是‘签证’专名。" },

  { w:"customs", ipa:"/ˈkʌstəmz/", pos:"n.", cat:"旅游",
    senses:[{ def:"海关",
      ex:["Declare the goods at customs.",
          "Customs checked our bags.",
          "We cleared customs in ten minutes."],
      note:"作‘海关’恒用复数形式；也指‘习俗’。" }],
    syn:["border control","immigration"], ant:[],
    synDiff:"immigration 指‘入境审查（人）’；border control 指‘边境管控’；customs 专指‘行李/货物关税检查’。" },

  { w:"backpacking", ipa:"/ˈbækpækɪŋ/", pos:"n.", cat:"旅游",
    senses:[{ def:"背包旅行",
      ex:["He went backpacking across Asia.",
          "Backpacking teaches independence.",
          "She enjoys budget backpacking."],
      note:"动词 backpack；背包客 backpacker。" }],
    syn:["hiking","budget travel"], ant:[],
    synDiff:"hiking 指‘徒步’；budget travel 指‘穷游’；backpacking 是‘背囊自助旅行’。" },

  { w:"sightseeing", ipa:"/ˈsaɪtsiːɪŋ/", pos:"n.", cat:"旅游",
    senses:[{ def:"观光；游览",
      ex:["We spent the day sightseeing.",
          "A sightseeing bus toured the city.",
          "Sightseeing tired but delighted us."],
      note:"形容词 sightseeing（a sightseeing tour）。" }],
    syn:["tourism","visiting"], ant:[],
    synDiff:"tourism 指‘旅游业’；visiting 指‘拜访’；sightseeing 是‘看景点’的游览活动。" },

  { w:"hospitality", ipa:"/ˌhɒspɪˈtæləti/", pos:"n.", cat:"旅游",
    senses:[{ def:"好客；款待（也指酒店业）",
      ex:["Their hospitality warmed our stay.",
          "She works in hospitality.",
          "Southern hospitality is famous."],
      note:"形容词 hospitable；反义 inhospitality。" }],
    syn:["welcome","guest care"], ant:["hostility"],
    synDiff:"welcome 指‘欢迎’；guest care 指‘宾客服务’；hospitality 是‘好客/接待业’专名。" },

  { w:"indigenous", ipa:"/ɪnˈdɪdʒənəs/", pos:"adj.", cat:"旅游",
    senses:[{ def:"土著的；原生的",
      ex:["Indigenous people have lived here for millennia.",
          "The plant is indigenous to the region.",
          "Respect indigenous cultures when you travel."],
      note:"名词 indigenous people / population；近 native（注意 native 在部分语境敏感）。" }],
    syn:["native","aboriginal"], ant:["foreign","introduced"],
    synDiff:"native 通用‘本土的’；aboriginal 多指‘澳洲原住’；indigenous 是‘原住民/原生’的正式、尊重用语。" },

  { w:"ecotourism", ipa:"/ˈiːkəʊtʊərɪzəm/", pos:"n.", cat:"旅游",
    senses:[{ def:"生态旅游",
      ex:["Ecotourism protects fragile habitats.",
          "They promote ecotourism over mass tourism.",
          "Ecotourism funds local communities."],
      note:"合成词 eco- + tourism；强调‘负责任的、保护导向’旅游。" }],
    syn:["sustainable tourism","nature tourism"], ant:["mass tourism"],
    synDiff:"nature tourism 指‘自然游’；sustainable tourism 指‘可持续旅游’；ecotourism 强调‘生态保育+社区受益’。" },

  // ---------------- 历史人物（补充） ----------------
  { w:"Julius Caesar", ipa:"/ˈdʒuːliəs ˈsiːzə(r)/", pos:"n.", cat:"历史人物",
    senses:[{ def:"尤利乌斯·凯撒（约前100–前44，罗马独裁官，遇刺）",
      ex:["Julius Caesar crossed the Rubicon in 49 BC.",
          "Julius Caesar was assassinated on the Ides of March.",
          "Julius Caesar reformed the calendar."],
      note:"‘越过卢比孔河’喻破釜沉舟；名言 Veni, vidi, vici（我来、我见、我胜）。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"Cleopatra", ipa:"/kliːəˈpætrə/", pos:"n.", cat:"历史人物",
    senses:[{ def:"克利奥帕特拉七世（前69–前30，埃及托勒密王朝末代女王）",
      ex:["Cleopatra allied with Caesar and Antony.",
          "Cleopatra was the last pharaoh of Egypt.",
          "Cleopatra's death ended the dynasty."],
      note:"与罗马政治纠葛；希腊化埃及统治者。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"Napoleon", ipa:"/nəˈpəʊliən/", pos:"n.", cat:"历史人物",
    senses:[{ def:"拿破仑·波拿巴（1769–1821，法国皇帝，军事天才）",
      ex:["Napoleon crowned himself emperor in 1804.",
          "Napoleon was defeated at Waterloo.",
          "Napoleon's code reshaped European law."],
      note:"《拿破仑法典》影响深远；流放圣赫勒拿岛。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"Shakespeare", ipa:"/ˈʃeɪkspɪə(r)/", pos:"n.", cat:"历史人物",
    senses:[{ def:"威廉·莎士比亚（1564–1616，英国剧作家、诗人）",
      ex:["Shakespeare wrote about 38 plays.",
          "Shakespeare coined many English words.",
          "Hamlet is by Shakespeare."],
      note:"‘生或死’To be or not to be 出自其手；被誉为语言大师。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"Isaac Newton", ipa:"/ˈaɪzək ˈnjuːtən/", pos:"n.", cat:"历史人物",
    senses:[{ def:"艾萨克·牛顿（1643–1727，英国物理学家，经典力学奠基人）",
      ex:["Isaac Newton formulated the laws of motion.",
          "Isaac Newton described universal gravitation.",
          "Isaac Newton co-invented calculus."],
      note:"《自然哲学的数学原理》；与莱布尼茨各自发明微积分。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"Charles Darwin", ipa:"/tʃɑːlz ˈdɑːwɪn/", pos:"n.", cat:"历史人物",
    senses:[{ def:"查尔斯·达尔文（1809–1882，英国博物学家，进化论提出者）",
      ex:["Charles Darwin sailed on the Beagle.",
          "Charles Darwin published On the Origin of Species in 1859.",
          "Charles Darwin proposed natural selection."],
      note:"《物种起源》；自然选择理论。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"Abraham Lincoln", ipa:"/ˈeɪbrəhæm ˈlɪŋkən/", pos:"n.", cat:"历史人物",
    senses:[{ def:"亚伯拉罕·林肯（1809–1865，美国第16任总统，废奴）",
      ex:["Abraham Lincoln issued the Emancipation Proclamation.",
          "Abraham Lincoln led the Union in the Civil War.",
          "Abraham Lincoln was assassinated in 1865."],
      note:"解放黑奴；葛底斯堡演说。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"Mahatma Gandhi", ipa:"/məˈhætmə ˈɡɑːndi/", pos:"n.", cat:"历史人物",
    senses:[{ def:"圣雄甘地（1869–1948，印度独立运动领袖，非暴力抗争）",
      ex:["Mahatma Gandhi led non-violent resistance.",
          "Mahatma Gandhi marched for salt rights.",
          "Mahatma Gandhi inspired civil-rights movements."],
      note:"非暴力不合作（Satyagraha）；遇刺。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"Nelson Mandela", ipa:"/ˈnelsn mænˈdelə/", pos:"n.", cat:"历史人物",
    senses:[{ def:"纳尔逊·曼德拉（1918–2013，南非反种族隔离领袖，总统）",
      ex:["Nelson Mandela spent 27 years in prison.",
          "Nelson Mandela became president in 1994.",
          "Nelson Mandela reconciled a divided nation."],
      note:"终结种族隔离；诺贝尔和平奖。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"Winston Churchill", ipa:"/ˈwɪnstən ˈtʃɜːtʃɪl/", pos:"n.", cat:"历史人物",
    senses:[{ def:"温斯顿·丘吉尔（1874–1965，英国首相，二战领袖）",
      ex:["Winston Churchill rallied Britain in 1940.",
          "Winston Churchill coined 'iron curtain'.",
          "Winston Churchill won the Nobel in Literature."],
      note:"战时演讲；‘铁幕’一词。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"Qin Shi Huang", ipa:"/tʃɪn ʃɪ ˈhwɑːŋ/", pos:"n.", cat:"历史人物",
    senses:[{ def:"秦始皇（前259–前210，中国首位皇帝，统一六国）",
      ex:["Qin Shi Huang unified China in 221 BC.",
          "Qin Shi Huang built the first Great Wall link.",
          "Qin Shi Huang standardized writing and weights."],
      note:"统一文字、度量衡、币制；兵马俑为其陵寝。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"Genghis Khan", ipa:"/ˈdʒeŋɡɪs ˈkɑːn/", pos:"n.", cat:"历史人物",
    senses:[{ def:"成吉思汗（约1162–1227，蒙古帝国建立者）",
      ex:["Genghis Khan united the Mongol tribes.",
          "Genghis Khan built the largest land empire.",
          "Genghis Khan reformed the cavalry."],
      note:"蒙古帝国奠基；横扫欧亚。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"Hammurabi", ipa:"/ˌhæmʊˈrɑːbi/", pos:"n.", cat:"历史人物",
    senses:[{ def:"汉谟拉比（约前1792–前1750，古巴比伦王，颁布法典）",
      ex:["Hammurabi issued one of the first law codes.",
          "The Code of Hammurabi used 'an eye for an eye'.",
          "Hammurabi unified Mesopotamia."],
      note:"《汉谟拉比法典》——现存最早成文法之一。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"Socrates", ipa:"/ˈsɒkrətiːz/", pos:"n.", cat:"历史人物",
    senses:[{ def:"苏格拉底（前470–前399，古希腊哲学家，问答法）",
      ex:["Socrates taught by questioning.",
          "Socrates was sentenced to death by Athens.",
          "The Socratic method probes assumptions."],
      note:"‘产婆术’问答法；无著作，事迹见柏拉图对话。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"Plato", ipa:"/ˈplɑːtəʊ/", pos:"n.", cat:"历史人物",
    senses:[{ def:"柏拉图（前428–前348，古希腊哲学家，理念论）",
      ex:["Plato founded the Academy in Athens.",
          "Plato wrote the Republic.",
          "Plato taught that forms are ideal."],
      note:"苏格拉底弟子；亚里士多德之师；理念论（Forms）。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"Aristotle", ipa:"/ˈærɪstɒtl/", pos:"n.", cat:"历史人物",
    senses:[{ def:"亚里士多德（前384–前322，古希腊哲学家，百科全书式学者）",
      ex:["Aristotle tutored Alexander the Great.",
          "Aristotle founded logic as a discipline.",
          "Aristotle's ethics stress virtue."],
      note:"柏拉图弟子；著作涵盖逻辑、物理、伦理、政治。" }],
    syn:[], ant:[],
    synDiff:"" }
];
