// 词汇复习站 · 扩展词库（第五批，全面加厚 + 新增 6 大类别）
// 难度定位 B2–C1（雅思 7.5 / 自评 6.5 区间），不含基础词。
const EXTRA4 = [
  // ============== 学术写作（补充） ==============
  { w:"delineate", ipa:"/dɪˈlɪnieɪt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"描绘；清晰界定", ex:["The report delineates three policy options.",
      "We must delineate the scope before analysis.",
      "The map delineates the fault lines."],
      note:"近 outline，但更强调‘勾画边界/范围’。" }],
    syn:["outline","define"], ant:[], synDiff:"delineate 偏‘划出清晰边界’；outline 偏‘列要点’。" },

  { w:"seminal", ipa:"/ˈsemɪnl/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"开创性的；影响深远的", ex:["His seminal paper reshaped the field.",
      "That book is a seminal work on cognition.",
      "The seminal study spawned a new discipline."],
      note:"形容著作/研究‘奠基性’，褒义强。" }],
    syn:["groundbreaking","influential"], ant:["derivative"], synDiff:"seminal 强调‘开创先河’；influential 仅指‘有影响’。" },

  { w:"stringent", ipa:"/ˈstrɪndʒənt/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"（标准、规定）严格的；苛刻的", ex:["Stringent rules govern clinical trials.",
      "The bank faces stringent capital requirements.",
      "We need more stringent emission standards."],
      note:"常接 rules/controls/standards/tests。" }],
    syn:["strict","rigorous"], ant:["lenient"], synDiff:"stringent 多用于规章标准；strict 通用。" },

  { w:"tenable", ipa:"/ˈtenəbl/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"（论点）站得住脚的；可防守的", ex:["That position is no longer tenable.",
      "Is the hypothesis tenable given the data?",
      "He held a barely tenable view."],
      note:"常用于否定：no longer tenable。" }],
    syn:["defensible"], ant:["untenable"], synDiff:"" },

  { w:"spurious", ipa:"/ˈspjʊəriəs/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"虚假的；站不住脚的", ex:["The study’s claims are spurious.",
      "He offered a spurious justification.",
      "Spurious correlations mislead readers."],
      note:"spurious correlation 是常见搭配（伪相关）。" }],
    syn:["false","baseless"], ant:["valid"], synDiff:"spurious 强调‘看似有理实则假’。" },

  { w:"stipulate", ipa:"/ˈstɪpjuleɪt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"规定；明确要求", ex:["The contract stipulates a 30-day notice.",
      "The grant stipulates how funds are used.",
      "The law stipulates minimum standards."],
      note:"正式‘明文规定’，后接 that 或名词。" }],
    syn:["specify","require"], ant:[], synDiff:"stipulate 偏法律/正式规定；specify 中性‘具体说明’。" },

  { w:"preclude", ipa:"/prɪˈkluːd/", pos:"v.", cat:"学术写作",
    senses:[{ def:"排除；阻止", ex:["Lack of data precludes a conclusion.",
      "His age does not preclude the role.",
      "The rule precludes appeals."],
      note:"preclude sb from doing / preclude sth。" }],
    syn:["prevent","rule out"], ant:["permit"], synDiff:"preclude 正式‘使不可能’；prevent 通用。" },

  { w:"propensity", ipa:"/prəˈpensəti/", pos:"n.", cat:"学术写作",
    senses:[{ def:"倾向；习性", ex:["He has a propensity for risk.",
      "Firms show a propensity to overhire.",
      "There is a propensity toward errors."],
      note:"propensity for / to / toward。" }],
    syn:["tendency","inclination"], ant:[], synDiff:"propensity 偏‘固有倾向’；tendency 更中性通用。" },

  { w:"pertinent", ipa:"/ˈpɜːtɪnənt/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"相关的；切题的", ex:["Ask pertinent questions only.",
      "The evidence is pertinent to the case.",
      "She made a pertinent observation."],
      note:"pertinent to。" }],
    syn:["relevant"], ant:["irrelevant"], synDiff:"pertinent 正式‘切题’；relevant 通用。" },

  { w:"unequivocal", ipa:"/ˌʌnɪˈkwɪvəkl/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"明确的；毫不含糊的", ex:["The data give unequivocal support.",
      "He issued an unequivocal denial.",
      "The verdict was unequivocal."],
      note:"强调‘无歧义’，程度强于 clear。" }],
    syn:["clear","unambiguous"], ant:["ambiguous"], synDiff:"" },

  { w:"reconcile", ipa:"/ˈrekənsaɪl/", pos:"v.", cat:"学术写作",
    senses:[{ def:"调和；使一致", ex:["We must reconcile the two findings.",
      "Theory and data are hard to reconcile.",
      "He reconciled the conflicting accounts."],
      note:"reconcile A with B。" }],
    syn:["resolve","harmonise"], ant:[], synDiff:"" },

  { w:"tenuous", ipa:"/ˈtenjuəs/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"脆弱的；微弱的；牵强的", ex:["The link is tenuous at best.",
      "They have a tenuous hold on power.",
      "His argument rests on a tenuous analogy."],
      note:"tenuous link/connection 常见。" }],
    syn:["weak","fragile"], ant:["strong"], synDiff:"tenuous 指‘薄弱、易断’（物理/逻辑皆可）。" },

  { w:"commensurate", ipa:"/kəˈmenʃərət/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"相称的；成比例的", ex:["Pay should be commensurate with effort.",
      "A penalty commensurate with the crime.",
      "Funding is not commensurate with need."],
      note:"commensurate with。" }],
    syn:["proportionate"], ant:["disproportionate"], synDiff:"" },

  { w:"obfuscate", ipa:"/ˈɒbfʌskeɪt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"使模糊；故意混淆", ex:["Jargon obfuscates the issue.",
      "He obfuscated his role in the affair.",
      "The report obfuscates the real costs."],
      note:"贬义‘把事情搞糊涂’，尤指故意。" }],
    syn:["confuse","obscure"], ant:["clarify"], synDiff:"obfuscate 比 confuse 更正式且含‘故意遮掩’。" },

  { w:"eschew", ipa:"/ɪsˈtʃuː/", pos:"v.", cat:"学术写作",
    senses:[{ def:"避开；戒绝", ex:["Good writers eschew cliché.",
      "The firm eschews debt.",
      "She eschews publicity."],
      note:"正式‘刻意回避’，及物。" }],
    syn:["avoid","shun"], ant:["embrace"], synDiff:"eschew 正式‘主动戒绝’；avoid 通用。" },

  { w:"enumerate", ipa:"/ɪˈnjuːməreɪt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"列举；枚举", ex:["He enumerated three objections.",
      "The risks were enumerated clearly.",
      "Let me enumerate the steps."],
      note:"比 list 正式，强调‘逐一列出’。" }],
    syn:["list","detail"], ant:[], synDiff:"enumerate 正式‘逐条枚举’。" },

  { w:"discrepancy", ipa:"/dɪsˈkrepənsi/", pos:"n.", cat:"学术写作",
    senses:[{ def:"差异；不符", ex:["There is a discrepancy in the accounts.",
      "We found a discrepancy between the two figures.",
      "The discrepancy remains unexplained."],
      note:"discrepancy between A and B。" }],
    syn:["difference","inconsistency"], ant:["agreement"], synDiff:"" },

  { w:"inherent", ipa:"/ɪnˈhɪərənt/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"固有的；内在的", ex:["Risk is inherent in the process.",
      "The method has inherent limitations.",
      "An inherent tension exists."],
      note:"inherent in / to。" }],
    syn:["intrinsic","built-in"], ant:["extrinsic"], synDiff:"inherent 偏‘与生俱来’；intrinsic 偏‘本质属性’。" },

  { w:"provisional", ipa:"/prəˈvɪʒənl/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"临时的；暂定的", ex:["We reached a provisional agreement.",
      "The figures are provisional.",
      "A provisional government was formed."],
      note:"provisional 与 tentative 近义，但更偏‘暂时生效’。" }],
    syn:["temporary","tentative"], ant:["final"], synDiff:"" },

  { w:"auspice", ipa:"/ˈɔːspɪs/", pos:"n.", cat:"学术写作",
    senses:[{ def:"赞助；主持（under the auspices of）", ex:["The summit met under UN auspices.",
      "Research was done under academic auspices.",
      "The project ran under private auspices."],
      note:"几乎只用 under the auspices of 短语。" }],
    syn:["sponsorship","patronage"], ant:[], synDiff:"" },

  { w:"nullify", ipa:"/ˈnʌlɪfaɪ/", pos:"v.", cat:"学术写作",
    senses:[{ def:"使无效；抵消", ex:["The court nullified the law.",
      "The goal was nullified by offside.",
      "The gain was nullified by costs."],
      note:"法律/正式‘作废’。" }],
    syn:["invalidate","cancel"], ant:["validate"], synDiff:"nullify 正式‘宣告无效’；cancel 通用。" },

  { w:"purport", ipa:"/pəˈpɔːt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"声称；意指", ex:["The letter purports to be official.",
      "The study purports to show a link.",
      "What does the clause purport to mean?"],
      note:"常带‘声称（未必属实）’的意味。" }],
    syn:["claim","allege"], ant:[], synDiff:"purport 暗示‘表面宣称’。" },

  { w:"pertaining", ipa:"/pəˈteɪnɪŋ/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"与…有关的（pertaining to）", ex:["Documents pertaining to the case.",
      "Matters pertaining to safety.",
      "Files pertaining to tax."],
      note:"正式书面语，= relating to。" }],
    syn:["relating","concerning"], ant:[], synDiff:"" },

  { w:"cogent", ipa:"/ˈkəʊdʒənt/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"（论证）有说服力的", ex:["She made a cogent argument.",
      "The case is cogent and clear.",
      "We need more cogent evidence."],
      note:"cogent reason/argument/evidence。" }],
    syn:["convincing","compelling"], ant:["weak"], synDiff:"cogent 专指‘逻辑上有力’。" },

  { w:"nuance", ipa:"/ˈnjuːɑːns/", pos:"n.", cat:"学术写作",
    senses:[{ def:"细微差别", ex:["The translator caught every nuance.",
      "There is a nuance of tone here.",
      "He missed the nuance of the law."],
      note:"nuance 已收入前批，此处补充作为名词用法锚定。" }],
    syn:["subtlety"], ant:[], synDiff:"" },

  // ============== 英语文学（补充） ==============
  { w:"anaphora", ipa:"/əˈnæfərə/", pos:"n.", cat:"英语文学",
    senses:[{ def:"首语重复（修辞格）", ex:["‘We shall fight…’ uses anaphora.",
      "Anaphora builds rhythm and force.",
      "The speech relies on anaphora."],
      note:"句首重复，如 Churchill 的 We shall fight…" }],
    syn:["repetition"], ant:[], synDiff:"" },

  { w:"paradox", ipa:"/ˈpærədɒks/", pos:"n.", cat:"英语文学",
    senses:[{ def:"悖论；看似矛盾实则有理的说法", ex:["‘Less is more’ is a paradox.",
      "The novel turns on a paradox.",
      "He voiced a painful paradox."],
      note:"文学/哲学常用，≠ oxymoron（矛盾修辞）。" }],
    syn:["contradiction"], ant:[], synDiff:"paradox 是命题级矛盾；oxymoron 是词组级（如 bitter-sweet）。" },

  { w:"synecdoche", ipa:"/sɪˈnekdəki/", pos:"n.", cat:"英语文学",
    senses:[{ def:"提喻（以部分代全体）", ex:["‘All hands on deck’ is synecdoche.",
      "‘The crown’ for the monarchy is synecdoche.",
      "Synecdoche links part to whole."],
      note:"部分代整体，与 metonymy（相关代）易混。" }],
    syn:["metonymy"], ant:[], synDiff:"synecdoche 必为‘部分—整体’；metonymy 是‘相关’代（如 White House=政府）。" },

  { w:"pathetic fallacy", ipa:"/pəˈθetɪk ˈfɔːləsi/", pos:"n.", cat:"英语文学",
    senses:[{ def:"移情谬误（将人性赋予自然）", ex:["The angry storm is pathetic fallacy.",
      "Romantics used pathetic fallacy often.",
      "‘Nature wept’ shows pathetic fallacy."],
      note:"把人的情感投射到无生命自然。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"frame narrative", ipa:"/freɪm ˈnærətɪv/", pos:"n.", cat:"英语文学",
    senses:[{ def:"框架叙事（故事套故事）", ex:["The Canterbury Tales uses a frame narrative.",
      "A frame narrative encloses tales.",
      "The film is a frame narrative."],
      note:"嵌套结构，如《西游记》取经框架内的单元故事。" }],
    syn:["embedded narrative"], ant:[], synDiff:"" },

  { w:"hamartia", ipa:"/ˌhɑːmɑːˈtiə/", pos:"n.", cat:"英语文学",
    senses:[{ def:"悲剧性缺陷（亚里士多德语）", ex:["Oedipus’ pride is his hamartia.",
      "Hamartia drives the tragic fall.",
      "The hero’s hamartia is hubris."],
      note:"悲剧主人公的性格弱点，导致陨落。" }],
    syn:["tragic flaw"], ant:[], synDiff:"" },

  { w:"leitmotif", ipa:"/ˈlaɪtməʊtiːf/", pos:"n.", cat:"英语文学",
    senses:[{ def:"主导动机（反复出现的主题）", ex:["A leitmotif recurs in the novel.",
      "Wagner coined the leitmotif.",
      "The colour red is a leitmotif."],
      note:"音乐/文学中反复出现的意象或旋律。" }],
    syn:["motif","theme"], ant:[], synDiff:"" },

  { w:"anagnorisis", ipa:"/ˌænəɡˈnɒrɪsɪs/", pos:"n.", cat:"英语文学",
    senses:[{ def:"发现／顿悟（悲剧转折点）", ex:["The anagnorisis reveals the truth.",
      "Oedipus’ anagnorisis is devastating.",
      "Recognition drives the plot."],
      note:"主人公‘发现真相’的时刻，常与 peripeteia（逆转）成对。" }],
    syn:["recognition","discovery"], ant:[], synDiff:"" },

  { w:"peripeteia", ipa:"/ˌperɪpəˈtaɪə/", pos:"n.", cat:"英语文学",
    senses:[{ def:"突转（情节逆转）", ex:["The peripeteia flips the fortune.",
      "A sudden peripeteia shocks the reader.",
      "Peripeteia follows anagnorisis."],
      note:"命运/情节的急剧反转。" }],
    syn:["reversal"], ant:[], synDiff:"" },

  { w:"mise en abyme", ipa:"/ˌmiːz ɒ̃ ˈabiːm/", pos:"n.", cat:"英语文学",
    senses:[{ def:"套盒结构（画中画／故事中故事）", ex:["The play is a mise en abyme.",
      "A story within a story is mise en abyme.",
      "The film frames a film."],
      note:"法文，指‘无限嵌套’的视觉/叙事结构。" }],
    syn:["nested structure"], ant:[], synDiff:"" },

  { w:"ekphrasis", ipa:"/ekˈfreɪsɪs/", pos:"n.", cat:"英语文学",
    senses:[{ def:"艺格敷词（以文字描摹艺术品）", ex:["The poem is an ekphrasis of a painting.",
      "Ekphrasis bridges word and image.",
      "He wrote ekphrasis of the statue."],
      note:"用文学描摹视觉艺术的传统。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"stream of consciousness", ipa:"/striːm əv ˈkɒnʃəsnəs/", pos:"n.", cat:"英语文学",
    senses:[{ def:"意识流", ex:["Woolf pioneered stream of consciousness.",
      "The passage is pure stream of consciousness.",
      "Joyce used stream of consciousness."],
      note:"内心独白式写法，代表作家 Woolf/Joyce。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"unreliable narrator", ipa:"/ˌʌnrɪˈlaɪəbl næˈreɪtə/", pos:"n.", cat:"英语文学",
    senses:[{ def:"不可靠叙述者", ex:["The narrator is unreliable by design.",
      "An unreliable narrator skews the truth.",
      "We doubt the unreliable narrator."],
      note:"叙述者偏见/说谎，读者须自行判断。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"magical realism", ipa:"/ˈmædʒɪkl ˈrɪəlɪzəm/", pos:"n.", cat:"英语文学",
    senses:[{ def:"魔幻现实主义", ex:["Marquez defined magical realism.",
      "Magical realism blends myth and fact.",
      "The novel is magical realism."],
      note:"现实底色 + 奇幻元素，拉美文学代表。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"motif", ipa:"/məʊˈtiːf/", pos:"n.", cat:"英语文学",
    senses:[{ def:"母题；反复出现的意象", ex:["Water is a recurring motif.",
      "The bird is a motif of freedom.",
      "Motifs unify the work."],
      note:"motif 与前批 leitmotif 近；motif 更泛。" }],
    syn:["theme","leitmotif"], ant:[], synDiff:"" },

  { w:"pastoral", ipa:"/ˈpɑːstərəl/", pos:"adj./n.", cat:"英语文学",
    senses:[{ def:"田园（诗/画）的", ex:["A pastoral poem of shepherds.",
      "The play has a pastoral setting.",
      "Pastoral idealises rural life."],
      note:"idealise 乡村生活，常带怀旧。" }],
    syn:["bucolic","rustic"], ant:[], synDiff:"pastoral 文学/艺术‘田园’；rustic 偏‘土气’。" },

  { w:"tragicomedy", ipa:"/ˌtrædʒɪˈkɒmədi/", pos:"n.", cat:"英语文学",
    senses:[{ def:"悲喜剧", ex:["The play is a tragicomedy.",
      "Tragicomedy mixes grief and farce.",
      "Stoppard wrote tragicomedy."],
      note:"悲喜交织的体裁。" }],
    syn:[], ant:[], synDiff:"" },

  // ============== 法律政治（补充） ==============
  { w:"jurisprudence", ipa:"/ˌdʒʊərɪsˈpruːdns/", pos:"n.", cat:"法律政治",
    senses:[{ def:"法理学；判例体系", ex:["The court follows civil jurisprudence.",
      "His jurisprudence favours restraint.",
      "Comparative jurisprudence helps."],
      note:" jurisprudence 已出现，此处作为名词锚定。" }],
    syn:["legal theory"], ant:[], synDiff:"" },

  { w:"extradition", ipa:"/ˌekstrəˈdɪʃn/", pos:"n.", cat:"法律政治",
    senses:[{ def:"引渡", ex:["The extradition was denied.",
      "They sought his extradition.",
      "Extradition requires a treaty."],
      note:"extradite 动词。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"indictment", ipa:"/ɪnˈdaɪtmənt/", pos:"n.", cat:"法律政治",
    senses:[{ def:"起诉书；控告", ex:["The grand jury issued an indictment.",
      "The report is an indictment of policy.",
      "He faces an indictment."],
      note:"indict 动词；也喻‘谴责’。" }],
    syn:["charge","accusation"], ant:[], synDiff:"indictment 正式刑事‘起诉’；accusation 通用‘指责’。" },

  { w:"subpoena", ipa:"/səˈpiːnə/", pos:"n./v.", cat:"法律政治",
    senses:[{ def:"传票；传唤", ex:["She received a subpoena.",
      "The court subpoenaed the witness.",
      "He ignored the subpoena."],
      note:"法律强制出庭/取证。" }],
    syn:["summons"], ant:[], synDiff:"" },

  { w:"tort", ipa:"/tɔːt/", pos:"n.", cat:"法律政治",
    senses:[{ def:"侵权（民事不法行为）", ex:["Negligence is a common tort.",
      "He sued in tort.",
      "Tort law differs from contract."],
      note:"民事侵权，非刑事；如诽谤、过失。" }],
    syn:["civil wrong"], ant:[], synDiff:"" },

  { w:"redress", ipa:"/rɪˈdres/", pos:"n./v.", cat:"法律政治",
    senses:[{ def:"纠正；赔偿", ex:["They sought redress in court.",
      "The law provides redress.",
      "We must redress the harm."],
      note:"redress a grievance/wrong。" }],
    syn:["remedy","compensation"], ant:[], synDiff:"" },

  { w:"impunity", ipa:"/ɪmˈpjuːnəti/", pos:"n.", cat:"法律政治",
    senses:[{ def:"免罚；不受惩罚", ex:["They acted with impunity.",
      "Impunity breeds abuse.",
      "No one should enjoy impunity."],
      note:"with impunity 短语。" }],
    syn:["exemption"], ant:[], synDiff:"" },

  { w:"arbitration", ipa:"/ˌɑːbɪˈtreɪʃn/", pos:"n.", cat:"法律政治",
    senses:[{ def:"仲裁", ex:["The dispute went to arbitration.",
      "Arbitration avoided a lawsuit.",
      "They agreed to binding arbitration."],
      note:"第三方裁决，区别于 litigation（诉讼）。" }],
    syn:["mediation"], ant:["litigation"], synDiff:"arbitration 裁决有约束力；mediation 仅调解。" },

  { w:"ratification", ipa:"/ˌrætɪfɪˈkeɪʃn/", pos:"n.", cat:"法律政治",
    senses:[{ def:"批准；核准", ex:["Ratification needs parliament.",
      "The treaty awaits ratification.",
      "Ratification was swift."],
      note:"ratify 动词。" }],
    syn:["approval"], ant:[], synDiff:"" },

  { w:"precedent", ipa:"/ˈpresɪdənt/", pos:"n.", cat:"法律政治",
    senses:[{ def:"先例", ex:["The ruling sets a precedent.",
      "There is no precedent for this.",
      "They cited a precedent."],
      note:"stare decisis 遵循先例原则。" }],
    syn:["example"], ant:[], synDiff:"precedent 专指‘可援引的先例’。" },

  { w:"sovereign", ipa:"/ˈsɒvrɪn/", pos:"adj./n.", cat:"法律政治",
    senses:[{ def:"主权（的）；君主", ex:["A sovereign state decides its laws.",
      "The sovereign ratified the treaty.",
      "Sovereign equality is a principle."],
      note:"sovereignty 主权（已收）。" }],
    syn:["independent","monarch"], ant:[], synDiff:"" },

  { w:"pluralism", ipa:"/ˈplʊərəlɪzəm/", pos:"n.", cat:"法律政治",
    senses:[{ def:"多元主义", ex:["The system favours pluralism.",
      "Cultural pluralism enriches society.",
      "Pluralism checks single power."],
      note:"政治/社会‘多元共存’。" }],
    syn:[], ant:["monism"], synDiff:"" },

  { w:"devolution", ipa:"/ˌdiːvəˈluːʃn/", pos:"n.", cat:"法律政治",
    senses:[{ def:"权力下放", ex:["Devolution gave regions power.",
      "Scottish devolution changed the UK.",
      "Devolution is contested."],
      note:"中央向地方放权。" }],
    syn:["decentralisation"], ant:[], synDiff:"" },

  { w:"impeachment", ipa:"/ɪmˈpiːtʃmənt/", pos:"n.", cat:"法律政治",
    senses:[{ def:"弹劾", ex:["The impeachment failed in the senate.",
      "Impeachment is a political process.",
      "They launched impeachment."],
      note:"impeach 动词。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"extraterritorial", ipa:"/ˌekstrəterəˈtɔːriəl/", pos:"adj.", cat:"法律政治",
    senses:[{ def:"治外法权的", ex:["Embassies have extraterritorial status.",
      "The base is extraterritorial.",
      "Extraterritorial claims spark rows."],
      note:"法律‘超越本国领土管辖’。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"codify", ipa:"/ˈkɒdɪfaɪ/", pos:"v.", cat:"法律政治",
    senses:[{ def:"将（法律）成文化；编纂", ex:["They codified customary law.",
      "The rules were codified in 1990.",
      "Codify the principles."],
      note:"把习惯/原则写成法典。" }],
    syn:["systematise","compile"], ant:[], synDiff:"" },

  { w:"writ", ipa:"/rɪt/", pos:"n.", cat:"法律政治",
    senses:[{ def:"令状；法院文书", ex:["The court issued a writ.",
      "A writ of habeas corpus was filed.",
      "Serve the writ."],
      note:"writ of habeas corpus 人身保护令。" }],
    syn:["order"], ant:[], synDiff:"" },

  { w:"amend", ipa:"/əˈmend/", pos:"v.", cat:"法律政治",
    senses:[{ def:"修正（法案）", ex:["They amended the constitution.",
      "Congress amended the act.",
      "The clause was amended."],
      note:"amendment 修正案（如宪法修正案）。" }],
    syn:["revise","alter"], ant:[], synDiff:"amend 正式‘修订（法律）’；revise 通用。" },

  { w:"constituency", ipa:"/kənˈstɪtjuənsi/", pos:"n.", cat:"法律政治",
    senses:[{ def:"选区；支持群体", ex:["He won his constituency.",
      "The policy pleases his constituency.",
      "Urban constituencies shifted."],
      note:"constituent 选民。" }],
    syn:["district","electorate"], ant:[], synDiff:"" },

  { w:"bicameral", ipa:"/baɪˈkæmərəl/", pos:"adj.", cat:"法律政治",
    senses:[{ def:"两院制的", ex:["The congress is bicameral.",
      "A bicameral system divides power.",
      "Bicameral legislatures are common."],
      note:"如美国参众两院。" }],
    syn:[], ant:["unicameral"], synDiff:"" },

  // ============== 医疗健康（补充） ==============
  { w:"morbidity", ipa:"/mɔːˈbɪdəti/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"发病率；病态", ex:["Morbidity rose after the flood.",
      "We track morbidity and mortality.",
      "Childhood morbidity fell."],
      note:"morbidity 已收，此处锚定。" }],
    syn:["illness rate"], ant:[], synDiff:"" },

  { w:"aetiology", ipa:"/ˌiːtiˈɒlədʒi/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"病因学；成因", ex:["The aetiology is unclear.",
      "We studied the aetiology of asthma.",
      "Aetiology guides treatment."],
      note:"美式拼法 etiology。" }],
    syn:["cause","origin"], ant:[], synDiff:"" },

  { w:"pathogen", ipa:"/ˈpæθədʒən/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"病原体", ex:["A pathogen entered the wound.",
      "Handwashing removes pathogens.",
      "The pathogen spread fast."],
      note:"bacteria/virus/fungus 等致病体统称。" }],
    syn:["germ","microbe"], ant:[], synDiff:"pathogen 医学‘病原体’；germ 口语‘细菌’。" },

  { w:"benign", ipa:"/bɪˈnaɪn/", pos:"adj.", cat:"医疗健康",
    senses:[{ def:"良性的（肿瘤）", ex:["The tumour was benign.",
      "A benign growth needs no surgery.",
      "The lump proved benign."],
      note:"反义 malignant（恶性）。也可形容人‘温和’。" }],
    syn:["harmless"], ant:["malignant"], synDiff:"benign 与 malignant 为医学对立词。" },

  { w:"prognosis", ipa:"/prɒɡˈnəʊsɪs/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"预后；前景", ex:["The prognosis is favourable.",
      "His prognosis improved.",
      "A poor prognosis was given."],
      note:"疾病转归预测。" }],
    syn:["outlook"], ant:[], synDiff:"" },

  { w:"incision", ipa:"/ɪnˈsɪʒn/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"切口；切开", ex:["The surgeon made a small incision.",
      "The incision healed well.",
      "A clean incision reduces risk."],
      note:"incise 动词。" }],
    syn:["cut"], ant:[], synDiff:"incision 外科‘切口’；cut 通用。" },

  { w:"palliative", ipa:"/ˈpæliətɪv/", pos:"adj./n.", cat:"医疗健康",
    senses:[{ def:"缓解的；姑息治疗", ex:["Palliative care eases symptoms.",
      "The drug is palliative, not curative.",
      "They offer palliation."],
      note:"palliative care 姑息/舒缓疗护。" }],
    syn:["relieving"], ant:["curative"], synDiff:"" },

  { w:"convalesce", ipa:"/ˌkɒnvəˈles/", pos:"v.", cat:"医疗健康",
    senses:[{ def:"康复；调养", ex:["She convalesced at home.",
      "He is convalescing after surgery.",
      "Convalesce by the sea."],
      note:"convalescence 康复期。" }],
    syn:["recover","recuperate"], ant:[], synDiff:"convalesce 正式‘病后静养’。" },

  { w:"averse", ipa:"/əˈvɜːs/", pos:"adj.", cat:"医疗健康",
    senses:[{ def:"反对的；厌恶的（averse to）", ex:["He is averse to risk.",
      "Patients were averse to the drug.",
      "She is risk-averse."],
      note:"averse to；反义 inclined。注意与 adverse（不利的）区分。" }],
    syn:["reluctant","opposed"], ant:["inclined"], synDiff:"averse ‘人反感’；adverse ‘事不利’（adverse effect）。" },

  { w:"idiopathic", ipa:"/ˌɪdiəˈpæθɪk/", pos:"adj.", cat:"医疗健康",
    senses:[{ def:"特发性的（原因不明）", ex:["The case is idiopathic.",
      "Idiopathic hypertension has no clear cause.",
      "An idiopathic fever puzzled doctors."],
      note:"医学‘查无明确病因’。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"comorbidity", ipa:"/ˌkəʊmɔːˈbɪdəti/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"共病；合并症", ex:["Diabetes is a common comorbidity.",
      "Comorbidity complicates treatment.",
      "Count the comorbidities."],
      note:"同时患两种以上疾病。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"nosocomial", ipa:"/ˌnɒsəˈkəʊmiəl/", pos:"adj.", cat:"医疗健康",
    senses:[{ def:"医院获得性的", ex:["A nosocomial infection spread.",
      "Nosocomial cases are preventable.",
      "The outbreak was nosocomial."],
      note:"医院内感染（如 MRSA）。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"prophylactic", ipa:"/ˌprɒfɪˈlæktɪk/", pos:"adj./n.", cat:"医疗健康",
    senses:[{ def:"预防（性）的；避孕药", ex:["Prophylactic antibiotics were given.",
      "Use prophylactic measures.",
      "A prophylactic prevents disease."],
      note:"prophylaxis 预防医学。" }],
    syn:["preventive"], ant:[], synDiff:"" },

  { w:"remission", ipa:"/rɪˈmɪʃn/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"（疾病）缓解；豁免", ex:["The cancer is in remission.",
      "A brief remission occurred.",
      "Tax remission helped firms."],
      note:"remit 动词。" }],
    syn:["relief","abatement"], ant:["relapse"], synDiff:"remission 症状消退；relapse 复发。" },

  { w:"sequela", ipa:"/sɪˈkwiːlə/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"后遗症", ex:["Paralysis was a sequela.",
      "The sequela lingered for years.",
      "Long-term sequelae worry doctors."],
      note:"复数 sequelae。" }],
    syn:["aftermath"], ant:[], synDiff:"sequela 医学‘后遗症’；aftermath 通用‘后果’。" },

  { w:"etiology", ipa:"/ˌiːtiˈɒlədʒi/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"病因（美式拼法）", ex:["The etiology remained unknown.",
      "Study the etiology of disease.",
      "Etiology informs prevention."],
      note:"= aetiology（英式）。" }],
    syn:["cause"], ant:[], synDiff:"" },

  { w:"acute", ipa:"/əˈkjuːt/", pos:"adj.", cat:"医疗健康",
    senses:[{ def:"急性的；剧烈的", ex:["He has acute pain.",
      "An acute infection struck suddenly.",
      "The angle is acute."],
      note:"acute 已收，此处锚定‘急性’义。" }],
    syn:["severe","sudden"], ant:["chronic"], synDiff:"" },

  { w:"iatrogenic", ipa:"/ˌaɪətrəˈdʒenɪk/", pos:"adj.", cat:"医疗健康",
    senses:[{ def:"医源性的（因治疗引起）", ex:["An iatrogenic error occurred.",
      "Iatrogenic harm is preventable.",
      "The infection was iatrogenic."],
      note:"由医疗行为本身导致。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"prodrome", ipa:"/ˈprəʊdrəʊm/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"前驱症状", ex:["A prodrome preceded the rash.",
      "Fatigue was the prodrome.",
      "Note the prodrome early."],
      note:"发病前的预警症状。" }],
    syn:["warning sign"], ant:[], synDiff:"" },

  // ============== 美食食品（补充） ==============
  { w:"umami", ipa:"/uːˈmɑːmi/", pos:"n.", cat:"美食食品",
    senses:[{ def:"鲜味（第五味）", ex:["Mushrooms add umami.",
      "Umami balances the dish.",
      "Soy sauce is rich in umami."],
      note:"umami 已收，此处锚定。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"umami-laden", ipa:"/uːˈmɑːmi ˌleɪdn/", pos:"adj.", cat:"美食食品",
    senses:[{ def:"富含鲜味的", ex:["An umami-laden broth.",
      "The sauce is umami-laden.",
      "Umami-laden stocks deepen flavour."],
      note:"umami-laden 已收，此处锚定。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"piquant", ipa:"/ˈpiːkənt/", pos:"adj.", cat:"美食食品",
    senses:[{ def:"开胃的；辛辣鲜爽的", ex:["A piquant sauce lifts the meal.",
      "The salsa is piquant.",
      "Piquant flavours cut the fat."],
      note:"刺激味蕾、不腻。" }],
    syn:["tangy","zesty"], ant:["bland"], synDiff:"piquant 偏‘鲜爽刺激’；tangy 偏‘酸爽’。" },

  { w:"confit", ipa:"/kɒnˈfiː/", pos:"n.", cat:"美食食品",
    senses:[{ def:"油封（料理法）", ex:["Duck confit is a French classic.",
      "Confit preserves the meat.",
      "Try the garlic confit."],
      note:"慢火油浸保存法。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"reduction", ipa:"/rɪˈdʌkʃn/", pos:"n.", cat:"美食食品",
    senses:[{ def:"（酱汁）浓缩收汁", ex:["A wine reduction sauces the steak.",
      "Make a reduction of stock.",
      "The reduction was glossy."],
      note:"烹调‘收汁’。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"julienne", ipa:"/ˌdʒuːliˈen/", pos:"v./n.", cat:"美食食品",
    senses:[{ def:"切丝（法式）", ex:["Julienne the carrots.",
      "A julienne of vegetables.",
      "Julienne cut aids cooking."],
      note:"细丝切法。" }],
    syn:["shred"], ant:[], synDiff:"julienne 法式‘细丝’；shred 通用‘切丝’。" },

  { w:"mirepoix", ipa:"/ˈmɪrwɑː/", pos:"n.", cat:"美食食品",
    senses:[{ def:"（法餐）香料底（丁状蔬肉）", ex:["A mirepoix starts the stew.",
      "Sweat the mirepoix first.",
      "Mirepoix builds the base."],
      note:"洋葱胡萝卜西芹切丁炒香作底。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"al dente", ipa:"/ˌæl ˈdenteɪ/", pos:"adj.", cat:"美食食品",
    senses:[{ def:"（意面）弹牙的", ex:["Cook the pasta al dente.",
      "Al dente means firm to the bite.",
      "He prefers al dente rice."],
      note:"意大利语‘有嚼劲’。" }],
    syn:[], ant:["mushy"], synDiff:"" },

  { w:"emulsify", ipa:"/ɪˈmʌlsɪfaɪ/", pos:"v.", cat:"美食食品",
    senses:[{ def:"乳化", ex:["Emulsify oil and vinegar.",
      "Mustard helps emulsify.",
      "The sauce emulsified smoothly."],
      note:"使油水混合，如蛋黄酱。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"degustation", ipa:"/ˌdeɪɡʌˈsteɪʃn/", pos:"n.", cat:"美食食品",
    senses:[{ def:"品鉴（套餐）", ex:["A degustation menu of seven courses.",
      "Degustation showcases the chef.",
      "They booked the degustation."],
      note:"tasting menu 品鉴菜单。" }],
    syn:["tasting"], ant:[], synDiff:"" },

  { w:"brunoise", ipa:"/bruːnˈkwɑːz/", pos:"n.", cat:"美食食品",
    senses:[{ def:"极细丁（切法）", ex:["A brunoise of pepper garnishes.",
      "Dice to a fine brunoise.",
      "Brunoise refines texture."],
      note:"比 julienne 更细的丁。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"fonds", ipa:"/fɔ̃/", pos:"n.", cat:"美食食品",
    senses:[{ def:"（法餐）高汤底", ex:["A brown fond flavours the pan.",
      "Deglaze the fond with wine.",
      "The fond is the base."],
      note:"煎烤后锅底的焦化物，提味。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"velouté", ipa:"/vəˈluːteɪ/", pos:"n.", cat:"美食食品",
    senses:[{ def:"（法餐）白汁酱", ex:["A velouté of chicken.",
      "Velouté is a mother sauce.",
      "Thicken with velouté."],
      note:"五大母酱之一（白汤+roux）。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"macerate", ipa:"/ˈmæsəreɪt/", pos:"v.", cat:"美食食品",
    senses:[{ def:"浸渍（软化）", ex:["Macerate the fruit in liqueur.",
      "Macerate overnight.",
      "Macerate to release juice."],
      note:"泡软/泡出味。" }],
    syn:["soak"], ant:[], synDiff:"macerate 烹饪‘浸渍’；soak 通用‘浸泡’。" },

  { w:"béchamel", ipa:"/ˈbeɪʃəmel/", pos:"n.", cat:"美食食品",
    senses:[{ def:"白酱（牛奶+roux）", ex:["A béchamel tops the lasagne.",
      "Béchamel is a mother sauce.",
      "Whisk a smooth béchamel."],
      note:"五大母酱之一。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"gastrique", ipa:"/ɡæsˈtriːk/", pos:"n.", cat:"美食食品",
    senses:[{ def:"糖醋焦化酱", ex:["A fruit gastrique cuts richness.",
      "Make a vinegar gastrique.",
      "The gastrique balanced sweet."],
      note:"焦糖+醋的酸甜味酱。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"sous vide", ipa:"/suː viːd/", pos:"n.", cat:"美食食品",
    senses:[{ def:"真空低温烹调", ex:["Sous vide keeps steak tender.",
      "Cook sous vide for two hours.",
      "Sous vide controls doneness."],
      note:"真空密封低温水浴。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"flambé", ipa:"/flɒmˈbeɪ/", pos:"v.", cat:"美食食品",
    senses:[{ def:"火焰上桌（淋酒点火）", ex:["They flambé the pancakes.",
      "Flambé the cherries in brandy.",
      "The dish was flambéed."],
      note:"淋酒点火。" }],
    syn:[], ant:[], synDiff:"" },

  // ============== 外貌性格（补充，C1 高阶） ==============
  { w:"mellifluous", ipa:"/məˈlɪfluəs/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"（声音）悦耳流畅的", ex:["She has a mellifluous voice.",
      "His mellifluous speech soothed.",
      "A mellifluous tone charms."],
      note:"声音甜美流畅。" }],
    syn:["silvery","smooth"], ant:["harsh"], synDiff:"mellifluous 专指声音‘如蜜流’。" },

  { w:"florid", ipa:"/ˈflɒrɪd/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"（面色）红润的；辞藻华丽的", ex:["A florid complexion.",
      "His florid prose tired readers.",
      "The speaker turned florid."],
      note:"可形容脸色红或文风浮夸。" }],
    syn:["ruddy","ornate"], ant:["pale"], synDiff:"florid 面色‘红润’；文风‘华丽过甚’。" },

  { w:"limpid", ipa:"/ˈlɪmpɪd/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"（眼神/水）清澈的", ex:["Her limpid eyes calmed him.",
      "A limpid stream ran by.",
      "He has a limpid gaze."],
      note:"清晰通透，常形容眼或水。" }],
    syn:["clear","transparent"], ant:["murky"], synDiff:"limpid 文学‘澄澈’。" },

  { w:"insouciant", ipa:"/ɪnˈsuːsiənt/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"漫不经心的；无忧无虑的", ex:["An insouciant shrug.",
      "She answered with insouciant ease.",
      "His insouciant manner hid worry."],
      note:"轻松不在意，带点潇洒。" }],
    syn:["carefree","nonchalant"], ant:["anxious"], synDiff:"insouciant 偏‘无忧’；nonchalant 偏‘故作冷淡’。" },

  { w:"bilious", ipa:"/ˈbɪliəs/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"暴躁的；坏脾气的", ex:["A bilious temper.",
      "He grew bilious at noon.",
      "Her bilious mood returned."],
      note:"本义‘胆汁的’，引申易怒。" }],
    syn:["irritable","peevish"], ant:["cheerful"], synDiff:"" },

  { w:"seraphic", ipa:"/səˈræfɪk/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"天使般的；圣洁温柔的", ex:["A seraphic smile.",
      "The child looked seraphic.",
      "Her seraphic calm soothed all."],
      note:"如天使般纯净。" }],
    syn:["angelic"], ant:["fiendish"], synDiff:"" },

  { w:"craven", ipa:"/ˈkreɪvn/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"怯懦的；卑怯的", ex:["A craven retreat.",
      "His craven lie shamed him.",
      "Craven fear gripped him."],
      note:"强烈贬义‘胆小如鼠’。" }],
    syn:["cowardly"], ant:["brave"], synDiff:"craven 比 cowardly 更书面贬义。" },

  { w:"phantasmagoric", ipa:"/ˌfæntæzməˈɡɒrɪk/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"幻影般的；光怪陆离的", ex:["A phantasmagoric dream.",
      "The light show was phantasmagoric.",
      "His tales are phantasmagoric."],
      note:"幻象纷呈、变幻莫测。" }],
    syn:["dreamlike","surreal"], ant:[], synDiff:"" },

  { w:"rebarbative", ipa:"/rɪˈbɑːbətɪv/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"令人生厌的；难亲近的", ex:["A rebarbative manner.",
      "His rebarbative prose repels.",
      "She found him rebarbative."],
      note:"正式‘招人烦/拒人千里’。" }],
    syn:["repellent","off-putting"], ant:["appealing"], synDiff:"" },

  { w:"beatific", ipa:"/ˌbiːəˈtɪfɪk/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"极乐的；安详幸福的", ex:["A beatific smile.",
      "The monk wore a beatific look.",
      "Her beatific calm blessed the room."],
      note:"blissful 的更文学说法。" }],
    syn:["blissful"], ant:[], synDiff:"" },

  { w:"churlish", ipa:"/ˈtʃɜːlɪʃ/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"粗野无礼的", ex:["A churlish reply.",
      "He was churlish to guests.",
      "Churlish behaviour shocked them."],
      note:"churlish 已收，此处锚定。" }],
    syn:["rude","boorish"], ant:["courteous"], synDiff:"" },

  { w:"vapid", ipa:"/ˈvæpɪd/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"（言谈）空洞乏味的", ex:["A vapid speech.",
      "His wit grew vapid.",
      "Vapid small talk bored her."],
      note:"无趣无内容。" }],
    syn:["dull","insipid"], ant:["witty"], synDiff:"vapid 言谈‘没味’；insipid 可指食物无味或文章无趣。" },

  { w:"lissome", ipa:"/ˈlɪsəm/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"（身姿）柔软灵巧的", ex:["A lissome dancer.",
      "Her lissome grace amazed.",
      "The lissome acrobat bent."],
      note:"身段柔韧优雅。" }],
    syn:["supple","lithe"], ant:["stiff"], synDiff:"lissome 柔美灵动；supple 偏‘柔韧’。" },

  { w:"saturnine", ipa:"/ˈsætənaɪn/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"阴郁的；冷峻的", ex:["A saturnine glare.",
      "His saturnine mood chilled.",
      "A saturnine stranger."],
      note:"saturnine 已收，此处锚定。" }],
    syn:["gloomy","morose"], ant:["cheerful"], synDiff:"" },

  { w:"imperious", ipa:"/ɪmˈpɪəriəs/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"专横傲慢的", ex:["An imperious gesture.",
      "Her imperious tone rankled.",
      "An imperious host commanded."],
      note:"命令式、高高在上。" }],
    syn:["domineering","haughty"], ant:["meek"], synDiff:"imperious 凭‘权威感’压人；haughty 凭‘优越感’轻视。" },

  { w:"mirthless", ipa:"/ˈmɜːθləs/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"无笑意的；强笑的", ex:["A mirthless smile.",
      "He gave a mirthless laugh.",
      "Her mirthless gaze unnerved."],
      note:"笑但无欢乐。" }],
    syn:[], ant:["merry"], synDiff:"" },

  { w:"sprightly", ipa:"/ˈspraɪtli/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"活泼轻快的（尤指老者）", ex:["A sprightly old man.",
      "She walked sprightly.",
      "His sprightly wit returned."],
      note:"精力充沛、轻盈。" }],
    syn:["lively","spry"], ant:["lethargic"], synDiff:"sprightly 常形容年长者‘精神矍铄’。" },

  { w:"withdrawn", ipa:"/wɪðˈdrɔːn/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"孤僻的；内向退缩的", ex:["A withdrawn child.",
      "He grew withdrawn and quiet.",
      "She seemed withdrawn at parties."],
      note:"社交退缩。" }],
    syn:["reticent","aloof"], ant:["outgoing"], synDiff:"withdrawn 退缩不社交；reticent 少言。" },

  // ============== 地理环境（补充） ==============
  { w:"estuary", ipa:"/ˈestʃuəri/", pos:"n.", cat:"地理环境",
    senses:[{ def:"河口（咸淡水交汇）", ex:["The Thames estuary is busy.",
      "Estuaries teem with life.",
      "The estuary widened."],
      note:"estuary 已收，此处锚定。" }],
    syn:["delta"], ant:[], synDiff:"" },

  { w:"karst", ipa:"/kɑːst/", pos:"n.", cat:"地理环境",
    senses:[{ def:"喀斯特地貌", ex:["Karst forms caves and sinkholes.",
      "The region is karst.",
      "Karst aquifers store water."],
      note:"石灰岩溶蚀地形。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"loess", ipa:"/ˈləʊəs/", pos:"n.", cat:"地理环境",
    senses:[{ def:"黄土", ex:["Loess covers the plateau.",
      "Loess is wind-blown silt.",
      "The loess fertilised farms."],
      note:"风积细黄土，如黄土高原。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"atoll", ipa:"/ˈætɒl/", pos:"n.", cat:"地理环境",
    senses:[{ def:"环礁", ex:["An atoll rings a lagoon.",
      "They landed on the atoll.",
      "The atoll is remote."],
      note:"环状珊瑚礁围湖。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"mesa", ipa:"/ˈmeɪsə/", pos:"n.", cat:"地理环境",
    senses:[{ def:"平顶山；台地", ex:["A red mesa rose in the desert.",
      "The mesa stood alone.",
      "Mesas dot the plateau."],
      note:"顶部平坦、侧壁陡峭。" }],
    syn:["plateau","butte"], ant:[], synDiff:"mesa 平顶宽；butte 平顶窄小。" },

  { w:"isthmus", ipa:"/ˈɪsməs/", pos:"n.", cat:"地理环境",
    senses:[{ def:"地峡", ex:["The isthmus links two lands.",
      "Ships cross the isthmus by canal.",
      "The isthmus is narrow."],
      note:"连接两大陆的狭长地带，如巴拿马。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"tundra", ipa:"/ˈtʌndrə/", pos:"n.", cat:"地理环境",
    senses:[{ def:"苔原", ex:["The tundra is frozen.",
      "Reindeer roam the tundra.",
      "Tundra has no trees."],
      note:"tundra 已收，此处锚定。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"steppe", ipa:"/step/", pos:"n.", cat:"地理环境",
    senses:[{ def:"干草原；大草原", ex:["The Eurasian steppe.",
      "Horses grazed the steppe.",
      "The steppe stretched far."],
      note:"无树广阔草原，如蒙古草原。" }],
    syn:["prairie","grassland"], ant:[], synDiff:"steppe 干旱草原；prairie 北美湿润草原。" },

  { w:"caldera", ipa:"/kælˈdeərə/", pos:"n.", cat:"地理环境",
    senses:[{ def:"火山口湖／破火山口", ex:["A lake fills the caldera.",
      "The caldera exploded millennia ago.",
      "They hiked the caldera rim."],
      note:"火山塌陷形成的大坑。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"moraine", ipa:"/məˈreɪn/", pos:"n.", cat:"地理环境",
    senses:[{ def:"冰碛", ex:["A moraine dammed the valley.",
      "Glaciers leave moraines.",
      "The moraine marked the ice edge."],
      note:"冰川搬运堆积的碎石。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"bolson", ipa:"/ˈbɒlsɒn/", pos:"n.", cat:"地理环境",
    senses:[{ def:"封闭盆地（荒漠）", ex:["A bolson holds no outlet.",
      "The bolson is arid.",
      "Playas fill the bolson."],
      note:"内流封闭洼地。" }],
    syn:["basin"], ant:[], synDiff:"" },

  { w:"escarpment", ipa:"/ɪˈskɑːpmənt/", pos:"n.", cat:"地理环境",
    senses:[{ def:"悬崖；断崖", ex:["The escarpment drops sharply.",
      "They climbed the escarpment.",
      "The escarpment divides regions."],
      note:"长条陡崖（如大裂谷边缘）。" }],
    syn:["cliff","ridge"], ant:[], synDiff:"escarpment 长延陡崖；cliff 通用峭壁。" },

  { w:"oxbow", ipa:"/ˈɒkbəʊ/", pos:"n.", cat:"地理环境",
    senses:[{ def:"牛轭湖（废弃河曲）", ex:["An oxbow curved in the plain.",
      "The river left an oxbow.",
      "Oxbows mark old channels."],
      note:"河流改道遗留的弯月湖。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"inselberg", ipa:"/ˈɪnslɪbɜːɡ/", pos:"n.", cat:"地理环境",
    senses:[{ def:"孤丘（岛山）", ex:["An inselberg rose alone.",
      "The plain held one inselberg.",
      "Inselbergs dot the savanna."],
      note:"平地上突起的孤立丘陵。" }],
    syn:["monadnock"], ant:[], synDiff:"" },

  { w:"fjeld", ipa:"/fjeːld/", pos:"n.", cat:"地理环境",
    senses:[{ def:"（北欧）荒原高地", ex:["The fjeld is bare rock.",
      "Reindeer cross the fjeld.",
      "The fjeld freezes in winter."],
      note:"斯堪的纳维亚裸岩高原。" }],
    syn:["tundra","heath"], ant:[], synDiff:"" },

  { w:"wadi", ipa:"/ˈwɒdi/", pos:"n.", cat:"地理环境",
    senses:[{ def:"（沙漠）季节河床", ex:["A wadi floods in rain.",
      "They camped in the wadi.",
      "The wadi was dry."],
      note:"阿拉伯语，旱谷，暴雨成河。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"scree", ipa:"/skriː/", pos:"n.", cat:"地理环境",
    senses:[{ def:"碎石坡", ex:["Loose scree slid underfoot.",
      "They climbed the scree.",
      "Scree covered the slope."],
      note:"山坡碎岩堆。" }],
    syn:["talus"], ant:[], synDiff:"" },

  { w:"thermocline", ipa:"/ˈθɜːməklaɪn/", pos:"n.", cat:"地理环境",
    senses:[{ def:"温跃层", ex:["A thermocline splits the lake.",
      "The thermocline blocks mixing.",
      "Fish stay above the thermocline."],
      note:"水温骤变的水层。" }],
    syn:[], ant:[], synDiff:"" },

  // ============== 动植物（补充，B2–C1，不收基础词） ==============
  { w:"lichen", ipa:"/ˈlaɪkən/", pos:"n.", cat:"动植物",
    senses:[{ def:"地衣", ex:["Lichen crusts the rock.",
      "Lichen signals clean air.",
      "Reindeer eat lichen."],
      note:"真菌+藻类共生体。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"bryophyte", ipa:"/ˈbraɪəfaɪt/", pos:"n.", cat:"动植物",
    senses:[{ def:"苔藓植物", ex:["Mosses are bryophytes.",
      "Bryophytes lack vessels.",
      "The bryophyte covered stone."],
      note:"非维管植物（苔/藓/角苔）。" }],
    syn:["moss"], ant:[], synDiff:"" },

  { w:"epiphyte", ipa:"/ˈepɪfaɪt/", pos:"n.", cat:"动植物",
    senses:[{ def:"附生植物", ex:["Orchids are epiphytes.",
      "Epiphytes grow on trees.",
      "The epiphyte needs no soil."],
      note:"依附他物生长（如空气凤梨）。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"xerophyte", ipa:"/ˈzɪərəfaɪt/", pos:"n.", cat:"动植物",
    senses:[{ def:"旱生植物", ex:["Cactus is a xerophyte.",
      "Xerophytes store water.",
      "The xerophyte survives drought."],
      note:"耐旱植物。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"mycorrhiza", ipa:"/ˌmaɪkəˈraɪzə/", pos:"n.", cat:"动植物",
    senses:[{ def:"菌根", ex:["Mycorrhiza aids roots.",
      "The fungus forms mycorrhiza.",
      "Mycorrhiza boosts uptake."],
      note:"植物根与真菌共生。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"chelonian", ipa:"/kɪˈləʊniən/", pos:"n./adj.", cat:"动植物",
    senses:[{ def:"龟鳖类（的）", ex:["Chelonians are ancient.",
      "The chelonian basked.",
      "Chelonian shells protect."],
      note:"龟/鳖总称。" }],
    syn:["turtle"], ant:[], synDiff:"" },

  { w:"amphibian", ipa:"/æmˈfɪbiən/", pos:"n.", cat:"动植物",
    senses:[{ def:"两栖动物", ex:["Frogs are amphibians.",
      "The amphibian breathes by skin.",
      "Amphibians need water."],
      note:"amphibian 已收，此处锚定。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"arthropod", ipa:"/ˈɑːθrəpɒd/", pos:"n.", cat:"动植物",
    senses:[{ def:"节肢动物", ex:["Insects are arthropods.",
      "The arthropod molted.",
      "Arthropods have exoskeletons."],
      note:"昆虫/蛛/甲壳类统称。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"mollusc", ipa:"/ˈmɒləsk/", pos:"n.", cat:"动植物",
    senses:[{ def:"软体动物", ex:["Snails are molluscs.",
      "The mollusc secreted shell.",
      "Molluscs include squid."],
      note:"美式 mollusk。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"echinoderm", ipa:"/ɪˈkaɪnəʊdɜːm/", pos:"n.", cat:"动植物",
    senses:[{ def:"棘皮动物", ex:["Starfish are echinoderms.",
      "The echinoderm regrew arms.",
      "Echinoderms have fivefold symmetry."],
      note:"海星/海胆/海参类。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"cetacean", ipa:"/sɪˈteɪʃn/", pos:"n.", cat:"动植物",
    senses:[{ def:"鲸目动物", ex:["Whales are cetaceans.",
      "The cetacean breached.",
      "Cetaceans are mammals."],
      note:"鲸/海豚类。" }],
    syn:["whale"], ant:[], synDiff:"" },

  { w:"chiropteran", ipa:"/kaɪˈrɒptərən/", pos:"n.", cat:"动植物",
    senses:[{ def:"翼手目（蝙蝠类）", ex:["Bats are chiropterans.",
      "The chiropteran roosted.",
      "Chiropterans echo-locate."],
      note:"蝙蝠学名类。" }],
    syn:["bat"], ant:[], synDiff:"" },

  { w:"gastropod", ipa:"/ˈɡæstrəpɒd/", pos:"n.", cat:"动植物",
    senses:[{ def:"腹足类（蜗牛等）", ex:["Snails are gastropods.",
      "The gastropod left a trail.",
      "Gastropods move on one foot."],
      note:"螺/蛞蝓类。" }],
    syn:["snail"], ant:[], synDiff:"" },

  { w:"proboscis", ipa:"/prəˈbɒsɪs/", pos:"n.", cat:"动植物",
    senses:[{ def:"（象）长鼻；（虫）喙", ex:["The trunk is a proboscis.",
      "The moth’s proboscis sips nectar.",
      "The proboscis is long."],
      note:"长吻/长鼻。" }],
    syn:["trunk"], ant:[], synDiff:"" },

  { w:"carapace", ipa:"/ˈkærəpeɪs/", pos:"n.", cat:"动植物",
    senses:[{ def:"（龟/蟹）背甲", ex:["The turtle’s carapace.",
      "The crab shed its carapace.",
      "The carapace hardened."],
      note:"硬壳背甲。" }],
    syn:["shell"], ant:[], synDiff:"carapace 专指背甲；shell 通用壳。" },

  { w:"plumage", ipa:"/ˈpluːmɪdʒ/", pos:"n.", cat:"动植物",
    senses:[{ def:"（鸟）羽毛", ex:["The peacock’s plumage.",
      "Bright plumage attracts mates.",
      "The plumage molted."],
      note:"鸟类全身羽衣。" }],
    syn:["feathers"], ant:[], synDiff:"plumage 集合‘羽衣’；feathers 单根羽。" },

  { w:"piscine", ipa:"/ˈpɪsaɪn/", pos:"adj.", cat:"动植物",
    senses:[{ def:"鱼的；似鱼的", ex:["A piscine shape.",
      "Piscine odour from the tank.",
      "The piscine diet."],
      note:"与 fish 相关。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"arboreal", ipa:"/ɑːˈbɔːriəl/", pos:"adj.", cat:"动植物",
    senses:[{ def:"树栖的", ex:["Monkeys are arboreal.",
      "Arboreal life needs grip.",
      "The arboreal sloth."],
      note:"生活在树上。" }],
    syn:[], ant:["terrestrial"], synDiff:"" },

  { w:"nocturnal", ipa:"/nɒkˈtɜːnl/", pos:"adj.", cat:"动植物",
    senses:[{ def:"夜行的；夜间的", ex:["Owls are nocturnal.",
      "A nocturnal bloom opens at night.",
      "The nocturnal hunt."],
      note:"反义 diurnal（昼行）。" }],
    syn:[], ant:["diurnal"], synDiff:"" },

  { w:"crepuscular", ipa:"/krɪˈpʌskjələ/", pos:"adj.", cat:"动植物",
    senses:[{ def:"晨昏活动的", ex:["Deer are crepuscular.",
      "Crepuscular insects swarm at dusk.",
      "A crepuscular routine."],
      note:"黎明/黄昏活跃。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"altricial", ipa:"/ælˈtrɪʃl/", pos:"adj.", cat:"动植物",
    senses:[{ def:"（雏鸟）晚成的", ex:["Altricial chicks are blind.",
      "Robins are altricial.",
      "Altricial young need care."],
      note:"出生无助需哺育；反义 precocial（早成）。" }],
    syn:[], ant:["precocial"], synDiff:"" },

  { w:"biomass", ipa:"/ˈbaɪəʊmæs/", pos:"n.", cat:"动植物",
    senses:[{ def:"生物量", ex:["The forest stores biomass.",
      "Biomass feeds the food web.",
      "Measure the biomass."],
      note:"生态‘生物总质量’。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"mycelium", ipa:"/maɪˈsiːliəm/", pos:"n.", cat:"动植物",
    senses:[{ def:"菌丝体", ex:["Mycelium threads the soil.",
      "The mycelium feeds the fungus.",
      "Mycelium binds substrate."],
      note:"真菌的营养体网络。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"rhizome", ipa:"/ˈraɪzəʊm/", pos:"n.", cat:"动植物",
    senses:[{ def:"根状茎", ex:["Ginger is a rhizome.",
      "The rhizome spreads underground.",
      "Cut the rhizome to divide."],
      note:"横走地下茎（如竹/姜）。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"tuber", ipa:"/ˈtjuːbə/", pos:"n.", cat:"动植物",
    senses:[{ def:"块茎", ex:["Potato is a tuber.",
      "The tuber stores starch.",
      "Plant the tuber."],
      note:"膨大地下茎（土豆/芋）。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"dicot", ipa:"/ˈdaɪkɒt/", pos:"n.", cat:"动植物",
    senses:[{ def:"双子叶植物", ex:["Oaks are dicots.",
      "The dicot has net veins.",
      "Dicots form a clade."],
      note:"两片子叶；反义 monocot（单子叶）。" }],
    syn:[], ant:["monocot"], synDiff:"" },

  { w:"gametophyte", ipa:"/ɡəˈmiːtəfaɪt/", pos:"n.", cat:"动植物",
    senses:[{ def:"配子体", ex:["Moss gametophytes are green.",
      "The gametophyte bears gametes.",
      "Gametophytes alternate with sporophytes."],
      note:"植物世代交替中产生配子的一代。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"allelopathy", ipa:"/ˌælɪˈlɒpəθi/", pos:"n.", cat:"动植物",
    senses:[{ def:"化感作用（植物互抑）", ex:["Allelopathy stops weeds.",
      "Walnut shows allelopathy.",
      "Allelopathy shapes the field."],
      note:"植物释化感物质抑制邻株。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"nectariferous", ipa:"/ˌnektəˈrɪfərəs/", pos:"adj.", cat:"动植物",
    senses:[{ def:"产蜜的", ex:["A nectariferous flower.",
      "Nectariferous glands attract.",
      "The nectariferous spur."],
      note:"分泌花蜜。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"zoophyte", ipa:"/ˈzəʊəfaɪt/", pos:"n.", cat:"动植物",
    senses:[{ def:"（旧称）植形动物", ex:["Corals were called zoophytes.",
      "The old term zoophyte misled.",
      "Zoophytes blur the line."],
      note:"旧时指似植物的动物（珊瑚）。" }],
    syn:[], ant:[], synDiff:"" },

  // ============== 艺术音乐（补充） ==============
  { w:"mise en scène", ipa:"/ˌmiːz ɒ̃ ˈsen/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"场面调度（舞台/镜头布置）", ex:["The film’s mise en scène.",
      "Mise en scène sets the mood.",
      "Study the mise en scène."],
      note:"法文，画面内一切元素安排。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"sfumato", ipa:"/sfuˈmɑːtəʊ/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"晕涂法（柔和轮廓）", ex:["Da Vinci used sfumato.",
      "Sfumato softens edges.",
      "The sfumato is subtle."],
      note:"达芬奇式烟雾渐变。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"grisaille", ipa:"/ɡrɪˈzaɪ/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"灰调单色画", ex:["A grisaille of stone.",
      "Grisaille imitates sculpture.",
      "The grisaille panel."],
      note:"灰阶单色绘画。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"fresco", ipa:"/ˈfreskəʊ/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"湿壁画", ex:["Michelangelo painted the fresco.",
      "The fresco covers the wall.",
      "A fresco decays slowly."],
      note:"灰泥未干时作画。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"contrapposto", ipa:"/ˌkɒntrəˈpɒstəʊ/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"对立式平衡（重心偏移站姿）", ex:["David stands in contrapposto.",
      "Contrapposto adds life.",
      "The statue’s contrapposto."],
      note:"古典雕塑放松站姿。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"polyphony", ipa:"/pəˈlɪfəni/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"复调（多声独立）", ex:["Bach mastered polyphony.",
      "Polyphony weaves lines.",
      "The motet is polyphony."],
      note:"多旋律并行；反义 monophony。" }],
    syn:[], ant:["monophony"], synDiff:"" },

  { w:"ostinato", ipa:"/ˌɒstɪˈnɑːtəʊ/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"固定音型（反复）", ex:["A bass ostinato drives it.",
      "The ostinato repeats.",
      "Ostinato underpins the theme."],
      note:"反复乐句（如《波莱罗》）。" }],
    syn:["riff"], ant:[], synDiff:"ostinato 古典‘固定音型’；riff 流行/爵士短句。" },

  { w:"cadenza", ipa:"/kəˈdenzə/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"华彩段", ex:["The soloist played a cadenza.",
      "The cadenza shows skill.",
      "A virtuoso cadenza."],
      note:"协奏曲中独奏炫技段。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"scherzo", ipa:"/ˈskeətsəʊ/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"诙谐曲", ex:["A scherzo lightens the symphony.",
      "Beethoven wrote the scherzo.",
      "The scherzo is quick."],
      note:"快活三段体乐章。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"diatonic", ipa:"/ˌdaɪəˈtɒnɪk/", pos:"adj.", cat:"艺术音乐",
    senses:[{ def:"自然音阶的", ex:["A diatonic scale.",
      "The tune is diatonic.",
      "Diatonic harmony."],
      note:"七声自然音；反义 chromatic（半音）。" }],
    syn:[], ant:["chromatic"], synDiff:"" },

  { w:"fortissimo", ipa:"/fɔːˈtɪsɪməʊ/", pos:"adv.", cat:"艺术音乐",
    senses:[{ def:"很强（ff）", ex:["Play fortissimo here.",
      "The fortissimo crashed.",
      "Fortissimo marks force."],
      note:"力度记号；反义 pianissimo。" }],
    syn:["very loud"], ant:["pianissimo"], synDiff:"" },

  { w:"andante", ipa:"/ænˈdɑːnteɪ/", pos:"adv.", cat:"艺术音乐",
    senses:[{ def:"行板（稍慢）", ex:["Mark it andante.",
      "The andante soothes.",
      "Andante, please."],
      note:"速度术语‘行走般’。" }],
    syn:["moderately slow"], ant:[], synDiff:"" },

  { w:"obbligato", ipa:"/ˌɒblɪˈɡɑːtəʊ/", pos:"adj./n.", cat:"艺术音乐",
    senses:[{ def:"助奏（不可或缺）", ex:["A violin obbligato.",
      "The obbligato binds the song.",
      "Sing with obbligato."],
      note:"不可或缺的伴奏声部。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"tonality", ipa:"/təʊˈnæləti/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"调性", ex:["The tonality shifts.",
      "Modal tonality here.",
      "Tonality centres on C."],
      note:"主音/调式中心。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"gestural", ipa:"/ˈdʒestʃərəl/", pos:"adj.", cat:"艺术音乐",
    senses:[{ def:"（绘画）表现性的；姿态的", ex:["A gestural stroke.",
      "Gestural abstraction.",
      "The gestural line."],
      note:"强调笔触动作（如抽象表现主义）。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"triptych", ipa:"/ˈtrɪptɪk/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"三联画", ex:["A religious triptych.",
      "The triptych opens.",
      "A modern triptych."],
      note:"三幅相连画作，中幅常最大。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"silhouette", ipa:"/ˌsɪluˈet/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"剪影；轮廓", ex:["A silhouette against the sun.",
      "The silhouette is stark.",
      "Cut a paper silhouette."],
      note:"深色侧影轮廓。" }],
    syn:["outline","profile"], ant:[], synDiff:"" },

  // ============== 旅游（补充） ==============
  { w:"ecotourism", ipa:"/ˈiːkəʊtʊərɪzəm/", pos:"n.", cat:"旅游",
    senses:[{ def:"生态旅游", ex:["Ecotourism protects reefs.",
      "They promote ecotourism.",
      "Ecotourism aids locals."],
      note:"负责任、低影响的旅游。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"gite", ipa:"/ʒiːt/", pos:"n.", cat:"旅游",
    senses:[{ def:"（法）乡村度假屋", ex:["They rented a gite.",
      "The gite sleeps six.",
      "A rural gite in Provence."],
      note:"法国乡村自炊式民宿。" }],
    syn:["cottage","lodging"], ant:[], synDiff:"" },

  { w:"flâneur", ipa:"/flɑːˈnɜː/", pos:"n.", cat:"旅游",
    senses:[{ def:"（巴黎）闲逛者", ex:["A flâneur of the boulevards.",
      "The flâneur observes the city.",
      "Be a flâneur in Paris."],
      note:"法文‘闲庭信步的都市观察者’。" }],
    syn:["stroller","observer"], ant:[], synDiff:"" },

  { w:"riad", ipa:"/riˈɑːd/", pos:"n.", cat:"旅游",
    senses:[{ def:"（摩洛哥）传统庭院宅", ex:["A riad in the medina.",
      "They stayed in a riad.",
      "The riad has a courtyard."],
      note:"北非 inward 庭院民宿。" }],
    syn:["courtyard house"], ant:[], synDiff:"" },

  { w:"piazza", ipa:"/piˈætsə/", pos:"n.", cat:"旅游",
    senses:[{ def:"（意）广场", ex:["The piazza filled with people.",
      "Coffee on the piazza.",
      "The piazza is grand."],
      note:"意大利城市广场。" }],
    syn:["square","plaza"], ant:[], synDiff:"" },

  { w:"ryokan", ipa:"/riˈəʊkən/", pos:"n.", cat:"旅游",
    senses:[{ def:"（日）传统旅馆", ex:["A ryokan by the sea.",
      "They slept on tatami.",
      "The ryokan served kaiseki."],
      note:"日式榻榻米旅馆。" }],
    syn:["inn"], ant:[], synDiff:"" },

  { w:"dacha", ipa:"/ˈdætʃə/", pos:"n.", cat:"旅游",
    senses:[{ def:"（俄）别墅/乡间小屋", ex:["A dacha outside Moscow.",
      "They summer at the dacha.",
      "The dacha in the woods."],
      note:"俄式度假别墅。" }],
    syn:["cottage"], ant:[], synDiff:"" },

  { w:"caravanserai", ipa:"/ˌkærəˈvansəraɪ/", pos:"n.", cat:"旅游",
    senses:[{ def:"（古）商队驿站", ex:["A caravanserai on the Silk Road.",
      "Traders rested at the caravanserai.",
      "The caravanserai is ruined."],
      note:"古代中亚商旅客栈。" }],
    syn:["inn","waystation"], ant:[], synDiff:"" },

  { w:"promontory", ipa:"/ˈprɒməntri/", pos:"n.", cat:"旅游",
    senses:[{ def:"海角；岬", ex:["A promontory juts to sea.",
      "The lighthouse crowns the promontory.",
      "They climbed the promontory."],
      note:"伸入海的高地。" }],
    syn:["headland","cape"], ant:[], synDiff:"" },

  { w:"midden", ipa:"/ˈmɪdn/", pos:"n.", cat:"旅游",
    senses:[{ def:"（考古）垃圾堆／贝冢", ex:["A shell midden by the shore.",
      "The midden reveals diet.",
      "Excavate the midden."],
      note:"史前垃圾/贝壳堆积。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"baedeker", ipa:"/ˈbeɪdɪkə/", pos:"n.", cat:"旅游",
    senses:[{ def:"（德）旅游指南", ex:["A Baedeker in hand.",
      "The Baedeker listed sights.",
      "Travel by Baedeker."],
      note:"老牌德文旅游手册，引申‘权威指南’。" }],
    syn:["guidebook"], ant:[], synDiff:"" },

  { w:"vista", ipa:"/ˈvɪstə/", pos:"n.", cat:"旅游",
    senses:[{ def:"远景；街景尽头的景", ex:["A vista of the lake.",
      "The avenue opens to a vista.",
      "Enjoy the mountain vista."],
      note:"vista 已收，此处锚定。" }],
    syn:["view","prospect"], ant:[], synDiff:"" },

  { w:"jetty", ipa:"/ˈdʒeti/", pos:"n.", cat:"旅游",
    senses:[{ def:"突堤；栈桥", ex:["The jetty reaches the water.",
      "Fish off the jetty.",
      "The jetty creaked."],
      note:"伸入水的小码头。" }],
    syn:["pier","wharf"], ant:[], synDiff:"jetty 小突堤；pier 大码头/栈桥。" },

  // ============== 历史人物（补充） ==============
  { w:"Pericles", ipa:"/ˈperɪkliːz/", pos:"n.", cat:"历史人物",
    senses:[{ def:"伯里克利（雅典政治家）", ex:["Pericles led Athens’ golden age.",
      "The Pericles funeral oration.",
      "Pericles built the Parthenon."],
      note:"公元前5世纪雅典民主代表。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Hannibal", ipa:"/ˈhænɪbl/", pos:"n.", cat:"历史人物",
    senses:[{ def:"汉尼拔（迦太基将领）", ex:["Hannibal crossed the Alps.",
      "Hannibal fought Rome.",
      "Hannibal’s elephants."],
      note:"二次布匿战争名将。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Julius Caesar", ipa:"/ˈdʒuːliəs ˈsiːzə/", pos:"n.", cat:"历史人物",
    senses:[{ def:"尤利乌斯·凯撒", ex:["Julius Caesar crossed the Rubicon.",
      "Caesar reformed the calendar.",
      "Caesar was assassinated in 44 BC."],
      note:"Julius Caesar 已收，此处锚定全名。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Constantine", ipa:"/ˈkɒnstəntaɪn/", pos:"n.", cat:"历史人物",
    senses:[{ def:"君士坦丁大帝", ex:["Constantine founded Constantinople.",
      "Constantine legalised Christianity.",
      "The Edict of Constantine."],
      note:"罗马首位基督教皇帝。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Charlemagne", ipa:"/ˈʃɑːləmeɪn/", pos:"n.", cat:"历史人物",
    senses:[{ def:"查理曼（法兰克王）", ex:["Charlemagne crowned in Rome.",
      "Charlemagne united Europe.",
      "The Charlemagne empire."],
      note:"Charlemagne 已收，此处锚定。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Ibn Khaldun", ipa:"/ˌɪbən kælˈduːn/", pos:"n.", cat:"历史人物",
    senses:[{ def:"伊本·赫勒敦（阿拉伯史家）", ex:["Ibn Khaldun wrote the Muqaddimah.",
      "Ibn Khaldun analysed cycles.",
      "The sociology of Ibn Khaldun."],
      note:"14世纪伊斯兰史学/社会学先驱。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Akbar", ipa:"/ˈækbɑː/", pos:"n.", cat:"历史人物",
    senses:[{ def:"阿克巴（莫卧儿皇帝）", ex:["Akbar expanded the empire.",
      "Akbar promoted tolerance.",
      "The Akbar court."],
      note:"16世纪印度莫卧儿盛世君主。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Catherine the Great", ipa:"/kəˈtrɪn ðə ɡreɪt/", pos:"n.", cat:"历史人物",
    senses:[{ def:"叶卡捷琳娜大帝", ex:["Catherine the Great ruled Russia.",
      "Catherine expanded the empire.",
      "The era of Catherine."],
      note:"Catherine the Great 已收，此处锚定。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Sun Yat-sen", ipa:"/ˌsʊn jɑːtˈsen/", pos:"n.", cat:"历史人物",
    senses:[{ def:"孙中山", ex:["Sun Yat-sen founded the republic.",
      "Sun Yat-sen led the revolution.",
      "The legacy of Sun Yat-sen."],
      note:"Sun Yat-sen 已收，此处锚定。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Mustafa Kemal Atatürk", ipa:"/mʊsˈtɑːfə kəˈmɑːl ˈætətɜːk/", pos:"n.", cat:"历史人物",
    senses:[{ def:"凯末尔（土耳其国父）", ex:["Atatürk modernised Turkey.",
      "Atatürk founded the republic.",
      "The reforms of Atatürk."],
      note:"20世纪世俗化改革者。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Ho Chi Minh", ipa:"/həʊ tʃiː mɪn/", pos:"n.", cat:"历史人物",
    senses:[{ def:"胡志明", ex:["Ho Chi Minh led Vietnam.",
      "Ho Chi Minh declared independence.",
      "The path of Ho Chi Minh."],
      note:"越南独立领袖。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Nelson Mandela", ipa:"/ˈnelsn mænˈdelə/", pos:"n.", cat:"历史人物",
    senses:[{ def:"曼德拉", ex:["Nelson Mandela ended apartheid.",
      "Mandela spent 27 years jailed.",
      "The courage of Mandela."],
      note:"Nelson Mandela 已收，此处锚定。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Winston Churchill", ipa:"/ˈwɪnstən ˈtʃɜːtʃɪl/", pos:"n.", cat:"历史人物",
    senses:[{ def:"丘吉尔", ex:["Churchill rallied Britain.",
      "Churchill’s speeches inspired.",
      "The resolve of Churchill."],
      note:"Winston Churchill 已收，此处锚定全名。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Deng Xiaoping", ipa:"/dɛŋ ʃaʊˈpɪŋ/", pos:"n.", cat:"历史人物",
    senses:[{ def:"邓小平", ex:["Deng Xiaoping opened reform.",
      "Deng launched modernisation.",
      "The vision of Deng Xiaoping."],
      note:"Deng Xiaoping 已收，此处锚定。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Rosa Parks", ipa:"/ˈrəʊzə pɑːks/", pos:"n.", cat:"历史人物",
    senses:[{ def:"罗莎·帕克斯", ex:["Rosa Parks refused to move.",
      "Parks sparked the boycott.",
      "The stand of Rosa Parks."],
      note:"Rosa Parks 已收，此处锚定。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Hypatia", ipa:"/haɪˈpeɪʃə/", pos:"n.", cat:"历史人物",
    senses:[{ def:"希帕提娅（女数学家）", ex:["Hypatia taught in Alexandria.",
      "Hypatia was a Neoplatonist.",
      "The murder of Hypatia."],
      note:"公元4–5世纪亚历山大女哲学家。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Ada Lovelace", ipa:"/ˈeɪdə ˈlʌvleɪs/", pos:"n.", cat:"历史人物",
    senses:[{ def:"爱达·洛芙莱斯（首位程序员）", ex:["Ada Lovelace wrote the first algorithm.",
      "Lovelace foresaw computing.",
      "The note of Ada Lovelace."],
      note:"19世纪分析机算法先驱。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Frida Kahlo", ipa:"/ˈfriːdə ˈkɑːləʊ/", pos:"n.", cat:"历史人物",
    senses:[{ def:"弗里达·卡洛（画家）", ex:["Frida Kahlo painted self-portraits.",
      "Kahlo blended myth and pain.",
      "The work of Frida Kahlo."],
      note:"20世纪墨西哥女画家。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"Galileo Galilei", ipa:"/ˌɡælɪˈleɪəʊ ɡælɪˈleɪ/", pos:"n.", cat:"历史人物",
    senses:[{ def:"伽利略", ex:["Galileo defended heliocentrism.",
      "Galileo faced the Inquisition.",
      "The telescope of Galileo."],
      note:"近代天文学/物理奠基人。" }],
    syn:[], ant:[], synDiff:"" },

  // ============== 新增：科技工程 ==============
  { w:"algorithm", ipa:"/ˈælɡərɪðəm/", pos:"n.", cat:"科技工程",
    senses:[{ def:"算法", ex:["The search algorithm ranks pages.",
      "We tuned the sorting algorithm.",
      "An algorithm learns from data."],
      note:"步骤化求解规则；AI 核心。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"latency", ipa:"/ˈleɪtənsi/", pos:"n.", cat:"科技工程",
    senses:[{ def:"延迟；时延", ex:["The network has low latency.",
      "Latency hurts real-time apps.",
      "Reduce latency in the pipeline."],
      note:"响应延迟，游戏/通信关键指标。" }],
    syn:["delay"], ant:[], synDiff:"" },

  { w:"throughput", ipa:"/ˈθruːpʊt/", pos:"n.", cat:"科技工程",
    senses:[{ def:"吞吐量", ex:["The server’s throughput doubled.",
      "Throughput limits the system.",
      "Measure throughput per second."],
      note:"单位时间处理量。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"scalability", ipa:"/ˌskeɪləˈbɪləti/", pos:"n.", cat:"科技工程",
    senses:[{ def:"可扩展性", ex:["The design lacks scalability.",
      "Cloud gives scalability.",
      "Test the scalability."],
      note:"随负载增长的能力。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"heuristics", ipa:"/hjʊˈrɪstɪks/", pos:"n.", cat:"科技工程",
    senses:[{ def:"启发式（经验法则）", ex:["Use heuristics to prune search.",
      "Heuristics trade optimality for speed.",
      "A heuristic guides the solver."],
      note:"近似策略，非保证最优。" }],
    syn:["rules of thumb"], ant:[], synDiff:"heuristics 经验近似；algorithm 精确步骤。" },

  { w:"redundancy", ipa:"/rɪˈdʌndənsi/", pos:"n.", cat:"科技工程",
    senses:[{ def:"冗余", ex:["Redundancy ensures reliability.",
      "Add redundancy to the link.",
      "Redundancy costs resources."],
      note:"备份以防失效。" }],
    syn:["backup"], ant:[], synDiff:"" },

  { w:"encapsulation", ipa:"/ɪnˌkæpsjuˈleɪʃn/", pos:"n.", cat:"科技工程",
    senses:[{ def:"封装", ex:["Encapsulation hides internals.",
      "OOP relies on encapsulation.",
      "Good encapsulation reduces bugs."],
      note:"面向对象隐藏实现。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"concurrency", ipa:"/kənˈkʌrənsi/", pos:"n.", cat:"科技工程",
    senses:[{ def:"并发", ex:["Concurrency needs locks.",
      "Manage concurrency with threads.",
      "Concurrency bugs are subtle."],
      note:"多任务同时推进；≠ parallelism（真并行）。" }],
    syn:[], ant:[], synDiff:"concurrency 交错执行；parallelism 同时执行。" },

  { w:"bandwidth", ipa:"/ˈbændwɪdθ/", pos:"n.", cat:"科技工程",
    senses:[{ def:"带宽", ex:["The link is low on bandwidth.",
      "Bandwidth caps the rate.",
      "Buy more bandwidth."],
      note:"数据传输能力。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"cache", ipa:"/kæʃ/", pos:"n./v.", cat:"科技工程",
    senses:[{ def:"缓存", ex:["Serve from cache.",
      "The cache missed.",
      "Cache the result."],
      note:"高速暂存以加速。" }],
    syn:["buffer"], ant:[], synDiff:"" },

  { w:"compiler", ipa:"/kəmˈpaɪlə/", pos:"n.", cat:"科技工程",
    senses:[{ def:"编译器", ex:["The compiler optimises code.",
      "A compiler turns source to binary.",
      "The compiler flagged an error."],
      note:"源码→机器码。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"iteration", ipa:"/ˌɪtəˈreɪʃn/", pos:"n.", cat:"科技工程",
    senses:[{ def:"迭代", ex:["Each iteration refines the model.",
      "Run ten iterations.",
      "Iteration converges slowly."],
      note:"反复逼近；ML 训练核心。" }],
    syn:["repetition","loop"], ant:[], synDiff:"" },

  { w:"granularity", ipa:"/ˌɡrænjuˈlærəti/", pos:"n.", cat:"科技工程",
    senses:[{ def:"粒度", ex:["The data needs finer granularity.",
      "Pick the right granularity.",
      "Coarse granularity hides detail."],
      note:"细节粗细程度。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"idempotent", ipa:"/ˌaɪdəmˈpəʊtənt/", pos:"adj.", cat:"科技工程",
    senses:[{ def:"幂等的（重复结果一致）", ex:["GET should be idempotent.",
      "The op is idempotent.",
      "Idempotent calls are safe."],
      note:"多次执行效果同一次。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"semiconductor", ipa:"/ˌsemikənˈdʌktə/", pos:"n.", cat:"科技工程",
    senses:[{ def:"半导体", ex:["The chip uses a semiconductor.",
      "Semiconductor supply is tight.",
      "Silicon is a semiconductor."],
      note:"导电性介于导体与绝缘体。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"quantum", ipa:"/ˈkwɒntəm/", pos:"n./adj.", cat:"科技工程",
    senses:[{ def:"量子", ex:["Quantum effects appear at small scales.",
      "A quantum computer.",
      "The quantum state."],
      note:"离散能量单位；量子计算前沿。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"nanoscale", ipa:"/ˈnænəskeɪl/", pos:"adj.", cat:"科技工程",
    senses:[{ def:"纳米尺度的", ex:["At the nanoscale, properties change.",
      "Nanoscale materials.",
      "A nanoscale device."],
      note:"十亿分之一米级。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"photovoltaic", ipa:"/ˌfəʊtəʊvɒlˈteɪɪk/", pos:"adj.", cat:"科技工程",
    senses:[{ def:"光伏的", ex:["Photovoltaic panels generate power.",
      "A photovoltaic cell.",
      "Photovoltaic efficiency rose."],
      note:"太阳能发电。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"biodegradable", ipa:"/ˌbaɪəʊdɪˈɡreɪdəbl/", pos:"adj.", cat:"科技工程",
    senses:[{ def:"可生物降解的", ex:["Use biodegradable packaging.",
      "Biodegradable plastic exists.",
      "The bag is biodegradable."],
      note:"环保材料属性。" }],
    syn:[], ant:["non-biodegradable"], synDiff:"" },

  { w:"aerodynamics", ipa:"/ˌeərəʊdaɪˈnæmɪks/", pos:"n.", cat:"科技工程",
    senses:[{ def:"空气动力学", ex:["Aerodynamics shapes the wing.",
      "Study aerodynamics of cars.",
      "Aerodynamics cuts drag."],
      note:"气流与受力。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"kinematics", ipa:"/ˌkɪnɪˈmætɪks/", pos:"n.", cat:"科技工程",
    senses:[{ def:"运动学", ex:["Kinematics ignores forces.",
      "Model the arm’s kinematics.",
      "Kinematics of the robot."],
      note:"研究运动而不究力。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"actuator", ipa:"/ˈæktʃueɪtə/", pos:"n.", cat:"科技工程",
    senses:[{ def:"执行器", ex:["The actuator moves the valve.",
      "A robotic actuator.",
      "The actuator failed."],
      note:"将信号转为机械动作。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"topology", ipa:"/təˈpɒlədʒi/", pos:"n.", cat:"科技工程",
    senses:[{ def:"拓扑（结构布局）", ex:["Network topology matters.",
      "The mesh topology.",
      "Study the topology."],
      note:"连接关系，不拘物理位置。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"hash", ipa:"/hæʃ/", pos:"n./v.", cat:"科技工程",
    senses:[{ def:"哈希（散列）", ex:["Hash the password.",
      "A hash maps keys to slots.",
      "The hash collided."],
      note:"定长摘要/索引函数。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"payload", ipa:"/ˈpeɪləʊd/", pos:"n.", cat:"科技工程",
    senses:[{ def:"有效载荷；数据体", ex:["The rocket carries a payload.",
      "The packet payload.",
      "Inspect the payload."],
      note:"实际载运/传输的内容。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"overhead", ipa:"/ˈəʊvəhed/", pos:"n./adj.", cat:"科技工程",
    senses:[{ def:"开销；间接成本", ex:["The overhead is high.",
      "Cut the runtime overhead.",
      "An overhead cost."],
      note:"非直接但必需的消耗。" }],
    syn:["cost"], ant:[], synDiff:"" },

  { w:"firmware", ipa:"/ˈfɜːmweə/", pos:"n.", cat:"科技工程",
    senses:[{ def:"固件", ex:["Update the firmware.",
      "Firmware bridges hardware and OS.",
      "The firmware crashed."],
      note:"嵌入硬件的底层软件。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"rendering", ipa:"/ˈrendərɪŋ/", pos:"n.", cat:"科技工程",
    senses:[{ def:"渲染；绘制", ex:["The rendering took hours.",
      "Real-time rendering.",
      "The render is noisy."],
      note:"GPU 生成图像。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"tensor", ipa:"/ˈtensə/", pos:"n.", cat:"科技工程",
    senses:[{ def:"张量", ex:["A tensor generalises a matrix.",
      "Feed the tensor to the model.",
      "The tensor has rank three."],
      note:"多维数组，深度学习基础。" }],
    syn:[], ant:[], synDiff:"" },

  // ============== 新增：商业金融 ==============
  { w:"liquidity", ipa:"/lɪˈkwɪdəti/", pos:"n.", cat:"商业金融",
    senses:[{ def:"流动性", ex:["The firm needs liquidity.",
      "Liquidity dried up in 2008.",
      "Improve cash liquidity."],
      note:"资产变现难易。" }],
    syn:[], ant:["illiquidity"], synDiff:"" },

  { w:"amortise", ipa:"/əˈmɔːtaɪz/", pos:"v.", cat:"商业金融",
    senses:[{ def:"摊销；分期偿还", ex:["Amortise the loan over ten years.",
      "Amortise the cost.",
      "The debt is amortised."],
      note:"逐期摊还（无形资产/贷款）。" }],
    syn:["write off gradually"], ant:[], synDiff:"amortise 摊还；depreciate 折旧（ tangible）。" },

  { w:"leverage", ipa:"/ˈliːvərɪdʒ/", pos:"n./v.", cat:"商业金融",
    senses:[{ def:"杠杆；利用", ex:["Use leverage to boost return.",
      "Leverage your network.",
      "High leverage is risky."],
      note:"借力放大；也作动词‘善用’。" }],
    syn:["gearing","use"], ant:[], synDiff:"" },

  { w:"equity", ipa:"/ˈekwəti/", pos:"n.", cat:"商业金融",
    senses:[{ def:"股权；净值", ex:["She holds equity in the firm.",
      "Raise equity, not debt.",
      "Shareholders’ equity."],
      note:"所有者权益；也指‘公平’。" }],
    syn:["ownership","fairness"], ant:["debt"], synDiff:"equity 股权/公平；debt 债权。" },

  { w:"margin", ipa:"/ˈmɑːdʒɪn/", pos:"n.", cat:"商业金融",
    senses:[{ def:"利润；保证金；边距", ex:["The margin is thin.",
      "Post margin to trade.",
      "A margin of safety."],
      note:"profit margin 利润率；也指交易保证金。" }],
    syn:["profit"], ant:[], synDiff:"" },

  { w:"overhead", ipa:"/ˈəʊvəhed/", pos:"n.", cat:"商业金融",
    senses:[{ def:"（企业）日常开支", ex:["Overhead eats profit.",
      "Cut overhead costs.",
      "High overhead hurts."],
      note:"房租/行政等固定支出（与科技义并存）。" }],
    syn:["fixed cost"], ant:[], synDiff:"" },

  { w:"valuation", ipa:"/ˌvæljuˈeɪʃn/", pos:"n.", cat:"商业金融",
    senses:[{ def:"估值", ex:["The valuation doubled.",
      "A fair valuation.",
      "Dispute the valuation."],
      note:"对企业的价值评估。" }],
    syn:["appraisal"], ant:[], synDiff:"" },

  { w:"diversify", ipa:"/daɪˈvɜːsɪfaɪ/", pos:"v.", cat:"商业金融",
    senses:[{ def:"分散；多元化", ex:["Diversify the portfolio.",
      "Firms diversify to cut risk.",
      "Diversify revenue."],
      note:"分散投资/业务。" }],
    syn:[], ant:["concentrate"], synDiff:"" },

  { w:"downsize", ipa:"/ˈdaʊnsaɪz/", pos:"v.", cat:"商业金融",
    senses:[{ def:"裁员；精简", ex:["The firm downsized.",
      "Downsize the workforce.",
      "They downsized the plant."],
      note:"缩编降本。" }],
    syn:["cut","restructure"], ant:["expand"], synDiff:"" },

  { w:"merger", ipa:"/ˈmɜːdʒə/", pos:"n.", cat:"商业金融",
    senses:[{ def:"合并", ex:["The merger created a giant.",
      "Approve the merger.",
      "A cross-border merger."],
      note:"merger 与 acquisition（收购）常并称 M&A。" }],
    syn:["combination"], ant:["split"], synDiff:"" },

  { w:"arbitrage", ipa:"/ˈɑːbɪtrɑːʒ/", pos:"n.", cat:"商业金融",
    senses:[{ def:"套利", ex:["Arbitrage pockets the price gap.",
      "Statistical arbitrage.",
      "Arbitrage keeps markets fair."],
      note:"利用价差无风险获利。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"fiduciary", ipa:"/fɪˈdjuːʃəri/", pos:"adj./n.", cat:"商业金融",
    senses:[{ def:"受托的（义务）", ex:["A fiduciary duty to clients.",
      "The fiduciary must act in trust.",
      "He is a fiduciary."],
      note:"以受益人利益为先的法律义务。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"amortisation", ipa:"/əˌmɔːtaɪˈzeɪʃn/", pos:"n.", cat:"商业金融",
    senses:[{ def:"摊销（名词）", ex:["Amortisation lowers tax.",
      "The schedule of amortisation.",
      "Amortisation spreads cost."],
      note:"amortise 的名词。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"commodity", ipa:"/kəˈmɒdəti/", pos:"n.", cat:"商业金融",
    senses:[{ def:"大宗商品", ex:["Oil is a commodity.",
      "Commodity prices swung.",
      "Trade the commodity."],
      note:"可交易原材料（油/金属/粮）。" }],
    syn:["good"], ant:[], synDiff:"" },

  { w:"stakeholder", ipa:"/ˈsteɪkhəʊldə/", pos:"n.", cat:"商业金融",
    senses:[{ def:"利益相关方", ex:["Consult all stakeholders.",
      "Stakeholders expect returns.",
      "A key stakeholder."],
      note:"股东/员工/社区等。" }],
    syn:["interest"], ant:[], synDiff:"" },

  { w:"turnover", ipa:"/ˈtɜːnəʊvə/", pos:"n.", cat:"商业金融",
    senses:[{ def:"营业额；周转率；流失率", ex:["Annual turnover rose.",
      "Staff turnover is high.",
      "Inventory turnover."],
      note:"销售/人事/库存多义。" }],
    syn:["revenue","churn"], ant:[], synDiff:"" },

  { w:"capitalise", ipa:"/ˈkæpɪtəlaɪz/", pos:"v.", cat:"商业金融",
    senses:[{ def:"利用；资本化", ex:["Capitalise on the trend.",
      "Capitalise the cost.",
      "They capitalised the gain."],
      note:"capitalise on 利用机会。" }],
    syn:["exploit","use"], ant:[], synDiff:"" },

  { w:"collateral", ipa:"/kəˈlætərəl/", pos:"n.", cat:"商业金融",
    senses:[{ def:"抵押品", ex:["Pledge collateral for the loan.",
      "The collateral secures debt.",
      "Seize the collateral."],
      note:"担保物。" }],
    syn:["security"], ant:[], synDiff:"" },

  { w:"insolvent", ipa:"/ɪnˈsɒlvənt/", pos:"adj.", cat:"商业金融",
    senses:[{ def:"资不抵债的", ex:["The firm went insolvent.",
      "An insolvent debtor.",
      "Declare insolvent."],
      note:"无法偿债；反义 solvent。" }],
    syn:["bankrupt"], ant:["solvent"], synDiff:"insolvent 法律‘无偿债能力’；bankrupt 已破产。" },

  { w:"projection", ipa:"/prəˈdʒekʃn/", pos:"n.", cat:"商业金融",
    senses:[{ def:"（财务）预测", ex:["The projection shows profit.",
      "Revise the projection.",
      "A five-year projection."],
      note:"前瞻估算。" }],
    syn:["forecast"], ant:[], synDiff:"" },

  { w:"due diligence", ipa:"/ˌdjuː ˈdɪlɪdʒəns/", pos:"n.", cat:"商业金融",
    senses:[{ def:"尽职调查", ex:["Do due diligence before buying.",
      "The due diligence found risks.",
      "Skip due diligence at peril."],
      note:"交易前核查。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"monopoly", ipa:"/məˈnɒpəli/", pos:"n.", cat:"商业金融",
    senses:[{ def:"垄断", ex:["The firm holds a monopoly.",
      "Break the monopoly.",
      "A natural monopoly."],
      note:"独占市场；反义 competition。" }],
    syn:[], ant:["competition"], synDiff:"" },

  { w:"hedge", ipa:"/hedʒ/", pos:"v./n.", cat:"商业金融",
    senses:[{ def:"对冲； hedging", ex:["Hedge the currency risk.",
      "A hedge against inflation.",
      "They hedged the bet."],
      note:"降低风险的反向操作。" }],
    syn:["offset"], ant:[], synDiff:"" },

  { w:"yield", ipa:"/jiːld/", pos:"n./v.", cat:"商业金融",
    senses:[{ def:"收益；产出", ex:["The bond yield fell.",
      "Yield to maturity.",
      "The crop yield rose."],
      note:"投资回报/农业产量。" }],
    syn:["return","output"], ant:[], synDiff:"" },

  { w:"inflation", ipa:"/ɪnˈfleɪʃn/", pos:"n.", cat:"商业金融",
    senses:[{ def:"通货膨胀", ex:["Inflation eroded savings.",
      "Tame inflation.",
      "Inflation hit 9%."],
      note:"物价普遍上涨；反义 deflation。" }],
    syn:[], ant:["deflation"], synDiff:"" },

  { w:"fiscal", ipa:"/ˈfɪskl/", pos:"adj.", cat:"商业金融",
    senses:[{ def:"财政的", ex:["Fiscal policy stimulates.",
      "The fiscal year ends in June.",
      "Fiscal deficit."],
      note:"政府收支；反义 monetary（货币）。" }],
    syn:[], ant:[], synDiff:"fiscal 财政；monetary 货币。" },

  // ============== 新增：军事国防 ==============
  { w:"sortie", ipa:"/ˈsɔːti/", pos:"n.", cat:"军事国防",
    senses:[{ def:"（军机）出击；出击架次", ex:["The squadron flew a sortie.",
      "A night sortie.",
      "Count the sorties."],
      note:"单次作战出动。" }],
    syn:["raid","mission"], ant:[], synDiff:"" },

  { w:"convoy", ipa:"/ˈkɒnvɔɪ/", pos:"n.", cat:"军事国防",
    senses:[{ def:"护航队；车队", ex:["A convoy crossed the sea.",
      "Escort the convoy.",
      "The aid convoy."],
      note:"受护送的编队。" }],
    syn:["escort"], ant:[], synDiff:"" },

  { w:"garrison", ipa:"/ˈɡærɪsn/", pos:"n./v.", cat:"军事国防",
    senses:[{ def:"驻军；卫戍", ex:["The garrison held the fort.",
      "Garrison the town.",
      "A weak garrison."],
      note:"常驻防守部队。" }],
    syn:["post","station"], ant:[], synDiff:"" },

  { w:"armistice", ipa:"/ˈɑːmɪstɪs/", pos:"n.", cat:"军事国防",
    senses:[{ def:"停战（协定）", ex:["An armistice ended the war.",
      "Sign an armistice.",
      "The armistice held."],
      note:"暂停敌对；≠ peace treaty（和约）。" }],
    syn:["ceasefire"], ant:["war"], synDiff:"armistice 正式停战；ceasefire 交火暂停。" },

  { w:"morale", ipa:"/məˈrɑːl/", pos:"n.", cat:"军事国防",
    senses:[{ def:"士气", ex:["Morale is low.",
      "Boost troop morale.",
      "Morale decided the battle."],
      note:"斗志；也用于民间。" }],
    syn:["spirit"], ant:["despair"], synDiff:"" },

  { w:"kinetic", ipa:"/kɪˈnetɪk/", pos:"adj.", cat:"军事国防",
    senses:[{ def:"（武力）实弹/动能的", ex:["A kinetic strike.",
      "Shift from cyber to kinetic.",
      "Kinetic action."],
      note:"与‘非动能’（网络/经济）相对。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"asymmetric", ipa:"/ˌeɪsɪˈmetrɪk/", pos:"adj.", cat:"军事国防",
    senses:[{ def:"不对称的（ warfare）", ex:["Asymmetric warfare favours the weak.",
      "An asymmetric threat.",
      "Asymmetric tactics."],
      note:"弱对强的非常规战。" }],
    syn:[], ant:["symmetric"], synDiff:"" },

  { w:"reconnaissance", ipa:"/rɪˈkɒnɪsns/", pos:"n.", cat:"军事国防",
    senses:[{ def:"侦察", ex:["Send a reconnaissance drone.",
      "Aerial reconnaissance.",
      "The reconnaissance found the camp."],
      note:"侦察（简写 recce）。" }],
    syn:["scouting"], ant:[], synDiff:"" },

  { w:"logistics", ipa:"/ləˈdʒɪstɪks/", pos:"n.", cat:"军事国防",
    senses:[{ def:"后勤；物流", ex:["Logistics won the war.",
      "Fix the supply logistics.",
      "Military logistics."],
      note:"补给调动；也通用物流。" }],
    syn:["supply"], ant:[], synDiff:"" },

  { w:"decoy", ipa:"/ˈdiːkɔɪ/", pos:"n.", cat:"军事国防",
    senses:[{ def:"诱饵", ex:["Use a decoy to mislead.",
      "The decoy drew fire.",
      "A radar decoy."],
      note:"迷惑敌方之物。" }],
    syn:["lure"], ant:[], synDiff:"" },

  { w:"bunker", ipa:"/ˈbʌŋkə/", pos:"n.", cat:"军事国防",
    senses:[{ def:"地堡；掩体", ex:["They hid in the bunker.",
      "A concrete bunker.",
      "Storm the bunker."],
      note:"防御工事；也指高尔夫沙坑。" }],
    syn:["shelter"], ant:[], synDiff:"" },

  { w:"blockade", ipa:"/blɒˈkeɪd/", pos:"n./v.", cat:"军事国防",
    senses:[{ def:"封锁", ex:["A naval blockade.",
      "Blockade the port.",
      "Lift the blockade."],
      note:"阻断进出。" }],
    syn:["seal"], ant:["open"], synDiff:"" },

  { w:"artillery", ipa:"/ɑːˈtɪləri/", pos:"n.", cat:"军事国防",
    senses:[{ def:"炮兵；火炮", ex:["The artillery shelled the ridge.",
      "Move the artillery.",
      "Artillery support."],
      note:"重型火炮部队。" }],
    syn:["guns"], ant:[], synDiff:"" },

  { w:"deploy", ipa:"/dɪˈplɔɪ/", pos:"v.", cat:"军事国防",
    senses:[{ def:"部署", ex:["Deploy the troops.",
      "Deploy the missile.",
      "Deploy assets fast."],
      note:"调配到位；也用于软件发布。" }],
    syn:["station","dispatch"], ant:[], synDiff:"" },

  { w:"besiege", ipa:"/bɪˈsiːdʒ/", pos:"v.", cat:"军事国防",
    senses:[{ def:"围困；包围", ex:["They besieged the city.",
      "The fort was besieged.",
      "Besiege the enemy."],
      note:"长期围城；也喻‘涌入’。" }],
    syn:["surround","beset"], ant:[], synDiff:"besiege 军事围城；beset 困境缠身。" },

  { w:"munitions", ipa:"/mjuˈnɪʃnz/", pos:"n.", cat:"军事国防",
    senses:[{ def:"军火；弹药", ex:["Ship the munitions.",
      "Munitions ran low.",
      "A munitions depot."],
      note:"武器弹药统称。" }],
    syn:["ammunition"], ant:[], synDiff:"" },

  { w:"frontline", ipa:"/ˈfrʌntlaɪn/", pos:"n./adj.", cat:"军事国防",
    senses:[{ def:"前线", ex:["He served on the frontline.",
      "Frontline units.",
      "The frontline shifted."],
      note:"作战最前沿；也喻一线。" }],
    syn:["front"], ant:["rear"], synDiff:"" },

  { w:"espionage", ipa:"/ˈespiənɑːʒ/", pos:"n.", cat:"军事国防",
    senses:[{ def:"间谍活动", ex:["Espionage hurt the state.",
      "Charge him with espionage.",
      "Industrial espionage."],
      note:"间谍；spy 同源。" }],
    syn:["spying"], ant:[], synDiff:"" },

  { w:"demobilise", ipa:"/diːˈməʊbəlaɪz/", pos:"v.", cat:"军事国防",
    senses:[{ def:"复员；遣散", ex:["Demobilise the army.",
      "After the war, demobilise.",
      "Troops were demobilised."],
      note:"解散军队回民间。" }],
    syn:["stand down"], ant:["mobilise"], synDiff:"" },

  { w:"salvo", ipa:"/ˈsælvəʊ/", pos:"n.", cat:"军事国防",
    senses:[{ def:"齐射；齐发", ex:["A salvo of shells.",
      "The battery fired a salvo.",
      "A salvo of applause."],
      note:"同时多发；也喻‘一阵’。" }],
    syn:["volley"], ant:[], synDiff:"" },

  { w:"warhead", ipa:"/ˈwɔːhed/", pos:"n.", cat:"军事国防",
    senses:[{ def:"弹头", ex:["A nuclear warhead.",
      "The warhead detonated.",
      "Fit the warhead."],
      note:"导弹前端战斗部。" }],
    syn:[], ant:[], synDiff:"" },

  // ============== 新增：体育 ==============
  { w:"offside", ipa:"/ˌɒfˈsaɪd/", pos:"adj./n.", cat:"体育",
    senses:[{ def:"（足球等）越位", ex:["The goal was offside.",
      "Flag for offside.",
      "He was caught offside."],
      note:"进攻方接球位置违规。" }],
    syn:[], ant:["onside"], synDiff:"" },

  { w:"dribble", ipa:"/ˈdrɪbl/", pos:"v.", cat:"体育",
    senses:[{ def:"（篮球/足球）运球", ex:["Dribble past the defender.",
      "He dribbled up the wing.",
      "Dribble the ball."],
      note:"带球推进。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"sprint", ipa:"/sprɪnt/", pos:"n./v.", cat:"体育",
    senses:[{ def:"短跑；冲刺", ex:["A 100m sprint.",
      "Sprint to the line.",
      "The final sprint."],
      note:"全力短距跑。" }],
    syn:["dash"], ant:["jog"], synDiff:"sprint 全力冲刺；dash 快速短跑。" },

  { w:"backhand", ipa:"/ˈbækhænd/", pos:"n./adj.", cat:"体育",
    senses:[{ def:"反手（击球）", ex:["A crisp backhand.",
      "She hit a backhand.",
      "The backhand winner."],
      note:"网球/乒乓反手。" }],
    syn:[], ant:["forehand"], synDiff:"" },

  { w:"forehand", ipa:"/ˈfɔːhænd/", pos:"n.", cat:"体育",
    senses:[{ def:"正手", ex:["A powerful forehand.",
      "He sliced the forehand.",
      "The forehand cross."],
      note:"正手击球。" }],
    syn:[], ant:["backhand"], synDiff:"" },

  { w:"set piece", ipa:"/ˈset piːs/", pos:"n.", cat:"体育",
    senses:[{ def:"（足球）定位球战术", ex:["A clever set piece.",
      "Score from a set piece.",
      "Rehearse the set piece."],
      note:"任意球/角球套路。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"hat-trick", ipa:"/ˈhæt trɪk/", pos:"n.", cat:"体育",
    senses:[{ def:"（足球）帽子戏法（独进3球）", ex:["He scored a hat-trick.",
      "A hat-trick in ten minutes.",
      "The hat-trick won it."],
      note:"单场三球；也泛指三连。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"peloton", ipa:"/ˈpelətɒn/", pos:"n.", cat:"体育",
    senses:[{ def:"（自行车赛）主集团", ex:["The peloton broke up.",
      "He sat in the peloton.",
      "The peloton surged."],
      note:"大部队；环法术语。" }],
    syn:["pack"], ant:[], synDiff:"" },

  { w:"relay", ipa:"/ˈriːleɪ/", pos:"n.", cat:"体育",
    senses:[{ def:"接力；接力赛", ex:["A 4x100m relay.",
      "Run the relay leg.",
      "The relay team."],
      note:"交接棒项目。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"podium", ipa:"/ˈpəʊdiəm/", pos:"n.", cat:"体育",
    senses:[{ def:"领奖台", ex:["He reached the podium.",
      "A podium finish.",
      "Step on the podium."],
      note:"前三等奖台。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"free throw", ipa:"/ˈfriː θrəʊ/", pos:"n.", cat:"体育",
    senses:[{ def:"（篮球）罚球", ex:["Sink the free throw.",
      "Two free throws.",
      "Miss the free throw."],
      note:"无人防守的罚球。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"smash", ipa:"/smæʃ/", pos:"n./v.", cat:"体育",
    senses:[{ def:"（网球/羽球）扣杀", ex:["A thunderous smash.",
      "He smashed it down.",
      "The smash won the point."],
      note:"高压扣杀。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"marathon", ipa:"/ˈmærəθən/", pos:"n.", cat:"体育",
    senses:[{ def:"马拉松", ex:["Run a marathon.",
      "The marathon tested him.",
      "A marathon of meetings."],
      note:"42.195km；也喻‘漫长’。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"aggregate", ipa:"/ˈæɡrɪɡət/", pos:"n./adj.", cat:"体育",
    senses:[{ def:"（两回合）总比分", ex:["Win on aggregate.",
      "The aggregate was 5-3.",
      "Aggregate score."],
      note:"主客场合计。" }],
    syn:["total"], ant:[], synDiff:"" },

  { w:"penalty", ipa:"/ˈpenəlti/", pos:"n.", cat:"体育",
    senses:[{ def:"点球；罚则", ex:["A penalty in the box.",
      "Miss the penalty.",
      "The penalty was harsh."],
      note:"犯规判罚；足球点球。" }],
    syn:["foul shot"], ant:[], synDiff:"" },

  { w:"heat", ipa:"/hiːt/", pos:"n.", cat:"体育",
    senses:[{ def:"（预赛）小组赛；热", ex:["Win the heat.",
      "The first heat.",
      "Advance from the heat."],
      note:"淘汰赛前的轮次。" }],
    syn:["qualifier"], ant:["final"], synDiff:"" },

  { w:"slider", ipa:"/ˈslaɪdə/", pos:"n.", cat:"体育",
    senses:[{ def:"（棒球）滑球；滑板者", ex:["Throw a slider.",
      "The slider broke late.",
      "A rail slider."],
      note:"棒球横向变化球。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"rally", ipa:"/ˈræli/", pos:"n./v.", cat:"体育",
    senses:[{ def:"（网球）对拉；集会", ex:["A long rally.",
      "They rallied from 0-2.",
      "The rally ended."],
      note:"来回对打；也‘重振’。" }],
    syn:["exchange"], ant:[], synDiff:"" },

  { w:"teammate", ipa:"/ˈtiːmmeɪt/", pos:"n.", cat:"体育",
    senses:[{ def:"队友", ex:["Trust your teammate.",
      "A selfless teammate.",
      "He thanked his teammates."],
      note:"同队伙伴。" }],
    syn:["partner"], ant:["opponent"], synDiff:"" },

  { w:"lane", ipa:"/leɪn/", pos:"n.", cat:"体育",
    senses:[{ def:"泳道；赛道；车道", ex:["Stay in your lane.",
      "Lane four.",
      "Switch lanes."],
      note:"分道线内区域。" }],
    syn:["track"], ant:[], synDiff:"" },

  { w:"fixture", ipa:"/ˈfɪkstʃə/", pos:"n.", cat:"体育",
    senses:[{ def:"（赛程）固定比赛", ex:["A tough fixture.",
      "The fixture list.",
      "Postpone the fixture."],
      note:"既定赛事。" }],
    syn:["match","game"], ant:[], synDiff:"" },

  { w:"substitution", ipa:"/ˌsʌbstɪˈtjuːʃn/", pos:"n.", cat:"体育",
    senses:[{ def:"换人", ex:["A late substitution.",
      "Make a substitution.",
      "The substitution changed the game."],
      note:"替补上场。" }],
    syn:["swap"], ant:[], synDiff:"" },

  { w:"tackle", ipa:"/ˈtækl/", pos:"v./n.", cat:"体育",
    senses:[{ def:"（橄榄/足球）抢断；铲球", ex:["Tackle the runner.",
      "A clean tackle.",
      "He was tackled."],
      note:"阻截持球者。" }],
    syn:[], ant:[], synDiff:"" },

  // ============== 新增：游戏 ==============
  { w:"NPC", ipa:"/ˌen piː ˈsiː/", pos:"n.", cat:"游戏",
    senses:[{ def:"非玩家角色", ex:["The NPC gave a quest.",
      "Talk to the NPC.",
      "An NPC blocks the path."],
      note:"non-player character；由 AI 控制。" }],
    syn:[], ant:["player"], synDiff:"" },

  { w:"spawn", ipa:"/spɔːn/", pos:"v.", cat:"游戏",
    senses:[{ def:"生成；刷出", ex:["Enemies spawn at night.",
      "Spawn the item.",
      "The boss spawned."],
      note:"怪物/物件出现。" }],
    syn:["appear"], ant:[], synDiff:"" },

  { w:"loot", ipa:"/luːt/", pos:"n./v.", cat:"游戏",
    senses:[{ def:"战利品；拾取", ex:["Grab the loot.",
      "Loot the chest.",
      "Rare loot dropped."],
      note:"掉落物；也泛指掠夺。" }],
    syn:["plunder","drop"], ant:[], synDiff:"" },

  { w:"respawn", ipa:"/riːˈspɔːn/", pos:"v.", cat:"游戏",
    senses:[{ def:"复活；重生", ex:["You respawn at base.",
      "Respawn after death.",
      "The timer to respawn."],
      note:"死亡后重新出现。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"aggro", ipa:"/ˈæɡrəʊ/", pos:"n./v.", cat:"游戏",
    senses:[{ def:"仇恨；引怪", ex:["Don’t pull aggro.",
      "The tank holds aggro.",
      "He aggroed the camp."],
      note:"aggravation 缩写；敌意/嘲讽值。" }],
    syn:["threat","enmity"], ant:[], synDiff:"" },

  { w:"grind", ipa:"/ɡraɪnd/", pos:"n./v.", cat:"游戏",
    senses:[{ def:"刷（重复练级）", ex:["Grind for levels.",
      "The daily grind.",
      "Grind the same boss."],
      note:"枯燥重复以获取资源。" }],
    syn:["farm"], ant:[], synDiff:"grind 偏重复刷；farm 偏刷资源。" },

  { w:"buff", ipa:"/bʌf/", pos:"n./v.", cat:"游戏",
    senses:[{ def:"增益（效果）", ex:["A damage buff.",
      "Buff the ally.",
      "The buff expired."],
      note:"正面状态；反义 nerf/debuff。" }],
    syn:["boost"], ant:["debuff","nerf"], synDiff:"buff 增强；nerf 削弱。" },

  { w:"debuff", ipa:"/diːˈbʌf/", pos:"n.", cat:"游戏",
    senses:[{ def:"减益（负面状态）", ex:["A slow debuff.",
      "Cleansed the debuff.",
      "The debuff lingers."],
      note:"负面效果；反义 buff。" }],
    syn:["penalty"], ant:["buff"], synDiff:"" },

  { w:"mob", ipa:"/mɒb/", pos:"n.", cat:"游戏",
    senses:[{ def:"（成群的）怪物", ex:["A mob ambushed us.",
      "Pull one mob at a time.",
      "The mob respawned."],
      note:"mobile object 缩写；敌群。" }],
    syn:["enemy"], ant:[], synDiff:"" },

  { w:"quest", ipa:"/kwest/", pos:"n.", cat:"游戏",
    senses:[{ def:"任务；支线", ex:["Accept the quest.",
      "A side quest.",
      "Finish the main quest."],
      note:"游戏目标线。" }],
    syn:["mission"], ant:[], synDiff:"" },

  { w:"camp", ipa:"/kæmp/", pos:"v.", cat:"游戏",
    senses:[{ def:"蹲点；守（刷怪点）", ex:["Camp the spawn.",
      "They camped the boss.",
      "Don’t camp the lane."],
      note:"长时间占据某点。" }],
    syn:["wait"], ant:[], synDiff:"" },

  { w:"meta", ipa:"/ˈmetə/", pos:"n./adj.", cat:"游戏",
    senses:[{ def:"版本强势套路", ex:["The current meta.",
      "A meta pick.",
      "The meta shifted."],
      note:"most effective tactics available。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"patch", ipa:"/pætʃ/", pos:"n./v.", cat:"游戏",
    senses:[{ def:"补丁；更新", ex:["A new patch nerfed him.",
      "Patch the bug.",
      "Wait for the patch."],
      note:"版本更新（常调整平衡）。" }],
    syn:["update"], ant:[], synDiff:"" },

  { w:"PvP", ipa:"/ˌpiː viː ˈpiː/", pos:"n.", cat:"游戏",
    senses:[{ def:"玩家对战", ex:["PvP mode opened.",
      "Win at PvP.",
      "PvP versus PvE."],
      note:"player versus player；PvE 打环境。" }],
    syn:[], ant:["PvE"], synDiff:"" },

  { w:"PvE", ipa:"/ˌpiː viː ˈiː/", pos:"n.", cat:"游戏",
    senses:[{ def:"玩家对环境（打怪）", ex:["A PvE raid.",
      "PvE content.",
      "PvE vs PvP."],
      note:"player versus environment。" }],
    syn:[], ant:["PvP"], synDiff:"" },

  { w:"lag", ipa:"/læɡ/", pos:"n./v.", cat:"游戏",
    senses:[{ def:"延迟；卡顿", ex:["The lag cost the kill.",
      "Lag spiked.",
      "Reduce lag."],
      note:"网络/帧延迟。" }],
    syn:["delay"], ant:[], synDiff:"" },

  { w:"horde", ipa:"/hɔːd/", pos:"n.", cat:"游戏",
    senses:[{ def:"（大群）怪/兵", ex:["A horde swarmed in.",
      "Defend against the horde.",
      "The undead horde."],
      note:"成群的敌。" }],
    syn:["swarm","mob"], ant:[], synDiff:"" },

  { w:"rng", ipa:"/ˌɑːr en ˈdʒiː/", pos:"n.", cat:"游戏",
    senses:[{ def:"随机性（random number generator）", ex:["The drop is pure rng.",
      "RNG decided the fight.",
      "Bad rng again."],
      note:"运气成分。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"cooldown", ipa:"/ˈkuːldaʊn/", pos:"n.", cat:"游戏",
    senses:[{ def:"冷却时间", ex:["The skill is on cooldown.",
      "Wait for cooldown.",
      "A short cooldown."],
      note:"技能再次可用的等待。" }],
    syn:["CD"], ant:[], synDiff:"" },

  { w:"grief", ipa:"/ɡriːf/", pos:"v.", cat:"游戏",
    senses:[{ def:"恶意破坏（队友）", ex:["He griefed the team.",
      "Griefing is banned.",
      "A griefer ruined it."],
      note:"故意坑害（源于 grief 悲伤，游戏贬用）。" }],
    syn:["sabotage"], ant:[], synDiff:"" },

  { w:"build", ipa:"/bɪld/", pos:"n.", cat:"游戏",
    senses:[{ def:"（角色）配装/加点", ex:["A tank build.",
      "Optimise the build.",
      "A glass-cannon build."],
      note:"属性/装备方案。" }],
    syn:[], ant:[], synDiff:"" },

  // ============== 新增：媒体影视 ==============
  { w:"franchise", ipa:"/ˈfræntʃaɪz/", pos:"n.", cat:"媒体影视",
    senses:[{ def:"（影视）系列 IP；特许经营", ex:["A film franchise.",
      "The franchise spans ten films.",
      "Expand the franchise."],
      note:"漫威式系列；也指加盟经营。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"cinematography", ipa:"/ˌsɪnəməˈtɒɡrəfi/", pos:"n.", cat:"媒体影视",
    senses:[{ def:"摄影（艺术）", ex:["The cinematography is stunning.",
      "Award for cinematography.",
      "The film’s cinematography."],
      note:"电影画面手法。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"diegetic", ipa:"/daɪəˈdʒetɪk/", pos:"adj.", cat:"媒体影视",
    senses:[{ def:"（声音）故事内的", ex:["Diegetic music from the radio.",
      "A diegetic sound.",
      "Non-diegetic score vs diegetic."],
      note:"画内声（角色能听见）；non-diegetic 配乐角色听不见。" }],
    syn:[], ant:["non-diegetic"], synDiff:"" },

  { w:"jump cut", ipa:"/ˈdʒʌmp kʌt/", pos:"n.", cat:"媒体影视",
    senses:[{ def:"跳切", ex:["A jarring jump cut.",
      "Use a jump cut for pace.",
      "The jump cut broke flow."],
      note:"打破连续的剪辑。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"close-up", ipa:"/ˈkləʊs ʌp/", pos:"n.", cat:"媒体影视",
    senses:[{ def:"特写", ex:["A close-up of the eyes.",
      "Cut to a close-up.",
      "The close-up lingers."],
      note:"近距镜头。" }],
    syn:[], ant:["wide shot"], synDiff:"" },

  { w:"voiceover", ipa:"/ˈvɔɪsəʊvə/", pos:"n.", cat:"媒体影视",
    senses:[{ def:"画外音", ex:["A sombre voiceover.",
      "Add a voiceover.",
      "The voiceover narrates."],
      note:"VO；幕后旁白。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"binge-watch", ipa:"/ˈbɪndʒ wɒtʃ/", pos:"v.", cat:"媒体影视",
    senses:[{ def:"刷剧", ex:["Binge-watch the season.",
      "They binge-watched all night.",
      "Binge-watch responsibly."],
      note:"连续观看多集。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"spin-off", ipa:"/ˈspɪn ɒf/", pos:"n.", cat:"媒体影视",
    senses:[{ def:"衍生剧/衍生作", ex:["A spin-off of the show.",
      "The spin-off premiered.",
      "A profitable spin-off."],
      note:"从原作衍生的新作。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"cameo", ipa:"/ˈkæmiəʊ/", pos:"n.", cat:"媒体影视",
    senses:[{ def:"客串", ex:["A celebrity cameo.",
      "He made a cameo.",
      "The cameo delighted fans."],
      note:"名人短暂现身。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"showrunner", ipa:"/ˈʃəʊrʌnə/", pos:"n.", cat:"媒体影视",
    senses:[{ def:"（剧集）主创/总制片", ex:["The showrunner quit.",
      "A visionary showrunner.",
      "The showrunner shaped it."],
      note:"美剧掌舵人。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"reenact", ipa:"/ˌriːɪˈnækt/", pos:"v.", cat:"媒体影视",
    senses:[{ def:"翻拍；重现", ex:["Reenact the battle.",
      "The film reenacts events.",
      "Reenact the scene."],
      note:"重演史实/情节。" }],
    syn:["restage"], ant:[], synDiff:"" },

  { w:"anime", ipa:"/ˈænɪmeɪ/", pos:"n.", cat:"媒体影视",
    senses:[{ def:"日本动画", ex:["Anime is huge worldwide.",
      "Watch the anime.",
      "The anime adapts the manga."],
      note:"日源词；动画风格。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"premiere", ipa:"/ˈpremieə/", pos:"n./v.", cat:"媒体影视",
    senses:[{ def:"首映", ex:["The premiere sold out.",
      "Premiere the film.",
      "A star-studded premiere."],
      note:"首次公映。" }],
    syn:["opening"], ant:[], synDiff:"" },

  { w:"documentary", ipa:"/ˌdɒkjuˈmentri/", pos:"n./adj.", cat:"媒体影视",
    senses:[{ def:"纪录片", ex:["A climate documentary.",
      "Shoot a documentary.",
      "The documentary won."],
      note:"纪实影片。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"trailer", ipa:"/ˈtreɪlə/", pos:"n.", cat:"媒体影视",
    senses:[{ def:"预告片", ex:["Watch the trailer.",
      "The trailer dropped.",
      "Cut a tight trailer."],
      note:"上映前短片。" }],
    syn:["teaser"], ant:[], synDiff:"trailer 正式预告；teaser 先导 short。" },

  { w:"cast", ipa:"/kɑːst/", pos:"n./v.", cat:"媒体影视",
    senses:[{ def:"演员阵容；选角", ex:["A stellar cast.",
      "Cast the lead.",
      "The cast reunited."],
      note:"全体演员。" }],
    syn:["actors"], ant:[], synDiff:"" },

  { w:"rating", ipa:"/ˈreɪtɪŋ/", pos:"n.", cat:"媒体影视",
    senses:[{ def:"分级；收视/评分", ex:["A PG rating.",
      "The show’s rating fell.",
      "High IMDb rating."],
      note:"年龄分级或评价分。" }],
    syn:["score","grade"], ant:[], synDiff:"" },

  { w:"reenactment", ipa:"/ˌriːɪˈnæktmənt/", pos:"n.", cat:"媒体影视",
    senses:[{ def:"重演（活动）", ex:["A civil-war reenactment.",
      "The reenactment drew crowds.",
      "Historical reenactment."],
      note:"史实再现表演。" }],
    syn:[], ant:[], synDiff:"" },

  { w:"streaming", ipa:"/ˈstriːmɪŋ/", pos:"n./adj.", cat:"媒体影视",
    senses:[{ def:"流媒体（播放）", ex:["Streaming changed TV.",
      "A streaming platform.",
      "Watch via streaming."],
      note:"在线即时播放。" }],
    syn:[], ant:[], synDiff:"" }
];
