// 词汇复习站 · 数据文件
// 每条词结构：
//   w   英文词  ipa 音标  pos 词性  cat 类别
//   senses: [{ def 释义, ex [≥3例句], note 注意点 }]
//   syn 近义词[]  ant 反义词[]  synDiff 近义词差别
// 想加词：在 WORDS 数组里照格式追加一条即可。
const WORDS = [
  // ---------------- 学术写作 ----------------
  { w:"postulate", ipa:"/ˈpɒstʃəleɪt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"假定；假设（作为推理或理论起点的命题，比 assume 更学术、更正式）",
      ex:["The theory postulates a direct link between diet and mood.",
          "It is postulated that the universe has been expanding since the Big Bang.",
          "We postulate a common ancestor for these two species."],
      note:"后常接 that 从句；名词 postulate 指‘公设 / 假定’，哲学、数学、理科高频。" }],
    syn:["assume","hypothesize","presuppose"], ant:["disprove","refute"],
    synDiff:"assume 最日常、把握最弱；hypothesize 强调基于有限证据的科学推测；postulate 多用于理论体系的逻辑起点，语气最正式。" },

  { w:"hypothesize", ipa:"/haɪˈpɒθəsaɪz/", pos:"v.", cat:"学术写作",
    senses:[{ def:"提出假说；推测（基于不完整证据，待检验）",
      ex:["Researchers hypothesize that sleep loss impairs memory consolidation.",
          "It was hypothesized that the drug would reduce inflammation.",
          "We hypothesize a causal relationship, not merely a correlation."],
      note:"名词 hypothesis（假说）；形容词 hypothetical（假设的）。常与 test / confirm / reject 搭配。" }],
    syn:["postulate","speculate","surmise"], ant:["confirm","verify"],
    synDiff:"speculate 更偏‘猜测、泛泛推想’；hypothesize 是科研语境下‘可检验的假设’；postulate 比 hypothesize 更正式、更偏理论前提。" },

  { w:"corroborate", ipa:"/kəˈrɒbəreɪt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"佐证；证实（用独立证据支撑已有结论）",
      ex:["Subsequent experiments corroborated the initial findings.",
          "Witness testimony corroborated the defendant's alibi.",
          "The data corroborate our earlier claim about rising temperatures."],
      note:"及物，宾语多为 finding / claim / theory；名词 corroboration，形容词 corroborating。" }],
    syn:["confirm","substantiate","verify"], ant:["contradict","refute"],
    synDiff:"confirm 泛指确认；substantiate 强调提供实质证据支撑主张；corroborate 特指‘另一来源的独立证据’与原有证据相互印证。" },

  { w:"refute", ipa:"/rɪˈfjuːt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"驳斥；推翻（用证据否定某观点）",
      ex:["These results refute the longstanding theory proposed by Smith (2010).",
          "The author refutes the claim that technology reduces employment.",
          "New fossils refute the idea that birds evolved later than mammals."],
      note:"注意：refute = 用证据反驳（不是 merely deny）。名词 refutation。" }],
    syn:["rebut","disprove","contradict"], ant:["support","corroborate"],
    synDiff:"rebut 多用于辩论/法律当场反驳；disprove 强调证明为假；refute 强调以论证+证据系统性推翻。" },

  { w:"elucidate", ipa:"/iˈluːsɪdeɪt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"阐明；解释清楚（把复杂、晦涩的概念讲明白）",
      ex:["The diagram elucidates the mechanism underlying cell division.",
          "Chapter 3 elucidates the difference between the two models.",
          "She elucidated her position with several historical examples."],
      note:"正式书面；名词 elucidation。比 explain 更学术。" }],
    syn:["clarify","explain","illuminate"], ant:["obscure","confuse"],
    synDiff:"clarify 侧重‘消除歧义’；illuminate 侧重‘照亮、使人领悟’；elucidate 侧重对复杂理论的细致剖析，最正式。" },

  { w:"extrapolate", ipa:"/ɪkˈstræpəleɪt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"外推；推断（由已知数据推测未知情况）",
      ex:["We can extrapolate from these trends to predict future demand.",
          "Do not extrapolate findings from mice to humans too readily.",
          "The chart lets us extrapolate the population in 2050."],
      note:"常与 from / to 搭配；名词 extrapolation。注意外推有风险，论文中宜用谨慎语气。" }],
    syn:["infer","project","deduce"], ant:[],
    synDiff:"infer 由证据推结论；project 多指‘预测’数值；extrapolate 特指沿已有趋势延伸到范围外。" },

  { w:"underscore", ipa:"/ˌʌndəˈskɔː(r)/", pos:"v.", cat:"学术写作",
    senses:[{ def:"强调；突出（比 emphasize 更书面）",
      ex:["These findings underscore the importance of early intervention.",
          "The crisis underscores how fragile global supply chains are.",
          "His silence underscored his disagreement."],
      note:"及物，宾语多为 importance / need / fact。亦可作名词 underscore（下划线）。" }],
    syn:["emphasize","highlight","stress"], ant:["understate","minimize"],
    synDiff:"highlight 像‘高亮’般凸显一点；stress 语气更重带‘施压’感；underscore 书面对重要性做低调而有力的强调。" },

  { w:"substantiate", ipa:"/səbˈstænʃieɪt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"证实；为（说法）提供实质证据",
      ex:["There is insufficient evidence to substantiate this claim.",
          "He substantiated his argument with court records.",
          "The allegations were never substantiated."],
      note:"宾语多为 claim / allegation / charge；名词 substantiation。" }],
    syn:["corroborate","confirm","verify"], ant:["disprove","refute"],
    synDiff:"confirm 泛确认；corroborate 强调‘另一独立来源印证’；substantiate 强调给主张‘填充实质证据’，常用在指控/声明语境。" },

  { w:"mitigate", ipa:"/ˈmɪtɪɡeɪt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"减轻；缓和（负面影响的程度）",
      ex:["Policies were introduced to mitigate the impact of climate change.",
          "Medicine can mitigate but not cure the symptoms.",
          "Steps were taken to mitigate the risk of flooding."],
      note:"宾语多为 impact / effect / risk / damage；名词 mitigation。勿与 militate（影响、起作用）混淆。" }],
    syn:["alleviate","lessen","diminish"], ant:["exacerbate","aggravate"],
    synDiff:"alleviate 多用于痛苦/负担；lessen 最通用；mitigate 书面、多用于风险/损害等负面事物。" },

  { w:"exacerbate", ipa:"/ɪɡˈzæsəbeɪt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"加剧；使恶化（负面情况）",
      ex:["Poor diet can exacerbate existing health conditions.",
          "The policy exacerbated rather than solved inequality.",
          "Stress exacerbates the symptoms of the disease."],
      note:"宾语多为 problem / condition / tension；名词 exacerbation。与 aggravate 近义。" }],
    syn:["aggravate","worsen","intensify"], ant:["mitigate","alleviate"],
    synDiff:"worsen 最通用；aggravate 可指‘激怒人’；exacerbate 最正式，专指使负面局势更糟。" },

  { w:"fluctuate", ipa:"/ˈflʌktʃueɪt/", pos:"v.", cat:"学术写作",
    senses:[{ def:"波动；起伏不定",
      ex:["Prices fluctuated wildly throughout the decade.",
          "Body temperature fluctuates slightly during the day.",
          "Public support for the policy fluctuated between 40% and 55%."],
      note:"名词 fluctuation；常与 widely / sharply / between A and B 搭配。" }],
    syn:["vary","oscillate","swing"], ant:["stabilize","steady"],
    synDiff:"vary 泛指变化；oscillate 多指在两极值间摆动（也用于观点）；fluctuate 强调无规律上下波动（数据、价格）。" },

  { w:"parameter", ipa:"/pəˈræmɪtə(r)/", pos:"n.", cat:"学术写作",
    senses:[{ def:"参数；界限（决定系统行为的可变因素）",
      ex:["Several key parameters were adjusted during the simulation.",
          "We must work within the parameters of the law.",
          "The model has too many unknown parameters."],
      note:"常用复数 parameters；口语中也指‘范围 / 限制’（within the parameters of...）。" }],
    syn:["variable","factor","criterion"], ant:[],
    synDiff:"variable 通用‘变量’；factor 指‘影响因素’；parameter 是模型/系统中的‘可调参数’，更技术化。" },

  { w:"correlation", ipa:"/ˌkɒrəˈleɪʃn/", pos:"n.", cat:"学术写作",
    senses:[{ def:"相关（性）；关联",
      ex:["There is a strong correlation between exercise and mental health.",
          "Correlation does not imply causation.",
          "The study found a positive correlation between the two variables."],
      note:"常接 between A and B；形容词 correlated。务必区分 correlation（相关）与 causation（因果）。" }],
    syn:["connection","link","association"], ant:["independence"],
    synDiff:"link / connection 泛指联系；association 偏统计‘共现’；correlation 是量化‘相关系数’意义上的相关。" },

  { w:"paradigm", ipa:"/ˈpærədaɪm/", pos:"n.", cat:"学术写作",
    senses:[{ def:"范式；典范（一套被广泛接受的理论/方法框架）",
      ex:["The discovery triggered a paradigm shift in physics.",
          "This model offers a new paradigm for understanding memory.",
          "We need a paradigm change in how cities are planned."],
      note:"paradigm shift = 范式转移（库恩《科学革命的结构》）。" }],
    syn:["model","framework","pattern"], ant:[],
    synDiff:"model 指具体模型；framework 指结构框架；paradigm 指一整套‘世界观/方法论’层面的典范，层级最高。" },

  { w:"robust", ipa:"/rəʊˈbʌst/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"稳健的；强健的（结果/方法经得起检验）",
      ex:["The conclusion is robust to changes in the data.",
          "We need a robust statistical method.",
          "A robust immune system resists infection."],
      note:"论文中常说 robust to / against...（对…稳健）。也形容人‘健壮’。" }],
    syn:["sound","sturdy","reliable"], ant:["fragile","weak"],
    synDiff:"sound 指‘合理可靠’（a sound argument）；sturdy 指物理结实；robust 在学术中指‘方法/结论不易被推翻’。" },

  { w:"rigorous", ipa:"/ˈrɪɡərəs/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"严密的；严格的（方法、标准）",
      ex:["The study used a rigorous experimental design.",
          "We applied rigorous quality controls.",
          "His reasoning is rigorous and well-supported."],
      note:"名词 rigour（美 rigor）。形容人‘一丝不苟’也可。" }],
    syn:["strict","meticulous","thorough"], ant:["sloppy","lax"],
    synDiff:"strict 侧重遵守规则严；meticulous 侧重细节精确；rigorous 强调逻辑/方法上的严密无漏洞。" },

  { w:"nuanced", ipa:"/ˈnjuːɑːnst/", pos:"adj.", cat:"学术写作",
    senses:[{ def:"细腻的；有细微差别的",
      ex:["The issue is more nuanced than it appears.",
          "She offered a nuanced analysis of the conflict.",
          "A nuanced view avoids simple right-or-wrong judgments."],
      note:"名词 nuance（细微差别）。常用于批评‘过度简化’。" }],
    syn:["subtle","complicated","refined"], ant:["crude","simplistic"],
    synDiff:"subtle 泛指微妙；complicated 指复杂；nuanced 强调‘包含需要体察的细微层次’，评价性偏正面。" },

  { w:"nevertheless", ipa:"/ˌnevəðəˈles/", pos:"adv.", cat:"学术写作",
    senses:[{ def:"然而；尽管如此（转折连接词）",
      ex:["The data are limited; nevertheless, the trend is clear.",
          "It is costly. Nevertheless, it is necessary.",
          "He was tired; nevertheless, he finished the work."],
      note:"正式，功能同 however / nonetheless，但更强调‘让步后仍成立’。" }],
    syn:["however","nonetheless","yet"], ant:[],
    synDiff:"however 最通用；nonetheless 语气略轻；nevertheless 在学术写作中表‘承认前述、仍坚持后述’的强转折。" },

  { w:"consequently", ipa:"/ˈkɒnsɪkwəntli/", pos:"adv.", cat:"学术写作",
    senses:[{ def:"因此；所以（表因果）",
      ex:["Demand fell; consequently, prices dropped.",
          "The bridge was closed; consequently, traffic worsened.",
          "He missed the deadline; consequently, the project was delayed."],
      note:"比 so 正式；近 therefore，但 consequently 更强调‘自然导致的结果’。" }],
    syn:["therefore","thus","hence"], ant:[],
    synDiff:"therefore 通用因果；thus 可表‘如此一来’也用于数学；hence 较简洁书面；consequently 偏‘顺理成章的结果’。" },

  // ---------------- 英语文学 ----------------
  { w:"metaphor", ipa:"/ˈmetəfə(r)/", pos:"n.", cat:"英语文学",
    senses:[{ def:"暗喻（直接把 A 说成 B，不用 like/as）",
      ex:["'Time is a thief' is a metaphor, not a simile.",
          "The poet uses the sea as a metaphor for the unconscious.",
          "Her voice was a metaphor for freedom in the novel."],
      note:"区别于 simile（明喻，用 like/as）。动词 metaphorize。" }],
    syn:["simile","analogy","figure of speech"], ant:[],
    synDiff:"simile 明喻（用 like/as）；analogy 类比是说明性比较；metaphor 是文学性直接等同，最凝练。" },

  { w:"irony", ipa:"/ˈaɪrəni/", pos:"n.", cat:"英语文学",
    senses:[{ def:"反讽（言意相反，或事态与预期相悖）",
      ex:["'What lovely weather,' she said, with irony, in the storm.",
          "The irony is that the fire station burned down.",
          "Verbal irony says the opposite of what is meant."],
      note:"分 verbal / situational / dramatic 三类；形容词 ironic。" }],
    syn:["sarcasm","paradox","contradiction"], ant:["sincerity"],
    synDiff:"sarcasm 是带刺的口头反讽（含贬义）；irony 范围更广、可中性甚至悲剧性；paradox 是逻辑上的自相矛盾。" },

  { w:"foil", ipa:"/fɔɪl/", pos:"n.", cat:"英语文学",
    senses:[{ def:"衬托角色（以对比凸显主角特质）",
      ex:["The cowardly friend is a foil to the brave hero.",
          "Her calmness acts as a foil to his agitation.",
          "In the play, the fool is the king's foil."],
      note:"也可作动词 foil = 阻止（The plan was foiled）。文学义专指‘衬托’。" }],
    syn:["contrast","counterpart","antithesis"], ant:[],
    synDiff:"contrast 通用对比；antithesis 是对立（黑vs白）；foil 专指文学中‘用来衬托主角的配角’。" },

  { w:"epiphany", ipa:"/ɪˈpɪfəni/", pos:"n.", cat:"英语文学",
    senses:[{ def:"顿悟（人物突然的领悟，常为转折）",
      ex:["The novel ends with the hero's epiphany about his past.",
          "She had an epiphany that she loved the city.",
          "His epiphany changes the whole meaning of the story."],
      note:"源自宗教‘显现’；在成长小说(bildungsroman)中常见。" }],
    syn:["realization","revelation","insight"], ant:[],
    synDiff:"realization 通用‘意识到’；revelation 强调‘被揭示的真相’；epiphany 特指文学中突然而深刻的顿悟时刻。" },

  { w:"bildungsroman", ipa:"/ˈbɪldʊŋzrəʊmɑːn/", pos:"n.", cat:"英语文学",
    senses:[{ def:"成长小说（记述主人公心理/道德成长）",
      ex:["'Great Expectations' is a classic bildungsroman.",
          "The film is a bildungsroman about a young artist.",
          "Many Victorian novels are bildungsromane (plural)."],
      note:"德语借词，复数 bildungsromane；常写 coming-of-age story。" }],
    syn:["coming-of-age story","apprenticeship novel"], ant:[],
    synDiff:"coming-of-age 是通俗说法；bildungsroman 是文学术语，强调‘教育/修养形成’的成长过程。" },

  // ---------------- 法律与政治 ----------------
  { w:"sovereignty", ipa:"/ˈsɒvrənti/", pos:"n.", cat:"法律政治",
    senses:[{ def:"主权（国家的最高独立权力）",
      ex:["The treaty respects the sovereignty of each member state.",
          "Questions of sovereignty lie at the heart of the conflict.",
          "Popular sovereignty holds that power resides in the people."],
      note:"形容词 sovereign（主权的；君主）。" }],
    syn:["autonomy","independence","authority"], ant:["subjection","dependency"],
    synDiff:"autonomy 指‘自治权’（可小于国家）；independence 指独立状态；sovereignty 是国际法上‘最高、对外独立’的主权。" },

  { w:"ratify", ipa:"/ˈrætɪfaɪ/", pos:"v.", cat:"法律政治",
    senses:[{ def:"批准；正式签署生效（条约、协议）",
      ex:["The senate ratified the trade treaty last year.",
          "The constitution was ratified by a public vote.",
          "The agreement cannot take effect until both sides ratify it."],
      note:"名词 ratification；名词 ratifier。" }],
    syn:["approve","confirm","sanction"], ant:["reject","void"],
    synDiff:"approve 通用批准；sanction 可指‘批准’也可指‘制裁’（看语境）；ratify 专指对条约/宪法等‘正式追认生效’。" },

  { w:"legislation", ipa:"/ˌledʒɪsˈleɪʃn/", pos:"n.", cat:"法律政治",
    senses:[{ def:"立法；法律（总称）",
      ex:["New legislation bans single-use plastics.",
          "The legislation was passed by a narrow margin.",
          "We need legislation to protect gig workers."],
      note:"不可数；动词 legislate；立法者 legislator。" }],
    syn:["law","statute","act"], ant:[],
    synDiff:"law 泛指法律；statute 指成文法条款；legislation 是‘立法行为或成套法规’的总称。" },

  { w:"acquit", ipa:"/əˈkwɪt/", pos:"v.", cat:"法律政治",
    senses:[{ def:"宣判无罪",
      ex:["The jury acquitted him of all charges.",
          "She was acquitted for lack of evidence.",
          "The court acquitted the defendant."],
      note:"多用于刑事；反义 convict。名词 acquittal。" }],
    syn:["clear","exonerate"], ant:["convict","condemn"],
    synDiff:"clear / exonerate 较通用‘洗清’；acquit 是法庭正式‘无罪开释’。" },

  { w:"convict", ipa:"/kənˈvɪkt/", pos:"v.", cat:"法律政治",
    senses:[{ def:"宣判有罪",
      ex:["He was convicted of fraud.",
          "The court convicted her on two counts.",
          "They were convicted and sentenced to prison."],
      note:"名词 /ˈkɒnvɪkt/ 指‘已定罪者’；反义 acquit。" }],
    syn:["find guilty","sentence"], ant:["acquit","exonerate"],
    synDiff:"find guilty 是陪审团‘认定有罪’；convict 是整个‘定罪’动作；sentence 是后续的‘判刑’。" },

  { w:"hegemony", ipa:"/hɪˈdʒeməni/", pos:"n.", cat:"法律政治",
    senses:[{ def:"霸权；支配地位（一国/集团的主导权）",
      ex:["The hegemony of the superpower is weakening.",
          "Cultural hegemony shapes what people accept as normal.",
          "They challenged the region's economic hegemony."],
      note:"形容词 hegemonic。源自希腊，政治/国际关系高频。" }],
    syn:["dominance","supremacy","leadership"], ant:["subordination"],
    synDiff:"dominance 通用‘主导’；supremacy 强调‘至高无上’；hegemony 特指一国对他国/地区的‘领导+控制’式霸权。" },

  { w:"deterrence", ipa:"/dɪˈterəns/", pos:"n.", cat:"法律政治",
    senses:[{ def:"威慑（以报复能力阻止敌对方行动）",
      ex:["Nuclear deterrence prevented direct war between the blocs.",
          "The fine acts as a deterrence to speeding.",
          "Deterrence relies on the threat, not the act."],
      note:"动词 deter；形容词 deterrent（也指‘威慑物/防盗装置’）。" }],
    syn:["prevention","discouragement"], ant:["encouragement"],
    synDiff:"prevention 指‘预防发生’；deterrence 指‘以惩罚/报复的威胁使人不敢做’，军事/外交核心概念。" },

  // ---------------- 医疗与健康 ----------------
  { w:"diagnosis", ipa:"/ˌdaɪəɡˈnəʊsɪs/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"诊断（对病症的判断）",
      ex:["The doctor made a diagnosis of pneumonia.",
          "Early diagnosis improves the chance of recovery.",
          "The diagnosis was confirmed by a blood test."],
      note:"动词 diagnose；复数 diagnoses；反义 prognosis（预后）。" }],
    syn:["identification","detection"], ant:["misdiagnosis"],
    synDiff:"detection 指‘发现疾病存在’；diagnosis 是完整的‘判断是什么病’；prognosis 是‘预后/会怎样’。" },

  { w:"prognosis", ipa:"/prɒɡˈnəʊsɪs/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"预后；对病程与康复的预测",
      ex:["The prognosis is good if treated early.",
          "Doctors gave him a poor prognosis.",
          "The long-term prognosis remains uncertain."],
      note:"复数 prognoses；与 diagnosis（诊断）易混，注意区分。" }],
    syn:["forecast","outlook"], ant:[],
    synDiff:"outlook 通用‘前景’；prognosis 专指医学上‘对疾病走向的预测’。" },

  { w:"chronic", ipa:"/ˈkrɒnɪk/", pos:"adj.", cat:"医疗健康",
    senses:[{ def:"慢性的；长期的（病症持续不愈）",
      ex:["He suffers from chronic back pain.",
          "Chronic stress harms the heart.",
          "Diabetes is a chronic condition."],
      note:"反义 acute（急性的）。也用于贬义‘严重的’（a chronic liar 惯骗）。" }],
    syn:["persistent","long-term","ongoing"], ant:["acute","temporary"],
    synDiff:"persistent 指‘持续存在’；long-term 中性‘长期’；chronic 医学专指‘慢性、迁延不愈’。" },

  { w:"acute", ipa:"/əˈkjuːt/", pos:"adj.", cat:"医疗健康",
    senses:[{ def:"急性的；剧烈的（突然、严重）",
      ex:["She was taken to hospital with acute appendicitis.",
          "The patient felt acute chest pain.",
          "There is an acute shortage of beds."],
      note:"反义 chronic（慢性）。也指‘敏锐’（an acute observer）或‘尖锐’（an acute angle 锐角）。" }],
    syn:["severe","intense","sharp"], ant:["chronic","mild"],
    synDiff:"severe 通用‘严重’；intense 指‘强烈’；acute 医学指‘突发且剧烈/急性’，与 chronic 相对。" },

  { w:"therapy", ipa:"/ˈθerəpi/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"治疗；疗法",
      ex:["She is undergoing physical therapy.",
          "Cognitive therapy helped his anxiety.",
          "Gene therapy is a promising field."],
      note:"复数 therapies；形容词 therapeutic（有疗效的）。" }],
    syn:["treatment","cure","remedy"], ant:[],
    synDiff:"treatment 通用‘治疗’；cure 强调‘治愈’；therapy 多指‘系统性理疗/心理疗法’过程。" },

  { w:"prescription", ipa:"/prɪˈskrɪpʃn/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"处方；处方药",
      ex:["The doctor wrote a prescription for antibiotics.",
          "You need a prescription to buy this medicine.",
          "Fill the prescription at the pharmacy."],
      note:"动词 prescribe；形容词 prescriptive（也指‘规定性的’）。" }],
    syn:["script","order","medication"], ant:[],
    synDiff:"medication 指‘药物本身’；prescription 是‘医生开的方子/凭方取的药’；script 是口语缩写。" },

  { w:"vaccine", ipa:"/ˈvæksiːn/", pos:"n.", cat:"医疗健康",
    senses:[{ def:"疫苗",
      ex:["The vaccine protects against the virus.",
          "She received two doses of the vaccine.",
          "A new vaccine is in clinical trials."],
      note:"动词 vaccinate；名词 vaccination。相关：antibody 抗体，immunity 免疫力。" }],
    syn:["inoculation","immunization"], ant:[],
    synDiff:"inoculation 泛指‘接种’（含疫苗）；immunization 强调‘获得免疫’；vaccine 特指‘疫苗制剂’。" },

  { w:"epidemic", ipa:"/ˌepɪˈdemɪk/", pos:"n./adj.", cat:"医疗健康",
    senses:[{ def:"（疾病）流行；传染高峰",
      ex:["An epidemic of flu swept the city.",
          "Measures slowed the epidemic.",
          "Obesity has become an epidemic in wealthy nations."],
      note:"范围跨地区用 pandemic（大流行）；形容词 endemic 指‘地方性的’。" }],
    syn:["outbreak","pandemic","plague"], ant:["endemic"],
    synDiff:"outbreak 指‘暴发’（事件）；pandemic 是跨国大流行；epidemic 是一国/地区内的流行。" },

  // ---------------- 美食与食品 ----------------
  { w:"avocado", ipa:"/ˌævəˈkɑːdəʊ/", pos:"n.", cat:"美食食品",
    senses:[{ def:"牛油果；鳄梨",
      ex:["I spread avocado on my toast.",
          "Guacamole is made from avocado.",
          "She added avocado to the salad."],
      note:"复数 avocados；也作形容词‘牛油果绿的’。" }],
    syn:["alligator pear"], ant:[],
    synDiff:"alligator pear 是旧称/别称；avocado 是标准名。" },

  { w:"pomegranate", ipa:"/ˈpɒmɪɡrænɪt/", pos:"n.", cat:"美食食品",
    senses:[{ def:"石榴",
      ex:["She squeezed the pomegranate for juice.",
          "The salad was topped with pomegranate seeds.",
          "Pomegranate is rich in antioxidants."],
      note:"籽 edible；皮不可食。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"quinoa", ipa:"/ˈkiːnwɑː/", pos:"n.", cat:"美食食品",
    senses:[{ def:"藜麦（高蛋白谷物）",
      ex:["Quinoa is a good source of protein.",
          "We served quinoa instead of rice.",
          "Boil the quinoa for about fifteen minutes."],
      note:"发音为 KEEN-wah；植物学上非真谷物但常作主食。" }],
    syn:["grain","pseudocereal"], ant:[],
    synDiff:"grain 是谷物统称；quinoa 是具体的高蛋白伪谷物。" },

  { w:"zucchini", ipa:"/zuˈkiːni/", pos:"n.", cat:"美食食品",
    senses:[{ def:"西葫芦（美）； courgette（英）",
      ex:["Slice the zucchini thinly.",
          "We grilled the zucchini with olive oil.",
          "Add diced zucchini to the stir-fry."],
      note:"英式 courgette；复数同形或 zucchini。" }],
    syn:["courgette"], ant:[],
    synDiff:"courgette 是英式说法；zucchini 是美式。" },

  { w:"yogurt", ipa:"/ˈjɒɡət/", pos:"n.", cat:"美食食品",
    senses:[{ def:"酸奶",
      ex:["I eat yogurt for breakfast.",
          "Greek yogurt is thicker than regular yogurt.",
          "The sauce is made with plain yogurt."],
      note:"也拼 yoghurt；可作形容词 yogurt-based。" }],
    syn:["curd"], ant:[],
    synDiff:"curd 多指‘凝乳’（制作环节）；yogurt 是成品酸奶。" },

  // ---------------- 高阶外貌与性格 ----------------
  { w:"magnanimous", ipa:"/mæɡˈnænɪməs/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"宽宏大量的；豁达的",
      ex:["He was magnanimous in victory and thanked his rival.",
          "A magnanimous leader forgives past insults.",
          "She made a magnanimous gesture of reconciliation."],
      note:"名词 magnanimity；勿与 unanimous（一致的）混淆。" }],
    syn:["generous","forgiving","noble"], ant:["petty","mean"],
    synDiff:"generous 通用‘慷慨’；forgiving 侧重‘原谅’；magnanimous 强调‘地位高者不念旧恶’的胸襟，最正式。" },

  { w:"pusillanimous", ipa:"/ˌpjuːsɪˈlænɪməs/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"怯懦的；胆小如鼠的",
      ex:["His pusillanimous refusal to speak up angered them.",
          "A pusillanimous ruler avoids all risk.",
          "Do not be so pusillanimous; state your view."],
      note:"正式、带贬义；名词 pusillanimity。" }],
    syn:["cowardly","timid","fainthearted"], ant:["brave","courageous"],
    synDiff:"timid 中性‘害羞胆小’；cowardly 常用贬义；pusillanimous 最正式、强调‘缺乏胆魄’。" },

  { w:"mercurial", ipa:"/mɜːˈkjʊəriəl/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"善变的；情绪起伏快的",
      ex:["His mercurial mood swings puzzled the team.",
          "She is a mercurial genius, brilliant yet unpredictable.",
          "The mercurial market rose and fell within a day."],
      note:"源自 Mercury（水星/神），喻‘多变、敏捷’；也形容‘机敏’。" }],
    syn:["volatile","capricious","changeable"], ant:["steady","stable"],
    synDiff:"capricious 强调‘任性、无理由地变’；volatile 强调‘剧烈不稳’；mercurial 偏‘敏捷而善变’，可褒可贬。" },

  { w:"ebullient", ipa:"/ɪˈbʌliənt/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"热情奔放的；兴致勃勃的",
      ex:["The ebullient host welcomed every guest.",
          "She gave an ebullient speech full of laughter.",
          "His ebullient nature lifts the room."],
      note:"名词 ebullience；比 enthusiastic 更有‘外溢的喜悦’之感。" }],
    syn:["exuberant","effervescent","cheerful"], ant:["morose","glum"],
    synDiff:"cheerful 通用‘开心’；effervescent 像气泡般活泼；ebullient 强调‘满溢的热情’，最生动。" },

  { w:"taciturn", ipa:"/ˈtæsɪtɜːn/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"沉默寡言的",
      ex:["The taciturn old man rarely spoke.",
          "His taciturn manner was mistaken for rudeness.",
          "She is taciturn in meetings but warm in private."],
      note:"反义 garrulous / loquacious；名词 taciturnity。" }],
    syn:["reserved","silent","reticent"], ant:["garrulous","talkative"],
    synDiff:"reserved 中性‘内敛’；reticent 指‘不愿吐露’；taciturn 强调‘天性少言’。" },

  { w:"garrulous", ipa:"/ˈɡærələs/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"饶舌的；爱说话的",
      ex:["The garrulous neighbor talked for an hour.",
          "He is garrulous when he drinks.",
          "A garrulous guide can exhaust tourists."],
      note:"略带贬义；反义 taciturn；名词 garrulity。" }],
    syn:["talkative","loquacious","voluble"], ant:["taciturn","reticent"],
    synDiff:"talkative 中性‘爱说话’；loquacious 较正式；garrulous 带‘絮叨、停不下来’的贬义。" },

  { w:"inscrutable", ipa:"/ɪnˈskruːtəbl/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"高深莫测的；难以看透的",
      ex:["He wore an inscrutable smile.",
          "Her motives remained inscrutable.",
          "The monk's face was calm and inscrutable."],
      note:"名词 inscrutability；常用于表情、意图。" }],
    syn:["enigmatic","mysterious","unfathomable"], ant:["transparent","clear"],
    synDiff:"mysterious 通用‘神秘’；enigmatic 偏‘谜样引人猜’；inscrutable 强调‘无法读懂（表情/心思）’。" },

  { w:"sanguine", ipa:"/ˈsæŋɡwɪn/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"乐观的；充满信心的（也指面色红润）",
      ex:["She is sanguine about the project's chances.",
          "He remained sanguine despite the setbacks.",
          "A sanguine complexion suggests good health."],
      note:"源于‘血’（体液说中血液旺则乐观）；反义 melancholic。" }],
    syn:["optimistic","hopeful","cheerful"], ant:["pessimistic","melancholic"],
    synDiff:"optimistic 通用‘乐观’；hopeful 指‘抱有希望’；sanguine 正式、带‘天性豁达’意味，也保留‘红润’古义。" },

  { w:"blasé", ipa:"/ˈblɑːzeɪ/", pos:"adj.", cat:"外貌性格",
    senses:[{ def:"见怪不怪的；漠然厌倦的",
      ex:["The blasé critic yawned at the fireworks.",
          "Having traveled everywhere, he is blasé about sights.",
          "Don't be so blasé; this is a real achievement."],
      note:"源自法语，常形容‘对寻常刺激无感、略显倦怠’。" }],
    syn:["jaded","apathetic","unimpressed"], ant:["enthusiastic","eager"],
    synDiff:"jaded 强调‘因过度经历而麻木’；apathetic 指‘冷漠无心’；blasé 强调‘见多不怪、不为所动’的倦怠感。" },

  // ---------------- 地理与环境 ----------------
  { w:"biodiversity", ipa:"/ˌbaɪəʊdaɪˈvɜːsəti/", pos:"n.", cat:"地理环境",
    senses:[{ def:"生物多样性",
      ex:["The rainforest is rich in biodiversity.",
          "Loss of biodiversity threatens ecosystems.",
          "Protected areas help preserve biodiversity."],
      note:"形容词 biodiverse；常用前缀 bio-（生命）。" }],
    syn:["variety of life","ecological richness"], ant:["monoculture"],
    synDiff:"variety of life 是通俗说法；biodiversity 是生态学术语，强调‘物种/基因/生态系统’多层次多样。" },

  { w:"sustainability", ipa:"/səˌsteɪnəˈbɪləti/", pos:"n.", cat:"地理环境",
    senses:[{ def:"可持续性",
      ex:["We must balance growth with environmental sustainability.",
          "The report measures the sustainability of farming.",
          "Urban sustainability requires clean transport."],
      note:"形容词 sustainable（可持续的）；动词 sustain。" }],
    syn:["endurance","viability"], ant:["depletion"],
    synDiff:"viability 指‘能否维持运转’；sustainability 专指‘不损害未来、长期可续’的发展观。" },

  { w:"erosion", ipa:"/ɪˈrəʊʒn/", pos:"n.", cat:"地理环境",
    senses:[{ def:"侵蚀；磨损（风、水、时间造成）",
      ex:["Soil erosion washed away the topsoil.",
          "Coastal erosion threatens the village.",
          "The erosion of trust damaged the team."],
      note:"动词 erode；也可喻‘侵蚀（权利/信任）’。" }],
    syn:["wearing away","corrosion","decline"], ant:["buildup"],
    synDiff:"corrosion 多指‘化学锈蚀’；wearing away 通用‘磨耗’；erosion 专指自然力对地表/物质的逐步剥蚀，亦可比喻。" },

  { w:"watershed", ipa:"/ˈwɔːtəʃed/", pos:"n.", cat:"地理环境",
    senses:[{ def:"分水岭（也喻重大转折点）",
      ex:["The year 1989 was a watershed in European history.",
          "The reform marked a watershed for the economy.",
          "The river's watershed covers three provinces."],
      note:"地理义‘流域分水岭’；比喻义‘转折点’更常用。" }],
    syn:["turning point","milestone","divide"], ant:[],
    synDiff:"milestone 指‘里程碑/标志事件’；turning point 指‘转折’；watershed 强调‘分界、此后截然不同’的转折。" },

  // ---------------- 动植物 ----------------
  { w:"mammal", ipa:"/ˈmæml/", pos:"n.", cat:"动植物",
    senses:[{ def:"哺乳动物",
      ex:["Whales are mammals, not fish.",
          "Humans are mammals that give birth to live young.",
          "The mammal feeds its young with milk."],
      note:"形容词 mammalian；特征：胎生、哺乳、恒温。" }],
    syn:["vertebrate"], ant:[],
    synDiff:"vertebrate 指‘脊椎动物’（含鱼鸟爬）；mammal 是其中‘哺乳’的一类。" },

  { w:"pollinate", ipa:"/ˈpɒlɪneɪt/", pos:"v.", cat:"动植物",
    senses:[{ def:"给…传粉",
      ex:["Bees pollinate most fruit trees.",
          "Wind pollinates grasses and cereals.",
          "The flower is pollinated by moths at night."],
      note:"名词 pollination；传粉者 pollinator（蜂、蝶等）。" }],
    syn:["fertilize"], ant:[],
    synDiff:"fertilize 可指‘施肥’或‘受精’；pollinate 专指‘花粉传递’这一生态过程。" },

  { w:"deciduous", ipa:"/dɪˈsɪdʒuəs/", pos:"adj.", cat:"动植物",
    senses:[{ def:"落叶的（树木季节性地落叶）",
      ex:["Oak is a deciduous tree.",
          "Deciduous forests turn red in autumn.",
          "Plant deciduous shrubs for seasonal color."],
      note:"反义 evergreen（常绿）。" }],
    syn:["leaf-shedding"], ant:["evergreen"],
    synDiff:"leaf-shedding 是描述；deciduous 是植物学术语，与 evergreen 相对。" },

  // ---------------- 艺术与音乐 ----------------
  { w:"renaissance", ipa:"/rɪˈneɪsns/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"文艺复兴；复兴",
      ex:["The Renaissance began in Italy in the 14th century.",
          "There is a renaissance of craft beer.",
          "Her work sparked a renaissance in local art."],
      note:"首字母大写指欧洲文艺复兴；小写指‘复兴’。" }],
    syn:["revival","rebirth","awakening"], ant:["decline"],
    synDiff:"revival 通用‘复兴’；rebirth 强调‘重生’；Renaissance 专指14–17世纪欧洲文化运动。" },

  { w:"crescendo", ipa:"/krəˈʃendəʊ/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"（音乐）渐强；高潮渐起",
      ex:["The music built to a crescendo.",
          "The applause reached a crescendo.",
          "Tensions rose in a crescendo before the war."],
      note:"源于意大利语；也喻‘逐步高涨到顶点’。" }],
    syn:["climax","swelling","peak"], ant:["decrescendo"],
    synDiff:"climax 指‘顶点’；peak 指‘峰值’；crescendo 强调‘由弱到强逐渐推到高潮’的过程。" },

  { w:"improvisation", ipa:"/ɪmˌprɒvəˈzeɪʃn/", pos:"n.", cat:"艺术音乐",
    senses:[{ def:"即兴创作；即兴表演",
      ex:["Jazz relies on improvisation.",
          "The actor's improvisation saved the scene.",
          "We performed with little preparation and much improvisation."],
      note:"动词 improvise；形容词 improvised。" }],
    syn:["extemporization","ad-lib"], ant:["scripting"],
    synDiff:"ad-lib 口语‘临时加词’；extemporization 偏演讲‘即兴’；improvisation 是音乐/戏剧通用的‘即兴创作’。" },

  // ---------------- 旅游 ----------------
  { w:"itinerary", ipa:"/aɪˈtɪnərəri/", pos:"n.", cat:"旅游",
    senses:[{ def:"行程单；旅行路线",
      ex:["Our itinerary includes three cities in five days.",
          "Send me the itinerary before we book.",
          "The tour's itinerary changed due to weather."],
      note:"也用于商务‘日程安排’。" }],
    syn:["schedule","route","plan"], ant:[],
    synDiff:"route 指‘路线’；schedule 指‘时刻表’；itinerary 是‘逐站旅行计划’。" },

  { w:"heritage", ipa:"/ˈherɪtɪdʒ/", pos:"n.", cat:"旅游",
    senses:[{ def:"遗产；传统（文化/自然）",
      ex:["The town is a UNESCO world heritage site.",
          "They preserve their cultural heritage.",
          "The festival celebrates local heritage."],
      note:"world heritage site = 世界遗产；形容词 heritage（heritage railway 遗产铁路）。" }],
    syn:["legacy","inheritance","tradition"], ant:[],
    synDiff:"legacy 多指‘先辈留下的影响/财物’；tradition 指‘传统习俗’；heritage 强调‘可珍视、需保护的文化/自然遗产’。" },

  // ---------------- 历史人物 ----------------
  { w:"Confucius", ipa:"/kənˈfjuːʃəs/", pos:"n.", cat:"历史人物",
    senses:[{ def:"孔子（公元前 551–479，中国思想家、儒家创始人）",
      ex:["Confucius emphasized filial piety and education.",
          "The sayings of Confucius were compiled in the Analects.",
          "Confucius influenced East Asian thought for two millennia."],
      note:"拉丁化名；本名孔丘，字仲尼。相关 Confucianism 儒家。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"Leonardo da Vinci", ipa:"/liːəˈnɑːdəʊ dɑː ˈvɪntʃi/", pos:"n.", cat:"历史人物",
    senses:[{ def:"列奥纳多·达·芬奇（1452–1519，意大利文艺复兴全才：画家、科学家、发明家）",
      ex:["Leonardo da Vinci painted the Mona Lisa.",
          "Leonardo da Vinci sketched early flying machines.",
          "Leonardo da Vinci embodies the Renaissance ideal of the universal genius."],
      note:"《蒙娜丽莎》《最后的晚餐》作者；也作科学家、工程师。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"Alexander the Great", ipa:"/ˌælɪɡˈzɑːndə ðə ˈɡreɪt/", pos:"n.", cat:"历史人物",
    senses:[{ def:"亚历山大大帝（公元前 356–323，马其顿国王，建立横跨欧亚非的帝国）",
      ex:["Alexander the Great conquered Persia by the age of 25.",
          "Alexander the Great spread Greek culture across his empire.",
          "The conquests of Alexander the Great shaped the ancient world."],
      note:"马其顿王，师事亚里士多德；帝国昙花一现。" }],
    syn:[], ant:[],
    synDiff:"" },

  { w:"Einstein", ipa:"/ˈaɪnʃtaɪn/", pos:"n.", cat:"历史人物",
    senses:[{ def:"爱因斯坦（1879–1955，物理学家，相对论提出者，1921 诺贝尔物理学奖）",
      ex:["Einstein published the theory of relativity in 1905.",
          "Einstein's E=mc² reshaped physics.",
          "Einstein fled Nazi Germany and later urged atomic caution."],
      note:"相对论的提出者；也象征‘天才’。" }],
    syn:[], ant:[],
    synDiff:"" }
];
