# -*- coding: utf-8 -*-
"""Export a verified bank section into the study site as bpho/data/bank-NN.js.

The Python source (sec01.py, sec02.py, ...) is the single source of truth; the JS file
is a build artefact, exactly like data/questions-5.js is for tools/r0sample.  Nothing
is ever hand-edited in the generated file, so the site can never drift from the bank
that the gates actually checked.

The gate run comes FIRST and is not optional.  If a section fails any gate this script
writes nothing and exits non-zero -- publishing an unchecked section is the one outcome
worth making impossible.

Run:  python build_site.py          (every section that has a module here)
      python build_site.py 1        (just section 1)
"""
import io
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import gates as G

FIGDIR = os.path.join(HERE, "fig")
OUTDIR = os.path.normpath(os.path.join(HERE, "..", "..", "data"))

# section number -> module name.  Adding a section is one line here plus its secNN.py
# and figsNN.py.
SECTIONS = {
    1: "sec01",
    2: "sec02",
    3: "sec03",
    4: "sec04",
    5: "sec05",
}

# Fields the site app reads.  Everything else in the source (distractors, profile,
# check, n) stays in Python: the app has no use for it, and `check` holds sympy
# expressions that would only confuse a reader of the JS.
EXPORT_FIELDS = ("id", "module", "topic", "diff", "rel", "key", "ans")


def js_template(s: str) -> str:
    """Wrap a string as a JS template literal.

    Template literals are used for the HTML fields because the figures are inline SVG
    and every SVG attribute is double-quoted; a normal quoted string would need every
    one of those escaped.  Three characters still have to be escaped, and getting any
    of them wrong is a syntax error at load time rather than a visible defect:
      \\  -> \\\\     `  -> \\`     ${  -> \\${
    """
    out = s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")
    return "`" + out + "`"


def expand(text: str, errs: list) -> str:
    """Replace {{FIG:key}} with the figure's SVG from fig/."""
    def rep(m):
        key = m.group(1)
        p = os.path.join(FIGDIR, key + ".svg")
        if not os.path.exists(p):
            errs.append("%s: figure %r has no file" % (m.group(0), key))
            return "<!-- MISSING FIGURE %s -->" % key
        return io.open(p, encoding="utf-8").read().rstrip()
    return re.sub(r"\{\{FIG:([A-Za-z0-9_.-]+)\}\}", rep, text)


def build_one(sec_no: int, base) -> str | None:
    modname = SECTIONS[sec_no]
    mod = __import__(modname)
    qs = mod.QUESTIONS

    # ── gate first.  A section that fails is not published. ────────────────────
    errs, stats = G.gate_section(sec_no, base=base, verbose=True,
                                 questions=[dict(q) for q in qs])
    if errs:
        print("\n!! REFUSING TO PUBLISH section %d -- %d gate finding(s)" % (sec_no, len(errs)))
        for e in errs:
            print("   -", e)
        return None

    tag = "BANK-" + stats["code"]                  # S01 -> BANK-S01

    blocks = []
    for q in qs:
        ferrs = []
        q_html = expand(q["stem"], ferrs)
        sol_html = expand(q["sol"], ferrs)
        trap_html = expand(q.get("trap", "") or "", ferrs)
        if ferrs:
            print("\n!! REFUSING TO PUBLISH section %d -- figure problems" % sec_no)
            for e in ferrs:
                print("   -", e)
            return None
        if "{{FIG" in (q_html + sol_html + trap_html):
            print("\n!! REFUSING TO PUBLISH: unresolved figure placeholder in %s" % q["id"])
            return None

        lines = ["{"]
        head = "  " + ", ".join(
            "%s: %s" % (k, json.dumps(q[k], ensure_ascii=False)) for k in EXPORT_FIELDS)
        lines.append(head + ', paper: "%s",' % tag)
        # rel comes through as a list of (module, topic) tuples
        rel = json.dumps([list(r) for r in q.get("rel", [])], ensure_ascii=False)
        lines.append("  rel: " + rel + ",")
        lines.append("  q: " + js_template(q_html) + ",")
        lines.append("  opts: " + json.dumps(list(q["opts"]), ensure_ascii=False) + ",")
        lines.append("  sol: " + js_template(sol_html) + ",")
        lines.append("  trap: " + js_template(trap_html))
        lines.append("}")
        blocks.append("\n".join(lines))

    letters = stats["letters"]
    # The mix is DERIVED, not written into the template.  It was hardcoded as section 1's
    # mix, which meant every later section's generated file would have described itself
    # with the wrong module counts -- a header that lies about its own contents is worse
    # than no header.
    mix = {}
    for q in qs:
        mix[q["module"]] = mix.get(q["module"], 0) + 1
    mixstr = " ".join("%s%d" % (m, mix[m]) for m in sorted(mix))
    head = """/* BPhO Round 0 — ORIGINAL bank, section %02d (S%02d-01 .. S%02d-%02d).
   GENERATED by tools/bank/build_site.py — do not edit by hand; edit sec%02d.py.

   These are original questions written to the Round 0 format, not past-paper items.
   The module mix is this section's allocation from the plan (%s), so this section works
   as a full-length mock.

   Before this file was written the section was put through ten gates: structure,
   distractor quality, agreement between key and solution, notation and the
   non-calculator rule, declared-profile vs solution, measured difficulty against the
   real paper's own quartiles, logic-level similarity, an independent numeric
   re-derivation of every answer, figure geometry, and answer-letter balance.  The
   gate suite itself is tested by 31 mutants, each of which breaks one thing and
   asserts that the right gate notices.

   Derived key: %s

   Figures are hand-authored inline SVG in tools/bank/fig/, not generated images. */

window.BPHO_QUESTIONS = (window.BPHO_QUESTIONS || []).concat([

""" % (sec_no, sec_no, sec_no, len(qs), sec_no, mixstr,
       " ".join(letters))

    out = head + ",\n\n".join(blocks) + "\n\n]);\n"
    path = os.path.join(OUTDIR, "bank-%02d.js" % sec_no)
    os.makedirs(OUTDIR, exist_ok=True)
    io.open(path, "w", encoding="utf-8").write(out)
    print("\npublished %s  (%d bytes, %d questions, tag %s)"
          % (path, len(out), len(qs), tag))
    return path


def main(argv):
    want = [int(a) for a in argv if a.isdigit()] or sorted(SECTIONS)
    base = G.baseline()
    ok = []
    for n in want:
        if n not in SECTIONS:
            print("section %d has no module yet" % n)
            continue
        print("\n" + "=" * 70)
        print("SECTION %d" % n)
        print("=" * 70)
        if build_one(n, base):
            ok.append(n)
    print("\n" + "=" * 70)
    if len(ok) != len(want):
        print("FAILED: %d of %d sections not published" % (len(want) - len(ok), len(want)))
        return 1
    print("published %d section(s): %s" % (len(ok), ", ".join(map(str, ok))))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
