#!/usr/bin/env python3
"""Build assets/js/search-index.js from every content page.

Run from the site root:  python3 tools/build_search_index.py

The index is written as a plain JS assignment (not JSON) so the site works when
opened directly from the filesystem, where fetch() would be blocked by CORS.
"""
import html
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKIP = {'_example.html'}
LIMIT = 12000  # characters of body text indexed per page

SUBJECTS = {
    'math': 'Maths AA HL', 'physics': 'Physics HL', 'cs': 'Computer Science HL',
    'english': 'English A SL', 'chinese': 'Chinese A SL', 'start': 'Study skills',
    'business': 'Business Management SL', 'core': 'DP core (TOK / EE / CAS)',
}


def strip_tags(s: str) -> str:
    s = re.sub(r'(?is)<(script|style|svg)\b.*?</\1>', ' ', s)
    s = re.sub(r'(?s)<!--.*?-->', ' ', s)
    s = re.sub(r'(?i)</(p|div|li|h[1-6]|tr|section|details)>', ' ', s)
    s = re.sub(r'<[^>]+>', ' ', s)
    s = html.unescape(s)
    return re.sub(r'\s+', ' ', s).strip()


def main() -> int:
    docs = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames
                       if d not in {'assets', 'tools', '.workbuddy-ai', '.git'}]
        for fn in sorted(filenames):
            if not fn.endswith('.html') or fn in SKIP:
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, ROOT)
            raw = open(full, encoding='utf-8').read()

            title = re.search(r'(?is)<title>(.*?)</title>', raw)
            title = html.unescape(title.group(1)).strip() if title else fn
            subject = re.search(r'data-subject="([^"]+)"', raw)
            subject = SUBJECTS.get(subject.group(1), '') if subject else ''
            heads = [html.unescape(h).strip()
                     for h in re.findall(r'(?is)<h[23][^>]*>(.*?)</h[23]>', raw)]
            heads = [re.sub(r'<[^>]+>', '', h) for h in heads]

            body = raw
            m = re.search(r'(?is)<div id="app-shell">(.*)</div>\s*<script', body)
            if m:
                body = m.group(1)
            text = strip_tags(body)[:LIMIT]

            docs.append({'path': rel.replace(os.sep, '/'), 'title': title,
                         'subject': subject, 'heads': heads[:60], 'text': text})

    docs.sort(key=lambda d: d['path'])
    out = os.path.join(ROOT, 'assets', 'js', 'search-index.js')
    payload = json.dumps(docs, ensure_ascii=False, separators=(',', ':')).replace('<', '\\u003c')
    with open(out, 'w', encoding='utf-8') as f:
        f.write('/* Generated by tools/build_search_index.py — do not edit by hand. */\n')
        f.write('window.DP_SEARCH_INDEX=' + payload + ';\n')

    kb = os.path.getsize(out) / 1024
    print(f'Indexed {len(docs)} pages -> assets/js/search-index.js ({kb:.0f} KB)')
    for d in docs:
        print(f"  {d['path']:44s} {len(d['text']):6d} chars  {d['title'][:48]}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
